# Generated by Django 4.2.18 on 2025-02-24 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0028_service_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0039_instance_rejection_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_step', models.CharField(choices=[('baufreigabe', 'Baufreigabe'), ('realisierung', 'Realisierung'), ('endabnahme', 'Endabnahme'), ('variabel', 'Variabel')], max_length=20)),
                ('assigned_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.service')),
                ('created_by_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.service')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_step', models.CharField(choices=[('baufreigabe', 'Baufreigabe'), ('realisierung', 'Realisierung'), ('endabnahme', 'Endabnahme'), ('variabel', 'Variabel')], max_length=20)),
                ('controlled_at', models.DateTimeField(null=True)),
                ('control_notes', models.TextField(blank=True, null=True)),
                ('assigned_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.service')),
                ('controlled_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.service')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.instance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sanction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('controlled_at__isnull', True), ('controlled_by_user__isnull', True)), models.Q(('controlled_at__isnull', False), ('controlled_by_user__isnull', False)), _connector='OR'), name='controlled_consistently'),
        ),
    ]
