# Generated by Django 4.2.20 on 2025-04-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sanctiontemplate',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
