CHANGE_FORM = {
    "default": {
        "INTERCHANGEABLE_FORMS": [],
    },
    "kt_bern": {
        "ENABLED": True,
        "INTERCHANGEABLE_FORMS": [
            ["baugesuch", "baugesuch-generell", "baugesuch-mit-uvp"],
            ["baugesuch-v2", "baugesuch-generell-v2", "baugesuch-mit-uvp-v2"],
            ["baugesuch-v3", "baugesuch-generell-v3", "baugesuch-mit-uvp-v3"],
            ["baugesuch-v5", "baugesuch-generell-v5", "baugesuch-mit-uvp-v5"],
            ["baugesuch-v6", "baugesuch-generell-v6", "baugesuch-mit-uvp-v6"],
        ],
    },
    "kt_schwyz": {
        "ENABLED": True,
        "INTERCHANGEABLE_FORMS": [
            [
                "vorentscheid-gemass-ss84-pbg-v2",
                "vorentscheid-gemass-ss84-pbg-v3",
                "vorentscheid-gemass-ss84-pbg-v4",
                "vorentscheid-gemass-ss84-pbg-v5",
                "vorentscheid-gemass-ss84-pbg-v6",
                "vorentscheid-gemass-ss84-pbg-v7",
                "vorentscheid-gemass-ss84-pbg-v8",
                "vorentscheid-gemass-ss84-pbg-v9",
                "vorentscheid-gemass-ss84-pbg-v10",
                "vorentscheid-gemass-ss84-pbg-v11",
                "baugesuch-reklamegesuch-v2",
                "baugesuch-reklamegesuch-v3",
                "baugesuch-reklamegesuch-v4",
                "baugesuch-reklamegesuch-v5",
                "baugesuch-reklamegesuch-v6",
                "baugesuch-reklamegesuch-v7",
                "baugesuch-reklamegesuch-v8",
                "baugesuch-reklamegesuch-v9",
                "baugesuch-reklamegesuch-v10",
                "baugesuch-reklamegesuch-v11",
                "baugesuch-reklamegesuch-v12",
                "projektanderung-v2",
                "projektanderung-v3",
                "projektanderung-v4",
                "projektanderung-v5",
                "projektanderung-v6",
                "projektanderung-v7",
                "projektanderung-v8",
                "projektanderung-v9",
                "projektanderung-v10",
                "projektanderung-v11",
                "projektanderung-v12",
                "technische-bewilligung",
                "technische-bewilligung-v2",
                "technische-bewilligung-v3",
                "technische-bewilligung-v4",
                "technische-bewilligung-v5",
                "baumeldung-fur-geringfugiges-vorhaben-v2",
                "baumeldung-fur-geringfugiges-vorhaben-v3",
                "baumeldung-fur-geringfugiges-vorhaben-v4",
                "baumeldung-fur-geringfugiges-vorhaben-v5",
                "baumeldung-fur-geringfugiges-vorhaben-v6",
                "anlassbewilligungen-verkehrsbewilligungen-v2",
                "anlassbewilligungen-verkehrsbewilligungen-v3",
                "projektgenehmigungsgesuch-gemass-ss15-strag-v2",
                "projektgenehmigungsgesuch-gemass-ss15-strag-v3",
                "projektgenehmigungsgesuch-gemass-ss15-strag-v4",
                "projektgenehmigungsgesuch-gemass-ss15-strag-v5",
                "projektgenehmigungsgesuch-gemass-ss15-strag-v6",
            ]
        ],
    },
    "kt_ag": {
        "ENABLED": True,
        "INTERCHANGEABLE_FORMS": [
            [
                "anfrage",
                "anfrage-intern",
                "baugesuch",
                "baugesuch-mit-uvp",
                "vorentscheid",
            ],
        ],
    },
}
