DJANGO_ADMIN = {
    "default": {
        "ENABLED_MODELS": [
            "caluma_workflow.Case",
            "caluma_workflow.WorkItem",
            "instance.InstanceState",
            "permissions.AccessLevel",
            "user.Group",
            "user.Role",
            "user.Service",
            "user.ServiceGroup",
            "user.User",
        ],
        "CUSTOMER_MANAGED_MODELS": ["user.User", "user.Group", "user.Service"],
    },
    "demo": {
        "ENABLED": True,
        "ENABLED_MODELS": ["core.InstanceResource", "core.Resource"],
    },
    "kt_gr": {
        "ENABLED": True,
        "ENABLED_MODELS": [
            "alexandria_core.Category",
            "alexandria_core.Mark",
            "core.InstanceResource",
            "core.Resource",
            "core.ServiceContent",
            "gis.GISDataSource",
            "notification.NotificationTemplate",
            "deadlines.DeadlineType",
            "ech0211.Message",
            "django_celery_beat.PeriodicTask",
            "django_celery_beat.CrontabSchedule",
        ],
        "CUSTOMER_MANAGED_MODELS": [
            "notification.NotificationTemplate",
            "core.ServiceContent",
            "deadlines.DeadlineType",
        ],
    },
    "kt_so": {
        "ENABLED": True,
        "ENABLED_MODELS": [
            "alexandria_core.Category",
            "alexandria_core.Mark",
            "core.InstanceResource",
            "core.Resource",
            "gis.GISDataSource",
            "notification.NotificationTemplate",
            "django_q.Success",
            "django_q.Failure",
            "django_q.OrmQ",
            "ech0211.Message",
            "django_celery_beat.PeriodicTask",
            "django_celery_beat.CrontabSchedule",
        ],
        "CUSTOMER_MANAGED_MODELS": ["gis.GISDataSource"],
    },
    "kt_bern": {
        "ENABLED": True,
        "ENABLED_MODELS": [
            "alexandria_core.Category",
            "alexandria_core.Mark",
            "gis.GISDataSource",
            "django_q.Success",
            "django_q.Failure",
            "django_q.OrmQ",
            "gever.CMIConstantValue",
            "gever.CMIObjectTemplate",
            "ech0211.Message",
            "user.GeometerChangeTask",
        ],
    },
    "kt_schwyz": {
        "ENABLED": True,
        "ENABLED_MODELS": [
            "billing.BillingV2EntryTemplate",
        ],
        "CUSTOMER_MANAGED_MODELS": [
            "billing.BillingV2EntryTemplate",
        ],
    },
    "kt_uri": {"ENABLED": True},
    "kt_ag": {
        "ENABLED": True,
        "ENABLED_MODELS": [
            "alexandria_core.Category",
            "alexandria_core.Mark",
            "caluma_workflow.Case",
            "caluma_workflow.WorkItem",
            "core.InstanceResource",
            "core.Resource",
            "billing.BillingV2EntryTemplate",
            "gis.GISDataSource",
            "notification.NotificationTemplate",
            "work_items.WorkItemTemplate",
            "work_items.WorkItemListFilterPreset",
            "deadlines.DeadlineType",
            "ech0211.Message",
            "django_celery_beat.PeriodicTask",
            "django_celery_beat.CrontabSchedule",
            "alert_message.AlertMessage",
        ],
        "CUSTOMER_MANAGED_MODELS": [
            "billing.BillingV2EntryTemplate",
            "work_items.WorkItemTemplate",
            "work_items.WorkItemListFilterPreset",
            "deadlines.DeadlineType",
            "alert_message.AlertMessage",
        ],
    },
}
