from django.utils.translation import gettext_lazy as _

from camac.constants import kt_ag as ag_constants, kt_gr as gr_constants

DMS = {
    "default": {
        "ADD_ADDRESS_DATA": False,
        "ADD_HEADER_DATA": True,
        "USE_NUMBER_SEPARATOR": False,
    },
    "demo": {
        "ENABLED": True,
        "FORM": {
            "_base": {
                "people_sources": [
                    "personalien-gesuchstellerin",
                    "personalien-vertreterin-mit-vollmacht",
                    "personalien-grundeigentumerin",
                    "personalien-gebaudeeigentumerin",
                    "personalien-projektverfasserin",
                ],
                "people_names": {
                    "name-gesuchstellerin": "familyName",
                    "vorname-gesuchstellerin": "givenName",
                    "name-juristische-person-gesuchstellerin": "juristicName",
                    "name-vertreterin": "familyName",
                    "vorname-vertreterin": "givenName",
                    "name-juristische-person-vertreterin": "juristicName",
                    "name-grundeigentuemerin": "familyName",
                    "vorname-grundeigentuemerin": "givenName",
                    "name-juristische-person-grundeigentuemerin": "juristicName",
                    "name-gebaeudeeigentuemerin": "familyName",
                    "vorname-gebaeudeeigentuemerin": "givenName",
                    "name-juristische-person-gebaeudeeigentuemerin": "juristicName",
                    "name-projektverfasserin": "familyName",
                    "vorname-projektverfasserin": "givenName",
                    "name-juristische-person-projektverfasserin": "juristicName",
                },
            },
            "baugesuch": {
                "forms": [
                    "baugesuch",
                ],
                "template": "form",
                "personalien": "personalien",
                "exclude_slugs": [
                    "is-paper",
                    "einreichen-button",
                    "dokumente-platzhalter",
                ],
            },
        },
        "ADD_HEADER_DATA": False,
    },
    "kt_bern": {
        "ENABLED": True,
        "FORM": {
            "_base": {
                "people_sources": [
                    # bulding permit
                    "personalien-gesuchstellerin",
                    "personalien-vertreterin-mit-vollmacht",
                    "personalien-grundeigentumerin",
                    "personalien-gebaudeeigentumerin",
                    "personalien-projektverfasserin",
                    "personalien-tragwerksplanerin-v5",
                    "personalien-sb",
                    # sb1 & sb2
                    "personalien-sb1-sb2",
                ],
                "people_names": {
                    "name-gesuchstellerin": "familyName",
                    "vorname-gesuchstellerin": "givenName",
                    "name-juristische-person-gesuchstellerin": "juristicName",
                    "name-vertreterin": "familyName",
                    "vorname-vertreterin": "givenName",
                    "name-juristische-person-vertreterin": "juristicName",
                    "name-grundeigentuemerin": "familyName",
                    "vorname-grundeigentuemerin": "givenName",
                    "name-juristische-person-grundeigentuemerin": "juristicName",
                    "name-gebaeudeeigentuemerin": "familyName",
                    "vorname-gebaeudeeigentuemerin": "givenName",
                    "name-juristische-person-gebaeudeeigentuemerin": "juristicName",
                    "name-projektverfasserin": "familyName",
                    "vorname-projektverfasserin": "givenName",
                    "name-juristische-person-projektverfasserin": "juristicName",
                    "name-tragwerksplanerin-v5": "familyName",
                    "vorname-tragwerksplanerin-v5": "givenName",
                    "name-juristische-person-tragwerksplanerin-v5": "juristicName",
                },
            },
            "baugesuch": {
                "forms": [
                    "baugesuch",
                    "baugesuch-v2",
                    "baugesuch-v3",
                    "baugesuch-v5",
                    "baugesuch-v6",
                    "baugesuch-v7",
                    "baugesuch-mit-uvp",
                    "baugesuch-mit-uvp-v2",
                    "baugesuch-mit-uvp-v3",
                    "baugesuch-mit-uvp-v5",
                    "baugesuch-mit-uvp-v6",
                    "baugesuch-mit-uvp-v7",
                    "baugesuch-generell",
                    "baugesuch-generell-v2",
                    "baugesuch-generell-v3",
                    "baugesuch-generell-v5",
                    "baugesuch-generell-v6",
                    "baugesuch-generell-v7",
                    "hecken-feldgehoelze-baeume",
                    "hecken-feldgehoelze-baeume-v2",
                    "baupolizeiliches-verfahren",
                    "baupolizeiliches-verfahren-v2",
                    "baupolizeiliches-verfahren-v3",
                    "zutrittsermaechtigung",
                    "zutrittsermaechtigung-v2",
                    "zutrittsermaechtigung-v3",
                    "klaerung-baubewilligungspflicht",
                    "klaerung-baubewilligungspflicht-v2",
                    "verlaengerung-geltungsdauer",
                ],
                "template": "form",
                "personalien": "personalien",
                "exclude_slugs": [
                    "is-paper",
                    "projektaenderung",
                    "einreichen-button",
                    "karte",
                    "dokumente-platzhalter",
                    "lu-kaltwasser-calculation-v5",
                    "bw-kaltwasser-calculation-v5",
                    "lu-warmwasser-calculation-v5",
                    "bw-warmwasser-calculation-v5",
                    "spezialinstallation-calculation-v5",
                    "pdf-herunterladen",
                    "entwurf-herunterladen-pdf",
                    "hinweis-zum-vorliegenden-dossier",
                ],
            },
            "vorabklaerung": {
                "forms": [
                    "vorabklaerung-einfach",
                    "vorabklaerung-einfach-v4",
                    "vorabklaerung-einfach-v5",
                    "vorabklaerung-vollstaendig",
                    "vorabklaerung-vollstaendig-v2",
                    "vorabklaerung-vollstaendig-v3",
                    "vorabklaerung-vollstaendig-v4",
                    "vorabklaerung-vollstaendig-v5",
                    "vorabklaerung-vollstaendig-v6",
                    "vorabklaerung-vollstaendig-v7",
                    "solaranlagen-meldung",
                    "solaranlagen-meldung-v2",
                    "solaranlagen-meldung-v3",
                    "heat-generator",
                    "heat-generator-v2",
                    "heat-generator-v3",
                    "reklamegesuch",
                    "benuetzung-oeffentlichem-terrain-meldung",
                    "solareignung-meldung",
                ],
                "template": "form",
                "personalien": "personalien",
                "exclude_slugs": [
                    "is-paper",
                    "projektaenderung",
                    "einreichen-button",
                    "karte",
                    "dokumente-platzhalter",
                    "lu-kaltwasser-calculation-v5",
                    "bw-kaltwasser-calculation-v5",
                    "lu-warmwasser-calculation-v5",
                    "bw-warmwasser-calculation-v5",
                    "spezialinstallation-calculation-v5",
                    "pdf-herunterladen",
                    "entwurf-herunterladen-pdf",
                    "hinweis-zum-vorliegenden-dossier",
                ],
            },
            "migriertes-dossier": {
                "forms": [
                    "migriertes-dossier",
                ],
                "template": "form",
                "personalien": "personalien",
                "exclude_slugs": [],
            },
            "selbstdeklaration": {
                "forms": ["sb1", "sb2", "sb1-v2"],
                "template": "form",
                "personalien": "personalien-sb1-sb2",
                "exclude_slugs": [
                    "is-paper",
                    "bewilligungspflichtig-v2",
                    "einreichen-button-sb1",
                    "einreichen-button-sb2",
                    "dokumente-sb1",
                    "dokumente-sb2",
                    "dokumente-platzhalter",
                    "pdf-herunterladen",
                    "entwurf-herunterladen-pdf",
                    "hinweis-zum-vorliegenden-dossier",
                ],
            },
            "regular-exams": {
                "forms": ["fp-form", "fp-form-v2", "bab-form"],
                "template": "audit-form",
                "exclude_slugs": [
                    "bab-01-07-1972-um-und-ausgebaut-meldung",
                    "bab-naehe-von-schutzenswerten-gebaeuden-meldung",
                ],
                "check_validity_for_draft": True,
            },
            "material-exam": {
                "forms": ["mp-form"],
                "template": "form",
                "check_validity_for_draft": True,
            },
        },
    },
    "kt_gr": {
        "ENABLED": True,
        "USE_NUMBER_SEPARATOR": True,
        "NUMBER_SEPARATOR_EXCEPTIONS": [
            "plz-parzelle",
            "plz-gesuchstellerin",
        ],
        "FORM": {
            "_base": {
                "people_sources": [
                    "personalien-gesuchstellerin",
                    "personalien-vertreterin-mit-vollmacht",
                    "personalien-grundeigentumerin",
                    "personalien-gebaudeeigentumerin",
                    "personalien-projektverfasserin",
                ],
                "people_names": {
                    "name-gesuchstellerin": "familyName",
                    "vorname-gesuchstellerin": "givenName",
                    "name-juristische-person-gesuchstellerin": "juristicName",
                    "name-vertreterin": "familyName",
                    "vorname-vertreterin": "givenName",
                    "name-juristische-person-vertreterin": "juristicName",
                    "name-grundeigentuemerin": "familyName",
                    "vorname-grundeigentuemerin": "givenName",
                    "name-juristische-person-grundeigentuemerin": "juristicName",
                    "name-gebaeudeeigentuemerin": "familyName",
                    "vorname-gebaeudeeigentuemerin": "givenName",
                    "name-juristische-person-gebaeudeeigentuemerin": "juristicName",
                    "name-projektverfasserin": "familyName",
                    "vorname-projektverfasserin": "givenName",
                    "name-juristische-person-projektverfasserin": "juristicName",
                },
            },
            "baugesuch": {
                "forms": [
                    *gr_constants.BAUGESUCH_FORMS,
                    "migriertes-dossier",
                ],
                "template": "form",
                "personalien": "personalien",
                "exclude_slugs": [
                    "is-paper",
                    "einreichen-button",
                    "dokumente",
                    "einreichen",
                    "bestaetigung",
                    "gis-map",
                    # eeba questions that are technical and need to be excluded
                    "eeba-confirmation",
                    "eeba-state",
                    "eeba-error",
                    "eeba-integration-id",
                    "eeba-is-dirty",
                    "eeba-link",
                ],
            },
            "bauanzeige": {
                "forms": gr_constants.BAUANZEIGE_FORMS,
                "template": "form",
                "personalien": "personalien",
                "exclude_slugs": [
                    "is-paper",
                    "einreichen-button",
                    "dokumente-ohne-pflichtdokumente",
                    "dokumente-platzhalter",
                    "einreichen",
                    "bestaetigung",
                    "gis-map",
                    # eeba questions that are technical and need to be excluded
                    "eeba-confirmation",
                    "eeba-state",
                    "eeba-error",
                    "eeba-integration-id",
                    "eeba-is-dirty",
                    "eeba-link",
                ],
            },
            "vorlaeufige-beurteilung": {
                "forms": gr_constants.VORLAEUFIGE_BEURTEILUNG_FORMS,
                "template": "form",
                "personalien": "personalien",
                "exclude_slugs": [
                    "is-paper",
                    "einreichen-button",
                    "dokumente-ohne-pflichtdokumente",
                    "dokumente-platzhalter",
                    "einreichen",
                    "bestaetigung",
                    "gis-map",
                    # eeba questions that are technical and need to be excluded
                    "eeba-confirmation",
                    "eeba-state",
                    "eeba-error",
                    "eeba-integration-id",
                    "eeba-is-dirty",
                    "eeba-link",
                ],
            },
            "solaranlage": {
                "forms": gr_constants.SOLARANLAGE_FORMS,
                "template": "form",
                "personalien": "personalien",
                "exclude_slugs": [
                    "is-paper",
                    "einreichen-button",
                    "dokumente-ohne-pflichtdokumente",
                    "dokumente-platzhalter",
                    "einreichen",
                    "bestaetigung",
                    "gis-map",
                    # eeba questions that are technical and need to be excluded
                    "eeba-confirmation",
                    "eeba-state",
                    "eeba-error",
                    "eeba-integration-id",
                    "eeba-is-dirty",
                    "eeba-link",
                ],
            },
        },
        "ALEXANDRIA_DOCUMENT_CATEGORIES": [
            "beilagen-zum-gesuch-grundstuecksangaben",
            "beilagen-zum-gesuch-gutachten-nachweise-begruendungen",
            "beilagen-zum-gesuch-brandschutz",
            "beilagen-zum-gesuch-weitere-gesuchsunterlagen",
            "nachforderung",
        ],
        "FILENAME_ADDITION_MAPPING": {
            "eingabequittung-de": _("Receipt"),
            "eingabequittung-it": _("Receipt"),
            "form": _("Form export"),
        },
    },
    "kt_so": {
        "ENABLED": True,
        "ADD_ADDRESS_DATA": True,
        "USE_NUMBER_SEPARATOR": True,
        "FORM": {
            "_base": {
                "people_sources": [
                    "bauherrin",
                    "grundeigentuemerin",
                    "projektverfasserin",
                ],
                "people_names": {
                    "nachname": "familyName",
                    "vorname": "givenName",
                    "juristische-person-name": "juristicName",
                    "vertretung-nachname": "representationFamilyName",
                    "vertretung-vorname": "representationGivenName",
                    "vertretung-juristische-person-name": "representationJuristicName",
                },
            },
            "baugesuch": {
                "forms": [
                    "baugesuch",
                    "baugesuch-v2",
                    "baugesuch-v3",
                    "erdwaermesonden",
                    "erdwaermesonden-v2",
                    "migriertes-dossier",
                    "voranfrage",
                    "voranfrage-v2",
                    "meldung",
                    "meldung-v2",
                    "meldung-pv",
                    "meldung-pv-v2",
                    "reklamegesuch",
                    "reklamegesuch-v2",
                ],
                "template": "form",
                "personalien": "personalien",
                "exclude_slugs": [
                    # Forms
                    "allgemeine-informationen",
                    "dokumente",
                    "einreichen",
                    # Questions
                    "is-paper",
                    "projektaenderung",
                    "nutzungsplanung-grundnutzung-kanton",
                ],
            },
        },
        "ALEXANDRIA_DOCUMENT_CATEGORIES": [
            "beilagen-zum-gesuch-grundstuecksangaben",
            "beilagen-zum-gesuch-gutachten-nachweise-begruendungen",
            "beilagen-zum-gesuch-projektplaene-projektbeschrieb",
            "beilagen-zum-gesuch-weitere-gesuchsunterlagen",
        ],
        "FILENAME_ADDITION_MAPPING": {
            "signatures": _("Signature page"),
        },
    },
    "kt_uri": {
        "ENABLED": True,
        "FORM": {
            "building-permit": {
                "forms": [
                    "building-permit",
                    "preliminary-clarification",
                    "commercial-permit",
                    "proposal-declaration",
                    "solar-declaration",
                    "cantonal-territory-usage",
                    "technische-bewilligung",
                    "oereb",
                    "mitbericht-kanton",
                    "mitbericht-bund",
                    "bgbb",
                    "archivdossier",
                    "konzession-waermeentnahme",
                    "bohrbewilligung-waermeentnahme",
                    "pgv-gemeindestrasse",
                    "oereb-verfahren-gemeinde",
                    "einfache-anfrage",
                    "gesuch-um-abbruchpraemie",
                    "antrag-auf-auszahlung",
                ],
                "people_sources": [
                    "applicant",
                    "landowner",
                    "project-author",
                ],
                "people_names": {
                    "last-name": "familyName",
                    "first-name": "givenName",
                },
                "template": "2-level-extended",
                "personalien": "personalien",
                "exclude_slugs": [
                    "is-paper",
                    "einreichen",  # Baugesuch and all other
                    "gesuch-einreichen",  # Konzessionsgesuch
                    "gis-karte",
                    "form-type",
                    "allgemeine-informationen-baugesuch",
                    "allgemeine-informationen-reklamegesuch",
                    "allgemeine-informationen-baugesuch-vorabklaerung",
                    "allgemeine-informationen-meldung-solaranlage",
                    "allgemeine-informationen-proposal-declaration",
                    "allgemeine-informationen-cantonal-territory-usage",
                    "allgemeine-informationen-mitbericht-kanton",
                    "allgemeine-informationen-oereb-verfahren",
                    "allgemeine-informationen-mitberichtsverfahren-bund",
                    "parzellen-oder-baurechtsnummer",
                ],
            },
        },
        "ADD_HEADER_DATA": False,
    },
    "kt_ag": {
        "ENABLED": True,
        "USE_NUMBER_SEPARATOR": True,
        "NUMBER_SEPARATOR_EXCEPTIONS": [
            "plz-parzelle",
            "plz-gesuchstellerin",
            "plz",
        ],
        "FORM": {
            "_base": {
                "people_sources": [
                    "personalien-gesuchstellerin",
                    "personalien-vertreterin-mit-vollmacht",
                    "personalien-grundeigentumerin",
                    "personalien-gebaudeeigentumerin",
                ],
                "people_names": {
                    "name-gesuchstellerin": "familyName",
                    "vorname-gesuchstellerin": "givenName",
                    "name-juristische-person-gesuchstellerin": "juristicName",
                    "name-vertreterin": "familyName",
                    "vorname-vertreterin": "givenName",
                    "name-juristische-person-vertreterin": "juristicName",
                    "name-grundeigentuemerin": "familyName",
                    "vorname-grundeigentuemerin": "givenName",
                    "name-juristische-person-grundeigentuemerin": "juristicName",
                    "name-gebaeudeeigentuemerin": "familyName",
                    "vorname-gebaeudeeigentuemerin": "givenName",
                    "name-juristische-person-gebaeudeeigentuemerin": "juristicName",
                    "name-projektverfasserin": "familyName",
                    "vorname-projektverfasserin": "givenName",
                    "name-juristische-person-projektverfasserin": "juristicName",
                },
            },
            "baugesuch": {
                "forms": [
                    "anfrage",
                    *ag_constants.ANFRAGE_INTERN_FORMS,
                    "anfrage-migration",
                    *ag_constants.BAUGESUCH_FORMS,
                    "baugesuch-migration",
                    "internes-dossier",
                    "pgv-migration",
                    *ag_constants.PGV_FORMS,
                    "reklame",
                    "reklame-migration",
                    "uvp-migration",
                    *ag_constants.VORENTSCHEID_FORMS,
                    "vorentscheid-migration",
                ],
                "template": "form",
                "personalien": "personalien",
                "exclude_slugs": [
                    "is-paper",
                    "einreichen-button",
                    "dokumente",
                    "einreichen",
                    "bestaetigung",
                    "gis-map",
                    "eingabequittung",
                ],
            },
        },
        "ALEXANDRIA_DOCUMENT_CATEGORIES": [
            "beilagen-zum-gesuch-grundstuecksangaben",
            "beilagen-zum-gesuch-gutachten-nachweise-begruendungen",
            "beilagen-zum-gesuch-brandschutz",
            "beilagen-zum-gesuch-weitere-gesuchsunterlagen",
        ],
        "FILENAME_ADDITION_MAPPING": {
            "eingabequittung-de": _("Receipt"),
            "form": _("Form"),
        },
    },
    "kt_schwyz": {"ENABLED": True},
}
