PLACEHOLDERS = {
    "default": {
        "LEGAL_SUBMISSIONS": {
            "FORM": "legal-submission-form",
            "LEGAL_CLAIMANTS_TABLE_QUESTION": "legal-submission-legal-claimants-table-question",
        },
        "PERSON_MAPPING": {
            "IS_JURISTIC": "juristische-person-gesuchstellerin",
            "IS_JURISTIC_YES": "juristische-person-gesuchstellerin-ja",
            "JURISTIC_NAME": "name-juristische-person-gesuchstellerin",
            "FIRST_NAME": "vorname-gesuchstellerin",
            "LAST_NAME": "name-gesuchstellerin",
            "STREET": "strasse-gesuchstellerin",
            "STREET_NUMBER": "nummer-gesuchstellerin",
            "ZIP": "plz-gesuchstellerin",
            "TOWN": "ort-gesuchstellerin",
        },
        "INQUIRY_DEFAULT_PROPS": [
            ("service", "NAME"),
            ("deadline", "FRIST"),
            ("creation_date", "ERSTELLT"),
            ("completion_date", "BEANTWORTET"),
        ],
        "INQUIRY_FIELD_MAPPINGS": {
            "opinion": ("inquiry-answer", "STATEMENT"),
            "ancillary_clauses": ("inquiry-answer", "ANCILLARY_CLAUSES"),
            "answer": ("inquiry-answer", "STATUS"),
        },
        "BILLING_ENTRY_FIELDS": ["POSITION", "BETRAG"],
        "PLACEHOLDER_CASE": "upper",  # one of "upper" or "lower"
    },
    "kt_so": {
        "ENABLED": True,
        "LEGAL_SUBMISSIONS": {
            "FORM": "einsprache",
            "LEGAL_CLAIMANTS_TABLE_QUESTION": "einsprache-einsprechende",
        },
        "PERSON_MAPPING": {
            "SALUTATION": "anrede",
            "IS_JURISTIC": "juristische-person",
            "IS_JURISTIC_YES": "juristische-person-ja",
            "JURISTIC_NAME": "juristische-person-name",
            "FIRST_NAME": "vorname",
            "LAST_NAME": "nachname",
            "STREET": "strasse",
            "STREET_NUMBER": "strasse-nummer",
            "ZIP": "plz",
            "TOWN": "ort",
            "HAS_REPRESENTATIVE": "vertretung",
            "HAS_REPRESENTATIVE_YES": "vertretung-ja",
            "IS_REPRESENTATIVE_JURISTIC": "vertretung-juristische-person",
            "IS_REPRESENTATIVE_JURISTIC_YES": "vertretung-juristische-person-ja",
            "REPRESENTATIVE_JURISTIC_NAME": "vertretung-juristische-person-name",
            "REPRESENTATIVE_SALUTATION": "vertretung-anrede",
            "REPRESENTATIVE_TITLE": "vertretung-titel",
            "REPRESENTATIVE_LAST_NAME": "vertretung-nachname",
            "REPRESENTATIVE_FIRST_NAME": "vertretung-vorname",
            "REPRESENTATIVE_STREET": "vertretung-strasse",
            "REPRESENTATIVE_STREET_NUMBER": "vertretung-nummer",
            "REPRESENTATIVE_ZIP": "vertretung-plz",
            "REPRESENTATIVE_TOWN": "vertretung-ort",
            "REPRESENTATIVE_COUNTRY": "vertretung-land",
            "REPRESENTATIVE_EMAIL": "vertretung-e-mail",
            "REPRESENTATIVE_TEL": "vertretung-telefon",
            "REPRESENTATIVE_PO_BOX": "vertretung-postfach",
        },
        "INQUIRY_DEFAULT_PROPS": [
            ("start_date", "DATUM_START"),
            ("end_date", "DATUM_ENDE"),
            ("feedback", "RUECKMELDUNG_FAZIT"),
            ("positive", "ZUSTIMMENDE_BEURTEILUNGEN"),
            ("negative", "ABLEHNENDE_BEURTEILUNGEN"),
            ("additional_demand", "NACHFORDERUNG"),
            ("objections", "EINSPRACHEN"),
            ("notices_applicant", "HINWEISE_AN_GESUCHSTELLERIN"),
            ("notices_authority", "HINWEISE_AN_LEITBEHOERDE"),
            ("notices_arp", "HINWEISE_AN_LEITBEHOERDE_ARP"),
            ("forward", "VERSAND_ENTSCHEID_WEITERE_STELLEN"),
            ("remark", "BEMERKUNGEN"),
            ("creation_date_timestamp", "ERSTELLT_TIMESTAMP"),
            ("completion_date_timestamp", "BEANTWORTET_TIMESTAMP"),
        ],
        "INQUIRY_FIELD_MAPPINGS": {
            "feedback": ("inquiry-answer", "STATUS"),
            "positive": ("inquiry-answer", "POSITIVE"),
            "negative": ("inquiry-answer", "NEGATIVE"),
            "additional_demand": ("inquiry-answer", "ADDITIONAL_DEMAND"),
            "objections": ("inquiry-answer", "OBJECTIONS"),
            "notices_applicant": ("inquiry-answer", "NOTICES_APPLICANT"),
            "notices_authority": ("inquiry-answer", "NOTICES_AUTHORITY"),
            "notices_arp": ("inquiry-answer", "NOTICES_ARP"),
            "forward": ("inquiry-answer", "FORWARD"),
            "remark": ("inquiry", "REMARK"),
        },
        "BILLING_ENTRY_FIELDS": [
            "POSITION",
            "BETRAG",
            "RECHTSGRUNDLAGE",
            "KOSTENSTELLE",
            "STUNDEN",
            "STUNDENSATZ",
            "ANTEIL_PROZENT",
            "GESAMTKOSTEN",
            "BERECHNUNG",
            "MEHRWERTSTEUER",
            "ART",
            "VERRECHNUNG",
            "ORGANISATION",
        ],
    },
    "kt_bern": {"ENABLED": True},
    "kt_gr": {
        "ENABLED": True,
        "INQUIRY_FIELD_MAPPINGS": {
            "situation": ("inquiry-answer", "SITUATION"),
            "considerations": ("inquiry-answer", "CONSIDERATIONS"),
            "statement": ("inquiry-answer", "STATEMENT"),
            "ancillary_clauses": ("inquiry-answer", "ANCILLARY_CLAUSES"),
            "comments": ("inquiry-answer", "COMMENTS"),
        },
    },
    "kt_uri": {
        "ENABLED": True,
        "INQUIRY_FIELD_MAPPINGS": {
            "clerk_decision": ("inquiry-answer", "CLERK_DECISION"),
        },
    },
    "kt_ag": {
        "ENABLED": True,
        "INQUIRY_DEFAULT_PROPS": [
            ("remarks", "BEMERKUNGEN"),
        ],
        "INQUIRY_FIELD_MAPPINGS": {
            "remarks": ("inquiry-answer", "STATEMENT"),
        },
        "BILLING_ENTRY_FIELDS": [
            "POSITION",
            "BETRAG",
            "BEMERKUNG",
            "VERRECHNET_AM",
        ],
    },
    "kt_sg": {"ENABLED": True},
    "kt_schwyz": {
        "ENABLED": True,
        "PLACEHOLDER_CASE": "lower",
        "INQUIRY_DEFAULT_PROPS": [
            # Selects and maps Inquiry attributes to alias
            # <Inquiry attr>, <ALIAS>
            ("deadline", "FRIST"),
            ("notices", "MELDUNGEN"),
            ("end_date", "DATUM_ENDE"),
            ("start_date", "DATUM_START"),
            ("reason", "REASON"),
            ("circulation_state", "ZIRKULATION_STATUS"),
            ("circulation_answer", "ZIRKULATION_ANTWORT"),
            ("service", "FACHSTELLE"),
        ],
        "INQUIRY_FIELD_MAPPINGS": {
            # "<PROP>": (["inquiry"|"inquiry-answer"], "<distribution question answer slug>")
            # `slug` is an allcaps key in settings.DISTRIBUTION['QUESTIONS'] associating a question-slug
            "reason": ("inquiry", "REMARK"),
            "circulation_answer": ("inquiry-answer", "STATUS"),
            # `notices`
            "request": ("inquiry-answer", "REQUEST"),
            "ancillary_clauses": ("inquiry-answer", "ANCILLARY_CLAUSES"),
            "answer_reason": ("inquiry-answer", "REASON"),
            "recommendation": ("inquiry-answer", "RECOMMENDATION"),
            "hint": ("inquiry-answer", "HINT"),
        },
        "BILLING_ENTRY_FIELDS": [
            "POSITION",
            "BETRAG",
            "VERRECHNET_AM",
            "ART",
            "BEMERKUNG",
        ],
    },
    "test": {"ENABLED": True},
}
