PLACEHOLDERS = {
    "default": {
        "LEGAL_SUBMISSIONS": {
            "FORM": "legal-submission-form",
            "LEGAL_CLAIMANTS_TABLE_QUESTION": "legal-submission-legal-claimants-table-question",
        },
        "PERSON_MAPPING": {
            "IS_JURISTIC": "juristische-person-gesuchstellerin",
            "IS_JURISTIC_YES": "juristische-person-gesuchstellerin-ja",
            "JURISTIC_NAME": "name-juristische-person-gesuchstellerin",
            "FIRST_NAME": "vorname-gesuchstellerin",
            "LAST_NAME": "name-gesuchstellerin",
            "STREET": "strasse-gesuchstellerin",
            "STREET_NUMBER": "nummer-gesuchstellerin",
            "ZIP": "plz-gesuchstellerin",
            "TOWN": "ort-gesuchstellerin",
        },
    },
    "kt_so": {
        "ENABLED": True,
        "LEGAL_SUBMISSIONS": {
            "FORM": "einsprache",
            "LEGAL_CLAIMANTS_TABLE_QUESTION": "einsprache-einsprechende",
        },
        "PERSON_MAPPING": {
            "SALUTATION": "anrede",
            "IS_JURISTIC": "juristische-person",
            "IS_JURISTIC_YES": "juristische-person-ja",
            "JURISTIC_NAME": "juristische-person-name",
            "FIRST_NAME": "vorname",
            "LAST_NAME": "nachname",
            "STREET": "strasse",
            "STREET_NUMBER": "strasse-nummer",
            "ZIP": "plz",
            "TOWN": "ort",
            "HAS_REPRESENTATIVE": "vertretung",
            "HAS_REPRESENTATIVE_YES": "vertretung-ja",
            "IS_REPRESENTATIVE_JURISTIC": "vertretung-juristische-person",
            "IS_REPRESENTATIVE_JURISTIC_YES": "vertretung-juristische-person-ja",
            "REPRESENTATIVE_JURISTIC_NAME": "vertretung-juristische-person-name",
            "REPRESENTATIVE_SALUTATION": "vertretung-anrede",
            "REPRESENTATIVE_TITLE": "vertretung-titel",
            "REPRESENTATIVE_LAST_NAME": "vertretung-nachname",
            "REPRESENTATIVE_FIRST_NAME": "vertretung-vorname",
            "REPRESENTATIVE_STREET": "vertretung-strasse",
            "REPRESENTATIVE_STREET_NUMBER": "vertretung-nummer",
            "REPRESENTATIVE_ZIP": "vertretung-plz",
            "REPRESENTATIVE_TOWN": "vertretung-ort",
            "REPRESENTATIVE_COUNTRY": "vertretung-land",
            "REPRESENTATIVE_EMAIL": "vertretung-e-mail",
            "REPRESENTATIVE_TEL": "vertretung-telefon",
            "REPRESENTATIVE_PO_BOX": "vertretung-postfach",
        },
    },
    "kt_bern": {"ENABLED": True},
    "kt_gr": {"ENABLED": True},
    "test": {"ENABLED": True},
}
