from django.db.models import F

from camac.settings.ebau_schema import ModuleConfig
from camac.settings.modules.work_item_list_schema import (
    AnnotationsConfig,
    WorkItemListConfig,
)

WORK_ITEM_LIST = ModuleConfig[WorkItemListConfig](
    default=WorkItemListConfig(),
    kt_ag=WorkItemListConfig(
        enabled=True,
        available_tasks_include_count=True,
        available_tasks_include_templates=True,
        available_tasks_for_role={
            "municipality": [
                "formal-exam",
                "publication",
                "information-of-neighbors",
                "init-distribution",
                "check-inquiries",
                "decision",
                "check-distribution",
                "init-construction-monitoring",
                "withdrawal-check",
                "check-additional-demand",
                "construction-step-baufreigabe",
                "construction-step-kanalisation-kontrollieren",
                "construction-step-plan-construction-stage",
                "construction-step-rohbau-kontrollieren",
                "construction-step-schlussabnahme-gebaeude",
                "construction-step-schlussabnahme-projekt",
                "construction-step-schlussabnahme-projekt-planen",
                "construction-step-schnurgeruestabnahme-planen",
                "construction-step-schnurgeruest-kontrollieren",
                "construction-step-zwischenkontrolle",
                "complete-instance",
            ],
            "service": ["inquiry", "check-inquiries"],
            "subservice": ["inquiry"],
        },
        available_tasks_for_service_group={
            "service-afb": [
                "check-pa",
                "cantonal-exam",
                "check-document-supplement",
                "trigger-billing",
            ],
        },
    ),
    kt_so=WorkItemListConfig(
        enabled=True,
        annotations=AnnotationsConfig(
            description="umschreibung-bauprojekt",
            applicants=None,
        ),
        available_tasks_include_count=True,
        available_tasks_include_templates=True,
        available_tasks_for_role={
            "municipality": [
                "formal-exam",
                "material-exam",
                "material-exam-bab",
                "publication",
                "init-distribution",
                "check-inquiries",
                "decision",
                "appeal",
                "objections",
                "check-distribution",
                "init-construction-monitoring",
                "construction-step-baubeginn-melden",
                "construction-step-baufreigabe",
                "construction-step-baufreigabe-beantragen",
                "construction-step-kanalisation-kontrollieren",
                "construction-step-kanalisationsabnahme-melden",
                "construction-step-plan-construction-stage",
                "construction-step-rohbauabnahme-melden",
                "construction-step-rohbau-kontrollieren",
                "construction-step-schlussabnahme-gebaeude",
                "construction-step-schlussabnahme-gebaeude-melden",
                "construction-step-schlussabnahme-projekt",
                "construction-step-schlussabnahme-projekt-melden",
                "construction-step-schlussabnahme-projekt-planen",
                "construction-step-schnurgeruestabnahme-melden",
                "construction-step-schnurgeruestabnahme-planen",
                "construction-step-schnurgeruest-kontrollieren",
                "construction-step-zwischenkontrolle",
                "construction-step-zwischenkontrolle-melden",
                "complete-instance",
                "complete-construction-monitoring",
            ],
            "service": ["inquiry", "check-inquiries"],
            "subservice": ["inquiry"],
        },
    ),
    kt_gr=WorkItemListConfig(
        enabled=True,
        available_tasks_for_role={
            "municipality": [
                "formal-exam",
                "publication",
                "init-distribution",
                "check-inquiries",
                "decision",
                "construction-acceptance",
            ],
            "service": ["inquiry", "check-inquiries", "check-additional-demand"],
            "subservice": ["inquiry"],
            "uso": ["inquiry"],
        },
        annotations=AnnotationsConfig(
            description=["beschreibung-projektaenderung", "beschreibung-bauvorhaben"],
        ),
    ),
    kt_schwyz=WorkItemListConfig(
        enabled=True,
        available_tasks_include_count=True,
        available_tasks_for_role={
            "municipality": [
                "complete-check",
                "init-distribution",
                "make-decision",
                "init-construction-monitoring",
                "complete-instance",
            ],
            "service": [
                "fill-inquiry",
                "inquiry",
                "check-inquiry",
                "alter-inquiry",
                "check-inquiries",
            ],
        },
        annotations=AnnotationsConfig(
            special_id=F("case__family__instance__identifier"),
            municipality=None,
            applicants=None,
        ),
    ),
)
