import Config

# Configure your database
# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
#
# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#

config :ebau, EbauWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "YQJEbV4PNghnQm7rjjkYtkiA/8yNipPpJRpBr4ITfEFO18jPiG77iUyguVY0dvjL",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ebau, ~w(--sourcemap=inline --watch)]},
    sass: {
      DartSass,
      :install_and_run,
      [:default, ~w(--embed-source-map --source-map-urls=absolute --watch)]
    }
  ]

# Reload browser tabs when matching files change.
config :ebau, EbauWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/ebau_web/router\.ex$",
      ~r"lib/ebau_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
config :ebau, dev_routes: true, token_signing_secret: "YoorlwyimV6kp8MGl5f74PhXVqJGvD4P"

# Do not include metadata nor timestamps in development logs
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# If desired, both `http:` and `https:` keys can be
# in production as building large stacktraces may be expensive.
# configured to run both http and https servers on
# different ports.
# Include debug annotations and locations in rendered markup.
# Changing this configuration will require mix clean and a full recompile.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
