# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20181119_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeExporterDocx',
            fields=[
                ('officeexporter_docx_id', models.AutoField(db_column='OFFICEEXPORTER_DOCX_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=100, null=True)),
                ('php_class', models.CharField(db_column='PHP_CLASS', max_length=100)),
            ],
            options={
                'db_table': 'OFFICEEXPORTER_DOCX',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfficeExporterDocxLog',
            fields=[
                ('officeexporter_docx_log_id', models.AutoField(db_column='OFFICEEXPORTER_DOCX_LOG_ID', primary_key=True, serialize=False)),
                ('modification_date', models.DateTimeField(db_column='MODIFICATION_DATE')),
                ('user_id', models.IntegerField(db_column='USER_ID')),
                ('action', models.CharField(db_column='ACTION', max_length=500)),
                ('data', models.TextField(db_column='DATA')),
                ('id', models.IntegerField(db_column='ID')),
            ],
            options={
                'db_table': 'OFFICEEXPORTER_DOCX_LOG',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfficeExporterDocxRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeexporter_docx', models.ForeignKey(db_column='OFFICEEXPORTER_DOCX_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='officeexporter.OfficeExporterDocx')),
                ('role', models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.Role')),
            ],
            options={
                'db_table': 'OFFICEEXPORTER_DOCX_ROLE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfficeExporterDocxT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_column='LANGUAGE', max_length=2)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('officeexporter_docx', models.ForeignKey(db_column='OFFICEEXPORTER_DOCX_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='officeexporter.OfficeExporterDocx')),
            ],
            options={
                'db_table': 'OFFICEEXPORTER_DOCX_T',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='officeexporterdocxt',
            unique_together=set([('officeexporter_docx', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='officeexporterdocxrole',
            unique_together=set([('officeexporter_docx', 'role')]),
        ),
    ]
