# Generated by Django 3.2.19 on 2023-08-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GISConfig',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('client', models.CharField(choices=[('camac.gis.clients.sogis.SoGisClient', 'GIS Canton Solothurn'), ('camac.gis.clients.param.ParamClient', 'Parameter')], max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
