# Generated by Django 3.2.19 on 2023-08-25 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GISDataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "client",
                    models.CharField(
                        choices=[
                            (
                                "camac.gis.clients.sogis.SoGisClient",
                                "GIS Canton Solothurn",
                            ),
                            ("camac.gis.clients.param.ParamGisClient", "Parameter"),
                            (
                                "camac.gis.clients.admin.AdminGisClient",
                                "Federal GIS Switzerland",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("disabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="GISConfig",
        ),
    ]
