# Generated by Django 3.2.19 on 2023-10-24 07:06

import camac.gis.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0003_alter_gisdatasource_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="gisdatasource",
            name="sort",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gisdatasource",
            name="sort",
            field=models.IntegerField(default=camac.gis.models.next_datasource_sort),
        ),
        migrations.AlterModelOptions(
            name="gisdatasource",
            options={"ordering": ["sort"]},
        ),
        migrations.AlterField(
            model_name="gisdatasource",
            name="client",
            field=models.CharField(
                choices=[
                    ("camac.gis.clients.sogis.SoGisClient", "GIS Canton Solothurn"),
                    ("camac.gis.clients.gr.GrGisClient", "GIS Canton GR"),
                    ("camac.gis.clients.param.ParamGisClient", "Parameter"),
                    ("camac.gis.clients.ech_0206.Ech0206", "Ech0206"),
                    (
                        "camac.gis.clients.admin.AdminGisClient",
                        "Federal GIS Switzerland",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
