# Generated by Django 3.2.19 on 2023-11-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0004_gisdatasource_add_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisdatasource',
            name='client',
            field=models.CharField(choices=[('camac.gis.clients.sogis.SoGisClient', 'GIS Canton Solothurn'), ('camac.gis.clients.gr.GrGisClient', 'GIS Canton GR'), ('camac.gis.clients.begis.BeGisClient', 'GIS Canton Bern'), ('camac.gis.clients.param.ParamGisClient', 'Parameter'), ('camac.gis.clients.ech_0206.Ech0206', 'Ech0206'), ('camac.gis.clients.admin.AdminGisClient', 'Federal GIS Switzerland')], max_length=255),
        ),
    ]
