# Generated by Django 4.2.16 on 2025-01-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0005_alter_gisdatasource_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisdatasource',
            name='client',
            field=models.CharField(choices=[('camac.gis.clients.sogis.SoGisClient', 'GIS Canton Solothurn'), ('camac.gis.clients.gr.GrGisClient', 'GIS Canton GR'), ('camac.gis.clients.ag.AgGisClient', 'GIS Canton AG'), ('camac.gis.clients.begis.BeGisClient', 'GIS Canton Bern'), ('camac.gis.clients.param.ParamGisClient', 'Parameter'), ('camac.gis.clients.ech_0206.Ech0206', 'Ech0206'), ('camac.gis.clients.admin.AdminGisClient', 'Federal GIS Switzerland')], max_length=255),
        ),
    ]
