mutation CreateInternalWorkflow {
  saveWorkflow(
    input: {
      slug: "internal"
      name: "Internes Verfahren"
      startTasks: ["submit"]
      allowForms: [
        "baupolizeiliches-verfahren"
        "baupolizeiliches-verfahren-v2"
        "zutrittsermaechtigung"
        "zutrittsermaechtigung-v2"
      ]
      isPublished: true
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlow {
  addWorkflowFlow(
    input: {
      workflow: "internal"
      tasks: ["submit"]
      next: "['ebau-number', 'audit', 'init-additional-demand', 'decision', 'create-manual-workitems']|tasks"
    }
  ) {
    clientMutationId
  }
}
