repos:
-   repo: local
    hooks:
    - id: ruff-check-and-fix
      stages: [pre-commit]
      name: fix style and imports
      language: system
      entry: ruff check --fix
      types: [python]
      pass_filenames: true
    - id: ruff-format
      stages: [pre-commit]
      name: format code
      language: system
      entry: ruff format
      args: ["--config", "django/pyproject.toml", "--isolated", "--force-exclude"]
      types: [python]
      pass_filenames: true
