# Generated by Django 4.2.20 on 2025-04-23 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0029_user_and_service_new_attributes'),
        ('caluma_form', '0049_uuid_v7'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleUserRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('application_types', models.ManyToManyField(blank=True, to='caluma_form.form')),
                ('municipalities', models.ManyToManyField(blank=True, to='user.service')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.service')),
            ],
            options={
                'ordering': ['sort'],
                'indexes': [models.Index(fields=['sort'], name='rulesets_re_sort_2e7c5b_idx')],
                'unique_together': {('service', 'sort')},
            },
        ),
    ]
