# Generated by Django 4.2.20 on 2025-07-30 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_user_division'),
        ('rulesets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionDeadlineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(365)])),
                ('source_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.service')),
                ('target_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.service')),
            ],
            options={
                'unique_together': {('source_service', 'target_service')},
            },
        ),
    ]
