/*
 * This will copy all "Baugesuch" activations (file, page, service) into
 * other similar forms ("Vorabklärung vollständig", "Generelles Baugesuch", "Baugesuch mit UVP", "Projekt änderungen")
 *
 * Usage:
 *		1. make dbshell on root directory
 *	    2. copy all scripts into the bash
 *		3. run
 *	    4. always check before committing your changes
 */

-- FILE ANSWER ACTIVATION
INSERT INTO "FILE_CONTENT_REQUIRED" ("FORM_ID", "CHAPTER_ID", "QUESTION_ID", "FILE_CONTENT_ID", "ANSWER", "ALWAYS_REQUIRED")
SELECT
	40001,
	"CHAPTER_ID",
	"QUESTION_ID",
    "FILE_CONTENT_ID",
	"ANSWER",
	"ALWAYS_REQUIRED"
FROM "FILE_CONTENT_REQUIRED"
WHERE "FORM_ID" = 1;

INSERT INTO "FILE_CONTENT_REQUIRED" ("FORM_ID", "CHAPTER_ID", "QUESTION_ID", "FILE_CONTENT_ID", "ANSWER", "ALWAYS_REQUIRED")
SELECT
	40002 ,
	"CHAPTER_ID",
	"QUESTION_ID",
    "FILE_CONTENT_ID",
	"ANSWER",
	"ALWAYS_REQUIRED"
FROM "FILE_CONTENT_REQUIRED"
WHERE "FORM_ID" = 1;

INSERT INTO "FILE_CONTENT_REQUIRED" ("FORM_ID", "CHAPTER_ID", "QUESTION_ID", "FILE_CONTENT_ID", "ANSWER", "ALWAYS_REQUIRED")
SELECT
	110001 ,
	"CHAPTER_ID",
	"QUESTION_ID",
    "FILE_CONTENT_ID",
	"ANSWER",
	"ALWAYS_REQUIRED"
FROM "FILE_CONTENT_REQUIRED"
WHERE "FORM_ID" = 1;


-- PAGE ANSWER ACTIVATION
INSERT INTO "PAGE_ANSWER_ACTIVATION" ("FORM_ID", "PAGE_ID", "CHAPTER_ID", "QUESTION_ID", "ANSWER")
SELECT
	40001,
	"PAGE_ID",
	"CHAPTER_ID",
	"QUESTION_ID",
	"ANSWER"
FROM "PAGE_ANSWER_ACTIVATION"
WHERE "FORM_ID" = 1;

INSERT INTO "PAGE_ANSWER_ACTIVATION" ("FORM_ID", "PAGE_ID", "CHAPTER_ID", "QUESTION_ID", "ANSWER")
SELECT
	40002,
	"PAGE_ID",
	"CHAPTER_ID",
	"QUESTION_ID",
	"ANSWER"
FROM "PAGE_ANSWER_ACTIVATION"
WHERE "FORM_ID" = 1;

INSERT INTO "PAGE_ANSWER_ACTIVATION" ("FORM_ID", "PAGE_ID", "CHAPTER_ID", "QUESTION_ID", "ANSWER")
SELECT
	110001,
	"PAGE_ID",
	"CHAPTER_ID",
	"QUESTION_ID",
	"ANSWER"
FROM "PAGE_ANSWER_ACTIVATION"
WHERE "FORM_ID" = 1;

-- SERVICE ANSWER ACTIVATION
INSERT INTO "SERVICE_ANSWER_ACTIVATION" ("FORM_ID", "SERVICE_ID", "CHAPTER_ID", "QUESTION_ID", "ANSWER")
SELECT
	40001,
	"SERVICE_ID",
	"CHAPTER_ID",
	"QUESTION_ID",
	"ANSWER"
FROM "SERVICE_ANSWER_ACTIVATION"
WHERE "FORM_ID" = 1;

INSERT INTO "SERVICE_ANSWER_ACTIVATION" ("FORM_ID", "SERVICE_ID", "CHAPTER_ID", "QUESTION_ID", "ANSWER")
SELECT
	40002,
	"SERVICE_ID",
	"CHAPTER_ID",
	"QUESTION_ID",
	"ANSWER"
FROM "SERVICE_ANSWER_ACTIVATION"
WHERE "FORM_ID" = 1;

INSERT INTO "SERVICE_ANSWER_ACTIVATION" ("FORM_ID", "SERVICE_ID", "CHAPTER_ID", "QUESTION_ID", "ANSWER")
SELECT
	110001,
	"SERVICE_ID",
	"CHAPTER_ID",
	"QUESTION_ID",
	"ANSWER"
FROM "SERVICE_ANSWER_ACTIVATION"
WHERE "FORM_ID" = 1;
