# Generated by Django 3.2.19 on 2023-11-20 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceacl',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='At this time, the ACL becomes valid'),
        ),
    ]
