# Generated by Django 3.2.23 on 2024-02-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_instanceacl_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevel',
            name='applicable_area',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('APPLICANT', 'Applicant'), ('INTERNAL', 'Internal'), ('ANY', 'Any')], default='ANY', max_length=50),
        ),
    ]
