# Generated by Django 3.2.25 on 2024-04-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_service_logo'),
        ('permissions', '0003_accesslevel_applicable_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceacl',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_acls', to='user.role'),
        ),
        migrations.AlterField(
            model_name='accesslevel',
            name='required_grant_type',
            field=models.CharField(blank=True, choices=[('SERVICE', 'Service'), ('ROLE', 'Role'), ('USER', 'User'), ('AUTHENTICATED_PUBLIC', 'Authenticated Public'), ('ANONYMOUS_PUBLIC', 'Anonymous Public'), ('TOKEN', 'Token')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instanceacl',
            name='grant_type',
            field=models.CharField(choices=[('SERVICE', 'Service'), ('ROLE', 'Role'), ('USER', 'User'), ('AUTHENTICATED_PUBLIC', 'Authenticated Public'), ('ANONYMOUS_PUBLIC', 'Anonymous Public'), ('TOKEN', 'Token')], max_length=50),
        ),
    ]
