# Generated by Django 5.2.8 on 2026-01-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_role_permissions'),
        ('user', '0039_role_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceacl',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acls', to='user.servicegroup'),
        ),
        migrations.AlterField(
            model_name='accesslevel',
            name='required_grant_type',
            field=models.CharField(blank=True, choices=[('SERVICE', 'Service'), ('SERVICE_GROUP', 'Service Group'), ('ROLE', 'Role'), ('USER', 'User'), ('AUTHENTICATED_PUBLIC', 'Authenticated Public'), ('ANONYMOUS_PUBLIC', 'Anonymous Public'), ('TOKEN', 'Token')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instanceacl',
            name='grant_type',
            field=models.CharField(choices=[('SERVICE', 'Service'), ('SERVICE_GROUP', 'Service Group'), ('ROLE', 'Role'), ('USER', 'User'), ('AUTHENTICATED_PUBLIC', 'Authenticated Public'), ('ANONYMOUS_PUBLIC', 'Anonymous Public'), ('TOKEN', 'Token')], max_length=50),
        ),
    ]
