query GetPublications(
  $instanceId: GenericScalar!
  $task: ID!
  $dateQuestions: [ID]!
) {
  allWorkItems(
    filter: [
      { task: $task }
      { status: SKIPPED, invert: true }
      { status: CANCELED, invert: true }
      { caseMetaValue: { key: "camac-instance-id", value: $instanceId } }
    ]
    order: [{ attribute: CREATED_AT }]
  ) {
    edges {
      node {
        id
        status
        createdAt
        closedByUser
        meta
        document {
          id
          form {
            id
            name
          }
          answers(filter: [{ questions: $dateQuestions }]) {
            edges {
              node {
                id
                question {
                  slug
                }
                ... on DateAnswer {
                  value
                }
              }
            }
          }
        }
      }
    }
  }
}
