query GetPublication($id: ID!) {
  node(id: $id) {
    id
    ... on WorkItem {
      status
      meta
      addressedGroups
      document {
        id
      }
      case {
        id
        meta
        family {
          id
          meta
          document {
            id
            form {
              name
            }
            answers {
              edges {
                node {
                  ... on StringAnswer {
                    value
                  }
                  question {
                    id
                    slug
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
