query GetWorkItemOfTask(
  $instanceId: GenericScalar!
  $task: ID!
  $status: Status = CANCELED
  $invert: Boolean = true
) {
  allWorkItems(
    filter: [
      { rootCaseMetaValue: { key: "camac-instance-id", value: $instanceId } }
      { task: $task }
      { status: $status, invert: $invert }
    ]
    first: 1
  ) {
    edges {
      node {
        id
        status
        addressedGroups
        task {
          slug
          meta
        }
        document {
          id
          form {
            slug
          }
        }
      }
    }
  }
}
