
<div class="table-container column column-100%">
	<div class="title">
		<ul>
			<li class="type">
				<span class="icon icon-info"  aria-hidden="true"></span>
			</li>
			<li class="active">
				<a href="javascript:void(0)">
					<span class="icon icon-puzzle"  aria-hidden="true"></span>
					<?php echo $this->translate("Attachment Type") ?>
				</a>
			</li>
		</ul>
		<div class="help">
			<a href="javascript:void(0)">
				<span class="icon icon-question"  aria-hidden="true"></span>
			</a>
			<div class="tooltip">
				<p>
					<?php echo $this->translate('The actions are availables through a context menu. Right click to trigger the context menu.') ?><br/>
				</p>
			</div>
		</div>
	</div>

	<table class="datatables context-menu attachmenttype" data-menu="attachmenttype" data-display-length="25" data-disable-sorting="1">
		<thead>
			<tr>
				<th class="no-sort">
					<?php echo $this->translate('ID') ?>
				</th>
				<th class="no-sort">
					<?php echo $this->translate('Name') ?>
				</th>
			</tr>
		</thead>
		<tbody>
			<?php if (count($this->rows)): ?>
				<?php foreach ($this->rows as $row) : ?>
					<tr data-id="<?php echo $row->attachmentTypeId ?>">
						<td>
							<?php echo $this->escape($row->attachmentTypeId) ?>
						</td>
						<td>
							<?php echo $this->escape($row->name) ?>
						</td>
					</tr>
				<?php endforeach ?>
			<?php else : ?>
				<tr class="alert information">
					<td class="empty" colspan="1">
						<span aria-hidden="true" class="icon-info"></span>
						<?php echo $this->translate('No attachment types found.') ?>
					</td>
					<td class="empty"></td>
				</tr>
			<?php endif ?>
		</tbody>
	</table>
</div>

<ul class="attachmenttype-menu context-menu">
	<li>
		<span><?php echo $this->translate('Attachment types') ?></span>
	</li>
	<li class="edit-only">
		<a href="<?php echo $this->url(array(
				'controller' => 'module_data-loader',
				'action'     => 'edit',
				'module-id'  => 'documents',
				'data-id'    => 'attachmenttype',
				'id'         => '%id'
			));?>">
			<span class="icon-pencil"></span>
			<?php echo $this->translate('Edit') ?>
		</a>
	</li>
	<li class="edit-only" data-confirm-dialog="true"
		data-title="<?php echo $this->translate('attachment type') ?>"
		data-confirm-message="<?php echo $this->translate('Are you sure you want to delete this type?') ?>">
	<a href="<?php echo $this->url(array(
				"controller" => 'module_data-loader',
				"action"     => "delete",
				"module-id"  => "documents",
				"data-id"    => "attachmenttype",
				"id"         => '%id'
			))?>">
			<span class="icon-remove"></span>
			<?php echo $this->translate('Delete') ?>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array(
				'controller' => 'module_data-loader',
				'action'     => 'add',
				'module-id'  => 'documents',
				'data-id'    => 'attachmenttype')) ?>">
			<span class="icon-plus"></span>
			<?php echo $this->translate('Add') ?>
		</a>
	</li>
</ul>
