# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RApiList',
            fields=[
                ('resource_id', models.AutoField(db_column='RESOURCE_ID', primary_key=True, serialize=False)),
                ('instance_states', models.CharField(db_column='INSTANCE_STATES', max_length=100)),
            ],
            options={
                'db_table': 'R_API_LIST',
                'managed': True,
            },
        ),
    ]
