# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RApiList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_state', models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState')),
                ('resource', models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Resource')),
            ],
            options={
                'db_table': 'R_API_LIST',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='rapilist',
            unique_together=set([('resource', 'instance_state')]),
        ),
    ]
