# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180423_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorityauthoritytype',
            unique_together=set([]),
        ),
    ]
