# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180423_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingentry',
            name='user_id',
        ),
        migrations.AddField(
            model_name='billingentry',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='predefined',
            field=models.PositiveSmallIntegerField(db_column='PREDEFINED', default=0),
        ),
        migrations.AlterField(
            model_name='billingentry',
            name='billing_account',
            field=models.ForeignKey(db_column='BILLING_ACCOUNT_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BillingAccount'),
        ),
        migrations.AlterField(
            model_name='billingentry',
            name='created',
            field=models.DateTimeField(db_column='CREATED'),
        ),
        migrations.AlterField(
            model_name='billingentry',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_entries', to='instance.Instance'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='activation',
            field=models.ForeignKey(db_column='ACTIVATION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notices', to='core.Activation'),
        ),
    ]
