# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('core', '0002_auto_20180112_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='finished_by_user',
            field=models.ForeignKey(blank=True, db_column='FINISHED_BY_USER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanction',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruseracl',
            name='resource',
            field=models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Resource'),
        ),
        migrations.AddField(
            model_name='ruseracl',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rserviceacl',
            name='resource',
            field=models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Resource'),
        ),
        migrations.AddField(
            model_name='rserviceacl',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='rsearchfilter',
            name='question',
            field=models.ForeignKey(blank=True, db_column='QUESTION_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='rroleacl',
            name='resource',
            field=models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Resource'),
        ),
        migrations.AddField(
            model_name='rroleacl',
            name='role',
            field=models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='role_parent',
            field=models.ForeignKey(blank=True, db_column='ROLE_PARENT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Role'),
        ),
        migrations.AddField(
            model_name='rgroupacl',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group'),
        ),
        migrations.AddField(
            model_name='rgroupacl',
            name='resource',
            field=models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='available_resource',
            field=models.ForeignKey(db_column='AVAILABLE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AvailableResource'),
        ),
        migrations.AddField(
            model_name='questionchapteruseracl',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='questionchapteruseracl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='questionchapteruseracl',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='questionchapteruseracl',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionchapterserviceacl',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='questionchapterserviceacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='questionchapterserviceacl',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='questionchapterserviceacl',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='questionchapterroleacl',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='questionchapterroleacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='questionchapterroleacl',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='questionchapterroleacl',
            name='role',
            field=models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Role'),
        ),
        migrations.AddField(
            model_name='questionchaptergroupacl',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='questionchaptergroupacl',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group'),
        ),
        migrations.AddField(
            model_name='questionchaptergroupacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='questionchaptergroupacl',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='questionchapter',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='questionchapter',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_query',
            field=models.ForeignKey(blank=True, db_column='ANSWER_QUERY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AnswerQuery'),
        ),
        migrations.AddField(
            model_name='question',
            name='mapping',
            field=models.ForeignKey(blank=True, db_column='MAPPING_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Mapping'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(db_column='QUESTION_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.QuestionType'),
        ),
        migrations.AddField(
            model_name='publicationentry',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='proposalactivation',
            name='circulation_state',
            field=models.ForeignKey(db_column='CIRCULATION_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationState'),
        ),
        migrations.AddField(
            model_name='proposalactivation',
            name='circulation_type',
            field=models.ForeignKey(db_column='CIRCULATION_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationType'),
        ),
        migrations.AddField(
            model_name='proposalactivation',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='proposalactivation',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='pageformuseracl',
            name='form',
            field=models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageForm'),
        ),
        migrations.AddField(
            model_name='pageformuseracl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='pageformuseracl',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageForm'),
        ),
        migrations.AddField(
            model_name='pageformuseracl',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageformserviceacl',
            name='form',
            field=models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageForm'),
        ),
        migrations.AddField(
            model_name='pageformserviceacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='pageformserviceacl',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageForm'),
        ),
        migrations.AddField(
            model_name='pageformserviceacl',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='pageformroleacl',
            name='form',
            field=models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageForm'),
        ),
        migrations.AddField(
            model_name='pageformroleacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='pageformroleacl',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageForm'),
        ),
        migrations.AddField(
            model_name='pageformroleacl',
            name='role',
            field=models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Role'),
        ),
        migrations.AddField(
            model_name='pageformgroupacl',
            name='form',
            field=models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageForm'),
        ),
        migrations.AddField(
            model_name='pageformgroupacl',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group'),
        ),
        migrations.AddField(
            model_name='pageformgroupacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='pageformgroupacl',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageForm'),
        ),
        migrations.AddField(
            model_name='pageform',
            name='form',
            field=models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Form'),
        ),
        migrations.AddField(
            model_name='pageform',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Page'),
        ),
        migrations.AddField(
            model_name='pageform',
            name='page_form_group',
            field=models.ForeignKey(blank=True, db_column='PAGE_FORM_GROUP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageFormGroup'),
        ),
        migrations.AddField(
            model_name='pageform',
            name='page_form_mode',
            field=models.ForeignKey(db_column='PAGE_FORM_MODE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageFormMode'),
        ),
        migrations.AddField(
            model_name='pageansweractivation',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='pageansweractivation',
            name='form',
            field=models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageForm'),
        ),
        migrations.AddField(
            model_name='pageansweractivation',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageForm'),
        ),
        migrations.AddField(
            model_name='pageansweractivation',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='circulation_type',
            field=models.ForeignKey(db_column='CIRCULATION_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationType'),
        ),
        migrations.AddField(
            model_name='noticeimage',
            name='activation',
            field=models.ForeignKey(db_column='ACTIVATION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Activation'),
        ),
        migrations.AddField(
            model_name='noticeimage',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='noticeimage',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='activation',
            field=models.ForeignKey(db_column='ACTIVATION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Activation'),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.ForeignKey(db_column='NOTICE_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.NoticeType'),
        ),
        migrations.AddField(
            model_name='letterimage',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='letterimage',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.InstanceResource'),
        ),
        migrations.AddField(
            model_name='letterimage',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='letter',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='letter',
            name='ir_editletter_answer',
            field=models.ForeignKey(blank=True, db_column='IR_EDITLETTER_ANSWER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.IrEditletterAnswer'),
        ),
        migrations.AddField(
            model_name='letter',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iruseracl',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.InstanceResource'),
        ),
        migrations.AddField(
            model_name='iruseracl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='iruseracl',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='irserviceacl',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.InstanceResource'),
        ),
        migrations.AddField(
            model_name='irserviceacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='irserviceacl',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='irroleacl',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.InstanceResource'),
        ),
        migrations.AddField(
            model_name='irroleacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='irroleacl',
            name='role',
            field=models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Role'),
        ),
        migrations.AddField(
            model_name='irgroupacl',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group'),
        ),
        migrations.AddField(
            model_name='irgroupacl',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.InstanceResource'),
        ),
        migrations.AddField(
            model_name='irgroupacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='ireditcirculationsg',
            name='service_group',
            field=models.ForeignKey(db_column='SERVICE_GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ServiceGroup'),
        ),
        migrations.AddField(
            model_name='instanceresourceaction',
            name='available_action',
            field=models.ForeignKey(db_column='AVAILABLE_ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AvailableAction'),
        ),
        migrations.AddField(
            model_name='instanceresourceaction',
            name='available_instance_resource',
            field=models.ForeignKey(db_column='AVAILABLE_INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AvailableInstanceResource'),
        ),
        migrations.AddField(
            model_name='instanceresource',
            name='available_instance_resource',
            field=models.ForeignKey(db_column='AVAILABLE_INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AvailableInstanceResource'),
        ),
        migrations.AddField(
            model_name='instanceresource',
            name='resource',
            field=models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Resource'),
        ),
        migrations.AddField(
            model_name='instancelocation',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='instancelocation',
            name='location',
            field=models.ForeignKey(db_column='LOCATION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Location'),
        ),
        migrations.AddField(
            model_name='instanceformpdf',
            name='action',
            field=models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Action'),
        ),
        migrations.AddField(
            model_name='instanceformpdf',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='instanceformpdf',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formgroupform',
            name='form',
            field=models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_group', to='instance.Form'),
        ),
        migrations.AddField(
            model_name='formgroupform',
            name='form_group',
            field=models.ForeignKey(db_column='FORM_GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='forms', to='core.FormGroup'),
        ),
        migrations.AddField(
            model_name='docgenpdfaction',
            name='action',
            field=models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Action'),
        ),
        migrations.AddField(
            model_name='docgenpdfaction',
            name='docgen_template',
            field=models.ForeignKey(db_column='DOCGEN_TEMPLATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DocgenTemplate'),
        ),
        migrations.AddField(
            model_name='docgenpdfaction',
            name='docgen_template_class',
            field=models.ForeignKey(db_column='DOCGEN_TEMPLATE_CLASS_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DocgenTemplateClass'),
        ),
        migrations.AddField(
            model_name='docgendocxaction',
            name='action',
            field=models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Action'),
        ),
        migrations.AddField(
            model_name='docgendocxaction',
            name='docgen_template',
            field=models.ForeignKey(db_column='DOCGEN_TEMPLATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DocgenTemplate'),
        ),
        migrations.AddField(
            model_name='docgendocxaction',
            name='docgen_template_class',
            field=models.ForeignKey(db_column='DOCGEN_TEMPLATE_CLASS_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DocgenTemplateClass'),
        ),
        migrations.AddField(
            model_name='docgenactivationdocket',
            name='activation',
            field=models.ForeignKey(blank=True, db_column='ACTIVATION_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Activation'),
        ),
        migrations.AddField(
            model_name='docgenactivationdocket',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='docgenactivationactionaction',
            name='action',
            field=models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Action'),
        ),
        migrations.AddField(
            model_name='docgenactivationactionaction',
            name='docgen_activation_action',
            field=models.ForeignKey(db_column='DOCGEN_ACTIVATION_ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DocgenActivationAction'),
        ),
        migrations.AddField(
            model_name='commissionassignment',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group'),
        ),
        migrations.AddField(
            model_name='commissionassignment',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='circulationtype',
            name='page',
            field=models.ForeignKey(blank=True, db_column='PAGE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Page'),
        ),
        migrations.AddField(
            model_name='circulationreason',
            name='circulation_type',
            field=models.ForeignKey(db_column='CIRCULATION_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationType'),
        ),
        migrations.AddField(
            model_name='circulationanswer',
            name='circulation_answer_type',
            field=models.ForeignKey(db_column='CIRCULATION_ANSWER_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationAnswerType'),
        ),
        migrations.AddField(
            model_name='circulationanswer',
            name='circulation_type',
            field=models.ForeignKey(db_column='CIRCULATION_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationType'),
        ),
        migrations.AddField(
            model_name='circulation',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='circulations', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='chapterpageuseracl',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ChapterPage'),
        ),
        migrations.AddField(
            model_name='chapterpageuseracl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='chapterpageuseracl',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ChapterPage'),
        ),
        migrations.AddField(
            model_name='chapterpageuseracl',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterpageserviceacl',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ChapterPage'),
        ),
        migrations.AddField(
            model_name='chapterpageserviceacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='chapterpageserviceacl',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ChapterPage'),
        ),
        migrations.AddField(
            model_name='chapterpageserviceacl',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='chapterpageroleacl',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ChapterPage'),
        ),
        migrations.AddField(
            model_name='chapterpageroleacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='chapterpageroleacl',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ChapterPage'),
        ),
        migrations.AddField(
            model_name='chapterpageroleacl',
            name='role',
            field=models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Role'),
        ),
        migrations.AddField(
            model_name='chapterpagegroupacl',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ChapterPage'),
        ),
        migrations.AddField(
            model_name='chapterpagegroupacl',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group'),
        ),
        migrations.AddField(
            model_name='chapterpagegroupacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='chapterpagegroupacl',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ChapterPage'),
        ),
        migrations.AddField(
            model_name='chapterpage',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='chapterpage',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Page'),
        ),
        migrations.AddField(
            model_name='button',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.InstanceResource'),
        ),
        migrations.AddField(
            model_name='buseracl',
            name='button',
            field=models.ForeignKey(db_column='BUTTON_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Button'),
        ),
        migrations.AddField(
            model_name='buseracl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='buseracl',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingauthoritysectiondis',
            name='ba_section',
            field=models.ForeignKey(db_column='BA_SECTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BuildingAuthoritySection'),
        ),
        migrations.AddField(
            model_name='buildingauthoritysectiondis',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='buildingauthorityitemdis',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='buildingauthorityitemdis',
            name='workflow_item',
            field=models.ForeignKey(db_column='WORKFLOW_ITEM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.WorkflowItem'),
        ),
        migrations.AddField(
            model_name='buildingauthorityemail',
            name='building_authority_button',
            field=models.ForeignKey(db_column='BUILDING_AUTHORITY_BUTTON_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BuildingAuthorityButton'),
        ),
        migrations.AddField(
            model_name='buildingauthoritydoc',
            name='building_authority_button',
            field=models.ForeignKey(db_column='BUILDING_AUTHORITY_BUTTON_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BuildingAuthorityButton'),
        ),
        migrations.AddField(
            model_name='buildingauthoritydoc',
            name='template',
            field=models.ForeignKey(db_column='TEMPLATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DocgenTemplate'),
        ),
        migrations.AddField(
            model_name='buildingauthoritydoc',
            name='template_class',
            field=models.ForeignKey(db_column='TEMPLATE_CLASS_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DocgenTemplateClass'),
        ),
        migrations.AddField(
            model_name='buildingauthoritycomment',
            name='building_authority_section',
            field=models.ForeignKey(db_column='BUILDING_AUTHORITY_SECTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BuildingAuthoritySection'),
        ),
        migrations.AddField(
            model_name='buildingauthoritycomment',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='buildingauthoritybuttonstate',
            name='building_authority_button',
            field=models.ForeignKey(db_column='BUILDING_AUTHORITY_BUTTON_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BuildingAuthorityButton'),
        ),
        migrations.AddField(
            model_name='buildingauthoritybuttonstate',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='bserviceacl',
            name='button',
            field=models.ForeignKey(db_column='BUTTON_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Button'),
        ),
        migrations.AddField(
            model_name='bserviceacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='bserviceacl',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='broleacl',
            name='button',
            field=models.ForeignKey(db_column='BUTTON_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Button'),
        ),
        migrations.AddField(
            model_name='broleacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='broleacl',
            name='role',
            field=models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Role'),
        ),
        migrations.AddField(
            model_name='billingentry',
            name='billing_account',
            field=models.ForeignKey(blank=True, db_column='BILLING_ACCOUNT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BillingAccount'),
        ),
        migrations.AddField(
            model_name='billingentry',
            name='instance',
            field=models.ForeignKey(blank=True, db_column='INSTANCE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='billingentry',
            name='service',
            field=models.ForeignKey(blank=True, db_column='SERVICE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='billingaccountstate',
            name='billing_account',
            field=models.ForeignKey(db_column='BILLING_ACCOUNT_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BillingAccount'),
        ),
        migrations.AddField(
            model_name='billingaccountstate',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='service_group',
            field=models.ForeignKey(blank=True, db_column='SERVICE_GROUP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ServiceGroup'),
        ),
        migrations.AddField(
            model_name='bgroupacl',
            name='button',
            field=models.ForeignKey(db_column='BUTTON_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Button'),
        ),
        migrations.AddField(
            model_name='bgroupacl',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group'),
        ),
        migrations.AddField(
            model_name='bgroupacl',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='babusage',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='authoritylocation',
            name='authority',
            field=models.ForeignKey(db_column='AUTHORITY_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Authority'),
        ),
        migrations.AddField(
            model_name='authoritylocation',
            name='location',
            field=models.ForeignKey(db_column='LOCATION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='authorityauthoritytype',
            unique_together=set([('authority_id', 'authority_type_id')]),
        ),
        migrations.AddField(
            model_name='attachmentextensionservice',
            name='attachment_extension',
            field=models.ForeignKey(db_column='ATTACHMENT_EXTENSION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AttachmentExtension'),
        ),
        migrations.AddField(
            model_name='attachmentextensionservice',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='attachmentextensionrole',
            name='attachment_extension',
            field=models.ForeignKey(db_column='ATTACHMENT_EXTENSION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AttachmentExtension'),
        ),
        migrations.AddField(
            model_name='attachmentextensionrole',
            name='role',
            field=models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Role'),
        ),
        migrations.AddField(
            model_name='araction',
            name='available_resource',
            field=models.ForeignKey(db_column='AVAILABLE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AvailableResource'),
        ),
        migrations.AddField(
            model_name='answerlist',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='answer',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='alocationqc',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='alocationqc',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='airaction',
            name='available_instance_resource',
            field=models.ForeignKey(db_column='AVAILABLE_INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AvailableInstanceResource'),
        ),
        migrations.AddField(
            model_name='activationanswer',
            name='activation',
            field=models.ForeignKey(db_column='ACTIVATION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Activation'),
        ),
        migrations.AddField(
            model_name='activationanswer',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='activationanswer',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='activation',
            name='activation_parent',
            field=models.ForeignKey(blank=True, db_column='ACTIVATION_PARENT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Activation'),
        ),
        migrations.AddField(
            model_name='activation',
            name='circulation',
            field=models.ForeignKey(db_column='CIRCULATION_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Circulation'),
        ),
        migrations.AddField(
            model_name='activation',
            name='circulation_answer',
            field=models.ForeignKey(blank=True, db_column='CIRCULATION_ANSWER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationAnswer'),
        ),
        migrations.AddField(
            model_name='activation',
            name='circulation_state',
            field=models.ForeignKey(db_column='CIRCULATION_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationState'),
        ),
        migrations.AddField(
            model_name='activation',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='activation',
            name='service_parent',
            field=models.ForeignKey(db_column='SERVICE_PARENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='activation',
            name='user',
            field=models.ForeignKey(blank=True, db_column='USER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='available_action',
            field=models.ForeignKey(db_column='AVAILABLE_ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AvailableAction'),
        ),
        migrations.AddField(
            model_name='action',
            name='button',
            field=models.ForeignKey(db_column='BUTTON_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Button'),
        ),
        migrations.AddField(
            model_name='acopydatamapping',
            name='chapter',
            field=models.ForeignKey(blank=True, db_column='CHAPTER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='acopydatamapping',
            name='question',
            field=models.ForeignKey(blank=True, db_column='QUESTION_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='acopyanswermapping',
            name='destination_chapter',
            field=models.ForeignKey(db_column='DESTINATION_CHAPTER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='acopyanswermapping',
            name='destination_question',
            field=models.ForeignKey(db_column='DESTINATION_QUESTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AddField(
            model_name='acopyanswermapping',
            name='source_chapter',
            field=models.ForeignKey(blank=True, db_column='SOURCE_CHAPTER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='acopyanswermapping',
            name='source_question',
            field=models.ForeignKey(blank=True, db_column='SOURCE_QUESTION_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowrole',
            unique_together=set([('role', 'workflow_item')]),
        ),
        migrations.AlterUniqueTogether(
            name='workflowentry',
            unique_together=set([('instance', 'workflow_item', 'group')]),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='workflow_item',
            field=models.ForeignKey(db_column='WORKFLOW_ITEM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.WorkflowItem'),
        ),
        migrations.AlterUniqueTogether(
            name='ruseracl',
            unique_together=set([('resource', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='rserviceacl',
            unique_together=set([('resource', 'service')]),
        ),
        migrations.AddField(
            model_name='rsearchfilter',
            name='resource',
            field=models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.RSearch'),
        ),
        migrations.AddField(
            model_name='rsearchcolumn',
            name='resource',
            field=models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.RSearch'),
        ),
        migrations.AlterUniqueTogether(
            name='rroleacl',
            unique_together=set([('resource', 'role')]),
        ),
        migrations.AddField(
            model_name='rlistcolumn',
            name='resource',
            field=models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.RList'),
        ),
        migrations.AlterUniqueTogether(
            name='rgroupacl',
            unique_together=set([('resource', 'group')]),
        ),
        migrations.AddField(
            model_name='rformlist',
            name='form',
            field=models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Form'),
        ),
        migrations.AlterUniqueTogether(
            name='questionchapteruseracl',
            unique_together=set([('question', 'chapter', 'user', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionchapterserviceacl',
            unique_together=set([('question', 'chapter', 'service', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionchapterroleacl',
            unique_together=set([('question', 'chapter', 'role', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionchaptergroupacl',
            unique_together=set([('question', 'chapter', 'group', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionchapter',
            unique_together=set([('question', 'chapter')]),
        ),
        migrations.AlterUniqueTogether(
            name='pageformuseracl',
            unique_together=set([('page', 'form', 'user', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='pageformserviceacl',
            unique_together=set([('page', 'form', 'service', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='pageformroleacl',
            unique_together=set([('page', 'form', 'role', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='pageformgroupacl',
            unique_together=set([('page', 'form', 'group', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='pageform',
            unique_together=set([('page', 'form')]),
        ),
        migrations.AddField(
            model_name='noticeimage',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.IrEditnotice'),
        ),
        migrations.AlterUniqueTogether(
            name='notice',
            unique_together=set([('notice_type', 'activation')]),
        ),
        migrations.AddField(
            model_name='letter',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.IrEditletter'),
        ),
        migrations.AlterUniqueTogether(
            name='iruseracl',
            unique_together=set([('instance_resource', 'user', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='irserviceacl',
            unique_together=set([('instance_resource', 'service', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='irroleacl',
            unique_together=set([('instance_resource', 'role', 'instance_state')]),
        ),
        migrations.AddField(
            model_name='irnewform',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='irnewform',
            name='page_form_group',
            field=models.ForeignKey(blank=True, db_column='PAGE_FORM_GROUP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageFormGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='irgroupacl',
            unique_together=set([('instance_resource', 'group', 'instance_state')]),
        ),
        migrations.AddField(
            model_name='irformwizard',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='irformwizard',
            name='page_form_group',
            field=models.ForeignKey(db_column='PAGE_FORM_GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageFormGroup'),
        ),
        migrations.AddField(
            model_name='irformpages',
            name='page_form_group',
            field=models.ForeignKey(blank=True, db_column='PAGE_FORM_GROUP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageFormGroup'),
        ),
        migrations.AddField(
            model_name='irformpage',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Page'),
        ),
        migrations.AddField(
            model_name='irformerror',
            name='ir_editformpages',
            field=models.ForeignKey(db_column='IR_EDITFORMPAGES_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.IrEditformpages'),
        ),
        migrations.AddField(
            model_name='ireditnotice',
            name='circulation_type',
            field=models.ForeignKey(db_column='CIRCULATION_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationType'),
        ),
        migrations.AddField(
            model_name='ireditletteranswer',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.IrEditletter'),
        ),
        migrations.AddField(
            model_name='ireditformpages',
            name='page_form_group',
            field=models.ForeignKey(blank=True, db_column='PAGE_FORM_GROUP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageFormGroup'),
        ),
        migrations.AddField(
            model_name='ireditformpage',
            name='page',
            field=models.ForeignKey(db_column='PAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Page'),
        ),
        migrations.AddField(
            model_name='ireditcirculationsg',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.IrEditcirculation'),
        ),
        migrations.AddField(
            model_name='ireditcirculation',
            name='circulation_type',
            field=models.ForeignKey(db_column='CIRCULATION_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationType'),
        ),
        migrations.AddField(
            model_name='ireditcirculation',
            name='draft_circulation_answer',
            field=models.ForeignKey(blank=True, db_column='DRAFT_CIRCULATION_ANSWER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationAnswer'),
        ),
        migrations.AddField(
            model_name='ircirculation',
            name='circulation_type',
            field=models.ForeignKey(db_column='CIRCULATION_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationType'),
        ),
        migrations.AddField(
            model_name='ircirculation',
            name='draft_circulation_answer',
            field=models.ForeignKey(blank=True, db_column='DRAFT_CIRCULATION_ANSWER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationAnswer'),
        ),
        migrations.AddField(
            model_name='ircirculation',
            name='service',
            field=models.ForeignKey(blank=True, db_column='SERVICE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='irallformpages',
            name='page_form_group',
            field=models.ForeignKey(blank=True, db_column='PAGE_FORM_GROUP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageFormGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='instanceresourceaction',
            unique_together=set([('available_instance_resource', 'available_action')]),
        ),
        migrations.AlterUniqueTogether(
            name='instancelocation',
            unique_together=set([('location', 'instance')]),
        ),
        migrations.AlterUniqueTogether(
            name='formgroupform',
            unique_together=set([('form_group', 'form')]),
        ),
        migrations.AlterUniqueTogether(
            name='docgenpdfaction',
            unique_together=set([('docgen_template', 'docgen_template_class', 'action')]),
        ),
        migrations.AlterUniqueTogether(
            name='docgendocxaction',
            unique_together=set([('docgen_template', 'docgen_template_class', 'action')]),
        ),
        migrations.AlterUniqueTogether(
            name='docgenactivationactionaction',
            unique_together=set([('docgen_activation_action', 'action')]),
        ),
        migrations.AlterUniqueTogether(
            name='commissionassignment',
            unique_together=set([('group', 'instance')]),
        ),
        migrations.AddField(
            model_name='circulation',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.IrEditcirculation'),
        ),
        migrations.AlterUniqueTogether(
            name='chapterpageuseracl',
            unique_together=set([('chapter', 'page', 'user', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='chapterpageserviceacl',
            unique_together=set([('chapter', 'page', 'service', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='chapterpageroleacl',
            unique_together=set([('chapter', 'page', 'role', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='chapterpagegroupacl',
            unique_together=set([('chapter', 'page', 'group', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='chapterpage',
            unique_together=set([('chapter', 'page')]),
        ),
        migrations.AlterUniqueTogether(
            name='buseracl',
            unique_together=set([('button', 'user', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='buildingauthoritycomment',
            unique_together=set([('building_authority_section', 'group', 'instance')]),
        ),
        migrations.AlterUniqueTogether(
            name='bserviceacl',
            unique_together=set([('button', 'service', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='broleacl',
            unique_together=set([('button', 'role', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='bgroupacl',
            unique_together=set([('button', 'group', 'instance_state')]),
        ),
        migrations.AlterUniqueTogether(
            name='babusage',
            unique_together=set([('instance', 'usage_type')]),
        ),
        migrations.AddField(
            model_name='avalidate',
            name='page_form_group',
            field=models.ForeignKey(blank=True, db_column='PAGE_FORM_GROUP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageFormGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='authoritylocation',
            unique_together=set([('authority', 'location')]),
        ),
        migrations.AlterUniqueTogether(
            name='attachmentextensionservice',
            unique_together=set([('attachment_extension', 'service')]),
        ),
        migrations.AlterUniqueTogether(
            name='attachmentextensionrole',
            unique_together=set([('attachment_extension', 'role')]),
        ),
        migrations.AddField(
            model_name='asavepdf',
            name='form',
            field=models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Form'),
        ),
        migrations.AddField(
            model_name='asavepdf',
            name='page_form_group',
            field=models.ForeignKey(blank=True, db_column='PAGE_FORM_GROUP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PageFormGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='araction',
            unique_together=set([('available_resource', 'action_name')]),
        ),
        migrations.AddField(
            model_name='aproposal',
            name='circulation_state',
            field=models.ForeignKey(db_column='CIRCULATION_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationState'),
        ),
        migrations.AddField(
            model_name='aproposal',
            name='circulation_type',
            field=models.ForeignKey(db_column='CIRCULATION_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationType'),
        ),
        migrations.AddField(
            model_name='apageredirect',
            name='instance_resource',
            field=models.ForeignKey(blank=True, db_column='INSTANCE_RESOURCE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.InstanceResource'),
        ),
        migrations.AddField(
            model_name='apageredirect',
            name='resource',
            field=models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('instance', 'question', 'chapter', 'item')]),
        ),
        migrations.AddField(
            model_name='anotice',
            name='notice_type',
            field=models.ForeignKey(db_column='NOTICE_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.NoticeType'),
        ),
        migrations.AddField(
            model_name='alocationqc',
            name='action',
            field=models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ALocation'),
        ),
        migrations.AlterUniqueTogether(
            name='airaction',
            unique_together=set([('available_instance_resource', 'action_name')]),
        ),
        migrations.AddField(
            model_name='aformtransition',
            name='current_instance_state',
            field=models.ForeignKey(blank=True, db_column='CURRENT_INSTANCE_STATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='aformtransition',
            name='next_instance_state',
            field=models.ForeignKey(blank=True, db_column='NEXT_INSTANCE_STATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AlterUniqueTogether(
            name='activationanswer',
            unique_together=set([('activation', 'question', 'chapter', 'item')]),
        ),
        migrations.AddField(
            model_name='acopydatamapping',
            name='action',
            field=models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ACopydata'),
        ),
        migrations.AddField(
            model_name='acopyanswermapping',
            name='action',
            field=models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ACopyanswer'),
        ),
        migrations.AddField(
            model_name='acirculationtransition',
            name='current_circulation_state',
            field=models.ForeignKey(blank=True, db_column='CURRENT_CIRCULATION_STATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationState'),
        ),
        migrations.AddField(
            model_name='acirculationtransition',
            name='next_circulation_state',
            field=models.ForeignKey(db_column='NEXT_CIRCULATION_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationState'),
        ),
        migrations.AlterUniqueTogether(
            name='letter',
            unique_together=set([('instance', 'instance_resource')]),
        ),
    ]
