# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180502_1731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowentry',
            unique_together=set([]),
        ),
    ]
