# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ireditcirculation_circulation_email_action_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RApiListCirculationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation_state', models.ForeignKey(db_column='CIRCULATION_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationState')),
                ('resource', models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Resource')),
            ],
            options={
                'db_table': 'R_API_LIST_CIRCULATION_STATE',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='RApiList',
            new_name='RApiListInstanceState',
        ),
        migrations.AlterModelTable(
            name='rapilistinstancestate',
            table='R_API_LIST_INSTANCE_STATE',
        ),
        migrations.AlterUniqueTogether(
            name='rapilistcirculationstate',
            unique_together=set([('resource', 'circulation_state')]),
        ),
    ]
