# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180404_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RApiListCirculationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation_type', models.ForeignKey(db_column='CIRCULATION_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.CirculationType')),
                ('resource', models.ForeignKey(db_column='RESOURCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Resource')),
            ],
            options={
                'db_table': 'R_API_LIST_CIRCULATION_TYPE',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='rapilistcirculationtype',
            unique_together=set([('resource', 'circulation_type')]),
        ),
    ]
