# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kt_uri_views'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowentry',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='authorityauthoritytype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='authorityauthoritytype',
            name='authority_id',
        ),
        migrations.RemoveField(
            model_name='authorityauthoritytype',
            name='authority_type_id',
        ),
        migrations.AddField(
            model_name='authorityauthoritytype',
            name='authority',
            field=models.ForeignKey(db_column='AUTHORITY_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Authority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authorityauthoritytype',
            name='authority_type',
            field=models.ForeignKey(db_column='AUTHORITY_TYPE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AuthorityType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authoritylocation',
            name='location',
            field=models.ForeignKey(db_column='LOCATION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Location'),
        ),
        migrations.AlterField(
            model_name='billingentry',
            name='created',
            field=models.DateTimeField(db_column='CREATED', null=True),
        ),
        migrations.AlterField(
            model_name='buildingauthoritycomment',
            name='building_authority_section',
            field=models.ForeignKey(db_column='BUILDING_AUTHORITY_SECTION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.BuildingAuthoritySection'),
        ),
        migrations.AlterField(
            model_name='buildingauthoritysectiondis',
            name='ba_section',
            field=models.ForeignKey(db_column='BA_SECTION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.BuildingAuthoritySection'),
        ),
    ]
