# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180503_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingauthoritysectiondis',
            name='ba_section',
            field=models.ForeignKey(db_column='BA_SECTION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.BuildingAuthoritySection'),
        ),
    ]
