# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180405_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceresource',
            name='form_group',
            field=models.ForeignKey(db_column='FORM_GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.FormGroup'),
        ),
    ]
