# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_camac_uri_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingauthoritybuttonstate',
            name='is_clicked',
            field=models.PositiveSmallIntegerField(db_column='IS_CLICKED', default=0),
        ),
        migrations.AlterField(
            model_name='buildingauthoritybuttonstate',
            name='is_disabled',
            field=models.PositiveSmallIntegerField(db_column='IS_DISABLED', default=0),
        ),
        migrations.AlterField(
            model_name='buildingauthoritycomment',
            name='building_authority_section',
            field=models.ForeignKey(db_column='BUILDING_AUTHORITY_SECTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BuildingAuthoritySection'),
        ),
    ]
