# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20180410_0902'),
        ('core', '0006_auto_20180409_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateGenerateAction',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('as_pdf', models.PositiveSmallIntegerField(db_column='AS_PDF', default=0)),
                ('action', models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Action')),
                ('template', models.ForeignKey(db_column='TEMPLATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='document.Template')),
            ],
            options={
                'db_table': 'TEMPLATE_GENERATE_ACTION',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='templategenerateaction',
            unique_together=set([('as_pdf', 'template', 'action')]),
        ),
    ]
