# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180430_1156'),
        ('core', '0006_auto_20180503_0811'),
    ]

    operations = [
    ]
