# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('core', '0007_auto_20180410_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANotification',
            fields=[
                ('action', models.OneToOneField(db_column='ACTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='core.Action')),
                ('recipient_type', models.CharField(db_column='RECIPIENT_TYPE', max_length=160)),
                ('processor', models.CharField(db_column='PROCESSOR', max_length=160)),
                ('template', models.ForeignKey(db_column='TEMPLATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notification.NotificationTemplate')),
            ],
            options={
                'db_table': 'ACTION_NOTIFICATION',
                'managed': True,
            },
        ),
    ]
