# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180515_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingauthoritysectiondis',
            name='ba_section',
            field=models.ForeignKey(db_column='BA_SECTION_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BuildingAuthoritySection'),
        ),
    ]
