# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180516_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingauthoritybuttonstate',
            name='building_authority_button',
            field=models.ForeignKey(db_column='BUILDING_AUTHORITY_BUTTON_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.BuildingAuthorityButton'),
        ),
    ]
