# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180530_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsearch',
            name='query',
            field=models.TextField(db_column='QUERY'),
        ),
    ]
