# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180627_1325'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE OR REPLACE VIEW "BILLING_ENTRY_ACTUAL_AMOUNT" AS
SELECT
    CASE "AMOUNT_TYPE"
        WHEN 0 THEN "AMOUNT"
        WHEN 1 THEN "AMOUNT" * (SELECT "VALUE" FROM "BILLING_CONFIG" WHERE "NAME" = 'hourly_rate')::int
        WHEN 2 THEN "AMOUNT" * (SELECT "VALUE" FROM "BILLING_CONFIG" WHERE "NAME" = 'hourly_rate')::int / 2
    END AS "ACTUAL_AMOUNT",
    "BILLING_ENTRY_ID"
FROM "BILLING_ENTRY";


CREATE OR REPLACE VIEW "BILLING_ENTRY_TYPE" AS
SELECT
     CASE "BILLING_ENTRY"."TYPE"
	 WHEN 0 THEN 'BEW'
         WHEN 1 THEN 'BGL'
     END AS "TYPE",
     "BILLING_ENTRY_ID"
FROM "BILLING_ENTRY";
            """
        )
    ]
