# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20180511_1450'),
        ('core', '0012_kt_uri_billing_amount_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('billing_invoice_id', models.AutoField(db_column='BILLING_INVOICE_ID', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_column='CREATED')),
                ('type', models.PositiveSmallIntegerField(db_column='TYPE')),
                ('attachment', models.ForeignKey(db_column='ATTACHMENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment', to='document.Attachment')),
            ],
            options={
                'db_table': 'BILLING_INVOICE',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='billingentry',
            name='invoice',
            field=models.ForeignKey(db_column='INVOICE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_invoice', to='core.BillingInvoice'),
        ),
    ]
