# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180703_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginvoice',
            name='billing_type',
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='type',
            field=models.PositiveSmallIntegerField(db_column='TYPE', default=0),
            preserve_default=False,
        ),
    ]
