# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180706_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCallbackExclude',
            fields=[
                ('activation_callback_exclude_id', models.AutoField(db_column='ACTIVATION_CALLBACK_EXCLUDE_ID', auto_created=True, primary_key=True, serialize=False)),
                ('service_id', models.IntegerField(db_column='SERVICE_ID')),
            ],
            options={
                'db_table': 'ACTIVATION_CALLBACK_EXCLUDE',
                'managed': True,
            },
        ),
    ]
