# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180831_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='circulation',
            field=models.ForeignKey(db_column='CIRCULATION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.Circulation'),
        ),
        migrations.AlterField(
            model_name='activationanswer',
            name='activation',
            field=models.ForeignKey(db_column='ACTIVATION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Activation'),
        ),
        migrations.AlterField(
            model_name='billingentry',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='billing_entries', to='instance.Instance'),
        ),
        migrations.AlterField(
            model_name='circulation',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='circulations', to='instance.Instance'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='activation',
            field=models.ForeignKey(db_column='ACTIVATION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='core.Activation'),
        ),
        migrations.AlterField(
            model_name='publicationentry',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instance.Instance'),
        ),
        migrations.AlterField(
            model_name='workflowentry',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, to='instance.Instance'),
        ),
    ]
