# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181024_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationentry',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='publication_entries', to='instance.Instance'),
        ),
    ]
