# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181119_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rlistcolumn',
            name='alias',
            field=models.CharField(blank=True, db_column='ALIAS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rlistcolumnt',
            name='alias',
            field=models.CharField(blank=True, db_column='ALIAS', max_length=50, null=True),
        ),
    ]
