# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181119_1558'),
        ('core', '0019_auto_20181207_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionassignment',
            name='creator_group',
            field=models.ForeignKey(db_column='CREATOR_GROUP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group'),
        ),
    ]
