# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_commissionassignment_creator_group'),
    ]

    def forwards(self, orm):
        db.rename_column('COMMISSION_ASSIGNMENT', 'ADDER_ID', 'CREATOR_USER_ID')

    def backwards(self, orm):
        db.rename_column('COMMISSION_ASSIGNMENT', 'CREATOR_USER_ID', 'ADDER_ID')
