# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_commissionassignment_creator_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionassignment',
            name='adder_id',
            field=models.FloatField(db_column='CREATOR_USER_ID'),
        ),
    ]
