# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190111_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionassignment',
            old_name='adder_id',
            new_name='creator_user',
        ),
    ]
