# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-25 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190111_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancelocation',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instance.Instance'),
        ),
    ]
