# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-01 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190125_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='additional_text',
            field=models.TextField(blank=True, db_column='ADDITIONAL_TEXT', null=True),
        ),
    ]
