# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-08 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_billingv2entry_organization'),
        ('core', '0025_journal_additional_text'),
    ]

    operations = [
    ]
