# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20190308_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCalumaList',
            fields=[
                ('resource_id', models.AutoField(db_column='RESOURCE_ID', primary_key=True, serialize=False)),
                ('instance_states', models.CharField(db_column='INSTANCE_STATES', max_length=400)),
            ],
            options={
                'db_table': 'R_CALUMA_LIST',
                'managed': True,
            },
        ),
    ]
