# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20190308_1805'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE OR REPLACE VIEW "OTHER_INTENTIONS" ("ANSWER", "INSTANCE_ID") AS
SELECT "ANSWER", "INSTANCE_ID"
FROM "ANSWER"
WHERE
    ("QUESTION_ID" = 98 AND ("CHAPTER_ID" = 21 OR "CHAPTER_ID" = 101) AND "ITEM" = 1)
    OR ("QUESTION_ID" = 244 AND "CHAPTER_ID" = 102);
            """
        )
    ]
