# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_fix_question_id_in_intentions_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, db_column='NAME', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resourcet',
            name='name',
            field=models.CharField(blank=True, db_column='NAME', max_length=100, null=True),
        ),
    ]
