# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190515_0735'),
        ('core', '0028_rcalumalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulation',
            name='service',
            field=models.ForeignKey(blank=True, db_column='SERVICE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Service'),
        ),
    ]
