# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190522_1458'),
        ('core', '0028_rcalumalist'),
    ]

    operations = [
    ]
