# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20190531_1504'),
        ('core', '0029_circulation_service'),
    ]

    operations = [
    ]
