# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20190605_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptert',
            name='chapter',
            field=models.ForeignKey(db_column='CHAPTER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='core.Chapter'),
        ),
        migrations.AlterField(
            model_name='questiont',
            name='question',
            field=models.ForeignKey(db_column='QUESTION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='core.Question'),
        ),
    ]
