# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0031_auto_20190607_1500")]

    operations = [
        migrations.AlterField(
            model_name="answerlist",
            name="question",
            field=models.ForeignKey(
                db_column="QUESTION_ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answerlist",
                to="core.Question",
            ),
        ),
        migrations.AlterField(
            model_name="answerlistt",
            name="answer_list",
            field=models.ForeignKey(
                db_column="ANSWER_LIST_ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trans",
                to="core.AnswerList",
            ),
        ),
        migrations.AlterField(
            model_name="paget",
            name="page",
            field=models.ForeignKey(
                db_column="PAGE_ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trans",
                to="core.Page",
            ),
        ),
    ]
