# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0032_multilingual_pages_answerlist")]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE reversion_revision
            DROP CONSTRAINT IF EXISTS reversion_revision_user_id_17095f45_fk_auth_user_id;

            -- Just for testing / safety reasons so the migration can be
            -- repeated in case of errors
            ALTER TABLE reversion_revision
            DROP CONSTRAINT IF EXISTS reversion_revision_user_id_17095f45_fk_USER_USER_ID;

            ALTER TABLE reversion_revision
            ADD CONSTRAINT reversion_revision_user_id_17095f45_fk_USER_USER_ID
            FOREIGN KEY (user_id) REFERENCES "USER" ("USER_ID");
        """
        )
    ]
