# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190726_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='NAME')),
            ],
            options={
                'db_table': 'PUBLICATION_TYPE',
                'managed': True,
            },
        ),
    ]
