# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-04 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_publicationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationentry',
            name='type',
            field=models.ForeignKey(blank=True, db_column='PUBLICATION_TYPE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PublicationType'),
        ),
        migrations.AddField(
            model_name='publicationsetting',
            name='type',
            field=models.ForeignKey(blank=True, db_column='PUBLICATION_TYPE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PublicationType'),
        ),
        migrations.AlterField(
            model_name='publicationentry',
            name='note',
            field=models.FloatField(db_column='NOTE', null=True),
        ),
    ]
