# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_publicationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationentry',
            name='type',
            field=models.ForeignKey(db_column='PUBLICATION_TYPE_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PublicationType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationsetting',
            name='type',
            field=models.ForeignKey(db_column='PUBLICATION_TYPE_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.PublicationType'),
            preserve_default=False,
        ),
    ]
