# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-22 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20190815_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationentry',
            name='note',
            field=models.FloatField(db_column='NOTE', null=True),
        ),
    ]
