# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_auto_20190710_1326'),
        ('core', '0037_fix_project_submitter_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingauthorityemail',
            name='attachment_section',
            field=models.ForeignKey(blank=True, db_column='ATTACHMENT_SECTION_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='document.AttachmentSection'),
        ),
    ]
