# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_fix_multiple_active_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationentry',
            name='note',
            field=models.FloatField(blank=True, db_column='NOTE', null=True),
        ),
    ]
