# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-04 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0042_revert_uri_project_submitter_view_change")]

    operations = [
        migrations.CreateModel(
            name="JournalT",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(db_column="LANGUAGE", max_length=2)),
                ("text", models.TextField(db_column="TEXT")),
                (
                    "additional_text",
                    models.TextField(
                        blank=True, db_column="ADDITIONAL_TEXT", null=True
                    ),
                ),
            ],
            options={"db_table": "JOURNAL_T", "managed": True},
        ),
        migrations.AlterField(
            model_name="journal",
            name="text",
            field=models.TextField(blank=True, db_column="TEXT", null=True),
        ),
        migrations.AddField(
            model_name="journalt",
            name="journal",
            field=models.ForeignKey(
                db_column="JOURNAL_ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trans",
                to="core.Journal",
            ),
        ),
    ]
