# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-22 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_activation_ech_msg_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationEntryUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('publication_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_permissions', to='core.PublicationEntry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='publicationentryuserpermission',
            unique_together=set([('publication_entry', 'user')]),
        ),
    ]
