# Generated by Django 2.2.8 on 2020-01-22 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_sanction_control_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_amtsblatt',
            field=models.DateField(db_column='PUBLICATION_DATE_AMTSBLATT', default=datetime.datetime(2020, 1, 22, 14, 10, 21, 621222, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_anzeiger_1',
            field=models.DateField(db_column='PUBLICATION_DATE_1_ANZEIGER', default=datetime.datetime(2020, 1, 22, 14, 10, 34, 602781, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_anzeiger_2',
            field=models.DateField(db_column='PUBLICATION_DATE_2_ANZEIGER', default=datetime.datetime(2020, 1, 22, 14, 10, 43, 997486, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
