# Generated by Django 2.2.8 on 2020-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200122_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_anzeiger_1',
            field=models.DateField(blank=True, db_column='PUBLICATION_DATE_1_ANZEIGER', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_anzeiger_2',
            field=models.DateField(blank=True, db_column='PUBLICATION_DATE_2_ANZEIGER', null=True),
        ),
    ]
