# Generated by Django 2.2.10 on 2020-03-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_change_to_notification_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='anzeiger',
            field=models.CharField(blank=True, db_column='ANZEIGER', max_length=255, null=True),
        ),
    ]
