# Generated by Django 2.2.10 on 2020-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_publication_anzeiger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotification',
            name='template',
            field=models.CharField(db_column='TEMPLATE_ID', max_length=100),
        ),
    ]
