# Generated by Django 2.2.10 on 2020-03-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_replace_sb_table_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceservice',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instance.Instance'),
        ),
    ]
