# Generated by Django 2.2.11 on 2020-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20200325_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(blank=True, db_column='TEXT', null=True),
        ),
    ]
