# Generated by Django 2.2.11 on 2020-04-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200402_1655'),
        ('core', '0054_wald_answer_cleanup'),
    ]

    operations = [
    ]
