# Generated by Django 2.2.11 on 2020-04-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_merge_20200403_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotification',
            name='template',
            field=models.SlugField(db_column='TEMPLATE_ID', max_length=100),
        ),
    ]
