# Generated by Django 2.2.11 on 2020-04-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_archive_workflow_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingauthorityemail',
            name='workflow_item',
            field=models.ForeignKey(blank=True, db_column='WORKFLOW_ITEM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.WorkflowItem'),
        ),
    ]
