# Generated by Django 2.2.11 on 2020-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20200427_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceportal',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
