# Generated by Django 2.2.13 on 2020-06-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_instanceportal_migrated'),
        ('core', '0060_cleanup_caluma_history'),
    ]

    operations = [
    ]
