# Generated by Django 2.2.11 on 2020-05-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0062_auto_20200622_1541")]

    operations = [
        migrations.CreateModel(
            name="HistoryActionConfig",
            fields=[
                (
                    "action",
                    models.OneToOneField(
                        db_column="ACTION_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="core.Action",
                    ),
                ),
                ("title", models.TextField(blank=True, db_column="TITLE", null=True)),
                ("body", models.TextField(blank=True, db_column="BODY", null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("notification", "notification"),
                            ("status-change", "status-change"),
                        ],
                        db_column="HISTORY_TYPE",
                        max_length=20,
                    ),
                ),
            ],
            options={"db_table": "HISTORY_ACTION_CONFIG", "managed": True},
        ),
        migrations.CreateModel(
            name="HistoryActionConfigT",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(db_column="TITLE")),
                ("body", models.TextField(blank=True, db_column="BODY", null=True)),
                ("language", models.CharField(db_column="LANGUAGE", max_length=2)),
                (
                    "action",
                    models.ForeignKey(
                        db_column="ACTION_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trans",
                        to="core.HistoryActionConfig",
                    ),
                ),
            ],
            options={"db_table": "HISTORY_ACTION_CONFIG_T", "managed": True},
        ),
    ]
