# Generated by Django 2.2.13 on 2020-07-01 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_historyactionconfig_historyactionconfigt'),
        ('instance', '0019_create_historyentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalT',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='JournalActionConfigT',
        ),
        migrations.DeleteModel(
            name='JournalActionConfig',
        ),
    ]
