# Generated by Django 2.2.13 on 2020-06-24 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_migrate_instance_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationanswer",
            name="activation",
            field=models.ForeignKey(
                db_column="ACTIVATION_ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Activation",
            ),
        ),
    ]
