# Generated by Django 2.2.13 on 2020-07-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20200722_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activationcallbacknotice',
            old_name='activation_id',
            new_name='activation',
        ),
        migrations.RenameField(
            model_name='activationcallbacknotice',
            old_name='circulation_id',
            new_name='circulation',
        ),
    ]
