# Generated by Django 2.2.13 on 2020-07-27 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_auto_20200722_1337"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionWorkitem",
            fields=[
                (
                    "action",
                    models.OneToOneField(
                        db_column="ACTION_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="core.Action",
                    ),
                ),
                ("task", models.CharField(db_column="TASK", max_length=255)),
                (
                    "process_type",
                    models.CharField(
                        choices=[("complete", "complete"), ("skip", "skip")],
                        db_column="PROCESS_TYPE",
                        max_length=10,
                    ),
                ),
                (
                    "process_all",
                    models.BooleanField(db_column="PROCESS_ALL", default=False),
                ),
                (
                    "is_activation",
                    models.BooleanField(db_column="IS_ACTIVATION", default=False),
                ),
            ],
            options={"db_table": "ACTION_WORKITEM", "managed": True,},
        ),
    ]
