# Generated by Django 2.2.14 on 2020-08-05 09:36

from django.db import migrations, models

from camac.core.db_views import create_view_sql, drop_view_sql


class Migration(migrations.Migration):

    dependencies = [("core", "0069_actionworkitem")]

    operations = [
        migrations.RunSQL(drop_view_sql(), create_view_sql()),
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.TextField(db_column="ANSWER"),
        ),
        migrations.RunSQL(create_view_sql(), drop_view_sql()),
    ]
