# Generated by Django 2.2.14 on 2020-08-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_extend_answer_field_length'),
        ('core', '0070_auto_20200805_1557'),
    ]

    operations = [
    ]
