# Generated by Django 2.2.14 on 2020-08-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20200811_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceservice',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='instance_services', to='instance.Instance'),
        ),
        migrations.AlterField(
            model_name='instanceservice',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instance_services', to='user.Service'),
        ),
    ]
