# Generated by Django 2.2.14 on 2020-09-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_actioncase'),
    ]

    operations = [
        migrations.CreateModel(
            name='REmberList',
            fields=[
                ('resource_id', models.AutoField(db_column='RESOURCE_ID', primary_key=True, serialize=False)),
                ('instance_states', models.CharField(db_column='INSTANCE_STATES', max_length=400)),
            ],
            options={
                'db_table': 'R_EMBER_LIST',
                'managed': True,
            },
        ),
    ]
