# Generated by Django 2.2.16 on 2020-10-09 14:14

from django.db import migrations

rename_papierdossier = """
begin;
alter table caluma_form_question disable trigger all;
alter table caluma_form_option disable trigger all;

update caluma_form_question set slug = 'is-paper' where slug='papierdossier';
update caluma_form_formquestion set id=replace(id, 'papierdossier', 'is-paper'), question_id = 'is-paper' where question_id='papierdossier';

update caluma_form_answer set value=to_jsonb('is-paper-no'::text), question_id = 'is-paper' where value @> to_jsonb('papierdossier-nein'::text);
update caluma_form_answer set value=to_jsonb('is-paper-yes'::text), question_id = 'is-paper' where value @> to_jsonb('papierdossier-ja'::text);

update caluma_form_option set slug='is-paper-yes' where slug='papierdossier-ja';
update caluma_form_option set slug='is-paper-no' where slug='papierdossier-nein';

update caluma_form_questionoption set id='is-paper.is-paper-yes', option_id='is-paper-yes', question_id='is-paper' where id='papierdossier.papierdossier-ja';
update caluma_form_questionoption set id='is-paper.is-paper-no', option_id='is-paper-no', question_id='is-paper' where id='papierdossier.papierdossier-nein';

alter table caluma_form_question enable trigger all;
alter table caluma_form_option enable trigger all;
commit;
"""


rename_papierdossier_reverse = """
begin;
alter table caluma_form_question disable trigger all;
alter table caluma_form_option disable trigger all;

update caluma_form_question set slug = 'papierdossier' where slug='is-paper';
update caluma_form_formquestion set id=replace(id, 'is-paper', 'papierdossier'), question_id = 'papierdossier' where question_id='is-paper';

update caluma_form_answer set value=to_jsonb('papierdossier-nein'::text), question_id = 'papierdossier' where value @> to_jsonb('is-paper-no'::text);
update caluma_form_answer set value=to_jsonb('papierdossier-ja'::text), question_id = 'papierdossier' where value @> to_jsonb('is-paper-yes'::text);

update caluma_form_option set slug='papierdossier-ja' where slug='is-paper-yes';
update caluma_form_option set slug='papierdossier-nein' where slug='is-paper-no';

update caluma_form_questionoption set id='papierdossier.papierdossier-ja', option_id='papierdossier-ja', question_id='papierdossier' where id='is-paper.is-paper-yes';
update caluma_form_questionoption set id='papierdossier.papierdossier-nein', option_id='papierdossier-nein', question_id='papierdossier' where id='is-paper.is-paper-no';

alter table caluma_form_question enable trigger all;
alter table caluma_form_option enable trigger all;
commit;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_remberlist"),
    ]

    operations = [
        migrations.RunSQL(sql=rename_papierdossier, reverse_sql=rename_papierdossier_reverse),
    ]
