# Generated by Django 2.2.16 on 2020-10-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20201009_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionworkitem',
            name='fail_on_empty',
            field=models.BooleanField(db_column='FAIL_ON_EMPTY', default=False),
        ),
    ]
