# Generated by Django 2.2.17 on 2021-01-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_remove_workflow_building_police_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='instance_resource',
            field=models.ForeignKey(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='core.InstanceResource'),
        ),
    ]
