# Generated by Django 2.2.17 on 2021-07-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20210715_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docxdecision',
            name='instance',
            field=models.OneToOneField(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='decision', serialize=False, to='instance.Instance'),
        ),
    ]
