# Generated by Django 2.2.17 on 2021-08-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20210729_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalactivation',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instance.Instance'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='instance.Instance'),
        ),
    ]
