# Generated by Django 2.2.17 on 2021-08-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caluma_workflow', '0027_add_modified_by_user_group'),
        ('core', '0083_on_delete_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrTaskform',
            fields=[
                ('instance_resource', models.OneToOneField(db_column='INSTANCE_RESOURCE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='core.InstanceResource')),
                ('task', models.ForeignKey(db_column='TASK', on_delete=django.db.models.deletion.CASCADE, to='caluma_workflow.Task')),
            ],
            options={
                'db_table': 'IR_TASKFORM',
                'managed': True,
            },
        ),
    ]
