# Generated by Django 2.2.17 on 2021-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_irtaskform'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationentry',
            name='publication_views',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PublicationEntryUserPermission',
        ),
    ]
