# Generated by Django 2.2.17 on 2021-09-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_publicaton_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingv2entry',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instance.Instance'),
        ),
    ]
