# Generated by Django 2.2.17 on 2021-10-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_billingv2_cascade'),
        ('core', '0086_remove_workflowitems'),
    ]

    operations = [
    ]
