# Generated by Django 2.2.17 on 2021-10-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_merge_20211005_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='instance.Instance'),
        ),
    ]
