# Generated by Django 2.2.17 on 2021-10-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20211008_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationentry',
            name='publication_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
