# Generated by Django 2.2.17 on 2021-11-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caluma_workflow', '0027_add_modified_by_user_group'),
        ('caluma_form', '0040_add_modified_by_user_group'),
        ('core', '0088_auto_20211008_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowitem',
            name='caluma_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='caluma_form.Question'),
        ),
        migrations.AddField(
            model_name='workflowitem',
            name='caluma_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='caluma_workflow.Task'),
        ),
    ]
