# Generated by Django 2.2.17 on 2021-12-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20211126_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docxdecision',
            name='decision_type',
            field=models.CharField(blank=True, db_column='DECISION_TYPE', max_length=90, null=True),
        ),
    ]
