# Generated by Django 3.2.12 on 2022-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_fix_billing_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeletecirculation',
            name='is_single_delete',
            field=models.BooleanField(db_column='IS_SINGLE_DELETE', null=True),
        ),
    ]
