# Generated by Django 3.2.12 on 2022-03-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_alter_adeletecirculation_is_single_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instanceresource',
            options={'managed': True, 'ordering': ['resource__sort', 'sort']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'managed': True, 'ordering': ['sort']},
        ),
    ]
