# Generated by Django 3.2.13 on 2022-06-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20220328_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSimpleList',
        ),
    ]
