# Generated by Django 3.2.13 on 2022-06-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_delete_rsimplelist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rapilistcirculationtype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rapilistcirculationtype',
            name='circulation_type',
        ),
        migrations.RemoveField(
            model_name='rapilistcirculationtype',
            name='resource',
        ),
        migrations.AlterUniqueTogether(
            name='rapilistinstancestate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rapilistinstancestate',
            name='instance_state',
        ),
        migrations.RemoveField(
            model_name='rapilistinstancestate',
            name='resource',
        ),
        migrations.DeleteModel(
            name='RApiListCirculationState',
        ),
        migrations.DeleteModel(
            name='RApiListCirculationType',
        ),
        migrations.DeleteModel(
            name='RApiListInstanceState',
        ),
    ]
