# Generated by Django 3.2.13 on 2022-05-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_delete_apilist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionworkitem",
            name="is_activation",
        ),
    ]
