# Generated by Django 3.2.14 on 2022-08-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_remove_actionworkitem_is_activation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RCalumaList',
        ),
    ]
