# Generated by Django 3.2.15 on 2022-10-31 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_delete_rcalumalist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instanceresource',
            options={'managed': True, 'ordering': ['sort']},
        ),
        migrations.AlterField(
            model_name='instanceresource',
            name='form_group',
            field=models.ForeignKey(db_column='FORM_GROUP_ID', default=2000000, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.formgroup'),
        ),
        migrations.AlterField(
            model_name='instanceresource',
            name='sort',
            field=models.IntegerField(db_column='SORT', default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='sort',
            field=models.IntegerField(db_column='SORT', default=0),
        ),
    ]
