# Generated by Django 3.2.15 on 2023-03-22 09:32

import camac.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_delete_rcalumalist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instanceresource',
            options={'managed': True, 'ordering': ['sort']},
        ),
        migrations.AddField(
            model_name='billingv2entry',
            name='date_charged',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instanceresource',
            name='form_group',
            field=models.ForeignKey(db_column='FORM_GROUP_ID', default=camac.core.models.get_first_form_group, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.formgroup'),
        ),
        migrations.AlterField(
            model_name='instanceresource',
            name='sort',
            field=models.IntegerField(db_column='SORT', default=camac.core.models.next_instance_resource_sort),
        ),
        migrations.AlterField(
            model_name='resource',
            name='sort',
            field=models.IntegerField(db_column='SORT', default=camac.core.models.next_resource_sort),
        ),
    ]
