# Generated by Django 3.2.15 on 2023-04-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_missing_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingv2entry',
            name='date_charged',
            field=models.DateField(blank=True, null=True),
        ),
    ]
