# Generated by Django 3.2.15 on 2023-05-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0104_alter_irtaskform_instance_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="class_field",
            field=models.CharField(
                blank=True, db_column="CLASS", max_length=250, null=True
            ),
        ),
    ]
