# Generated by Django 3.2.19 on 2023-09-28 12:24

import localized_fields.fields.text_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_alter_resource_class_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticContent",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                (
                    "content",
                    localized_fields.fields.text_field.LocalizedTextField(
                        required=["de"]
                    ),
                ),
            ],
        ),
    ]
