# Generated by Django 3.2.19 on 2023-11-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_move_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceresource',
            name='require_permission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
