# Generated by Django 3.2.25 on 2024-06-14 07:31

import uuid

import django.db.models.deletion
import localized_fields.fields.text_field
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0026_service_external_identifier"),
        ("core", "0109_case_insensitive_collation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    localized_fields.fields.text_field.LocalizedTextField(
                        required=["de"]
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="user.service",
                    ),
                ),
            ],
        ),
    ]
