# Generated by Django 4.2.13 on 2024-07-11 13:59

from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_user_email'),
        ('core', '0110_servicecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecontent',
            options={'verbose_name': 'Service content', 'verbose_name_plural': 'Service contents'},
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='content',
            field=localized_fields.fields.text_field.LocalizedTextField(required=['de'], verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.service', verbose_name='Service'),
        ),
    ]
