# Generated by Django 4.2.15 on 2024-09-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caluma_form', '0048_option_is_hidden'),
        ('core', '0111_alter_servicecontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontent',
            name='forms',
            field=models.ManyToManyField(to='caluma_form.form', verbose_name='Forms'),
        ),
    ]
