# Generated by Django 4.2.16 on 2024-11-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_servicecontent_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHPSession',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('modified', models.IntegerField()),
                ('lifetime', models.IntegerField()),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'php_session',
            },
        ),
    ]
