# Generated by Django 5.2.6 on 2025-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_phpsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='disable_xss_protection',
            field=models.BooleanField(default=False),
        ),
    ]
