# Generated by Django 5.2.11 on 2026-02-23 09:17

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the GEVER models."""

    # We're doing it here so we can remove the GEVER module in one go and don't
    # have to do a staged removal, where we need to keep the GEVER module around
    # just to execute this migration. And since the GEVER app is now gone, we
    # don't have it's virtual (migration-constructed) representation anymore, so
    # we're deleting the models (and it's entries from the migrations table) via
    # plain SQL.
    #
    # The removal from the migrations table is there so we can -- in the very unlikely
    # case of resurrecting the module -- just restore the code, and the migrations
    # will run again, restoring the models as it it never happened.

    dependencies = [
        ("core", "0114_staticcontent_disable_xss_protection"),
    ]

    operations = [
        migrations.RunSQL(
            """
               DROP TABLE IF EXISTS gever_cmiconstantvalue;
               DROP TABLE IF EXISTS gever_cmiobjecttemplate;
               DELETE FROM django_migrations WHERE app = 'gever';
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
