# Generated by Django 5.2.11 on 2026-03-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_drop_gever_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyactionconfig',
            name='history_type',
            field=models.CharField(choices=[('notification', 'notification'), ('status-change', 'status-change'), ('document-mark', 'document-mark')], db_column='HISTORY_TYPE', max_length=20),
        ),
    ]
