# Generated by Django 5.2.11 on 2026-03-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_alter_historyactionconfig_history_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyactionconfig',
            name='history_type',
            field=models.CharField(choices=[('notification', 'notification'), ('status-change', 'status-change'), ('document-mark', 'document-mark'), ('publication', 'publication')], db_column='HISTORY_TYPE', max_length=20),
        ),
    ]
