# Generated by Django 5.2.11 on 2026-03-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_alter_historyactionconfig_history_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationentry',
            name='publication_journal_number',
            field=models.IntegerField(blank=True, db_column='PUBLICATION_JOURNAL_NUMBER', null=True),
        ),
    ]
