# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot

snapshots = Snapshot()

snapshots["test_get_document 1"] = {
    "ableitung-haeusliche-abwaesser": ["ARA", "Güllegrube"],
    "ableitung-in-guellegrube": "Ja",
    "abstellplaetze-fuer-fahrraeder-und-motorfahrraeder": 23,
    "aenderungen-dachflaechen-zufahrten-plaetzen": "Ja",
    "alkoholausschank": "Ja",
    "amts-verfugungsnummer": "555",
    "andere-dokument": ["Andere"],
    "anforderungen-eingehalten": [
        "Die Anforderungen sind gemäss Art. 11 – 15 BewD eingehalten."
    ],
    "anschluss-sammelkanaele-vorfluter-dokument": [
        "Zustimmung des Eigentümers für den Anschluss an die Sammelkanäle bzw. zur Einleitung in einen Vorfluter wenn die Gemeinde nicht Eigentümerin ist"
    ],
    "anzahl-abstellplaetze-fur-motorfahrzeuge": 23,
    "anzahl-arbeitsplaetze-aktuell": 700,
    "anzahl-arbeitsplaetze-nach-umbau": 7000,
    "anzahl-damen-toiletten": 7,
    "anzahl-gaerten-terrassen": 4,
    "anzahl-jugendliche-aktuell": 9000,
    "anzahl-jugendliche-nach-umbau": 90000,
    "anzahl-mitarbeitende-aktuell": 800,
    "anzahl-mitarbeitende-nach-umbau": 8000,
    "anzahl-pissoire": 7,
    "anzahl-sitzplaetze-fumoir": 10000,
    "anzahl-stehplaetze-fumoir": 10000,
    "anzahl-toiletten-herren": 7,
    "appartements": 2,
    "arbeit-waehrend-nachtzeit": "Ja",
    "art-der-baugrubenumschliessung": ["Spundwand"],
    "art-der-emmission-tabelle": [
        {
            "abluftentreinigungsanlage-beinhaltet": "Ja",
            "art-der-emmission": ["Gas- und dampfförmige Stoffe"],
            "brennstoff": "Holz",
            "feuerung": "Ja",
            "feuerwaermleistung-in-kw": 568,
            "kaminmuendung-ueberragt-dachfirst-um-meter": 89.0,
            "typ-der-abluftentreinigungsanlage": "Testabluftreinigungsanlage",
        }
    ],
    "art-der-fundationsmassnahmen": ["Tiefenfundation, Pfahlsystem"],
    "art-der-grundwasserabsenkung": ["Vakuumverfahren"],
    "art-der-notausgaenge": [
        "Drehflügeltüren",
        "Schiebetüren",
        "Roll-, Fall- oder Klapptore",
    ],
    "atmosphaerischer-unterdruck": "Ja",
    "auffangwanne": "Stahl",
    "auskleidung": "Beschichtung",
    "ausnahme-im-sinne-von-artikel-64-kenv": "Ja",
    "ausnahmebegruendung-dokument": ["Ausnahmebegründung"],
    "ausnahmegesuch-energie-dokument": ["Ausnahmegesuch Energie"],
    "ausnuetzung": "100",
    "ausnuetzung-dokument": ["Ausnützung"],
    "ausschankraeume": [
        {
            "davon-in-saelen": 45,
            "flaeche-in-quadratmeter": 45,
            "sitzplaetze": 45,
            "stockwerk": "Parterre",
            "zahl": 2,
        },
        {
            "davon-in-saelen": 40,
            "flaeche-in-quadratmeter": 45,
            "sitzplaetze": 45,
            "stockwerk": "1. Stock",
            "zahl": 45,
        },
    ],
    "aussenlaerm": "Ja",
    "auto-oder-fahrradabstellplaetze": "Ja",
    "bar-buffet-im-fumoir": "Ja",
    "bau-im-wald-oder-innerhalb-von-30-m-abstand": "Ja",
    "baubeschrieb": [
        "Neubau",
        "Um- / Ausbau",
        "Umnutzung",
        "Erweiterung / Anbau",
        "Abbruch",
        "Technische Anlage",
        "Reklame",
        "Tiefbauanlage",
        "Andere",
    ],
    "baugrunduntersuchung-dokument": [
        "Baugrunduntersuchung / Hydrogeologisches Gutachten"
    ],
    "baugruppe-bauinventar": "Ja",
    "baukosten-in-chf": 232323,
    "bauprofile-bleiben-bis-bauentscheid-stehen": [
        "Die Bauprofile sind gemäss Art. 16 BewD gestellt. Hiermit wird bestätigt, dass die Bauprofile bis zum rechtskräftigen Bauentscheid stehen bleiben und vor diesem Entscheid mit den Bauarbeiten nicht begonnen wird."
    ],
    "bauten-mit-mehr-als-30-grossvieheinheiten": "Ja",
    "bauten-oder-pfaehlen-im-grundwasser": "Ja",
    "be-gid": "23",
    "beanspruchte-flache-ober-unterboden-2000-m2": "Ja",
    "beanspruchte-flaeche-ober-unterboden-5000-m2": "Ja",
    "begasung-moeglich": "Ja",
    "begruendung-waldabstand-unterschritten": "Testbegründung",
    "belasteter-standort": "Ja",
    "bemerkungen": "Testbemerkung",
    "berechnung-kinderspielplaetze-dokument": [
        "Berechnung Kinderspielplätze / Aufenthaltsbereiche"
    ],
    "berechnungen-abstellplaetze-dokument": ["Berechnungen Abstellplätze"],
    "beschreibung-bauvorhaben": "Testbeschreibung&#13;&#10;blabla&#13;&#10;multiline",
    "beschreibung-boden-untergrund": "Testanderebeschreibung",
    "beschreibung-der-prozessart-tabelle": [
        {
            "beschreibung-der-gefaehrdung": "Testbeschreibung",
            "hauptprozessart": "Rutschung",
            "prozessart": "Fliesslawine",
        }
    ],
    "beschreibung-geplante-taetigkeit": "Testtätigkeitsbeschreibung",
    "beschreibung-organismen": "Testanderebeschreibung",
    "beschreibung-tiefenfundation": "Testtiefenfundationsbeschreib",
    "beschrieb-der-lueftung-dokument": [
        "Beschrieb der Lüftung/Bestätigung des Lüftungsbauers, dass die Lüftung keinen Rauch in die übrigen Räume des Betriebs gelangen lässt"
    ],
    "besondere-brandrisiken": "Ja",
    "bestaetigung-hydrogeo-begleitung-dokument": [
        "Auftragsbestätigung des Fachbüro für die hydrogeologische Begleitung"
    ],
    "bestaetigung-liegenschaftsentwaesserung": [
        'Der/die Gesuchsteller/in bestätigt, dass die Liegenschaftsentwässerung gemäss dem AWA-Merkblatt "Entwässerung von Industrie- und Gewerbeliegenschaften" geplant und realisiert werden. Als Beilage enthält das Gesuch einen Umgebungsplan, auf dem bei allen Teilfächen die vorgesehene Nutzung, die Befestigungsart, das Gefälle sowie die Entwässerungsart eingetragen sind.'
    ],
    "bestaetigung-mit-unterschrift": [
        "Der/die Gesuchsteller/in resp. die bevollmächtigte Vertretung bestätigt mit rechtsgültiger Unterschrift, dass die elektronisch übermittelten Daten (inkl. dem unterzeichneten Situationsplan) vollständig und wahrheitsgetreu ausgefüllt und eingereicht worden sind."
    ],
    "betriebskonzept": "Testbetriebskonzept",
    "betriebskonzept-gastgewerbe-dokument": ["Betriebskonzept Gastgewerbe"],
    "betriebsweise": "Bivalent",
    "bezeichnung-baugruppe": "Testbaugruppe",
    "bisherige-nutzung": "Test bisherige Nutzung",
    "bodenschutzkonzept-dokument": ["Bodenschutzkonzept"],
    "brandbelastung": "Ja",
    "brandschutzkonzept-dokument": ["Brandschutzkonzept"],
    "brandschutzplan-dokument": ["Brandschutzplan"],
    "brandschutzrisiken": [
        "Aussenwand: Bekleidung",
        "Tragwerk brennbar",
        "Dämmschichtbildende Systeme",
        "Brennbare Gase bis 1000 kg",
        "Brennbare Gase über 1000 kg",
        "bis 2000kg brennbare Flüssigkeit",
        "über 2000kg brennbare Flüssigkeit",
        "Pneulager bis 60t",
        "Pneulager über 60t",
        "Feuerwerkskörper bis 300kg",
        "Feuerwerkskörper über 300kg",
        "Mensch und Umwelt gefährdende Stoffe",
        "Explosionsgefährdete Räume oder Zonen",
        "Bauten mit Atrien oder Doppelfassaden",
        "Brandabschnittsfläche über 7200 m²",
        "Bruttogeschossfläche über 12000 m²",
        "Anwendung von Nachweisverfahren",
        "Hoher Anteil an Brandschutzmassnahmen",
        "Lagerung fester Brennstoffe 5m³",
    ],
    "brecher-oder-holzhacker": "Ja",
    "dach-farbe": "Testdachfarbe",
    "dach-form": "Testform",
    "dach-material": "Testdachmaterial",
    "dach-neigung": "Testneigung",
    "dauer-in-monaten": 23,
    "davon-in-garagen-oder-einstellhallen": 23,
    "davon-ueberdacht": 23,
    "dimensionierung-erdwaermesonden": "Berechnungsverfahren für komplexe Anlagen",
    "dokumente-der-bauausfuehrung-dokument": ["Dokumente der Bauausführung"],
    "druckausgleichsleitung-durchmesser-in-zoll": 500,
    "druckausgleichsleitung-rohrlaenge-in-meter": 1000,
    "duschmoeglichkeit-in-der-schleuse": "Ja",
    "e-mail-energie": "test@example.com",
    "e-mail-gastgewerbe": "smith@example.com",
    "e-mail-gewaesserschutzfragen": "smith@example.com",
    "e-mail-kontaktperson": "smith@example.com",
    "ech-subject": "Baugesuch",
    "effektive-geschosszahl": 21,
    "eigenstaendiger-grossverbraucher": "Ja",
    "eigentuemer-tabelle": [
        {
            "grundbuch-nr-wald-eigentuemer": 23807,
            "name-wald-eigentuemer": "Testname",
            "nr-wald-eigentuemer": "23",
            "ort-wald-eigentuemer": "Burgdorf",
            "parzellen-nr": "56",
            "plz-wald-eigentuemer": 2323,
            "strasse-wald-eigentuemer": "Teststrasse",
            "vorname-wald-eigentuemer": "Testvorname",
            "waldabstand": 789,
        }
    ],
    "einhaltung-asbestvorgaben": [
        "Der/die Gesuchsteller/in ist verantwortlich für die Einhaltung der Asbestvorgaben des Bundes (Chemikalien-Risikoreduktions-Verordnung, ChemRRV)."
    ],
    "einhaltung-radonvorgaben": [
        "Der/die Gesuchsteller/in ist verantwortlich für die Einhaltung der Radonvorgaben gemäss Strahlenschutzverordnung des Bundes."
    ],
    "einreichen-button": ["Eingereicht"],
    "empfindlichkeitsstufe": "5",
    "energiedokumente-dokument": ["Energiedokumente"],
    "entsorgungskonzept-dokument": ["Entsorgungskonzept"],
    "entwaesserung-der-dachflaechen": "Neu",
    "entzug-von-waerme-mittels-erdwaermesonde": "Ja",
    "erdwaermensondendimensionierung-dokument": ["Erdwärmensondendimensionierung"],
    "erhaltenswert": "Ja",
    "erleichterungen-waermeschutz": "Ja",
    "fabrikat": "Tesfabrikat",
    "fabrikat-auskleidung": "Testfabrikat 3",
    "fabrikat-fuellsicherung": "Testfabrikat 1",
    "fabrikat-leckwarnsystem": "Testfabrikat 2",
    "fallen-abwaesser-an": "Ja",
    "fallen-abwaesser-an-neuer-betrieb": "Ja",
    "fassaden-ansichten-dokument": [
        "Fassaden / Ansichten (inklusive Angaben zu Fensterflächen)"
    ],
    "fassaden-farbe": "Testfassadenfarbe",
    "fassaden-material": "Testfassadenmaterial",
    "fassadenplan-reklamestandort-dokument": [
        "Fassadenplan mit eingezeichnetem Reklamestandort"
    ],
    "feuerungsanlagen": [
        "Öl- oder Gasfeuerungen mit einer Feuerungswärmeleistung ≥ 350 kW",
        "Holzfeuerungen mit einer Feuerungswärmeleistung ≥ 70 kW",
        "Pellet-, Späne- oder Schnitzelfeuerungsanlage",
    ],
    "finden-bauarbeiten-in-der-nacht-statt": "Ja",
    "flaeche-fumoir": 3000,
    "fluessigkeiten-wassergefaehrdungsklasse-a": "Ja",
    "folgender-raum-soll-als-fumoir-bewilligt-werden": "Alles",
    "forstliche-baute": "Ja",
    "fruchtfolgeflaeche-ausgeschieden": "Ja",
    "fuellmenge-in-kg": 555,
    "fuellmenge-total-in-liter": 9000,
    "fuellsicherung": [
        "Elektrooptische Sonde",
        "Spezialfüllsicherung",
        "Mechanische Füllsicherung",
    ],
    "fumoir": ["Neu", "Bestehend", "Erweiterung"],
    "fundation-system": "Testsystem",
    "gaestebetten": 12,
    "gaestezimmer": 6,
    "gebaeudeversicherungswert-in-chf": 90000,
    "gebiet-mit-archaeologischen-objekten": "Ja",
    "gebiet-mit-naturgefahren": "Ja",
    "gebinde-in-grundwasserschutzzone": "Ja",
    "gebindelager-mit-totalem-nutzvolumen": "Ja",
    "gefaehrlich-fuer-bevoelkerung-oder-umwelt": "Ja",
    "gefaehrliche-stoffe": "Ja",
    "gefahrengutachten-dokument": ["Gefahrengutachten"],
    "gefahrenstufe": ["Rot"],
    "gemeinde": "Burgdorf",
    "gentechnisch-veraenderte-organismen": "Ja",
    "gentechnisch-veraenderte-pathogene-organismen": "Ja",
    "geplante-anlagen": ["Solar- oder Photovoltaik-Anlage"],
    "geplanter-baustart": "2019-09-15",
    "geschossflaeche-in-quadratmeter": "200",
    "geschossflaechen-dokument": ["Geschossflächen"],
    "gesuch-ausnahmebewilligung-dokument": [
        "Gesuch für eine Ausnahmebewilligung mit hydrogeologisches Gutachten und Nachweis, dass die Durchflusskapazität des Grundwassers gegenüber dem unbeinflussten Zustand um höchstens 10% vemindert wird."
    ],
    "gesuch-erleichterung-waermeschutz-dokument": [
        "Gesuch um Erleichterung oder Befreiung Wärmeschutz"
    ],
    "gesuch-zur-ausnahme-dokument": ["Gesuch zur Ausnahme gemäss Art 31 Abs. 2 LSV"],
    "gewaesserschutz-landwirtschaft-dokument": ["Gewässerschutz Landwirtschaft"],
    "gewaesserschutzbereich": ["Ao"],
    "gibt-es-bewilligungspflichtige-reklame": "Ja",
    "grenzwerte-fenster-ueberschritten": "Ja",
    "grenzwerte-ueberschritten": "Ja",
    "gruenflache-in-quadratmeter": "23",
    "gruenflaeche-dokument": ["Grünfläche"],
    "grundriss-angabe-bodenflaeche-dokument": [
        "Grundriss (Massstäblich (1:100 / 1:50) mit Angabe der Bodenfläche)"
    ],
    "grundriss-dokument": ["Grundriss"],
    "grundstuecksentwaesserungsplan-dokument": [
        "Grundstücksentwässerungsplan SN 592 000"
    ],
    "grundwasserschutzzonen": ["S1"],
    "gueterumschlag-im-freien-oder-an-rampen": "Ja",
    "gwr-egid": "23",
    "handelt-es-sich-um-ein-baudenkmal": "Ja",
    "handelt-es-sich-um-ein-sensibles-objekt": "Ja",
    "handelt-es-sich-um-eine-baute-im-wald": "Ja",
    "heizleistungsbedarf-boden-untergrund": 555,
    "hepa-filter-abluft": "Nein",
    "hepa-filter-zuluft": "Nein",
    "hoechstmoeglicher-grundwasserspiegel": "23",
    "hoehe": ["Mittlere Höhe zwischen 11 m und 30 m"],
    "hoehe-groesser-als-1800-m-ue-m": "Ja",
    "hydrogeologische-begleitung-dokument": [
        "Auftragsbestätigung für Hydrogeologische Begleitung"
    ],
    "im-grundwasser-verbleibendes-einbauvolumen": 7,
    "in-quadratmeter": 400,
    "integration-anderer-gebaeude": "Ja",
    "ist-das-vorhaben-energierelevant": "Ja",
    "ist-durch-das-bauvorhaben-boden-betroffen": "Ja",
    "ist-ein-fumoir-betroffen": "Ja",
    "ist-fuer-das-vorhaben-eine-rodung-notwendig": "Ja",
    "ist-mit-bauabfaellen-zu-rechnen": "Ja",
    "k-objekt": "Ja",
    "kaelteleistung-boden-untergrund": 2323,
    "kaeltemittel": "Testkältemittel",
    "kanalisationskatasterplan-dokument": ["Kanalisationskatasterplan"],
    "kann-inhalt-zurueckgehalten-werden": "Nein",
    "keine-rueckhiebe-oder-aushiebe": [
        "Die Bauherrschaft nimmt für sich und ihre Rechtsnachfolge zur Kenntnis, dass keine Rückhiebe oder andere über das Kapprecht hinausgehenden Aushiebe an dem vom Näherbau tangierten Wald bewilligt werden; es ist verboten, auch wenn der Wald ihr gehört, solche Hiebe zwecks Verminderung des Schattenwurfes, zur Verbesserung der Aussicht oder aus anderen Gründen vorzunehmen."
    ],
    "keine-tangierung-natur-wild-vogelschutz": [
        "Der/die Gesuchsteller/in bestätigt, dass er keinen Tatbestand zu den Bestimmungen zum Natur-, Wild- und Vogelschutz tangiert."
    ],
    "klassierung-der-taetigkeit": "Klasse 2",
    "kontaktperson-name-energie": "Testkontaktvorname",
    "kontaktperson-vorname-energie": "Testkontaktname",
    "kontrolle-der-abwaesser-vorhanden-geplant": "Ja",
    "kurzbericht-datum": "2019-10-19",
    "kurzbericht-gemaess-stfv-dokument": ["Kurzbericht gemäss StFV"],
    "laden": [
        {
            "oeffnungszeit-laden": "01:00",
            "schliesszeit-laden": "23:00",
            "wochentag-laden": "Samstag",
        },
        {
            "oeffnungszeit-laden": "05:00",
            "schliesszeit-laden": "09:00",
            "wochentag-laden": "Montag",
        },
    ],
    "laermige-bauphase-laenger-als-6-tage": "Ja",
    "laermintensive-bauarbeiten-ueber-6-tage": "Ja",
    "lagerung-von-stoffen": [
        {
            "brennbare-fluessigkeit-gas": "Ja",
            "flammpunkt": "Leichtbrennbare Flüssigkeit mit Flammpunkt < 30 Grad",
            "gesundheitsschaedlich-oder-explosiv": "Ja",
            "lagerort": "Kühlschrank",
            "lagerstoff": "Plutonium",
            "massangabe": "Kg",
            "menge": 50000,
            "neu-bestehend": "Neu",
            "wassergefaehrdend": "Ja",
        },
        {
            "brennbare-fluessigkeit-gas": "Ja",
            "flammpunkt": "Brennbare Flüssigkeit mit Flammpunkt < 60 Grad",
            "gesundheitsschaedlich-oder-explosiv": "Ja",
            "lagerort": "Keller",
            "lagerstoff": "Alkohol",
            "massangabe": "Liter",
            "menge": 10000,
            "neu-bestehend": "Bestehend",
            "wassergefaehrdend": "Ja",
        },
    ],
    "leckwarnsystem": [
        "Mit Unterdruck (Vakuum)",
        "Mit Flüssigkeitsfühler",
        "Mit Überdruck",
    ],
    "leitungsbau-auf-landwirtschaftlichem-boden": "Ja",
    "liegt-die-baute-im-waldabstandsbereich": "Ja",
    "liegt-kurzbericht-vor": "Ja",
    "liegt-risikoermittlung-vor": "Ja",
    "luftreinigung-mit-hepa-filter": "Ja",
    "maschinelle-arbeitsmittel": "Ja",
    "maschinen-aus-den-folgenden-kategorien": [
        "Für die Reinigung-, Aufbereitung- und Beschichtung",
        "Für den Transport und das Verpacken von Materialien",
        "Für die industrielle / gewerbliche Erzeugung von Lebens- oder Futtermittel",
        "Für die Erzegung, Speicherung oder Lagerung von Strom, Wärme oder Brennstoffen",
        "Für Deponien, Werkhöfe, Betriebsgebäude oder auf Betriebsarealen",
    ],
    "maschinen-mit-aussenlaermimmissionen": "Ja",
    "maschinen-und-anlagen-tabelle": [
        {
            "bezeichnung-maschinen-und-anlagen": "Testbezeichnung Maschine 1",
            "standort-maschinen-und-anlagen": "Teststandort Maschine 1",
            "typ-maschinen-und-anlagen": "Testtyp Maschine 1",
            "verwendung-maschinen-und-anlagen": "Testverwendung Maschine 1",
        },
        {
            "bezeichnung-maschinen-und-anlagen": "Testbezeichnung Maschine 2",
            "standort-maschinen-und-anlagen": "Teststandort Maschine 2",
            "typ-maschinen-und-anlagen": "Testtyp Maschine 2",
            "verwendung-maschinen-und-anlagen": "Testverwendung Maschine 2",
        },
    ],
    "massenlager": 4,
    "mechanische-lueftung": "Ja",
    "mehr-als-1500-m3-bodenmaterial": "Ja",
    "mehr-als-500-m3-bodenmaterial": "Ja",
    "mehrkammertanks-tabelle": [
        {
            "behaelterwerkstoff-mehrkammertanks": ["Metall"],
            "fassvermoegen-in-liter-mehrkammertanks": 20000,
            "kammer": "Was?",
            "lagergut": ["-"],
            "tankfabrikant-mehrkammertanks": "Testtankfabrikant 1",
        },
        {
            "behaelterwerkstoff-mehrkammertanks": ["Kunststoff"],
            "fassvermoegen-in-liter-mehrkammertanks": 50000,
            "kammer": "Wie?",
            "lagergut": ["-"],
            "tankfabrikant-mehrkammertanks": "Testtankfabrikant 2",
        },
    ],
    "meldeblatt-terrainveraenderungen-dokument": [
        "Meldeblatt für Terrainveränderungen zur Bodenaufwertung"
    ],
    "meldeblatt-zur-fruchtfolgeflaeche-dokument": ["Meldeblatt zur Fruchtfolgefläche"],
    "menge-des-abzuleitenden-grundwassers": 9000,
    "mengenschwelle-hochaktive-stoffe": "Ja",
    "mengenschwelle-sonderabfaelle-ueberschritten": "Ja",
    "mit-invasiven-neophyten-belasteter-boden": "Ja",
    "mit-schadstoffen-belastete-luft-aus-gebaeuden": "Ja",
    "mittlerer-grundwasserspiegel": "12",
    "mittlerer-schallabsorptionsgrad": "Ja",
    "nachhallzeiten": "Ja",
    "nachweis-anforderungen-dokument": ["Nachweis Anforderungen gemäss Art 31 LSV"],
    "naeherbau-grenzbaurecht-dokument": ["Näherbau- / Grenzbaurecht"],
    "name-betrieb-energie": "Testbetrieb",
    "name-betrieb-gastgewerbe": "Gasthof Rössli",
    "name-betrieb-personalien": "Testname des Betriebs",
    "name-des-gewaessers-regen": "Mittelmeer",
    "name-gastgewerbe": "McFly",
    "name-gewaesserschutzfragen": "Smith",
    "name-kontaktperson": "Smith",
    "naturschutz": "Ja",
    "neubau-abwasseranlagen-grundleitungen": "Ja",
    "neue-dachflaechen-in-quadratmeter": 23.0,
    "nicht-forstliche-kleinbaute": "Nein",
    "notbeleuchtung": "Ja",
    "nr": "23",
    "nummer-energie": "5",
    "nummer-gastgewerbe": "5",
    "nummer-personalien": "46",
    "nutzungsart": [
        "Wohnen",
        "Industrie",
        "Gewerbe",
        "Dienstleistung",
        "Verkauf",
        "Lager",
        "Landwirtschaft",
        "Gastgewerbe",
        "Andere",
    ],
    "nutzungszone": "Testnutzungszone",
    "oberflaechengewaesser-regenabwasserleitung": "Ja",
    "objekt-des-besonderen-landschaftsschutzes": "Ja",
    "objektbezeichnung": "Testobjektbezeichnung",
    "oeffentlichkeit": "öffentlich",
    "oeffnungszeiten": "generelle Überzeit",
    "offnungszeiten-tabelle": [
        {"schliessungszeit": "23:00", "wochentag": "Sonntag"},
        {"schliessungszeit": "10:00", "wochentag": "Freitag"},
    ],
    "organismen-in-anlage": [
        "Prionen",
        "Viren",
        "Bakterien",
        "Parasiten",
        "Pflanzen",
        "andere",
    ],
    "ort": "Test Ort für Notbeleuchtung",
    "ort-energie": "Burgdorf",
    "ort-gastgewerbe": "Burgdorf",
    "ort-grundstueck": "Burgdorf",
    "ort-personalien": "Burgdorf",
    "parzelle": [
        {
            "baurecht-nummer": "23",
            "e-grid-nr": "23",
            "lagekoordinaten-nord": "1070500.000",
            "lagekoordinaten-ost": "2480034.0",
            "liegenschaftsnummer": 23,
            "nummer-parzelle": "23",
            "ort-parzelle": "Burgdorf",
            "parzellennummer": "1586",
            "plz-parzelle": 2323,
            "strasse-parzelle": "Teststrasse",
        }
    ],
    "personalbetten": 45,
    "personalien-gesuchstellerin": [
        {
            "e-mail-gesuchstellerin": "test@example.com",
            "juristische-person-gesuchstellerin": "Nein",
            "name-gesuchstellerin": "Testname",
            "nummer-gesuchstellerin": "23",
            "ort-gesuchstellerin": "Burgdorf",
            "plz-gesuchstellerin": 2323,
            "strasse-gesuchstellerin": "Teststrasse",
            "telefon-oder-mobile-gesuchstellerin": "0781234567",
            "vorname-gesuchstellerin": "Testvorname",
        }
    ],
    "personalien-vertreterin-mit-vollmacht": [
        {
            "e-mail-vertreterin": "test@example.com",
            "juristische-person-vertreterin": "Nein",
            "name-vertreterin": "Testname",
            "nummer-vertreterin": "23",
            "ort-vertreterin": "Burgdorf",
            "plz-vertreterin": 2323,
            "strasse-vertreterin": "Teststrasse",
            "telefon-oder-mobile-vertreterin": "0791234567",
            "vollmacht": [
                "Der/die Gesuchsteller/in bestätigt mit Unterschrift, die Generalvollmacht an Bevollmächtigte"
            ],
            "vorname-vertreterin": "Testvorname",
        }
    ],
    "plaene-fumoir-dokument": ["Pläne Fumoir"],
    "plaene-gewaesserschutz-dokument": [
        "Pfahl-, Injektions- oder Ankerpläne, Situation und Schnittpläne mit Koten in m ü.M. (falls geplant)"
    ],
    "plaene-schleusen-dokument": ["Pläne - Zugang zum Arbeitsbereich über Schleusen"],
    "plaene-unterdruck-dokument": ["Pläne - Atmosphärischer Unterdruck"],
    "plane-gastgewerbebetrieb-dokument": ["Pläne Gastgewerbebetrieb"],
    "platz-und-verkehrsflaechen": "Neu",
    "plz-energie": 2000,
    "plz-gastgewerbe": 3400,
    "plz-personalien": 3400,
    "produkteleitung": [
        "Sichtbar",
        "Mit Rücklauf",
        "Im Leckerkennungsrohr",
        "1-Strang",
        "Saugbetrieb",
        "Druckpumpe",
        "Doppelmantel",
        "Leckwarngerät",
        "Vakuum- / Magnetventil",
        "Eigensicher",
    ],
    "projektverfasserin-identisch": "Nein",
    "prostitution": "Ja",
    "qss-stufe": ["1"],
    "rechtliche-sicherung-fremden-bodens": "Nein",
    "regeneration-oder-aktive-thermische-aufladung": "Ja",
    "regierungsratsbeschluss-bauinventar-dokument": [
        "Regierungsratsbeschluss zum Bauinventar"
    ],
    "reklame-tabelle": [
        {
            "abschaltung-geplant": "Nein",
            "abstand-boden-bis-unterkante": 6,
            "abstand-fahrbahnrand-bis-aussenkante": 9,
            "abstand-fassade-bis-aussenkante": 7,
            "art-der-beleuchtung": [
                "Keine",
                "Leuchtkasten",
                "einzelne Buchstaben",
                "blinkend",
                "Bildschirm",
                "von oben",
                "von unten",
            ],
            "bemerkung-zur-beleuchtung": "Testbemerkung",
            "bemerkungen-reklame": "Testbemerkung",
            "breite-in-cm": "90000",
            "gesamtlaenge-in-cm": 90000.0,
            "grundfarben": "schwarz",
            "montageort-am-gebaeude": "Testmontageort",
            "montageort-freistehende-reklame": "Testbeschrieb",
            "reklame-neu-oder-ersatz": "Neu",
            "schriftfarben-bei-nacht": "blau",
            "schriftfarben-bei-tag": "rot",
            "text": "Testtext",
        }
    ],
    "risikoermittlung-datum": "2019-10-26",
    "risikoermittlung-gemaess-stfv-dokument": ["Risikoermittlung gemäss StFV"],
    "rodungs-und-ersatzaufforstungsplan-dokument": [
        "Rodungs- und Ersatzaufforstungsplan"
    ],
    "rodungsgesuchsformular-bafu-dokument": ["Rodungsgesuchsformular BAFU"],
    "rrb": "Ja",
    "rrb-vom": "2019-10-26",
    "rueckbau-checkliste-selbstdeklaration-dokument": [
        "Rückbau Checkliste / Selbstdeklaration"
    ],
    "rueckhaltevolumen-der-auffangwanne-in-prozent": 90,
    "sammelschutzraum": "Nein",
    "sanitaertechnische-anpassungen-liegenschaft": "Ja",
    "schalldruckpegelabnahme": "Ja",
    "schmutz-oder-mischwasserkanalisation": "Ja",
    "schnitt-dokument": ["Schnitt"],
    "schnittplan-gewaesserschutz-dokument": [
        "Schnittplan mit Untergeschoss und Baugrubenumschliessung, eingezeichneter Wasserhaltung sowie mittlerem Grundwasserspiegel (mit den entsprechenden Koten in m ü.M.)"
    ],
    "schuetzenswert": "Ja",
    "schutzbauwerk": [
        "Beton nach SIA Norm 262 und SN-EN 206-1",
        "Mit Auskleidung",
        "Ohne Auskleidung",
        "Dichtigkeitsprüfung mit Wasserflutung",
    ],
    "schutzraum-pflicht": "Ja",
    "schutzraumbefreiung-beantragt": "Nein",
    "seit-welchem-jahr-besteht-der-betrieb-am-standort": 1900,
    "sicherheitsdaten-stoerfallvorsorge-dokument": [
        "Sicherheitsdatenblätter Störfallvorsorge"
    ],
    "sicherheitsmassnahmen-eingehalten": "Ja",
    "sicherheitsstufe-der-anlage": "Stufe 4",
    "sicherungsleistung-befreit-dokument": [
        "Vertrag - mit Sicherungsleistung befreite Gebäude"
    ],
    "sicherungsmassnahme-dokument": ["Sicherungsmassnahme"],
    "sind-bauschadstoffe-zu-erwarten": "Ja",
    "sind-belange-des-gewasserschutzes-betroffen": "Ja",
    "situationsplan-dokument": ["Situationsplan"],
    "sitzplaetze-garten": 300,
    "skizze-der-reklame-mit-farbangaben-dokument": [
        "Skizze der Reklame mit Farbangaben"
    ],
    "sondenmodelle": [
        {
            "anzahl-sonden": 6,
            "bohrlaenge-einzeln-in-meter": 466,
            "sondendurchmesser-in-mm": 23,
            "sondenmodell": "Doppel-U-Sonde",
        }
    ],
    "spezifische-waermeentzugsleistung-in-wm": "453",
    "sterilisation-abwasser-dokument": ["Sterilisation Abwasser"],
    "sterilisation-des-abwassers": "Ja",
    "stoerende-lichtreflektionen": "Ja",
    "stoffliste-stoerfallvorsorge-dokument": ["Stoffliste Störfallvorsorge"],
    "strasse-energie": "Teststrasse",
    "strasse-flurname": "Teststrasse",
    "strasse-gastgewerbe": "Teststrasse",
    "strasse-personalien": "Teststrasse",
    "striptease": "Ja",
    "system": "Testsystem",
    "taetigkeit-des-betriebs-gastgewerbe": "Test Tätigkeit des Betriebs",
    "taetigkeit-des-betriebs-personalien": "Test Tätigkeit des Betriebs",
    "tankanlage-ueber-2000-liter": "Ja",
    "tanks-in-gewaesserschutzbereichen": "Ja",
    "tanzbetrieb": "Ja",
    "telefon-oder-mobile-energie": "0791234567",
    "telefon-oder-mobile-gastgewerbe": "0761234567",
    "telefon-oder-mobile-gewaesserschutzfragen": "0761234567",
    "telefon-oder-mobile-kontaktperson": "0761234567",
    "terrain-kote": "100",
    "terrainveraenderung-weniger-als-2000m2": "Ja",
    "tiefste-kote-der-aushubsohle": 500.0,
    "total-bohrlaenge": "666",
    "tragkonstruktion-decken": "Testdecken",
    "tragkonstruktion-stuetzen": "Teststützen",
    "tragkonstruktion-waende": "Testände",
    "typ-dachflaechen": "Typ A",
    "typ-platz-und-verkehrsflaechen": "Über Schulter",
    "typ-waermepumpen": "Testtyp",
    "ueberbauung-dokument": ["Überbauung"],
    "ueberbauung-in-prozent": "100",
    "ueberbauungsordnung": "???",
    "uebersichtsplan-dokument": ["Übersichtsplan 1:25'000"],
    "um-was-fuer-ein-gebaeude-handelt-es-sich": ["EFH", "MFH"],
    "umfasst-die-bauabfallmenge-200-kubikmeter": "Ja",
    "unterkante-der-baugrubenumschliessung": 200.0,
    "verfahren-fuer-die-sterilisation-des-abwassers": "Testverfahren",
    "verpflichtung-bei-handaenderung": [
        "Bei einer allfälligen Handänderung verpflichten sich die Bauherrschaft und Grundeigentümerin/Grundeigentümer, bzw. Baurechtsnehmerin/Baurechtsnehmer, diese Erklärung einer allfälligen Rechtsnachfolge zu überbinden."
    ],
    "versickerung": "Ja",
    "versickerung-dachflaechen": "Ja",
    "versickerung-platz-und-verkehrsflaechen": "Ja",
    "versickerungsanlagen-dokument": [
        "Pläne, Berichte und Berechnungen über neue und bestehende Versickerungsanlagen"
    ],
    "vertrag": "Ja",
    "vertrag-vom": "2019-10-19",
    "vertrag-zum-bauinventar-dokument": ["Vertrag zum Bauinventar"],
    "verunreinigte-abluft": "Ja",
    "verwendungszweck-boden-untergrund": ["Raumheizung", "Kühlen", "Andere"],
    "verwendungszweck-der-anlage": [
        "Forschung",
        "Produktion",
        "Diagnostik",
        "Tieranlage",
    ],
    "verwertung-abgetragenem-boden-dokument": [
        "Deklaration zur Verwertung von abgetragenem Boden"
    ],
    "verzicht-schadensersatz-naturereignisse": [
        "Der/die Gesuchsteller/in verzichtet für sich und seine/ihre Rechtsnachfolger ausdrücklich auf jeden Ersatz von Schaden, der durch den Forstbetrieb oder durch Naturereignisse, wie Schneedruck, Windfall usw. an der zu erstellenden Baute, bzw. ähnlichen Anlage verursacht werden könnte. Vorbehalten bleiben jedoch die Bestimmungen der Art. 41 ff. OR."
    ],
    "vollmacht-dokument": ["Vollmacht"],
    "vorabklaerung-dokument": ["Vorabklärung"],
    "vorbereitende-massnahmen": ["Rammen"],
    "vorname-gastgewerbe": "Marty",
    "vorname-gewaesserschutzfragen": "Winston",
    "vorname-kontaktperson": "Winston",
    "waermetraegerfluessigkeit": "Methylalkohol (Methanol)",
    "was-fuer-ein-vorhaben": [
        "Verkehrintensives Vorhaben",
        "Verwaltungsgebäude",
        "Verkaufsgeschäfte / Geschäftshäuser / Einkaufszentren",
        "Gastgewerbe (Restaurant)",
        "Grossraumbüros 400 m² oder mehr als 20 Arbeitsplätze im gleichen Raum",
        "Spitäler, Kliniken, Heime, Schwimmbäder, Sportplätze / Sportanlagen, Eishallen, Kinos, Theater, Museen, Kirchen und Schulhäuser mit mech. Werkstätten, Lagerhallen",
        "Beherbergungsbetriebe (Hotel, Ferienheim, ...)",
        "Andere",
    ],
    "wassergefaehrdende-explosive-stoffe": "Ja",
    "wasserverbrauch-im-bestehenden-betrieb": 1000,
    "wasserverbrauch-im-neuen-betrieb": 2000,
    "weitere-personen": ["Vertreter/in mit Vollmacht"],
    "weitere-vorhaben": "Test weitere Vorhaben",
    "welche-art-vorhaben": [
        "Gebäude geringer Abmessung",
        "Erschliessungsanlagen (z.B. Alpwege, Waldstrassen, ...)",
        "Schule / Kindergarten",
        "Parking",
        "Räume mit grosser Personenbelegung (über 300 Personen)",
        "Erstellung / Erneuerung von Aussenraum (Strasse, Fussweg, Trottoirs, Haltestellen, etc.)",
        "Bauten unbekannter Nutzung",
        "Ferienhaus",
        "Umnutzungen (z.B. zivile Nutzung militärischer Bauten)",
        "Tourismus (z.B. Bikestrecke, Spielplätze, Wanderwege)",
        "Fischhaltung / Aquakulturanlage",
        "Planungen (z.B. UeO mit Baubewilligung)",
        "Reklamevorhaben",
        "Weitere",
    ],
    "welche-waermepumpen": ["Boden / Untergrund"],
    "werden-bestehende-bauten-zurueckgebaut": "Ja",
    "werden-brandschutzabstaende-unterschritten": "Ja",
    "werden-luftemissionen-erzeugt": "Ja",
    "werden-neue-hofduengeranlagen-erstellt": "Ja",
    "werden-siloanlagen-erstellt": "Ja",
    "wert-mittlerer-schallabsorptionsgrad": 45,
    "wert-nachhallzeiten": 5,
    "wert-schalldruckpegelabnahme": 70,
    "wildtierschutz": "Ja",
    "wird-aussenlaerm-erzeugt": "Ja",
    "wird-kuehlwasser-im-betrieb-verwendet": "Ja",
    "wohnungen": [
        {
            "anzahl-wohnungen-bestehend": 0,
            "anzahl-wohnungen-neu": 21,
            "wohnungsgroesse": "7",
        }
    ],
    "wurden-vorabklaerungen-durchgefuehrt": "Nein",
    "zufahrten-plaetze-in-quadratmeter": 23.0,
    "zugang-zum-arbeitsbereich-ueber-schleuse": "Ja",
    "zulaessige-geschosszahl": "23",
    "zustimmung-der-anstoesser-dokument": [
        "Zustimmung der Anstösser falls die Versickerung nicht publiziert wurde"
    ],
    "zustimmung-der-nachbarn-dokument": ["Zustimmung der Nachbarn nach 27 / 4 BewD"],
}
