parent=keycloak

styles=css/style.css
scripts=js/script.js

locales=de,fr

# !!! hint: empty definitions are on purpose to clear default values!!!
kcFormClass=
kcFormGroupClass=form-group
kcLabelWrapperClass=label-wrapper
kcLabelClass=floating-label
kcInputWrapperClass=input-wrapper
kcInputClass=floating-input
kcInputErrorMessageClass=form-error-text
kcButtonBlockClass=block-button
kcButtonClass=button
kcButtonDefaultClass=secondary
kcButtonPrimaryClass=primary
kcButtonLargeClass=
kcLocaleListClass=language-selector
kcLocaleListItemClass=language
kcLocaleItemClass=service-menue language-tag

