# Generated by Django 2.2.11 on 2020-04-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0017_fix_submit_date'),
        ('objection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectionTimeframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objection_timeframes', to='instance.Instance')),
            ],
        ),
    ]
