# Generated by Django 2.2.17 on 2021-06-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objection', '0002_objectiontimeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
