<h3 class="headingWithDisable">2 <?php echo $this->sections[1]->name; ?></h3>
<div class="disableBox">
	<label for="section2disabled"><?php echo $this->translate('Rechtsmittelverfahren ausblenden'); ?></label>
	<input
		id="section2disabled"
		name="disabledSections[<?php echo $this->sections[1]->baSectionId;  ?>]"
		type="checkbox"
		data-disable-query="table.section2"
		<?php if ($this->sections[1]->isDisabled($this->instanceId)) { echo 'checked="checked"';} ?>
	>
</div>
<div style="clear: right"></div>
<table
	class="buildingAuthority section2"
	<?php if ($this->sections[1]->isDisabled($this->instanceId)) { echo 'style="display: none"';} ?>
>
	<tr>
		<td>
			<label for="workflowItem48">
				<?php echo $this->translate($this->workflowItems[48]->getName()); ?>
			</label><br>
			<input
				id="workflowItem48"
				name="workflowItem[48]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[48], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<label for="workflowItem51">
				<?php echo $this->translate($this->workflowItems[51]->getName()); ?>
			</label><br>
			<input
				id="workflowItem51"
				name="workflowItem[51]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[51], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<label for="workflowItem50">
				<?php echo $this->translate($this->workflowItems[50]->getName()); ?>
			</label><br>
			<input
				id="workflowItem50"
				name="workflowItem[50]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[50], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<label for="workflowItem49">
				<?php echo $this->translate($this->workflowItems[49]->getName()); ?>
			</label><br>
			<input
				id="workflowItem49"
				name="workflowItem[49]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[49], $this->instanceId)); ?>"
			>
		</td>
	</tr>
	<tr>
		<td>
			<label for="workflowItem52">
				<?php echo $this->translate($this->workflowItems[52]->getName()); ?>
			</label><br>
			<input
				id="workflowItem52"
				name="workflowItem[52]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[52], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<label for="workflowItem53">
				<?php echo $this->translate($this->workflowItems[53]->getName()); ?>
			</label><br>
			<input
				id="workflowItem53"
				name="workflowItem[53]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[53], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<label for="workflowItem63">
				<?php echo $this->translate($this->workflowItems[63]->getName()); ?>
			</label><br>
			<input
				id="workflowItem63"
				name="workflowItem[63]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[63], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<label for="workflowItem64">
				<?php echo $this->translate($this->workflowItems[64]->getName()); ?>
			</label><br>
			<input
				id="workflowItem64"
				name="workflowItem[64]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[64], $this->instanceId)); ?>"
			>
		</td>
	</tr>
	<tr>
		<td>
			<label for="workflowItem54">
				<?php echo $this->translate($this->workflowItems[54]->getName()); ?>
			</label><br>
			<input
				id="workflowItem54"
				name="workflowItem[54]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[54], $this->instanceId)); ?>"
			>
		</td>
	</tr>
	<tr>
		<td colspan="4">
			<label for="comment2"><?php echo $this->translate('Bemerkungen'); ?></label><br>
			<textarea
				id="comment2"
				name="comment[<?php echo $this->sections[1]->baSectionId;  ?>]"
			><?php
				if (isset($this->comments[$this->sections[1]->baSectionId])) {
					echo $this->comments[$this->sections[1]->baSectionId][1]->text;
				}
			?></textarea>
		</td>
	</tr>
</table>
