<h3>3 <?php echo $this->sections[2]->name; ?></h3>
<table class="buildingAuthority section3">
	<?php for($i = 1; $i <= $this->groupCount; $i++): ?>
	<?php if ($i > 1): ?><tr><td colspan="4" class="stageDivide"><hr></td></tr><?php endif; ?>
	<tr>
		<td>
		<label for="workflowItem55-<?php echo $i; ?>">
				<?php echo $this->translate($this->workflowItems[55]->getName()); ?>
			</label><br>
			<input
				id="workflowItem55-<?php echo $i; ?>"
				name="workflowItem[55][<?php echo $i; ?>]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[55], $this->instanceId, $i)); ?>"
			>
		</td>
		<td>
			<label for="workflowItem56-<?php echo $i; ?>">
				<?php echo $this->translate($this->workflowItems[56]->getName()); ?>
			</label><br>
			<input
				id="workflowItem56-<?php echo $i; ?>"
				name="workflowItem[56][<?php echo $i; ?>]"
				type="text"
				class="date withDisable"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[56], $this->instanceId, $i)); ?>"
				<?php if ($this->isItemDisabled(56, $this->instanceId, $i)) { echo 'disabled'; } ?>
			>
			<div class="disableBoxInline">
				<label for="item56disable"><?php echo $this->translate('Feld deaktivieren'); ?></label>
				<input
					id="item56disable"
					name="disabledItems[56][<?php echo $i; ?>]"
					type="checkbox"
					data-disable-query="input#workflowItem56-<?php echo $i; ?>"
					<?php if ($this->isItemDisabled(56, $this->instanceId, $i)) { echo 'checked'; } ?>
				>
			</div>
		</td>
		<td>
			<label for="workflowItem58-<?php echo $i; ?>">
				<?php echo $this->translate($this->workflowItems[58]->getName()); ?>
			</label><br>
			<input
				id="workflowItem58-<?php echo $i; ?>"
				name="workflowItem[58][<?php echo $i; ?>]"
				type="text"
				class="date withDisable"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[58], $this->instanceId, $i)); ?>"
				<?php if ($this->isItemDisabled(58, $this->instanceId, $i)) { echo 'disabled'; } ?>
			>
			<div class="disableBoxInline">
				<label for="item58disable"><?php echo $this->translate('Feld deaktivieren'); ?></label>
				<input
					id="item58disable"
					name="disabledItems[58][<?php echo $i; ?>]"
					type="checkbox"
					data-disable-query="input#workflowItem58-<?php echo $i; ?>"
					<?php if ($this->isItemDisabled(58, $this->instanceId, $i)) { echo 'checked'; } ?>
				>
			</div>
		</td>
		<td>
			<label for="workflowItem67-<?php echo $i; ?>">
				<?php echo $this->translate($this->workflowItems[67]->getName()); ?>
			</label><br>
			<input
				id="workflowItem67-<?php echo $i; ?>"
				name="workflowItem[67][<?php echo $i; ?>]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[67], $this->instanceId, $i)); ?>"
			>
		</td>
	</tr>
	<tr>
		<td>
			<label for="workflowItem59-<?php echo $i; ?>">
				<?php echo $this->translate($this->workflowItems[59]->getName()); ?>
			</label><br>
			<input
				id="workflowItem59-<?php echo $i; ?>"
				name="workflowItem[59][<?php echo $i; ?>]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[59], $this->instanceId, $i)); ?>"
			>
		</td>
		<td colspan="3">
			<label for="comment3-<?php echo $i; ?>"><?php echo $this->translate('Bemerkungen'); ?></label><br>
			<textarea
				id="comment3-<?php echo $i; ?>"
				name="comment[<?php echo $this->sections[2]->baSectionId;  ?>][<?php echo $i; ?>]"
			><?php
				if (isset($this->comments[$this->sections[2]->baSectionId][$i])) {
					echo $this->comments[$this->sections[2]->baSectionId][$i]->text;
				}
			?></textarea>
		</td>
	</tr>
	<?php endfor; ?>
	<tr>
		<td colspan="4">
			<button id="addStage" class="button" type="button"><?php echo $this->translate('Etappe hinzufügen'); ?></button>
		</td>
	</tr>
	<tr>
		<td colspan="3"></td>
		<td>
			<label for="workflowItem61">
				<?php echo $this->translate($this->workflowItems[61]->getName()); ?>
			</label><br>
			<input
				id="workflowItem61"
				name="workflowItem[61]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[61], $this->instanceId)); ?>"
			>
		</td>
	</tr>
</table>
<script>var dateFormat = '<?php echo $this->dateFormat; ?>'</script>
<script src="<?php echo $this->baseUrl('node_modules/handlebars/dist/handlebars.min.js') ?>"></script>
<script id="new-stage" type="text/x-handlebars-template">
	<tr><td colspan="4" class="stageDivide"><hr></td></tr>
		<tr>
		<td>
			<label for="workflowItem55-{{group_id}}">
				<?php echo $this->translate($this->workflowItems[55]->getName()); ?>
			</label><br>
			<input
				id="workflowItem55-{{group_id}}"
				name="workflowItem[55][{{group_id}}]"
				type="text"
				class="date_start"
				readonly
			>
		</td>
		<td>
			<label for="workflowItem56-{{group_id}}">
				<?php echo $this->translate($this->workflowItems[56]->getName()); ?>
			</label><br>
			<input
				id="workflowItem56-{{group_id}}"
				name="workflowItem[56][{{group_id}}]"
				type="text"
				class="date_start withDisable"
				readonly
			>
			<div class="disableBoxInline">
				<label for="item56disable-{{group_id}}"><?php echo $this->translate('Feld deaktivieren'); ?></label>
				<input
					id="item56disable-{{group_id}}"
					name="disabledItems[56][{{group_id}}]"
					type="checkbox"
					data-disable-query="input#workflowItem56-{{group_id}}"
				>
			</div>
		</td>
		<td>
			<label for="workflowItem58-{{group_id}}">
				<?php echo $this->translate($this->workflowItems[58]->getName()); ?>
			</label><br>
			<input
				id="workflowItem58-{{group_id}}"
				name="workflowItem[58][{{group_id}}]"
				type="text"
				class="date_start withDisable"
				readonly
			>
			<div class="disableBoxInline">
				<label for="item58disable-{{group_id}}"><?php echo $this->translate('Feld deaktivieren'); ?></label>
				<input
					id="item58disable-{{group_id}}"
					name="disabledItems[58][{{group_id}}]"
					type="checkbox"
					data-disable-query="input#workflowItem58-{{group_id}}"
				>
			</div>
		</td>
		<td>
			<label for="workflowItem67-{{group_id}}">
				<?php echo $this->translate($this->workflowItems[67]->getName()); ?>
			</label><br>
			<input
				id="workflowItem67-{{group_id}}"
				name="workflowItem[67][{{group_id}}]"
				type="text"
				class="date_start"
				readonly
			>
		</td>
	</tr>
	<tr>
		<td>
			<label for="workflowItem59-{{group_id}}">
				<?php echo $this->translate($this->workflowItems[59]->getName()); ?>
			</label><br>
			<input
				id="workflowItem59-{{group_id}}"
				name="workflowItem[59][{{group_id}}]"
				type="text"
				class="date_start"
				readonly
			>
		</td>
		<td colspan="3">
			<div><?php echo $this->translate('Bemerkungen'); ?></div>
			<textarea
				name="comment[<?php echo $this->sections[2]->baSectionId;  ?>][{{group_id}}]"
			></textarea>
		</td>
	</tr>
</script>
