<h3>1 <?php echo $this->sections[0]->name; ?></h3>
<table class="buildingAuthority section1">
	<tr>
		<td>
			<label for="workflowItem10">
				<?php echo $this->translate($this->workflowItems[10]->getName()); ?>
			</label><br>
			<input
				id="workflowItem10"
				name="workflowItem[10]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[10], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<?php echo $this->translate($this->workflowItems[12]->getName()); ?>
			<div class="noInputDate">
				<?php echo $this->date($this->getItemDate(
					$this->workflowItems[12], $this->instanceId)); ?>
			</div>
		</td>
		<td>
			<label for="workflowItem13">
				<?php echo $this->translate($this->workflowItems[13]->getName()); ?>
			</label><br>
			<input
				id="workflowItem13"
				name="workflowItem[13]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[13], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<label for="workflowItem14">
				<?php echo $this->translate($this->workflowItems[14]->getName()); ?>
			</label><br>
			<input
				id="workflowItem14"
				name="workflowItem[14]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[14], $this->instanceId)); ?>"
			>
		</td>
	</tr>
	<tr>
		<td>
			<label for="workflowItem1">
				<?php echo $this->translate($this->workflowItems[1]->getName()); ?>
			</label><br>
			<input
				id="workflowItem1"
				name="workflowItem[1]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[1], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<?php echo $this->translate($this->workflowItems[15]->getName()); ?>
			<div class="noInputDate">
				<?php echo $this->date($this->getItemDate(
					$this->workflowItems[15], $this->instanceId)); ?>
			</div>
		</td>
		<td>
			<?php echo $this->translate($this->workflowItems[65]->getName()); ?>
			<div class="noInputDate">
				<?php echo $this->date($this->getItemDate(
					$this->workflowItems[65], $this->instanceId)); ?>
			</div>
		</td>
		<td>
			<label for="workflowItem21">
				<?php echo $this->translate($this->workflowItems[21]->getName()); ?>
			</label><br>
			<input
				id="workflowItem21"
				name="workflowItem[21]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[21], $this->instanceId)); ?>"
			>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->translate($this->workflowItems[16]->getName()); ?>
			<div class="noInputDate">
				<?php echo $this->date($this->getItemDate(
					$this->workflowItems[16], $this->instanceId)); ?>
			</div>
		</td>
		<td>
			<?php echo $this->translate($this->workflowItems[46]->getName()); ?>
			<div class="noInputDate">
				<?php echo $this->date($this->getItemDate(
					$this->workflowItems[46], $this->instanceId)); ?>
			</div>
		</td>
		<td colspan="2"></td>
	</tr>
	<tr>
		<td>
			<label for="workflowItem47">
				<?php echo $this->translate($this->workflowItems[47]->getName()); ?>
			</label><br>
			<input
				id="workflowItem47"
				name="workflowItem[47]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[47], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<label for="workflowItem72">
				<?php echo $this->translate($this->workflowItems[72]->getName()); ?>
			</label><br>
			<input
				id="workflowItem72"
				name="workflowItem[72]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[72], $this->instanceId)); ?>"
			>
		</td>
		<td>
			<?php echo $this->translate($this->workflowItems[71]->getName()); ?>
			<div class="noInputDate">
				<?php echo $this->date($this->getItemDate(
					$this->workflowItems[71], $this->instanceId)); ?>
			</div>
		</td>
		<td>
			<label for="workflowItem73">
				<?php echo $this->translate($this->workflowItems[73]->getName()); ?>
			</label><br>
			<input
				id="workflowItem73"
				name="workflowItem[73]"
				type="text"
				class="date"
				value="<?php echo $this->date($this->getItemDate(
					$this->workflowItems[73], $this->instanceId)); ?>"
			>
		</td>
	</tr>
	<tr>
		<td colspan="4">
			<label for="comment1"><?php echo $this->translate('Bemerkungen'); ?></label><br>
			<textarea
				id="comment1"
				name="comment[<?php echo $this->sections[0]->baSectionId;  ?>]"
			><?php
				if (isset($this->comments[$this->sections[0]->baSectionId])) {
					echo $this->comments[$this->sections[0]->baSectionId][1]->text;
				}
			?></textarea>
		</td>
	</tr>
</table>
