# Generated by Django 3.2.19 on 2023-12-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_service_relationships'),
        ('instance', '0039_instance_rejection_feedback'),
        ('tags', '0002_auto_20200427_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instances', models.ManyToManyField(related_name='keywords', to='instance.Instance')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.service')),
            ],
            options={
                'managed': True,
                'unique_together': {('name', 'service')},
            },
        ),
    ]
