# Generated by Django 5.2.11 on 2026-02-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0043_alter_historyentry_user'),
        ('tags', '0003_keyword'),
        ('user', '0039_role_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instances', models.ManyToManyField(blank=True, related_name='static_keywords', to='instance.instance')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.service')),
            ],
            options={
                'managed': True,
                'unique_together': {('name', 'service')},
            },
        ),
    ]
