# Generated by Django 5.2.11 on 2026-04-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_statickeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='statickeyword',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
