# Generated by Django 5.2.11 on 2026-05-04 14:00

import camac.tags.models
import django.core.validators
import localized_fields.fields.text_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_statickeyword_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', localized_fields.fields.text_field.LocalizedTextField(max_length=50, required=['de'])),
                ('icon', models.CharField(max_length=50)),
                ('background_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #RRGGBB)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('text_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #RRGGBB)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('sort', models.PositiveIntegerField(default=camac.tags.models.next_instance_mark_sort)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
