# Generated by Django 4.2.20 on 2025-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CMIObjectTemplate",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                (
                    "use_for",
                    models.CharField(
                        choices=[
                            ("Geschaeft", "Geschaeft"),
                            ("Aufgabe", "Aufgabe"),
                            ("Beteiligung", "Beteiligung"),
                        ],
                        max_length=100,
                    ),
                ),
                ("template_path", models.CharField(max_length=250)),
            ],
        ),
    ]
