# Generated by Django 4.2.20 on 2025-05-07 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gever", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cmiobjecttemplate",
            options={"ordering": ("use_for", "slug")},
        ),
    ]
