# Generated by Django 4.2.20 on 2025-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gever", "0002_add_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMIConstantValue",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                (
                    "use_for",
                    models.CharField(
                        choices=[
                            ("Verfahrensstand", "Verfahrensstand"),
                            ("Herkunft", "Herkunft"),
                        ],
                        max_length=100,
                    ),
                ),
                ("label", models.CharField(max_length=250)),
            ],
            options={
                "ordering": ("use_for", "slug"),
            },
        ),
    ]
