<form action="<?php echo $this->url(array('action'=>'save')) ?>" method="post">
	<?php if ($this->publicationEntry->publicationEntryID !== null){echo sprintf('<input name="publicationID" type="hidden" value="%d">', $this->publicationEntry->publicationEntryID);} ?>
	<div class="element">
		<div class="column-1">Bauherrschaft:</div>
		<div class="column-2"><?php echo $this->info['organisation'] ?> <br /><?php echo $this->info['person'] ?></div>
	</div>
	<div class="element">
		<div class="column-1">Bauvorhaben:</div>
		<div class="column-2"><?php echo implode(', ', $this->info['intent']) ?></div>
	</div>
	<div class="element">
		<div class="column-1">Bauplatz:</div>
		<div class="column-2"><?php if ($this->info['place']['street'] && $this->info['place']['parcelNr']) {echo sprintf('%s, Parzelle Nr. %d', $this->info['place']['street'], $this->info['place']['parcelNr']);}?></div>
	</div>
	<div class="element">
		<div class="column-1">Bemerkungen: (zutreffendes ankreuzen)</div>
		<div class="column-2">
			<input id="note1" type="radio" name="note" value="1"<?php if ((int)$this->publicationEntry->note === 1 || $this->publicationEntry->note === null){echo ' checked="checked"';} ?>><label for="note1"> Profilierung auf Verlangen</label><br>
			<input id="note2" type="radio" name="note" value="2"<?php if ((int)$this->publicationEntry->note === 2){echo ' checked="checked"';} ?>><label for="note2"> Profiliert</label><br>
			<input id="note3" type="radio" name="note" value="3"<?php if ((int)$this->publicationEntry->note === 3){echo ' checked="checked"';} ?>><label for="note3"> Verpflockt</label>
		</div>
	</div>
	<div class="element">
		<div class="column-1"><label for="publishDate">Publikationsbeginn (Freitag):</label></div>
		<div class="column-2"><input id="publishDate" class="date" type="text" name="publishDate" value="<?php if ($this->publicationEntry->publicationDate !== null){echo $this->publicationEntry->publicationDate->format('d.m.y');} ?>"></div>
	</div>
	<div class="element">
		<div class="column-1"><label for="publishDate">Dauer:</label></div>
		<div class="column-2"><?php echo $this->info['duration']->value ?></div>
	</div>
	<?php if ($this->showWarning) : ?>
		<p><strong>Achtung! Sie haben noch keine Dokumente im Publikationsordner abgelegt.</strong></p>
	<?php endif; ?>
	<div class="element">
		<input name="save" type="submit" class="button" value="Speichern">
		<input name="preview" type="submit" class="button" value="Vorschau / Publizieren">
	</div>
	<div class="clear"></div>
</form>
