<form action="<?php echo $this->url(array('action'=>'publish')) ?>" method="post">
	<div>
		<?php if (!$this->publicationEntry->isPublished) {
			echo '<b>Voransicht</b><br>';
			echo 'Der Text kann vor der Publikation noch bearbeitet werden:';
		}
		else {
			echo sprintf('Publiziert am <strong>%s</strong> mit folgender Nachricht:', $this->publicationEntry->publicationDate->format('d.m.Y'));
		} ?>
	</div>
	<?php if (!$this->publicationEntry->isPublished) { ?>
	<textarea name="publicationText" style="width:100%; height:400px;"><?php echo $this->publicationText ?></textarea>
	<?php } else {
	echo '<p>' . nl2br($this->publicationEntry->text) . '</p>';
	} ?>
	<div class="actions">
		<input name="button_293" type="submit" class="button downloady" value="Drucken">
		<?php if (!$this->publicationEntry->isPublished) { ?>
		<input name="publish" type="submit" class="button" value="Publizieren">
		<input name="cancel" type="submit" class="button" value="Abbrechen">
		<?php } ?>
	</div>
</form>