# Generated by Django 4.2.20 on 2025-03-31 03:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.field
import simple_history.models
import uuid
import uuid_extensions.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caluma_workflow', '0035_uuid_v7'),
        ('caluma_form', '0049_uuid_v7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caluma_workflow.workitem',),
        ),
        migrations.CreateModel(
            name='HistoricalInquiry',
            fields=[
                ('history_user_id', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('created_by_user', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('created_by_group', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('modified_by_user', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('modified_by_group', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid_extensions.uuid7, editable=False)),
                ('name', localized_fields.fields.field.LocalizedField(help_text='Will be set from Task, if not provided.', required=[])),
                ('description', localized_fields.fields.field.LocalizedField(blank=True, help_text='Will be set from Task, if not provided.', null=True, required=[])),
                ('closed_at', models.DateTimeField(blank=True, help_text='Time when work item has either been canceled or completed', null=True)),
                ('closed_by_user', models.CharField(blank=True, max_length=150, null=True)),
                ('closed_by_group', models.CharField(blank=True, max_length=150, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ready', 'Work item is ready to be processed.'), ('completed', 'Work item is done.'), ('canceled', 'Work item is canceled.'), ('skipped', 'Work item is skipped.'), ('suspended', 'Work item is suspended.'), ('redo', 'Work item has been marked for redo.')], db_index=True, max_length=50)),
                ('meta', models.JSONField(default=dict)),
                ('addressed_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, help_text='Offer work item to be processed by a group of users, such are not committed to process it though.', size=None)),
                ('controlling_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, help_text='List of groups this work item is assigned to for controlling.', size=None)),
                ('assigned_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, help_text='Users responsible to undertake given work item.', size=None)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caluma_workflow.case')),
                ('child_case', models.ForeignKey(blank=True, db_constraint=False, help_text='Defines case of a sub-workflow', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caluma_workflow.case')),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caluma_form.document')),
                ('previous_work_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caluma_workflow.workitem')),
                ('task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caluma_workflow.task')),
            ],
            options={
                'verbose_name': 'historical inquiry',
                'verbose_name_plural': 'historical inquirys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
