# Generated by Django 4.2.20 on 2025-04-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caluma_workflow', '0035_uuid_v7'),
        ('caluma', '0001_inquiry_proxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalInquiry',
        ),
        migrations.CreateModel(
            name='HistoricalInquiry',
            fields=[
            ],
            options={
                'verbose_name': 'historical inquiry',
                'verbose_name_plural': 'historical inquirys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caluma_workflow.historicalworkitem',),
        ),
    ]
