# Generated by Django 4.2.20 on 2025-07-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instance', '0041_instance_copy_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGGISExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('hash', models.CharField()),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='instance.instance')),
                ('coordinate_x', models.FloatField(blank=True, null=True)),
                ('coordinate_y', models.FloatField(blank=True, null=True)),
                ('dossier_number', models.CharField(blank=True, null=True)),
                ('responsible_user', models.CharField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, null=True)),
                ('url', models.CharField()),
                ('municipality', models.CharField(blank=True, null=True)),
                ('plot_number', models.CharField(blank=True, null=True)),
                ('status', models.CharField()),
                ('applicant', models.CharField(blank=True, null=True)),
                ('submit_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceProxyAG',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('instance.instance', models.Model),
        ),
    ]
