<div class="table-container column column-100 main-content">
	<div class="title">
		<ul>
			<li class="type">
				<span class="icon icon-plus"  aria-hidden="true"></span>
			</li>
			<li class="active">
				<a href="javascript:void(0)">
					<span class="icon icon-stackoverflow"  aria-hidden="true"></span>
					<?php echo $this->translate('Attachmentextension') ?>
				</a>
			</li>
		</ul>
	</div>
	<?php echo $this->form ?>
</div>
