ARE_SERVICE_GROUP = "authority-bab"
CANTON_SERVICE_GROUP = "service"
MUNICIPALITY_SERVICE_GROUP = "municipality"

# ALEXANDRIA_MAPPING = {ARE_SERVICE_GROUP: "are", CANTON_SERVICE_GROUP: "canton"}
ALEXANDRIA_MAPPING = {ARE_SERVICE_GROUP: "are"}

# Instance states
INSTANCE_STATE_NEW = 1
INSTANCE_STATE_SUBM = 120004
INSTANCE_STATE_CIRCULATION = 120005
INSTANCE_STATE_FINISHED = 120006
INSTANCE_STATE_DECISION = 120007
INSTANCE_STATE_CORRECTION = 120008
INSTANCE_STATE_INIT_DISTRIBUTION = 120009

# Public instance states
PUBLIC_INSTANCE_STATE_CREATING = "creation"
PUBLIC_INSTANCE_STATE_RECEIVING = "receiving"
PUBLIC_INSTANCE_STATE_IN_PROGRESS = "in-progress"
PUBLIC_INSTANCE_STATE_FINISHED = "finished"
PUBLIC_INSTANCE_STATE_REJECTED = "rejected"
