ARE_SERVICE_GROUP = "authority-bab"
CANTON_SERVICE_GROUP = "service"
MUNICIPALITY_SERVICE_GROUP = "municipality"

# ALEXANDRIA_MAPPING = {ARE_SERVICE_GROUP: "are", CANTON_SERVICE_GROUP: "canton"}
ALEXANDRIA_MAPPING = {ARE_SERVICE_GROUP: "are"}
