KOOR_BG_SERVICE_ID = 1
KOOR_NP_SERVICE_ID = 87
KOOR_BD_SERVICE_ID = 302

CIRCULATION_STATE_RUN = 1
CIRCULATION_STATE_OK = 2
CIRCULATION_STATE_IDLE = 21
CIRCULATION_STATE_NFD = 41

ROLE_MUNICIPALITY = 6  # Sekretariat der Gemeindebaubehörde

INSTANCE_STATE_COMM = 21
INSTANCE_STATE_EXT = 22
INSTANCE_STATE_EXT_GEM = 32
INSTANCE_STATE_CIRC = 23
INSTANCE_STATE_REDAC = 24
INSTANCE_STATE_DONE = 25
INSTANCE_STATE_ARCH = 26
INSTANCE_STATE_DEL = 27
INSTANCE_STATE_NEW = 1
INSTANCE_STATE_NEW_PORTAL = 28
INSTANCE_STATE_CONTROL = 34

# TODO theoretically, we'd like to hide COMM as well, but instances can be sent
# "back" into "COMM" if the canton didn't do a circulation
INSTANCE_STATES_HIDDEN_FOR_KOOR = [INSTANCE_STATE_NEW, INSTANCE_STATE_NEW_PORTAL]

# Question identifiers (Chapter/Question/Item) for various information that we need
# Format: List of 3-tuples to implement fallback
CQI_FOR_PROPOSAL = [(21, 97, 1)]
CQI_FOR_PROPOSAL_DESCRIPTION = [(21, 98, 1)]
CQI_FOR_PARZELLE = [(21, 91, 1), (101, 91, 1), (102, 91, 1)]
CQI_FOR_STREET = [(21, 93, 1), (101, 93, 1), (102, 93, 1)]
CQI_FOR_APPLICANT_NAME = [(1, 23, 1)]
CQI_FOR_APPLICANT_ORGANISATION = [(1, 221, 1)]
CQI_FOR_APPLICANT_STREET = [(1, 61, 1)]
CQI_FOR_APPLICANT_ZIP_CITY = [(1, 62, 1)]
CQI_FOR_NFD_COMPLETION_DATE = (41, 243, 1)


NOTIFICATION_TEMPLATE_DEADLINE_DATE_FACHSTELLE = (
    "aktivierung-deadline-überzogen-fachstelle"  # 1448
)
NOTIFICATION_TEMPLATE_COMPLETION_DATE_FACHSTELLE = (
    "aktivierung-nfd-vollständig-überzogen-fachstelle"  # 1449
)
NOTIFICATION_TEMPLATE_DEADLINE_DATE_LEITBEHOERDE = (
    "aktivierung-deadline-überzogen-leitbehoerde"  # 1450
)
NOTIFICATION_TEMPLATE_COMPLETION_DATE_LEITBEHOERDE = (
    "aktivierung-nfd-vollständig-überzogen-leitbehoerde"  # 1451
)
CQI_FOR_GESUCHSTELLER = [(1, 23, 1)]

FORM_BAUGESUCH_MIT_KANTON = 44
FORM_BAUGESUCH_OHNE_KANTON = 47
FORM_VORABKLAERUNG_MIT_KANTON = 21
FORM_VORABKLAERUNG_OHNE_KANTON = 61
FORM_REKLAME = 121
FORM_MELDUNG_SOLARANLAGE = 141
FORM_MELDUNG_VORHABEN = 290

FORM_PGV_EISENBAHNGESETZ = 244
FORM_PGV_SEILBAHNGESETZ = 250
FORM_MITBERICHT_BUNDESSTELLE = 292

PORTAL_FORMS = [
    FORM_BAUGESUCH_MIT_KANTON,
    FORM_BAUGESUCH_OHNE_KANTON,
    FORM_VORABKLAERUNG_MIT_KANTON,
    FORM_VORABKLAERUNG_OHNE_KANTON,
    FORM_REKLAME,
    FORM_MELDUNG_SOLARANLAGE,
    FORM_MELDUNG_VORHABEN,
]

RESPONSIBLE_KOORS = {
    KOOR_BD_SERVICE_ID: [FORM_PGV_EISENBAHNGESETZ],
    KOOR_BG_SERVICE_ID: [FORM_PGV_SEILBAHNGESETZ, FORM_MITBERICHT_BUNDESSTELLE],
}
