# Generated by Django 4.2.19 on 2025-03-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0008_billingv2entry_product_number_and_more'),
        ('instance', '0039_instance_rejection_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField()),
                ('clerk', models.CharField()),
                ('user_id', models.CharField()),
                ('invoice_text', models.CharField()),
                ('payment_purpose', models.CharField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_completed', models.DateField(null=True)),
                ('date_sent', models.DateField(null=True)),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='instance.instance')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('designation', models.CharField()),
                ('product_number', models.CharField()),
                ('created_on', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_v2_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.billingv2entry')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
            ],
        ),
    ]
