<script src="<?php echo $this->baseUrl(); ?>/public/js/overlay.js"></script>
<div>
	<p>
		Damit Ihr Dossier (Baugesuch, Baugesuch - Vorabklärung, Reklamegesuch oder Meldung
		Solaranlage) ohne Verzögerung behandelt werden kann, ist es wichtig dass das
		Dossier möglichst vollständig eingereicht wird. <br>
		Im Merkblatt "Baugesuche einreichen" zeigen wir Ihnen auf, welche Unterlagen und Angaben für die
		Behandlung der unterschiedlichen Dossiers notwendig sind. Bei Fragen rund um
		die Eingabe von Dossiers ist Ihnen die zuständige Gemeindebaubehörde gerne
		behilflich (die Kontaktdaten finden Sie im Formular A).
	</p>
	<ul class="portalPdfLinks">
		<li class="clearfix">
			<span>Formular A (bitte downloaden, ausfüllen und unter <br />der Auswahl Formular A wieder hochladen)</span>
			<a href="<?php echo $this->partial('/portal/download_link.phtml') ?>" target="_blank">
				<img src="<?php echo $this->baseUrl('/public/images/uri/pdf.svg') ?>">
			</a>
		</li>
		<li class="clearfix">
			<span>Gemeindebauordnung</span>
			<a href="<?php echo $this->partial('/portal/download_gbo_link.phtml') ?>" target="_blank">
				<img src="<?php echo $this->baseUrl('/public/images/uri/pdf.svg') ?>">
			</a>
		</li>
		<li class="clearfix">
			<span>Merkblatt "Baugesuche einreichen"</span>
			<a href="<?php echo $this->baseUrl('/public/pdf/form_a/Baugesuche_Merkblatt_Version_1.0_Neu.pdf') ?>" target="_blank">
				<img src="<?php echo $this->baseUrl('/public/images/uri/pdf.svg') ?>">
			</a>
		</li>
		<li class="clearfix">
			<span>Merkblatt "Farbgebung in Ortsbildern und in der Landschaft"</span>
			<a href="http://www.ur.ch/dl.php/de/591bfbfaa8fca/Farbgebung_Merkblatt_ARE_20170512.pdf" target="_blank">
				<img src="<?php echo $this->baseUrl('/public/images/uri/pdf.svg') ?>">
			</a>
		</li>
		<li class="clearfix">
			<span>BaB Merkblatt</span>
			<a href="<?php echo $this->baseUrl('/public/pdf/form_a/BaB_Merkblatt_Version_11.pdf') ?>" target="_blank">
				<img src="<?php echo $this->baseUrl('/public/images/uri/pdf.svg') ?>">
			</a>
		</li>
		<li class="clearfix">
			<span>Planungs- und Baugesetz (PBG)</span>
			<a href="<?php echo $this->baseUrl('/public/pdf/form_a/PBG_Planung_Baugesetz.pdf') ?>" target="_blank">
				<img src="<?php echo $this->baseUrl('/public/images/uri/pdf.svg') ?>">
			</a>
		</li>
		<li class="clearfix">
			<span>Reglement zum Planungs- und Baugesetz (RPBG)</span>
			<a href="<?php echo $this->baseUrl('/public/pdf/form_a/RPBG_Reglement_Planung_Baugesetz.pdf') ?>" target="_blank">
				<img src="<?php echo $this->baseUrl('/public/images/uri/pdf.svg') ?>">
			</a>
		</li>
	</ul>
</div>

<?php if (count($this->messages) > 0) { ?>
<?php foreach($this->messages as $message) { ?>
	<div class="alert error"><p><?php echo $message; ?></p></div>
<?php }} ?>

<form method="post" enctype="multipart/form-data" class="portalupload">
<?php echo $this->form->getCsrf(); ?>

	<h3>Dokumente</h3>

	<div>
		<p>Bitte laden Sie die nötigen Dokumente hoch und wählen Sie dazu jeweils die
		entsprechende Dokumentbezeichnung aus (Auswahl links).<br>
		Bei allen Dossiers sind zwingend mindestens das Formular A (digital oder schriftlich unterzeichnet),
		ein Situationsplan (Auszug Katasterplan) sowie die notwendigen Plandokumente
		notwendig. Falls möglich und zweckmässig bitte auch Fotos hochladen.</p>
		<p><strong>Bitte beachten!</strong><br>
		Aus rechtlichen Gründen (öffentliche Bauplanauflage und Visierung der bewilligten Pläne) müssen,
		nebst der digitalen Eingabe, zwei physische Dossiers (Planunterlagen) bei der zuständigen Gemeinde
		eingereicht werden.<br>
		Die hier hochgeladenen Dokumente sind Bestandteil der öffentlichen Bauplanauflage und können auch
		<a href="/core/simplelist/index/resource-id/293" target="_blank">online eingesehen werden</a>.</p>
	</div>

	<div style="margin-top: 15px;">

		<input name="file" type="file" />

		<input type="checkbox" id="signature" name="signature" value="1">
        <label for="signature"><?php echo $this->translate('Digitale Signatur '); ?></label>
		<input type="checkbox" id="isConfidential" name="isConfidential" value="1">
        <label for="isConfidential"><?php echo $this->translate('Vertraulich'); ?></label>
        <p>(PDF, JPG, PNG oder GIF; max. <?= $this->maxFileSize ?>. Bitte aktivieren Sie bei digital signiertem Dokument das dafür vorgesehene Feld)</p>
	</div>

	<input type="submit" value="Hochladen" name="upload">
</form>

<table class="portaldocuments">
	<thead>
		<tr>
			<th><?php echo $this->translate('Datei'); ?></th>
			<th><?php echo $this->translate('Grösse'); ?></th>
			<th><?php echo $this->translate('Datum'); ?></th>
			<th class="center"><?php echo $this->translate('Digitale Signatur'); ?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->attachments as $attachment) { ?>
		<tr>
			<td><?php echo $this->makeLink($attachment); ?>
				<?php if ($attachment->isConfidential) : ?>
					<span class="confidential-marker">vertraulich</span>
				<?php endif ?>
			</td>
			<td><?php echo $this->humanReadable($attachment->size); ?></td>
			<td><?php echo $this->date($attachment->date); ?></td>
			<td class="center">
				<i title="<?php echo $attachment->digitalSignature ? "Digital signiert" : "Nicht signiert" ?>"
					 class="fa fa-<?php echo $attachment->digitalSignature ? "lock" : "unlock"; ?>"></i>
			</td>
			<td>
				<?php if ($this->canDelete) { ?>
				<a class="delete" href="<?php echo $this->url(array('action'=>'delete', 'attachmentid' => $attachment->identifier))?>">löschen</a>
				<?php } ?>
			</td>
		</tr>
	<?php } ?>
<?php if (count($this->attachments) == 0): ?>
	<tr>
		<td colspan="4"><?php echo $this->translate('Keine Dokumente gefunden'); ?></td>
	</tr>
<?php endif ?>
	</tbody>
</table>

<form action="<?php echo $this->baseUrl('/documents/portal/navigate/instance-resource-id/678/instance-id/' . $this->instanceId) ?>" method="post">
	<input type="submit" value="Zurück" name="previous">
	<input type="submit" value="Weiter" name="next">
</form>
