
<div class="table-container column column-100%">
	<div class="title">
		<ul>
			<li class="type">
				<span class="icon icon-info"  aria-hidden="true"></span>
			</li>
			<li class="active">
				<a href="javascript:void(0)">
					<span class="icon icon-puzzle"  aria-hidden="true"></span>
					<?php echo $this->translate("Attachment Section Role Privileges") ?>
				</a>
			</li>
			<li class="help">
				<a href="javascript:void(0)">
					<span class="icon icon-question"  aria-hidden="true"></span>
				</a>
				<div class="tooltip">
					<p>
						<?php echo $this->translate('The actions are availables through a context menu. Right click to trigger the context menu.') ?><br/>
					</p>
				</div>
			</li>
		</ul>
	</div>
	<table class="datatables context-menu attachmentsectionrole" data-menu="attachmentsectionrole" data-display-length="25" data-disable-sorting="1">
		<thead>
			<tr>
				<th class="no-sort">
					<?php echo $this->translate('Role') ?>
				</th>
				<th class="no-sort">
					<?php echo $this->translate('Attachment Section') ?>
				</th>
				<th>
					<?php echo $this->translate('Mode') ?>
				</th>
			</tr>
		</thead>
		<tbody>
			<?php if (count($this->rows)): ?>
				<?php foreach ($this->rows as $row) : ?>
					<tr data-id="<?php echo $row->id ?>">
						<td>
							<?php echo $this->getRole($row->roleID) ?>
						</td>
						<td>
							<?php echo $this->getAttachmentSection($row->attachmentSectionID) ?>
						</td>
						<td>
							<?php echo $row->mode ?>
						</td>
					</tr>
				<?php endforeach ?>
			<?php else : ?>
				<tr class="alert information">
					<td class="empty">
						<span aria-hidden="true" class="icon-info"></span>
						<?php echo $this->translate('No attachment section role privileges found.') ?>
					</td>
					<td class="empty"></td>
					<td class="empty"></td>
				</tr>
			<?php endif ?>
		</tbody>
	</table>
</div>

<ul class="attachmentsectionrole-menu context-menu">
	<li>
		<span><?php echo $this->translate('Attachment section roles') ?></span>
	</li>
	<li class="edit-only">
		<a href="<?php echo $this->url(array(
				'controller' => 'module_data-loader',
				'action'     => 'edit',
				'module-id'  => 'documents',
				'data-id'    => 'attachmentsectionrole',
				'id'         => '%id'
			));?>">
			<span class="icon-pencil"></span>
			<?php echo $this->translate('Edit') ?>
		</a>
	</li>
	<li class="edit-only" data-confirm-dialog="true"
		data-title="<?php echo $this->translate('attachment section') ?>"
		data-confirm-message="<?php echo $this->translate('Are you sure you want to delete this setting?') ?>">
	<a href="<?php echo $this->url(array(
				"controller" => 'module_data-loader',
				"action"     => "delete",
				"module-id"  => "documents",
				"data-id"    => "attachmentsectionrole",
				"id"         => '%id'
			))?>">
			<span class="icon-remove"></span>
			<?php echo $this->translate('Delete') ?>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array(
				'controller' => 'module_data-loader',
				'action'     => 'add',
				'module-id'  => 'documents',
				'data-id'    => 'attachmentsectionrole')) ?>">
			<span class="icon-plus"></span>
			<?php echo $this->translate('Add') ?>
		</a>
	</li>
</ul>
