# Generated by Django 4.2.20 on 2025-04-15 12:36

from django.db import migrations, models
import uuid_extensions.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0028_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lead_time', models.PositiveIntegerField(blank=True, help_text='The current date in addition to this value will determine the deadline', null=True, verbose_name='Lead time in days')),
                ('addressed_to_current_service', models.BooleanField(default=False, verbose_name='Automatically addressed to current service')),
                ('assigned_to_current_user', models.BooleanField(default=False, help_text='This can only be enabled if "Automatically addressed to current service" is enabled as well', verbose_name='Automatically assigned to current user')),
                ('service_groups', models.ManyToManyField(blank=True, to='user.servicegroup', verbose_name='Service groups')),
                ('services', models.ManyToManyField(blank=True, to='user.service', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Work item template',
                'verbose_name_plural': 'Work item templates',
            },
        ),
        migrations.AddConstraint(
            model_name='workitemtemplate',
            constraint=models.CheckConstraint(check=models.Q(('assigned_to_current_user', False), models.Q(('addressed_to_current_service', True), ('assigned_to_current_user', True)), _connector='OR'), name='current_user_requires_current_service'),
        ),
    ]
