# Generated by Django 4.2.20 on 2025-04-28 12:47

import camac.work_items.models
from django.db import migrations, models

def set_sort(apps, schema_editor):
    WorkItemTemplate = apps.get_model("work_items", "WorkItemTemplate")

    for i, tpl in enumerate(WorkItemTemplate.objects.order_by("name")):
        tpl.sort = i
        tpl.save()

def unset_sort(apps, schema_editor):
    WorkItemTemplate = apps.get_model("work_items", "WorkItemTemplate")

    WorkItemTemplate.objects.update(sort=0)

class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitemtemplate',
            options={'ordering': ['sort'], 'verbose_name': 'Work item template', 'verbose_name_plural': 'Work item templates'},
        ),
        migrations.AddField(
            model_name='workitemtemplate',
            name='sort',
            field=models.PositiveIntegerField(default=camac.work_items.models.next_sort),
        ),
        migrations.RunPython(set_sort, unset_sort)
    ]
