# Generated by Django 4.2.20 on 2025-06-02 10:26

from django.db import migrations, models

def migrate_responsibility_rule(apps, schema_editor):
    WorkItemTemplate = apps.get_model("work_items", "WorkItemTemplate")

    for tpl in WorkItemTemplate.objects.all():
        if not tpl.addressed_to_current_service:
            tpl.responsibility_rule = "NONE"
        elif tpl.assigned_to_current_user:
            tpl.responsibility_rule = "CURRENT_USER"
        else:
            tpl.responsibility_rule = "RESPONSIBLE_USER"

        tpl.save()


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0002_workitemtemplate_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemtemplate',
            name='responsibility_rule',
            field=models.CharField(blank=True, choices=[('NONE', 'No service'), ('RESPONSIBLE_USER', 'Current service and responsible user (if exists)'), ('CURRENT_USER', 'Current service and current user'), ('NO_USER', 'Current service and no user')], max_length=20, null=True, verbose_name='Responsibility rule'),
        ),
        migrations.RunPython(migrate_responsibility_rule, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='workitemtemplate',
            name='current_user_requires_current_service',
        ),
        migrations.RemoveField(
            model_name='workitemtemplate',
            name='addressed_to_current_service',
        ),
        migrations.RemoveField(
            model_name='workitemtemplate',
            name='assigned_to_current_user',
        ),
        migrations.AlterField(
            model_name='workitemtemplate',
            name='responsibility_rule',
            field=models.CharField(choices=[('NONE', 'No service'), ('RESPONSIBLE_USER', 'Current service and responsible user (if exists)'), ('CURRENT_USER', 'Current service and current user'), ('NO_USER', 'Current service and no user')], max_length=20, verbose_name='Responsibility rule'),
        ),
    ]
