# Generated by Django 4.2.20 on 2025-05-23 13:50

from django.db import migrations, models
import localized_fields.fields.char_field
import uuid_extensions.uuid7


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_and_service_new_attributes'),
        ('work_items', '0003_workitemtemplate_responsibility_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemListFilterPreset',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', localized_fields.fields.char_field.LocalizedCharField(required=['de'])),
                ('query_params', models.JSONField()),
                ('service_groups', models.ManyToManyField(blank=True, to='user.servicegroup', verbose_name='Service groups')),
                ('services', models.ManyToManyField(blank=True, to='user.service', verbose_name='Services')),
            ],
        ),
    ]
