# Generated by Django 4.2.20 on 2025-06-20 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_items', '0003_workitemtemplate_responsibility_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemtemplate',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='Der zuständige Benutzer wird nur beachtet, wenn die Zuständigkeitsregel "Eigene Organisation und bestimmter Benutzer" oberhalb ausgewählt wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned user'),
        ),
        migrations.AlterField(
            model_name='workitemtemplate',
            name='responsibility_rule',
            field=models.CharField(choices=[('NONE', 'No service'), ('RESPONSIBLE_USER', 'Current service and responsible user (if exists)'), ('CURRENT_USER', 'Current service and current user'), ('SPECIFIC_USER', 'Current service and specific user'), ('NO_USER', 'Current service and no user')], max_length=20, verbose_name='Responsibility rule'),
        ),
    ]
