# Generated by Django 4.2.20 on 2025-06-23 08:40

import django.contrib.postgres.fields
from django.db import migrations, models
import localized_fields.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0004_workitemlistfilterpreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitemlistfilterpreset',
            options={'verbose_name': 'Work item list filter preset', 'verbose_name_plural': 'Work item list filter presets'},
        ),
        migrations.AddField(
            model_name='workitemlistfilterpreset',
            name='prefilter_tasks',
            field=models.BooleanField(default=False, verbose_name='Prefilter tasks'),
        ),
        migrations.AddField(
            model_name='workitemlistfilterpreset',
            name='prefilter_work_item_templates',
            field=models.BooleanField(default=False, verbose_name='Prefilter work item templates'),
        ),
        migrations.AddField(
            model_name='workitemlistfilterpreset',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, size=None, verbose_name='Tasks'),
        ),
        migrations.AddField(
            model_name='workitemlistfilterpreset',
            name='work_item_templates',
            field=models.ManyToManyField(blank=True, related_name='filter_presets', to='work_items.workitemtemplate', verbose_name='Work item templates'),
        ),
        migrations.AlterField(
            model_name='workitemlistfilterpreset',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(required=['de'], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='workitemlistfilterpreset',
            name='query_params',
            field=models.JSONField(verbose_name='Query params'),
        ),
    ]
