# Generated by Django 4.2.20 on 2025-06-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0004_workitemtemplate_assigned_user'),
        ('work_items', '0005_alter_workitemlistfilterpreset_options_and_more'),
    ]

    operations = [
    ]
