# Generated by Django 4.2.20 on 2025-06-24 08:54

from django.conf import settings
import camac.work_items.models
from django.db import migrations, models
import functools


def migrate_tasks(apps, schema_editor):
    WorkItemListFilterPreset = apps.get_model("work_items", "WorkItemListFilterPreset")
    Task = apps.get_model("caluma_workflow", "Task")

    for preset in WorkItemListFilterPreset.objects.all():
        tasks = Task.objects.filter(pk__in=preset.tasks)
        preset.new_tasks.set(tasks)


def migrate_tasks_reverse(apps, schema_editor):
    WorkItemListFilterPreset = apps.get_model("work_items", "WorkItemListFilterPreset")

    for preset in WorkItemListFilterPreset.objects.all():
        tasks = preset.new_tasks.all().values_list("slug", flat=True)
        preset.tasks = list(tasks)
        preset.save()


def set_sort(apps, schema_editor):
    WorkItemListFilterPreset = apps.get_model("work_items", "WorkItemListFilterPreset")

    for i, tpl in enumerate(WorkItemListFilterPreset.objects.order_by("name")):
        tpl.sort = i
        tpl.save()


def unset_sort(apps, schema_editor):
    WorkItemListFilterPreset = apps.get_model("work_items", "WorkItemListFilterPreset")

    WorkItemListFilterPreset.objects.update(sort=0)


class Migration(migrations.Migration):

    dependencies = [
        ('caluma_workflow', '0035_uuid_v7'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_items', '0006_merge_20250626_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitemlistfilterpreset',
            options={'ordering': ['sort'], 'verbose_name': 'Work item list filter preset', 'verbose_name_plural': 'Work item list filter presets'},
        ),
        migrations.AddField(
            model_name='workitemlistfilterpreset',
            name='new_tasks',
            field=models.ManyToManyField(blank=True, related_name='+', to='caluma_workflow.task', verbose_name='Tasks'),
        ),
        migrations.AddField(
            model_name='workitemlistfilterpreset',
            name='sort',
            field=models.PositiveIntegerField(default=functools.partial(camac.work_items.models.next_sort, *('WorkItemListFilterPreset',), **{})),
        ),
        migrations.AlterField(
            model_name='workitemtemplate',
            name='sort',
            field=models.PositiveIntegerField(default=functools.partial(camac.work_items.models.next_sort, *('WorkItemTemplate',), **{})),
        ),
        migrations.RunPython(set_sort, unset_sort),
        migrations.RunPython(migrate_tasks, migrate_tasks_reverse),
        migrations.RemoveField(
            model_name='workitemlistfilterpreset',
            name='tasks',
        ),
        migrations.RenameField(
            model_name='workitemlistfilterpreset',
            old_name='new_tasks',
            new_name='tasks',
        ),
    ]
