# Generated by Django 4.2.20 on 2025-06-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_items', '0007_alter_workitemlistfilterpreset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitemtemplate',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='Der zuständige Benutzer wird nur beachtet, wenn die Zuständigkeitsregel "Eigene Organisation und bestimmter Benutzer" oberhalb ausgewählt wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned user'),
        ),
    ]
