# Generated by Django 4.2.20 on 2025-07-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caluma_workflow', '0035_uuid_v7'),
        ('work_items', '0008_alter_workitemtemplate_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkItemListRow',
            fields=[
            ],
            options={
                'verbose_name': 'historical work item list row',
                'verbose_name_plural': 'historical work item list rows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caluma_workflow.historicalworkitem',),
        ),
        migrations.CreateModel(
            name='WorkItemListRow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caluma_workflow.workitem',),
        ),
    ]
