# Generated by Django 4.2.20 on 2025-07-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0009_workitemlistrow'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX caluma_work_status_deadline_not_null
                ON caluma_workflow_workitem
                USING btree (status, deadline) WHERE (deadline IS NOT NULL);
                ANALYZE caluma_workflow_workitem;
            """,
            reverse_sql="""
                DROP INDEX caluma_work_status_deadline_not_null;
                ANALYZE caluma_workflow_workitem;
            """,
        ),
    ]
