# Generated by Django 5.2.8 on 2025-12-01 15:49

from django.db import migrations

def migrate(apps, schema_editor):
    WorkItem = apps.get_model("caluma_workflow", "WorkItem")

    for work_item in WorkItem.objects.filter(**{"meta__template-id": "NONE"}):
        del work_item.meta["template-id"]
        work_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0010_workitem_index'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
