# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(db_column='PURPOSE', max_length=100)),
                ('subject', models.TextField(db_column='SUBJECT')),
                ('body', models.TextField(db_column='BODY')),
            ],
            options={
                'db_table': 'NOTIFICATION_TEMPLATE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplateT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_column='LANGUAGE', max_length=2)),
                ('purpose', models.CharField(db_column='PURPOSE', max_length=100)),
                ('subject', models.TextField(db_column='SUBJECT')),
                ('body', models.TextField(db_column='BODY')),
                ('template', models.ForeignKey(db_column='TEMPLATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notification.NotificationTemplate')),
            ],
            options={
                'db_table': 'NOTIFICATION_TEMPLATE_T',
                'managed': True,
            },
        ),
    ]
