# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='purpose',
            field=models.CharField(db_column='PURPOSE', db_index=True, max_length=100),
        ),
    ]
