# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20180426_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(blank=True, db_column='BODY', null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='purpose',
            field=models.CharField(blank=True, db_column='PURPOSE', db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.TextField(blank=True, db_column='SUBJECT', null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplatet',
            name='template',
            field=models.ForeignKey(db_column='TEMPLATE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='notification.NotificationTemplate'),
        ),
    ]
