# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("notification", "0003_auto_20181126_1633")]

    operations = [
        migrations.AlterField(
            model_name="notificationtemplatet",
            name="template",
            field=models.ForeignKey(
                db_column="TEMPLATE_ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trans",
                to="notification.NotificationTemplate",
            ),
        )
    ]
