# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_duplicated_users'),
        ('notification', '0004_auto_20190627_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Service'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(blank=True, choices=[('email', 'E-Mail'), ('textcomponent', 'Textcomponent')], default='email', max_length=20, null=True),
        ),
    ]
