# Generated by Django 2.2.14 on 2020-09-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notificationtemplate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmitterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('answer', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'PROJECT_SUBMITTER_DATA',
                'managed': False,
            },
        ),
    ]
