# Generated by Django 3.2.19 on 2023-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0007_projectsubmitterdata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationtemplate",
            options={
                "managed": True,
                "verbose_name": "Notification template",
                "verbose_name_plural": "Notification templates",
            },
        ),
        migrations.AlterField(
            model_name="notificationtemplatet",
            name="body",
            field=models.TextField(db_column="BODY", verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="notificationtemplatet",
            name="purpose",
            field=models.CharField(
                db_column="PURPOSE", max_length=100, verbose_name="Purpose"
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplatet",
            name="subject",
            field=models.TextField(db_column="SUBJECT", verbose_name="Subject"),
        ),
    ]
