mutation CreateSubmitTask {
  saveCompleteWorkflowFormTask(
    input: {
      slug: "submit"
      name: "Gesuch einreichen"
      addressGroups: "[\"applicant\"]"
    }
  ) {
    clientMutationId
  }
}

mutation CreateManualWorkItemTask {
  saveSimpleTask(
    input: {
      slug: "create-manual-workitems"
      name: "Manuelle Aufgaben erfassen"
      addressGroups: "[]"
      isMultipleInstance: true
      meta: "{\"is-manually-completable\":true}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFormalExamTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "formal-exam"
      form: "vorlaeufige-pruefung"
      name: "Vorläufige Prüfung"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
      leadTime: 1728000 # 20 days
      meta: "{\"directLink\":{\"route\":\"cases.detail.task-form\",\"models\":[\"INSTANCE_ID\",\"TASK_SLUG\"]}}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateObjectionsTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "objections"
      form: "einwendungen"
      name: "Einwendungen erfassen"
      addressGroups: "[\"municipality\"]|groups"
      meta: "{\"directLink\":{\"route\":\"cases.detail.legal-submissions\",\"models\":[\"INSTANCE_ID\"]}}"
    }
  ) {
    clientMutationId
  }
}

mutation CreatePublicationTask {
  saveSimpleTask(
    input: {
      slug: "publication"
      name: "Dossier publizieren"
      addressGroups: "['municipality']|groups"
      controlGroups: "['municipality']|groups"
      leadTime: 604800 # 7 days
      meta: "{\"is-manually-completable\":true,\"directLink\":{\"route\":\"cases.detail.publication\",\"models\":[\"INSTANCE_ID\",\"public\"]}}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFillPublicationTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "fill-publication"
      name: "Publikation ausfüllen"
      form: "publikation"
      addressGroups: "['municipality']|groups"
    }
  ) {
    clientMutationId
  }
}

mutation CreateNewPublicationTask {
  saveSimpleTask(
    input: {
      slug: "create-publication"
      name: "Neue Publikation erfassen"
      addressGroups: "['municipality']|groups"
    }
  ) {
    clientMutationId
  }
}

mutation CreateInformationOfNeighborsTask {
  saveSimpleTask(
    input: {
      slug: "information-of-neighbors"
      name: "Information auswärtige Anstösser"
      addressGroups: "['municipality']|groups"
      controlGroups: "['municipality']|groups"
      leadTime: 604800 # 7 days
      meta: "{\"is-manually-completable\":true,\"directLink\":{\"route\":\"cases.detail.publication\",\"models\":[\"INSTANCE_ID\",\"neighbors\"]}}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFillInformationOfNeighborsTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "fill-information-of-neighbors"
      name: "Information auswärtige Anstösser ausfüllen"
      form: "nachbarschaftsorientierung"
      addressGroups: "['municipality']|groups"
    }
  ) {
    clientMutationId
  }
}

mutation CreateNewInformationOfNeighborsTask {
  saveSimpleTask(
    input: {
      slug: "create-information-of-neighbors"
      name: "Neue Information auswärtige Anstösser erstellen"
      addressGroups: "['municipality']|groups"
    }
  ) {
    clientMutationId
  }
}

mutation CreateCantonalExamTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "cantonal-exam"
      form: "kantonale-pruefung"
      name: "Eingang neues Gesuch prüfen"
      addressGroups: "[\"afb\"]|groups"
      controlGroups: "[\"afb\"]|groups"
      meta: "{\"directLink\":{\"route\":\"cases.detail.task-form\",\"models\":[\"INSTANCE_ID\",\"TASK_SLUG\"]}}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateDecisionTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "decision"
      form: "entscheid"
      name: "Entscheid / Stellungnahme erstellen"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
      leadTime: 1209600 # 14 days
      meta: "{\"directLink\":{\"route\":\"cases.detail.task-form\",\"models\":[\"INSTANCE_ID\",\"TASK_SLUG\"]}}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateCompleteInstanceTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "complete-instance"
      form: "complete-instance"
      name: "Verfahren abschliessen"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
      leadTime: 2592000 # 30 days
      meta: "{\"directLink\":{\"route\":\"cases.detail.task-form\",\"models\":[\"INSTANCE_ID\",\"TASK_SLUG\"]},\"redirectToWorkItemsAfterCompletion\":true}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateArchiveInstanceTask {
  saveSimpleTask(
    input: {
      slug: "archive-instance"
      name: "Dossier archivieren"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
    }
  ) {
    clientMutationId
  }
}

mutation CreateCheckPATask {
  saveSimpleTask(
    input: {
      slug: "check-pa"
      name: "PA kontrollieren und Gebühren auslösen"
      addressGroups: "[\"afb\"]|groups"
      controlGroups: "[\"afb\"]|groups"
      leadTime: 1209600 # 14 days
      meta: "{\"is-manually-completable\":true}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateTriggerBillingTask {
  saveSimpleTask(
    input: {
      slug: "trigger-billing"
      name: "Gebühren auslösen"
      addressGroups: "[\"afb\"]|groups"
      controlGroups: "[\"afb\"]|groups"
      leadTime: 31536000 # 365 days
      meta: "{\"is-manually-completable\":true}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateWithdrawalRequestTask {
  saveSimpleTask(
    input: {
      slug: "withdrawal-request"
      name: "Rückzug beantragen"
      addressGroups: "[\"applicant\"]"
    }
  ) {
    clientMutationId
  }
}

mutation CreateWithdrawalCheckTask {
  saveSimpleTask(
    input: {
      slug: "withdrawal-check"
      name: "Rückzug prüfen"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
    }
  ) {
    clientMutationId
  }
}
