mutation CreateBuildingPermitWorkflow {
  saveWorkflow(
    input: {
      slug: "building-permit"
      name: "Baugesuch"
      startTasks: ["submit"]
      allowForms: [
        "anfrage"
        "anfrage-intern"
        "baugesuch"
        "baugesuch-mit-uvp"
        "plangenehmigungsverfahren-bund"
        "plangenehmigungsverfahren-gas"
        "reklame"
        "vorentscheid"
      ]
      isPublished: true
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterSubmit {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["submit"]
      next: "[\"create-manual-workitems\", \"formal-exam\", \"init-additional-demand\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterFormalExam {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["formal-exam"]
      next: "[\"distribution\", \"cantonal-exam\", \"maybe-publication\", \"objections\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterFillPublication {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["fill-publication"]
      next: "[\"create-publication\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterCreatePublication {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["create-publication"]
      next: "[\"fill-publication\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterFillInformationOfNeighbors {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["fill-information-of-neighbors"]
      next: "[\"create-information-of-neighbors\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterCreateInformationOfNeighbors {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["create-information-of-neighbors"]
      next: "[\"fill-information-of-neighbors\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterDistribution {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["distribution"]
      next: "[\"decision\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterDecision {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["decision"]
      next: "[]|tasks"
      redoable: "'distribution'|task"
    }
  ) {
    clientMutationId
  }
}
