mutation CreateBuildingPermitWorkflow {
  saveWorkflow(
    input: {
      slug: "building-permit"
      name: "Baugesuch"
      startTasks: ["submit"]
      allowForms: [
        "anfrage"
        "baugesuch"
        "baugesuch-mit-uvp"
        "plangenehmigungsverfahren-bund"
        "plangenehmigungsverfahren-gas"
        "reklame"
        "vorentscheid"
        "baugesuch-migration"
        "uvp-migration"
      ]
      isPublished: true
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterSubmit {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["submit"]
      next: "[\"after-submit\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterFormalExam {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["formal-exam"]
      next: "[\"distribution\", \"cantonal-exam\", \"maybe-publication\", \"objections\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterFillPublication {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["fill-publication"]
      next: "[\"create-publication\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterCreatePublication {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["create-publication"]
      next: "[\"fill-publication\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterFillInformationOfNeighbors {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["fill-information-of-neighbors"]
      next: "[\"create-information-of-neighbors\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterCreateInformationOfNeighbors {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["create-information-of-neighbors"]
      next: "[\"fill-information-of-neighbors\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterDistribution {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["distribution"]
      next: "[\"decision\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterDecision {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["decision"]
      next: "[\"after-decision\"]|tasks"
      redoable: "'distribution'|task"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterWithdrawal {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["withdrawal-request"]
      next: "[\"withdrawal-check\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterCompleteConstructionMonitoring {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["complete-construction-monitoring"]
      next: "[\"complete-instance\"]|tasks"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlowAfterCompleteInstance {
  addWorkflowFlow(
    input: {
      workflow: "building-permit"
      tasks: ["complete-instance"]
      next: "[\"archive-instance\"]|tasks"
    }
  ) {
    clientMutationId
  }
}
