--
-- OFFENE GESUCHE VON EBAU-GEMEINDEN
--
select g.*, t.TXT30 as GEMEINDE_STATUS, te.TXT30 as KANTONS_STATUS, rt.DESCRIPTION as GESART_KANTON, city.*,
       ge.CREATED_ON as KANTON_EINGANG, ge.BEARBEITUNGSFRIST as KANTON_BEARBEITUNGSFRIST, rgt.DESCRIPTION as KANTON_GRUPPE,
       rgt.DESCRIPTION2 as KANTON_GRUPPE2, ge.PERSON_RESPONSIBLE as KANTON_SACHBEARBEITER,
       ge.COMPLETION_DATE as KANTON_VORL_ABSCHLUSS, rcct.DESCRIPTION as KANTON_ABSCHLUSSCODE,
       ge.COMPLETION_DURATION as KANTON_DAUER, ge.EXTERNAL_BUSINESS_CASE as KANTON_LWAG_NR,
       ge.KA_BAN_KNZ as KANTON_KANALISATION, ge.MAWALD_KNZ AS KANTON_MAWALD_KNZ, ge.SNDF_ENTW_KNZ AS KANTON_SNDF_ENTW_KNZ,
       ge.GWABSNK_KNZ AS KANTON_GWABSNK_KNZ, ge.AWA_KNZ AS KANTON_AWA_KNZ, ge.BVWALD_KNZ AS KANTON_BVWALD_KNZ,
       ge.HWG_KNZ AS KANTON_HWG_KNZ, ge.DENKMAL_KNZ AS KANTON_DENKMAL_KNZ, ge.WANDERWEGE_KNZ AS KANTON_WANDERWEGE_KNZ,
       ge.ORTSBILD AS KANTON_ORTSBILD, ge.STOER_KNZ AS KANTON_STOER_KNZ, ge.ARCH_KNZ AS KANTON_ARCH_KNZ,
       ge.VERKEHR_KNZ AS KANTON_VERKEHR_KNZ, ge.LSMERF_KNZ AS KANTON_LSMERF_KNZ, ge.MATABB_KNZ AS KANTON_MATABB_KNZ,
       ge.AGV_KNZ AS KANTON_AGV_KNZ, ge.RADWEGE_KNZ AS KANTON_RADWEGE_KNZ,
       ge.FLACHENVERBRAUCH AS KANTON_FLACHENVERBRAUCH, ge.KOKO_DATUM AS KANTON_KOKO_DATUM, ge.KOKO_STATUS AS KANTON_KOKO_STATUS,
       ge.BESCHLUSS_GEMEINDE AS KANTON_BESCHLUSS_GEMEINDE, ge.BESCHLUSS_ART AS KANTON_BESCHLUSS_ART,
       ge.VERZOGERUNG AS KANTON_VERZOGERUNG, ge.BEGRUNDUNG AS KANTON_BEGRUNDUNG, ge.NACHTR_GESUCH_KNZ AS KANTON_NACHTR_GESUCH_KNZ,
       ge.KANTSTR_KNZ AS KANTON_KANTSTR_KNZ, ge.OEFFGW_KNZ AS KANTON_OEFFGW_KNZ
from ZEBP_GESUCH g
         left join ZEB2_A_REQUEST ge on g.GESUCH_ID = ge.GESUCH_ID
         left join TJ30T t on t.ESTAT = g.ESTAT and t.STSMA = 'ZEBP'
         left join TJ30T te on te.ESTAT = ge.KANTON_STATUS and te.STSMA = 'ZEB2_REQ'
         left join ZEZS_CITY city on city.CITY_ID = g.GEMEINDE_ID
         left join ZEB2_C_REQ_TYPET rt on ge.REQUEST_TYPE = rt.REQUEST_TYPE
         left join ZEB2_C_GRUPPET rgt on ge.GROUP_ID = rgt.id
         left join ZEB2_C_COMPCODET rcct on ge.COMPLETION_CODE = rcct.COMPLETION_CODE
where t.TXT30 in ('Verfügung erstellt', 'Gesuch in Bearbeitung', 'Gesuch übermittelt', 'Anfrage / Stellungnahme offen',
                  'In öffentlicher Auflage', 'An Kanton gesendet')
  and city.CITY in
      ('Aarau', 'Aarburg', 'Arni (AG)', 'Biberstein', 'Dietwil', 'Endingen', 'Fischbach-Göslikon', 'Freienwil', 'Hellikon',
       'Lengnau (AG)', 'Meisterschwanden', 'Menziken', 'Mettauertal', 'Möhlin', 'Mülligen', 'Obermumpf', 'Oberwil-Lieli',
       'Olsberg', 'Riniken', 'Suhr', 'Tägerig', 'Tegerfelden', 'Wallbach', 'Würenlingen', 'Zuzgen')
  and g.DIVERSES_KNZ != 'X' and g.VORABKL_KNZ != 'X';

--
-- OFFENE GESUCHE VON NICHT-EBAU-GEMEINDEN
--
select g.*, t.TXT30 as GEMEINDE_STATUS, te.TXT30 as KANTONS_STATUS, rt.DESCRIPTION as GESART_KANTON, city.*,
       ge.CREATED_ON as KANTON_EINGANG, ge.BEARBEITUNGSFRIST as KANTON_BEARBEITUNGSFRIST, rgt.DESCRIPTION as KANTON_GRUPPE,
       rgt.DESCRIPTION2 as KANTON_GRUPPE2, ge.PERSON_RESPONSIBLE as KANTON_SACHBEARBEITER,
       ge.COMPLETION_DATE as KANTON_VORL_ABSCHLUSS, rcct.DESCRIPTION as KANTON_ABSCHLUSSCODE,
       ge.COMPLETION_DURATION as KANTON_DAUER, ge.EXTERNAL_BUSINESS_CASE as KANTON_LWAG_NR,
       ge.KA_BAN_KNZ as KANTON_KANALISATION, ge.MAWALD_KNZ AS KANTON_MAWALD_KNZ, ge.SNDF_ENTW_KNZ AS KANTON_SNDF_ENTW_KNZ,
       ge.GWABSNK_KNZ AS KANTON_GWABSNK_KNZ, ge.AWA_KNZ AS KANTON_AWA_KNZ, ge.BVWALD_KNZ AS KANTON_BVWALD_KNZ,
       ge.HWG_KNZ AS KANTON_HWG_KNZ, ge.DENKMAL_KNZ AS KANTON_DENKMAL_KNZ, ge.WANDERWEGE_KNZ AS KANTON_WANDERWEGE_KNZ,
       ge.ORTSBILD AS KANTON_ORTSBILD, ge.STOER_KNZ AS KANTON_STOER_KNZ, ge.ARCH_KNZ AS KANTON_ARCH_KNZ,
       ge.VERKEHR_KNZ AS KANTON_VERKEHR_KNZ, ge.LSMERF_KNZ AS KANTON_LSMERF_KNZ, ge.MATABB_KNZ AS KANTON_MATABB_KNZ,
       ge.AGV_KNZ AS KANTON_AGV_KNZ, ge.RADWEGE_KNZ AS KANTON_RADWEGE_KNZ,
       ge.FLACHENVERBRAUCH AS KANTON_FLACHENVERBRAUCH, ge.KOKO_DATUM AS KANTON_KOKO_DATUM, ge.KOKO_STATUS AS KANTON_KOKO_STATUS,
       ge.BESCHLUSS_GEMEINDE AS KANTON_BESCHLUSS_GEMEINDE, ge.BESCHLUSS_ART AS KANTON_BESCHLUSS_ART,
       ge.VERZOGERUNG AS KANTON_VERZOGERUNG, ge.BEGRUNDUNG AS KANTON_BEGRUNDUNG, ge.NACHTR_GESUCH_KNZ AS KANTON_NACHTR_GESUCH_KNZ,
       ge.KANTSTR_KNZ AS KANTON_KANTSTR_KNZ, ge.OEFFGW_KNZ AS KANTON_OEFFGW_KNZ
from ZEBP_GESUCH g
         left join ZEB2_A_REQUEST ge on g.GESUCH_ID = ge.GESUCH_ID
         left join TJ30T t on t.ESTAT = g.ESTAT and t.STSMA = 'ZEBP'
         left join TJ30T te on te.ESTAT = ge.KANTON_STATUS and te.STSMA = 'ZEB2_REQ'
         left join ZEZS_CITY city on city.CITY_ID = g.GEMEINDE_ID
         left join ZEB2_C_REQ_TYPET rt on ge.REQUEST_TYPE = rt.REQUEST_TYPE
         left join ZEB2_C_GRUPPET rgt on ge.GROUP_ID = rgt.id
         left join ZEB2_C_COMPCODET rcct on ge.COMPLETION_CODE = rcct.COMPLETION_CODE
where te.TXT30 in
      ('Vorläufiger Abschluss', 'Sistiert', 'Fachstelle Aufgabe offen', 'Weiterbearbeitung AfB', 'Freigabeverfahren',
       'Zurückgewiesen', 'Neues Gesuch')
  and city.CITY not in
      ('Aarau', 'Aarburg', 'Arni (AG)', 'Biberstein', 'Dietwil', 'Endingen', 'Fischbach-Göslikon', 'Freienwil', 'Hellikon',
       'Lengnau (AG)', 'Meisterschwanden', 'Menziken', 'Mettauertal', 'Möhlin', 'Mülligen', 'Obermumpf', 'Oberwil-Lieli',
       'Olsberg', 'Riniken', 'Suhr', 'Tägerig', 'Tegerfelden', 'Wallbach', 'Würenlingen', 'Zuzgen',
       'ZZ Testgemeinde', 'ZZ Testgemeinde MH 1')
  and g.DIVERSES_KNZ != 'X' and g.VORABKL_KNZ != 'X';


--
-- ABGESCHLOSSENE GESUCHE VON NICHT-EBAU-GEMEINDEN
--
select g.*, t.TXT30 as GEMEINDE_STATUS, te.TXT30 as KANTONS_STATUS, rt.DESCRIPTION as GESART_KANTON, city.*,
       ge.CREATED_ON as KANTON_EINGANG, ge.BEARBEITUNGSFRIST as KANTON_BEARBEITUNGSFRIST, rgt.DESCRIPTION as KANTON_GRUPPE,
       rgt.DESCRIPTION2 as KANTON_GRUPPE2, ge.PERSON_RESPONSIBLE as KANTON_SACHBEARBEITER,
       ge.COMPLETION_DATE as KANTON_VORL_ABSCHLUSS, rcct.DESCRIPTION as KANTON_ABSCHLUSSCODE,
       ge.COMPLETION_DURATION as KANTON_DAUER, ge.EXTERNAL_BUSINESS_CASE as KANTON_LWAG_NR,
       ge.KA_BAN_KNZ as KANTON_KANALISATION, ge.MAWALD_KNZ AS KANTON_MAWALD_KNZ, ge.SNDF_ENTW_KNZ AS KANTON_SNDF_ENTW_KNZ,
       ge.GWABSNK_KNZ AS KANTON_GWABSNK_KNZ, ge.AWA_KNZ AS KANTON_AWA_KNZ, ge.BVWALD_KNZ AS KANTON_BVWALD_KNZ,
       ge.HWG_KNZ AS KANTON_HWG_KNZ, ge.DENKMAL_KNZ AS KANTON_DENKMAL_KNZ, ge.WANDERWEGE_KNZ AS KANTON_WANDERWEGE_KNZ,
       ge.ORTSBILD AS KANTON_ORTSBILD, ge.STOER_KNZ AS KANTON_STOER_KNZ, ge.ARCH_KNZ AS KANTON_ARCH_KNZ,
       ge.VERKEHR_KNZ AS KANTON_VERKEHR_KNZ, ge.LSMERF_KNZ AS KANTON_LSMERF_KNZ, ge.MATABB_KNZ AS KANTON_MATABB_KNZ,
       ge.AGV_KNZ AS KANTON_AGV_KNZ, ge.RADWEGE_KNZ AS KANTON_RADWEGE_KNZ,
       ge.FLACHENVERBRAUCH AS KANTON_FLACHENVERBRAUCH, ge.KOKO_DATUM AS KANTON_KOKO_DATUM, ge.KOKO_STATUS AS KANTON_KOKO_STATUS,
       ge.BESCHLUSS_GEMEINDE AS KANTON_BESCHLUSS_GEMEINDE, ge.BESCHLUSS_ART AS KANTON_BESCHLUSS_ART,
       ge.VERZOGERUNG AS KANTON_VERZOGERUNG, ge.BEGRUNDUNG AS KANTON_BEGRUNDUNG, ge.NACHTR_GESUCH_KNZ AS KANTON_NACHTR_GESUCH_KNZ,
       ge.KANTSTR_KNZ AS KANTON_KANTSTR_KNZ, ge.OEFFGW_KNZ AS KANTON_OEFFGW_KNZ
from ZEBP_GESUCH g
         left join ZEB2_A_REQUEST ge on g.GESUCH_ID = ge.GESUCH_ID
         left join TJ30T t on t.ESTAT = g.ESTAT and t.STSMA = 'ZEBP'
         left join TJ30T te on te.ESTAT = ge.KANTON_STATUS and te.STSMA = 'ZEB2_REQ'
         left join ZEZS_CITY city on city.CITY_ID = g.GEMEINDE_ID
         left join ZEB2_C_REQ_TYPET rt on ge.REQUEST_TYPE = rt.REQUEST_TYPE
         left join ZEB2_C_GRUPPET rgt on ge.GROUP_ID = rgt.id
         left join ZEB2_C_COMPCODET rcct on ge.COMPLETION_CODE = rcct.COMPLETION_CODE
where te.TXT30 in ('Definitiver Abschluss')
  and city.CITY not in
      ('Aarau', 'Aarburg', 'Arni (AG)', 'Biberstein', 'Dietwil', 'Endingen', 'Fischbach-Göslikon', 'Freienwil', 'Hellikon',
       'Lengnau (AG)', 'Meisterschwanden', 'Menziken', 'Mettauertal', 'Möhlin', 'Mülligen', 'Obermumpf', 'Oberwil-Lieli',
       'Olsberg', 'Riniken', 'Suhr', 'Tägerig', 'Tegerfelden', 'Wallbach', 'Würenlingen', 'Zuzgen',
       'ZZ Testgemeinde', 'ZZ Testgemeinde MH 1')
  and g.DIVERSES_KNZ != 'X' and g.VORABKL_KNZ != 'X';

--
-- ABGESCHLOSSENE GESUCHE VON EBAU-GEMEINDEN
--
select g.*, t.TXT30 as GEMEINDE_STATUS, te.TXT30 as KANTONS_STATUS, rt.DESCRIPTION as GESART_KANTON, city.*,
       ge.CREATED_ON as KANTON_EINGANG, ge.BEARBEITUNGSFRIST as KANTON_BEARBEITUNGSFRIST, rgt.DESCRIPTION as KANTON_GRUPPE,
       rgt.DESCRIPTION2 as KANTON_GRUPPE2, ge.PERSON_RESPONSIBLE as KANTON_SACHBEARBEITER,
       ge.COMPLETION_DATE as KANTON_VORL_ABSCHLUSS, rcct.DESCRIPTION as KANTON_ABSCHLUSSCODE,
       ge.COMPLETION_DURATION as KANTON_DAUER, ge.EXTERNAL_BUSINESS_CASE as KANTON_LWAG_NR,
       ge.KA_BAN_KNZ as KANTON_KANALISATION, ge.MAWALD_KNZ AS KANTON_MAWALD_KNZ, ge.SNDF_ENTW_KNZ AS KANTON_SNDF_ENTW_KNZ,
       ge.GWABSNK_KNZ AS KANTON_GWABSNK_KNZ, ge.AWA_KNZ AS KANTON_AWA_KNZ, ge.BVWALD_KNZ AS KANTON_BVWALD_KNZ,
       ge.HWG_KNZ AS KANTON_HWG_KNZ, ge.DENKMAL_KNZ AS KANTON_DENKMAL_KNZ, ge.WANDERWEGE_KNZ AS KANTON_WANDERWEGE_KNZ,
       ge.ORTSBILD AS KANTON_ORTSBILD, ge.STOER_KNZ AS KANTON_STOER_KNZ, ge.ARCH_KNZ AS KANTON_ARCH_KNZ,
       ge.VERKEHR_KNZ AS KANTON_VERKEHR_KNZ, ge.LSMERF_KNZ AS KANTON_LSMERF_KNZ, ge.MATABB_KNZ AS KANTON_MATABB_KNZ,
       ge.AGV_KNZ AS KANTON_AGV_KNZ, ge.RADWEGE_KNZ AS KANTON_RADWEGE_KNZ,
       ge.FLACHENVERBRAUCH AS KANTON_FLACHENVERBRAUCH, ge.KOKO_DATUM AS KANTON_KOKO_DATUM, ge.KOKO_STATUS AS KANTON_KOKO_STATUS,
       ge.BESCHLUSS_GEMEINDE AS KANTON_BESCHLUSS_GEMEINDE, ge.BESCHLUSS_ART AS KANTON_BESCHLUSS_ART,
       ge.VERZOGERUNG AS KANTON_VERZOGERUNG, ge.BEGRUNDUNG AS KANTON_BEGRUNDUNG, ge.NACHTR_GESUCH_KNZ AS KANTON_NACHTR_GESUCH_KNZ,
       ge.KANTSTR_KNZ AS KANTON_KANTSTR_KNZ, ge.OEFFGW_KNZ AS KANTON_OEFFGW_KNZ
from ZEBP_GESUCH g
         left join ZEB2_A_REQUEST ge on g.GESUCH_ID = ge.GESUCH_ID
         left join TJ30T t on t.ESTAT = g.ESTAT and t.STSMA = 'ZEBP'
         left join TJ30T te on te.ESTAT = ge.KANTON_STATUS and te.STSMA = 'ZEB2_REQ'
         left join ZEZS_CITY city on city.CITY_ID = g.GEMEINDE_ID
         left join ZEB2_C_REQ_TYPET rt on ge.REQUEST_TYPE = rt.REQUEST_TYPE
         left join ZEB2_C_GRUPPET rgt on ge.GROUP_ID = rgt.id
         left join ZEB2_C_COMPCODET rcct on ge.COMPLETION_CODE = rcct.COMPLETION_CODE
where t.TXT30 in ('Gesuch archiviert', 'Gesuch storniert', 'Gesuch abgeschrieben', 'Gesuch zurückgezogen')
  and city.CITY in
      ('Aarau', 'Aarburg', 'Arni (AG)', 'Biberstein', 'Dietwil', 'Endingen', 'Fischbach-Göslikon', 'Freienwil', 'Hellikon',
       'Lengnau (AG)', 'Meisterschwanden', 'Menziken', 'Mettauertal', 'Möhlin', 'Mülligen', 'Obermumpf', 'Oberwil-Lieli',
       'Olsberg', 'Riniken', 'Suhr', 'Tägerig', 'Tegerfelden', 'Wallbach', 'Würenlingen', 'Zuzgen')
  and g.DIVERSES_KNZ != 'X' and g.VORABKL_KNZ != 'X';
