POST http://{{SOAP_SERVER}}.ktag.ch:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=EBP_Out&
    receiverParty=&receiverService=&interface=Gesuch_Out&interfaceNamespace=urn:ag.ch:KTAG_CRM_EBP:Gesuch
Accept-Encoding: gzip,deflate
Content-Type: application/soap+xml
Authorization: Basic {{SOAP_USER}} {{SOAP_PASSWORD}}

<?xml version="1.0" encoding="utf-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SOAP-ENV:Header>
    <WSCorIDSOAPHeader xmlns="http://www.ca.com/apm" />
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <yq1:Gesuch_Request_Access xmlns:yq1="urn:ag.ch:KTAG_CRM_EBP:Gesuch">
      <accessType>RO</accessType>
      <ges_id>{{GESUCH_ID}}</ges_id>
    </yq1:Gesuch_Request_Access>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
