# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 11:30
from __future__ import unicode_literals

import camac.document.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(db_column='ATTACHMENT_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255)),
                ('path', models.FileField(db_column='PATH', max_length=1024, upload_to=camac.document.models.attachment_path_directory_path)),
                ('size', models.IntegerField(db_column='SIZE')),
                ('date', models.DateTimeField(db_column='DATE', default=django.utils.timezone.now)),
                ('mime_type', models.CharField(db_column='MIME_TYPE', max_length=255)),
                ('is_parcel_picture', models.PositiveIntegerField(db_column='IS_PARCEL_PICTURE', default=0)),
                ('digital_signature', models.PositiveSmallIntegerField(db_column='DIGITAL_SIGNATURE', default=0)),
                ('is_confidential', models.PositiveSmallIntegerField(db_column='IS_CONFIDENTIAL', default=0)),
                ('identifier', models.CharField(blank=True, db_column='IDENTIFIER', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ATTACHMENT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttachmentSection',
            fields=[
                ('attachment_section_id', models.AutoField(db_column='ATTACHMENT_SECTION_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100, unique=True)),
                ('sort', models.IntegerField(db_column='SORT')),
            ],
            options={
                'db_table': 'ATTACHMENT_SECTION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttachmentSectionRoleAcl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mode', models.CharField(blank=True, db_column='MODE', max_length=10, null=True)),
            ],
            options={
                'db_table': 'ATTACHMENT_SECTION_ROLE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttachmentSectionServiceAcl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mode', models.CharField(db_column='MODE', max_length=20)),
                ('attachment_section', models.ForeignKey(db_column='ATTACHMENT_SECTION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='document.AttachmentSection')),
            ],
            options={
                'db_table': 'ATTACHMENT_SECTION_SERVICE',
                'managed': True,
            },
        ),
    ]
