# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instance', '0001_initial'),
        ('core', '0003_auto_20180110_1331'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentsectionserviceacl',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='attachmentsectionroleacl',
            name='attachment_section',
            field=models.ForeignKey(db_column='ATTACHMENT_SECTION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='document.AttachmentSection'),
        ),
        migrations.AddField(
            model_name='attachmentsectionroleacl',
            name='role',
            field=models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Role'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_section',
            field=models.ForeignKey(db_column='ATTACHMENT_SECTION_ID', on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='document.AttachmentSection'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='user.Group'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='instance.Instance'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='service',
            field=models.ForeignKey(blank=True, db_column='SERVICE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Service'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attachmentsectionserviceacl',
            unique_together=set([('attachment_section', 'service')]),
        ),
        migrations.AlterUniqueTogether(
            name='attachmentsectionroleacl',
            unique_together=set([('attachment_section', 'role')]),
        ),
    ]
