# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 14:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentsection',
            name='notification_template',
            field=models.ForeignKey(blank=True, db_column='NOTIFICATION_TEMPLATE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notification.NotificationTemplate'),
        ),
        migrations.AddField(
            model_name='attachmentsection',
            name='recipient_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('applicant', 'applicant'), ('municipality', 'municipality'), ('service', 'service')], max_length=12), blank=True, null=True, size=None),
        ),
    ]
