# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachmentsectiongroupacl',
            table='ATTACHMENT_SECTION_GROUP',
        ),
    ]
