# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentsection',
            name='sort',
            field=models.IntegerField(db_column='SORT', db_index=True, default=0),
        ),
    ]
