# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20180426_1106'),
        ('document', '0002_auto_20180427_1637'),
    ]

    operations = [
    ]
