# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20180426_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='is_parcel_picture',
            field=models.PositiveIntegerField(db_column='IS_PARCEL_PICTURE', default=0, null=True),
        ),
    ]
