# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20180409_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='id',
        ),
        migrations.AddField(
            model_name='template',
            name='template_id',
            field=models.AutoField(db_column='TEMPLATE_ID', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
