# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-06 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_template_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='question',
            field=models.CharField(blank=True, db_column='QUESTION', max_length=255, null=True),
        ),
    ]
