# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("document", "0006_assign_attachment_service")]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="attachment_sections",
            field=models.ManyToManyField(to="document.AttachmentSection"),
        )
    ]
