# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("document", "0008_migrate_attachment_attachment_section_data")]

    operations = [
        migrations.RemoveField(model_name="attachment", name="attachment_section"),
        migrations.AlterField(
            model_name="attachment",
            name="attachment_sections",
            field=models.ManyToManyField(
                related_name="attachments", to="document.AttachmentSection"
            ),
        ),
    ]
