# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0009_auto_20190218_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentDownloadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_download_history', to='document.Attachment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_download_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
