# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20190605_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentsectiongroupacl',
            name='mode',
            field=models.CharField(choices=[('read', 'Read permissions'), ('write', 'Read and write permissions'), ('admin', 'Read, write and delete permissions'), ('adminsvc', 'Read, write and delete permission only on service attachments')], max_length=10),
        ),
        migrations.AlterField(
            model_name='attachmentsectionroleacl',
            name='mode',
            field=models.CharField(choices=[('read', 'Read permissions'), ('write', 'Read and write permissions'), ('admin', 'Read, write and delete permissions'), ('adminsvc', 'Read, write and delete permission only on service attachments')], db_column='MODE', max_length=10),
        ),
        migrations.AlterField(
            model_name='attachmentsectionserviceacl',
            name='attachment_section',
            field=models.ForeignKey(db_column='ATTACHMENT_SECTION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='service_acls', to='document.AttachmentSection'),
        ),
        migrations.AlterField(
            model_name='attachmentsectionserviceacl',
            name='mode',
            field=models.CharField(choices=[('read', 'Read permissions'), ('write', 'Read and write permissions'), ('admin', 'Read, write and delete permissions'), ('adminsvc', 'Read, write and delete permission only on service attachments')], db_column='MODE', max_length=20),
        ),
    ]
