# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-09 09:51
from __future__ import unicode_literals

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Attachment = apps.get_model('document', 'Attachment')
    for row in Attachment.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_auto_20191009_1139'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
