# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-09 09:51
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
