# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-22 08:13
from __future__ import unicode_literals

from django.db import migrations

sql = """
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
ALTER TABLE "ATTACHMENT" ALTER COLUMN uuid SET DEFAULT uuid_generate_v4();
"""


class Migration(migrations.Migration):

    dependencies = [("document", "0017_remove_uuid_null")]

    operations = [migrations.RunSQL(sql)]
