# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 10:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("document", "0018_auto_20191022_1013")]

    operations = [
        migrations.CreateModel(
            name="AttachmentSectionT",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(db_column="LANGUAGE", max_length=2)),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="NAME", max_length=100, null=True
                    ),
                ),
            ],
            options={"db_table": "ATTACHMENT_SECTION_T", "managed": True},
        ),
        migrations.AlterField(
            model_name="attachmentsection",
            name="name",
            field=models.CharField(db_column="NAME", max_length=100),
        ),
        migrations.AddField(
            model_name="attachmentsectiont",
            name="attachment_section",
            field=models.ForeignKey(
                db_column="ATTACHMENT_SECTION_ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trans",
                to="document.AttachmentSection",
            ),
        ),
    ]
