# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("document", "0019_auto_20191023_1213")]

    operations = []
