# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-28 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_usergrouplog'),
        ('document', '0020_auto_20191023_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(db_column='NAME', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set([('name', 'service')]),
        ),
    ]
