# Generated by Django 2.2.9 on 2020-02-28 15:44

import django.contrib.postgres.fields
from django.db import migrations, models

import camac.document.models


class Migration(migrations.Migration):

    dependencies = [("document", "0022_add_attachment_section_permission")]

    operations = [
        migrations.AddField(
            model_name="attachmentsection",
            name="allowed_mime_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("application/pdf", "application/pdf"),
                        (
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                        ),
                        (
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        ),
                        (
                            "application/vnd.openxmlformats-officedocument.presentationml.presentationapplication/xml",
                            "application/vnd.openxmlformats-officedocument.presentationml.presentationapplication/xml",
                        ),
                        ("image/gif", "image/gif"),
                        ("image/jpeg", "image/jpeg"),
                        ("image/png", "image/png"),
                        ("image/tiff", "image/tiff"),
                        ("text/plain", "text/plain"),
                    ],
                    max_length=255,
                ),
                default=camac.document.models._get_default_mime_types,
                size=None,
            ),
        )
    ]
