# Generated by Django 2.2.9 on 2020-02-28 14:17

import django.contrib.postgres.fields
from django.db import migrations, models

import camac.document.models


class Migration(migrations.Migration):

    dependencies = [("document", "0022_add_attachment_section_permission")]

    operations = [
        migrations.AddField(
            model_name="attachmentsection",
            name="allowed_mime_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("image/png", "image/png"),
                        ("image/jpeg", "image/jpeg"),
                        ("application/pdf", "application/pdf"),
                    ],
                    max_length=255,
                ),
                default=camac.document.models._get_allowed_mime_types,
                size=None,
            ),
        )
    ]
