# Generated by Django 2.2.11 on 2020-05-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0023_attachmentsection_allowed_mime_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentsection',
            name='description',
            field=models.CharField(blank=True, db_column='DESCRIPTION', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='attachmentsectiont',
            name='description',
            field=models.CharField(blank=True, db_column='DESCRIPTION', max_length=2000, null=True),
        ),
    ]
