# Generated by Django 2.2.17 on 2021-03-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0024_auto_20200506_1016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentdownloadhistory",
            name="attachment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download_history",
                to="document.Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="attachmentdownloadhistory",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment_download_history",
                to="user.Group",
            ),
        ),
    ]
