# Generated by Django 2.2.17 on 2021-04-13 16:50

from django.db import migrations
from django.conf import settings


def replace_is_confidential(apps, schema_editor):
    if settings.APPLICATION_NAME == "kt_uri":
        Attachment = apps.get_model("document", "Attachment")

        for attachment in Attachment.objects.all():
            attachment.context = {"isConfidential": bool(attachment.is_confidential)}
            attachment.save()


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0025_auto_20210322_1146"),
    ]

    operations = [migrations.RunPython(replace_is_confidential)]
