# Generated by Django 3.2.12 on 2022-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0028_add_user_to_attachment_download_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='context',
            field=models.JSONField(default=dict),
        ),
    ]
