# Generated by Django 3.2.19 on 2023-07-28 11:30

import camac.document.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0029_alter_attachment_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('path', models.FileField(max_length=1024, upload_to=camac.document.models.version_path_directory_path)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='document.attachment')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='attachmentversion',
            constraint=models.UniqueConstraint(fields=('attachment', 'version'), name='unique_attachment_version'),
        ),
    ]
