-- PENDENZENLISTE START KOORD BG

UPDATE R_LIST 
SET QUERY = '

SELECT
	"INSTANCE"."INSTANCE_ID"   AS "INSTANCE_ID",
	"ANSWER_DOK_NR"."ANSWER"   AS "DOSSIER_NR",
	"FORM"."NAME"              AS "FORM",
	"LOCATION"."NAME"          AS "COMMUNITY",
	"USER"."USERNAME"          AS "USER",
	"ANSWER_OTHER_INTENT"."ANSWER" AS "ANSWER_OTHER_INTENT",
	CASE WHEN
			"ANSWER_COMPANY"."ANSWER" IS NOT NULL 
		THEN "ANSWER_COMPANY"."ANSWER"
		ELSE "ANSWER_APPLICANT"."ANSWER"
	END AS "PETITION",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",

	"ANSWER_STREET"."ANSWER"     AS "STREET",
	"INSTANCE_STATE"."NAME"    AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"
FROM
	"INSTANCE"
JOIN
	"INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
	)
JOIN 
	"LOCATION" ON (
	 "INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
	)
JOIN
	FORM ON (
		"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)
JOIN
	"USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)
JOIN
	"ANSWER" "ANSWER_DOK_NR" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_DOK_NR"."INSTANCE_ID"
		AND
		"ANSWER_DOK_NR"."QUESTION_ID" = 6
		AND
		"ANSWER_DOK_NR"."CHAPTER_ID" = 2
		AND
		"ANSWER_DOK_NR"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)
LEFT JOIN 
	"ANSWER" "ANSWER_COMPANY" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_COMPANY"."INSTANCE_ID"
		AND
		"ANSWER_COMPANY"."QUESTION_ID" = 221
		AND
		"ANSWER_COMPANY"."CHAPTER_ID" = 1
		AND
		"ANSWER_COMPANY"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET"."INSTANCE_ID"
		AND
		"ANSWER_STREET"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET"."CHAPTER_ID" = 21
		AND
		"ANSWER_STREET"."ITEM" = 1
	)
JOIN 
	"INSTANCE_STATE" ON (
	"INSTANCE_STATE"."NAME" = ''ext''
)
LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE"."INSTANCE_STATE_ID"
	)
JOIN
	"FORM_GROUP_FORM" ON (
	"FORM_GROUP_FORM"."FORM_ID" = "INSTANCE"."FORM_ID"
)
JOIN "ANSWER" "ANSWER_OTHER_INTENT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_OTHER_INTENT"."INSTANCE_ID"
		AND
		"ANSWER_OTHER_INTENT"."QUESTION_ID" = 98
		AND
		"ANSWER_OTHER_INTENT"."CHAPTER_ID" = 21
		AND
		"ANSWER_OTHER_INTENT"."ITEM" = 1
)
WHERE
	"INSTANCE"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	AND
	"FORM_GROUP_FORM"."FORM_GROUP_ID" = 30

'

WHERE RESOURCE_ID = 24;

-- PENDENZENLISTE ENDE KOORD BG


UPDATE R_LIST 
SET QUERY = '

	
SELECT
	"INSTANCE"."INSTANCE_ID"   AS "INSTANCE_ID",
	"ANSWER_DOK_NR"."ANSWER"   AS "DOSSIER_NR",
	"FORM"."NAME"              AS "FORM",
	"LOCATION"."NAME"          AS "COMMUNITY",
	"USER"."USERNAME"          AS "USER",
	CASE WHEN
			"ANSWER_COMPANY"."ANSWER" IS NOT NULL 
		THEN "ANSWER_COMPANY"."ANSWER"
		ELSE "ANSWER_APPLICANT"."ANSWER"
	END AS "PETITION",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",
	"ANSWER_STREET"."ANSWER"     AS "STREET",
	"INSTANCE_STATE"."NAME"    AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"
FROM
	"INSTANCE"
JOIN
	"INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
	)
JOIN 
	"LOCATION" ON (
	 "INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
	)
JOIN
	FORM ON (
		"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)
JOIN
	"USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)
JOIN
	"ANSWER" "ANSWER_DOK_NR" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_DOK_NR"."INSTANCE_ID"
		AND
		"ANSWER_DOK_NR"."QUESTION_ID" = 6
		AND
		"ANSWER_DOK_NR"."CHAPTER_ID" = 2
		AND
		"ANSWER_DOK_NR"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)
LEFT JOIN 
	"ANSWER" "ANSWER_COMPANY" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_COMPANY"."INSTANCE_ID"
		AND
		"ANSWER_COMPANY"."QUESTION_ID" = 221
		AND
		"ANSWER_COMPANY"."CHAPTER_ID" = 1
		AND
		"ANSWER_COMPANY"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET"."INSTANCE_ID"
		AND
		"ANSWER_STREET"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET"."CHAPTER_ID" = 21
		AND
		"ANSWER_STREET"."ITEM" = 1
	)
JOIN 
	"INSTANCE_STATE" ON (
	"INSTANCE_STATE"."NAME" = ''redac''
)

LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE"."INSTANCE_STATE_ID"
	)
JOIN
	"FORM_GROUP_FORM" ON (
	"FORM_GROUP_FORM"."FORM_ID" = "INSTANCE"."FORM_ID"
)
WHERE
	"INSTANCE"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	AND
	"FORM_GROUP_FORM"."FORM_GROUP_ID" = 30

'
WHERE RESOURCE_ID = 62;


-- DOSSIERLISTE ALG

UPDATE R_LIST 
SET QUERY = '
	
SELECT  DISTINCT
	"INSTANCE"."INSTANCE_ID",
	"DOSSIERNR"."ANSWER" as "DOSSIER_NR",
	"FORM"."NAME"        as "FORM",
	"LOCATION"."NAME"    as "COMMUNITY",
	"USER"."USERNAME"        AS "USER",
	CASE WHEN
			"ANSWER_COMPANY"."ANSWER" IS NOT NULL 
		THEN "ANSWER_COMPANY"."ANSWER"
		ELSE "ANSWER_APPLICANT"."ANSWER"
	END AS "PETITION",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",
	CASE
		WHEN "ANSWER_STREET_BG"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_BG"."ANSWER"
		WHEN "ANSWER_STREET_NP"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_NP"."ANSWER"
	END AS "STREET",
	GET_STATE_NAME_BY_ID("INSTANCE"."INSTANCE_STATE_ID") AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"

	
FROM "INSTANCE"

JOIN "INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
)

JOIN "LOCATION" ON (
		"INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
)

LEFT JOIN "ANSWER"  "DOSSIERNR" ON (
		"DOSSIERNR"."INSTANCE_ID" = "INSTANCE"."INSTANCE_ID"
		AND
		"DOSSIERNR"."QUESTION_ID" = 6
		AND
		"DOSSIERNR"."CHAPTER_ID" = 2
		AND
		"DOSSIERNR"."ITEM" = 1
	)

LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)

LEFT JOIN 
	"ANSWER" "ANSWER_COMPANY" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_COMPANY"."INSTANCE_ID"
		AND
		"ANSWER_COMPANY"."QUESTION_ID" = 221
		AND
		"ANSWER_COMPANY"."CHAPTER_ID" = 1
		AND
		"ANSWER_COMPANY"."ITEM" = 1
	)

LEFT JOIN
	"ANSWER" "ANSWER_STREET_BG" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_BG"."INSTANCE_ID"
		AND
		"ANSWER_STREET_BG"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_BG"."CHAPTER_ID" = 21
		AND
		"ANSWER_STREET_BG"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET_NP" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_NP"."INSTANCE_ID"
		AND
		"ANSWER_STREET_NP"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_NP"."CHAPTER_ID" = 101
		AND
		"ANSWER_STREET_NP"."ITEM" = 1
	)

join "FORM" ON (
	"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)

JOIN "USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)
LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE"."INSTANCE_STATE_ID"
	)

JOIN
	"FORM_GROUP_FORM" ON (
	"FORM_GROUP_FORM"."FORM_ID" = "INSTANCE"."FORM_ID"
)

WHERE
	([ROLE_ID] = 3 AND "FORM_GROUP_FORM"."FORM_GROUP_ID" = 30)
	OR
	([ROLE_ID] = 1061 AND "FORM_GROUP_FORM"."FORM_GROUP_ID" = 141)
	OR
	([ROLE_ID] NOT IN (3, 1061))
'

WHERE RESOURCE_ID = 1;

-- DOSSIERLISTE BK

UPDATE R_LIST
SET QUERY  = '

select 
	"INSTANCE"."INSTANCE_ID" as "INSTANCE_ID",
	"DOSSIERNR"."ANSWER" as "DOSSIER_NR",
	"FORM"."NAME"        as "FORM",
	"USER"."USERNAME"        AS "USER",
	CASE WHEN
			"ANSWER_COMPANY"."ANSWER" IS NOT NULL 
		THEN "ANSWER_COMPANY"."ANSWER"
		ELSE "ANSWER_APPLICANT"."ANSWER"
	END AS "PETITION",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",
	CASE
		WHEN "ANSWER_STREET_BG"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_BG"."ANSWER"
		WHEN "ANSWER_STREET_NP"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_NP"."ANSWER"
	END AS "STREET",
	GET_STATE_NAME_BY_ID("INSTANCE"."INSTANCE_STATE_ID") AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"

	
FROM "INSTANCE"

JOIN "INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
)

JOIN "LOCATION" ON (
		"INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
)

LEFT JOIN "ANSWER"  "DOSSIERNR" ON (
		"DOSSIERNR"."INSTANCE_ID" = "INSTANCE"."INSTANCE_ID"
		AND
		"DOSSIERNR"."QUESTION_ID" = 6
		AND
		"DOSSIERNR"."CHAPTER_ID" = 2
		AND
		"DOSSIERNR"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)
LEFT JOIN 
	"ANSWER" "ANSWER_COMPANY" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_COMPANY"."INSTANCE_ID"
		AND
		"ANSWER_COMPANY"."QUESTION_ID" = 221
		AND
		"ANSWER_COMPANY"."CHAPTER_ID" = 1
		AND
		"ANSWER_COMPANY"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET_BG" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_BG"."INSTANCE_ID"
		AND
		"ANSWER_STREET_BG"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_BG"."CHAPTER_ID" = 21
		AND
		"ANSWER_STREET_BG"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET_NP" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_NP"."INSTANCE_ID"
		AND
		"ANSWER_STREET_NP"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_NP"."CHAPTER_ID" = 101
		AND
		"ANSWER_STREET_NP"."ITEM" = 1
	)

LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE"."INSTANCE_STATE_ID"
	)

join "FORM" ON (
	"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)

JOIN "USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)
JOIN
	"GROUP_LOCATION" ON (
	 	"GROUP_LOCATION"."GROUP_ID" = [GROUP_ID]
	)
WHERE
	"GROUP_LOCATION"."LOCATION_ID" = "INSTANCE_LOCATION"."LOCATION_ID"

ORDER BY "INSTANCE"."INSTANCE_ID" DESC
'
WHERE RESOURCE_ID = 82;


-- DOSSIERSUCHE ALG

UPDATE R_SEARCH
SET QUERY = '



select  distinct
	"INSTANCE"."INSTANCE_ID",
	"DOSSIERNR"."ANSWER" as "DOSSIER_NR",
	"FORM"."NAME"        as "FORM",
	"LOCATION"."NAME"    as "COMMUNITY",
	"USER"."USERNAME"        AS "USER",
	CASE WHEN
			"ANSWER_COMPANY"."ANSWER" IS NOT NULL 
		THEN "ANSWER_COMPANY"."ANSWER"
		ELSE "ANSWER_APPLICANT"."ANSWER"
	END AS "PETITION",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",
	CASE
		WHEN "ANSWER_STREET_BG"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_BG"."ANSWER"
		WHEN "ANSWER_STREET_NP"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_NP"."ANSWER"
	END AS "STREET",
	GET_STATE_NAME_BY_ID("INSTANCE"."INSTANCE_STATE_ID") AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"


	
FROM "INSTANCE"

JOIN "INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
)

JOIN "LOCATION" ON (
		"INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
)

LEFT JOIN "ANSWER"  "DOSSIERNR" ON (
		"DOSSIERNR"."INSTANCE_ID" = "INSTANCE"."INSTANCE_ID"
		AND
		"DOSSIERNR"."QUESTION_ID" = 6
		AND
		"DOSSIERNR"."CHAPTER_ID" = 2
		AND
		"DOSSIERNR"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_INTENT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_INTENT"."INSTANCE_ID"
		AND
		"ANSWER_INTENT"."QUESTION_ID" = 97
		AND
		"ANSWER_INTENT"."CHAPTER_ID" = 21
		AND
		"ANSWER_INTENT"."ITEM" = 1
	)
LEFT JOIN 
	"ANSWER" "ANSWER_COMPANY" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_COMPANY"."INSTANCE_ID"
		AND
		"ANSWER_COMPANY"."QUESTION_ID" = 221
		AND
		"ANSWER_COMPANY"."CHAPTER_ID" = 1
		AND
		"ANSWER_COMPANY"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET_BG" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_BG"."INSTANCE_ID"
		AND
		"ANSWER_STREET_BG"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_BG"."CHAPTER_ID" = 21
		AND
		"ANSWER_STREET_BG"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET_NP" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_NP"."INSTANCE_ID"
		AND
		"ANSWER_STREET_NP"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_NP"."CHAPTER_ID" = 101
		AND
		"ANSWER_STREET_NP"."ITEM" = 1
	)



join "FORM" ON (
	"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)

JOIN "USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)

LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE"."INSTANCE_STATE_ID"
	)

LEFT JOIN ANSWER  PARCEL_NR ON ( 
  "INSTANCE"."INSTANCE_ID" = "PARCEL_NR"."INSTANCE_ID" AND "PARCEL_NR".QUESTION_ID = 91 AND "PARCEL_NR".CHAPTER_ID = 21 AND "PARCEL_NR".ITEM = 1
  )

JOIN
	"FORM_GROUP_FORM" ON (
	"FORM_GROUP_FORM"."FORM_ID" = "INSTANCE"."FORM_ID"
)

WHERE
	(([ROLE_ID] = 3 AND "FORM_GROUP_FORM"."FORM_GROUP_ID" = 30)
	OR
	([ROLE_ID] = 1061 AND "FORM_GROUP_FORM"."FORM_GROUP_ID" = 141)
	OR
	([ROLE_ID] NOT IN (3, 1061)))

'
WHERE RESOURCE_ID = 42;


-- DOSSIERSUCHE BK

UPDATE R_SEARCH
SET QUERY = '



select distinct
	"INSTANCE"."INSTANCE_ID",
	"DOSSIERNR"."ANSWER" as "DOSSIER_NR",
	"FORM"."NAME"        as "FORM",
	"USER"."USERNAME"        AS "USER",
	CASE WHEN
			"ANSWER_COMPANY"."ANSWER" IS NOT NULL 
		THEN "ANSWER_COMPANY"."ANSWER"
		ELSE "ANSWER_APPLICANT"."ANSWER"
	END AS "PETITION",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",
	CASE
		WHEN "ANSWER_STREET_BG"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_BG"."ANSWER"
		WHEN "ANSWER_STREET_NP"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_NP"."ANSWER"
	END AS "STREET",
	GET_STATE_NAME_BY_ID("INSTANCE"."INSTANCE_STATE_ID") AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"
	
FROM "INSTANCE"

JOIN "INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
)

JOIN "LOCATION" ON (
		"INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
)

LEFT JOIN "ANSWER"  "DOSSIERNR" ON (
		"DOSSIERNR"."INSTANCE_ID" = "INSTANCE"."INSTANCE_ID"
		AND
		"DOSSIERNR"."QUESTION_ID" = 6
		AND
		"DOSSIERNR"."CHAPTER_ID" = 2
		AND
		"DOSSIERNR"."ITEM" = 1
	)

LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)
LEFT JOIN 
	"ANSWER" "ANSWER_COMPANY" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_COMPANY"."INSTANCE_ID"
		AND
		"ANSWER_COMPANY"."QUESTION_ID" = 221
		AND
		"ANSWER_COMPANY"."CHAPTER_ID" = 1
		AND
		"ANSWER_COMPANY"."ITEM" = 1
	)

LEFT JOIN
	"ANSWER" "ANSWER_INTENT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_INTENT"."INSTANCE_ID"
		AND
		"ANSWER_INTENT"."QUESTION_ID" = 97
		AND
		"ANSWER_INTENT"."CHAPTER_ID" = 21
		AND
		"ANSWER_INTENT"."ITEM" = 1
	)

LEFT JOIN
	"ANSWER" "ANSWER_STREET_BG" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_BG"."INSTANCE_ID"
		AND
		"ANSWER_STREET_BG"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_BG"."CHAPTER_ID" = 21
		AND
		"ANSWER_STREET_BG"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET_NP" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_NP"."INSTANCE_ID"
		AND
		"ANSWER_STREET_NP"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_NP"."CHAPTER_ID" = 101
		AND
		"ANSWER_STREET_NP"."ITEM" = 1
	)

LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE"."INSTANCE_STATE_ID"
	)


join "FORM" ON (
	"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)

JOIN "USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)

LEFT JOIN ANSWER  PARCEL_NR ON ( 
  "INSTANCE"."INSTANCE_ID" = "PARCEL_NR"."INSTANCE_ID" AND "PARCEL_NR".QUESTION_ID = 91 AND "PARCEL_NR".CHAPTER_ID =21 AND "PARCEL_NR".ITEM = 1
  )
JOIN
	"GROUP_LOCATION" ON (
	 	"GROUP_LOCATION"."GROUP_ID" = [GROUP_ID]
	)
WHERE
	"GROUP_LOCATION"."LOCATION_ID" = "INSTANCE_LOCATION"."LOCATION_ID"


'
WHERE RESOURCE_ID = 102;


-- PENDENZENLISTE END GEMEINDE 

UPDATE R_LIST
SET QUERY =  '



SELECT
	"INSTANCE"."INSTANCE_ID"   AS "INSTANCE_ID",
	"ANSWER_DOK_NR"."ANSWER"   AS "DOSSIER_NR",
	"FORM"."NAME"              AS "FORM",
	"LOCATION"."NAME"          AS "COMMUNITY",
	"USER"."USERNAME"          AS "USER",
	CASE WHEN
			"ANSWER_COMPANY"."ANSWER" IS NOT NULL 
		THEN "ANSWER_COMPANY"."ANSWER"
		ELSE "ANSWER_APPLICANT"."ANSWER"
	END AS "PETITION",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",
	CASE
		WHEN "ANSWER_STREET_BG"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_BG"."ANSWER"
		WHEN "ANSWER_STREET_NP"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_NP"."ANSWER"
	END AS "STREET",
	"INSTANCE_STATE"."NAME"    AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"
FROM
	"INSTANCE"
JOIN
	"INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
	)
JOIN 
	"LOCATION" ON (
	 "INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
	)
JOIN
	FORM ON (
		"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)
JOIN
	"USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)
JOIN
	"ANSWER" "ANSWER_DOK_NR" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_DOK_NR"."INSTANCE_ID"
		AND
		"ANSWER_DOK_NR"."QUESTION_ID" = 6
		AND
		"ANSWER_DOK_NR"."CHAPTER_ID" = 2
		AND
		"ANSWER_DOK_NR"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)
LEFT JOIN 
	"ANSWER" "ANSWER_COMPANY" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_COMPANY"."INSTANCE_ID"
		AND
		"ANSWER_COMPANY"."QUESTION_ID" = 221
		AND
		"ANSWER_COMPANY"."CHAPTER_ID" = 1
		AND
		"ANSWER_COMPANY"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET_BG" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_BG"."INSTANCE_ID"
		AND
		"ANSWER_STREET_BG"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_BG"."CHAPTER_ID" = 21
		AND
		"ANSWER_STREET_BG"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET_NP" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_NP"."INSTANCE_ID"
		AND
		"ANSWER_STREET_NP"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_NP"."CHAPTER_ID" = 101
		AND
		"ANSWER_STREET_NP"."ITEM" = 1
	)
JOIN 
	"INSTANCE_STATE" ON (
	"INSTANCE_STATE"."NAME" = ''done''
)
LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE"."INSTANCE_STATE_ID"
	)


JOIN
	"GROUP_LOCATION" ON (
	 	"GROUP_LOCATION"."GROUP_ID" = [GROUP_ID]
	)
WHERE
	"INSTANCE"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	AND
	"GROUP_LOCATION"."LOCATION_ID" = "INSTANCE_LOCATION"."LOCATION_ID"

'
WHERE RESOURCE_ID = 63;


-- PENDENZENLISTE START GEMEINDE

UPDATE R_LIST
SET QUERY = '


SELECT
	"INSTANCE"."INSTANCE_ID"   AS "INSTANCE_ID",
	"ANSWER_DOK_NR"."ANSWER"   AS "DOSSIER_NR",
	"FORM"."NAME"              AS "FORM",
	"LOCATION"."NAME"          AS "COMMUNITY",
	"USER"."USERNAME"          AS "USER",
	CASE WHEN
			"ANSWER_COMPANY"."ANSWER" IS NOT NULL 
		THEN "ANSWER_COMPANY"."ANSWER"
		ELSE "ANSWER_APPLICANT"."ANSWER"
	END AS "PETITION",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",
	CASE
		WHEN "ANSWER_STREET_BG"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_BG"."ANSWER"
		WHEN "ANSWER_STREET_NP"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_NP"."ANSWER"
	END AS "STREET",
	"INSTANCE_STATE"."NAME"    AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"
FROM
	"INSTANCE"
JOIN
	"INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
	)
JOIN 
	"LOCATION" ON (
	 "INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
	)
JOIN
	FORM ON (
		"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)
JOIN
	"USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)
JOIN
	"ANSWER" "ANSWER_DOK_NR" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_DOK_NR"."INSTANCE_ID"
		AND
		"ANSWER_DOK_NR"."QUESTION_ID" = 6
		AND
		"ANSWER_DOK_NR"."CHAPTER_ID" = 2
		AND
		"ANSWER_DOK_NR"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)
LEFT JOIN 
	"ANSWER" "ANSWER_COMPANY" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_COMPANY"."INSTANCE_ID"
		AND
		"ANSWER_COMPANY"."QUESTION_ID" = 221
		AND
		"ANSWER_COMPANY"."CHAPTER_ID" = 1
		AND
		"ANSWER_COMPANY"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET_BG" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_BG"."INSTANCE_ID"
		AND
		"ANSWER_STREET_BG"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_BG"."CHAPTER_ID" = 21
		AND
		"ANSWER_STREET_BG"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET_NP" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_NP"."INSTANCE_ID"
		AND
		"ANSWER_STREET_NP"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_NP"."CHAPTER_ID" = 101
		AND
		"ANSWER_STREET_NP"."ITEM" = 1
	)
JOIN 
	"INSTANCE_STATE" ON (
	"INSTANCE_STATE"."NAME" = ''comm''
)
LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	)
JOIN
	"GROUP_LOCATION" ON (
	 	"GROUP_LOCATION"."GROUP_ID" = [GROUP_ID]
	)
WHERE
	"INSTANCE"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	AND
	"GROUP_LOCATION"."LOCATION_ID" = "INSTANCE_LOCATION"."LOCATION_ID"

'

WHERE RESOURCE_ID = 23 ;

-- PEND START KOORD NP


UPDATE R_LIST
SET QUERY = '


SELECT
	"INSTANCE"."INSTANCE_ID"   AS "INSTANCE_ID",
	"ANSWER_DOK_NR"."ANSWER"   AS "DOSSIER_NR",
	"FORM"."NAME"              AS "FORM",
	"LOCATION"."NAME"          AS "COMMUNITY",
	"USER"."USERNAME"          AS "USER",
	CASE WHEN
			"ANSWER_COMPANY"."ANSWER" IS NOT NULL 
		THEN "ANSWER_COMPANY"."ANSWER"
		ELSE "ANSWER_APPLICANT"."ANSWER"
	END AS "PETITION",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",
	"ANSWER_STREET"."ANSWER"     AS "STREET",
	"INSTANCE_STATE"."NAME"      AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"
FROM
	"INSTANCE"
JOIN
	"INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
	)
JOIN 
	"LOCATION" ON (
	 "INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
	)
JOIN
	FORM ON (
		"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)
JOIN
	"USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)
JOIN
	"ANSWER" "ANSWER_DOK_NR" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_DOK_NR"."INSTANCE_ID"
		AND
		"ANSWER_DOK_NR"."QUESTION_ID" = 6
		AND
		"ANSWER_DOK_NR"."CHAPTER_ID" = 2
		AND
		"ANSWER_DOK_NR"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)
LEFT JOIN 
	"ANSWER" "ANSWER_COMPANY" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_COMPANY"."INSTANCE_ID"
		AND
		"ANSWER_COMPANY"."QUESTION_ID" = 221
		AND
		"ANSWER_COMPANY"."CHAPTER_ID" = 1
		AND
		"ANSWER_COMPANY"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET"."INSTANCE_ID"
		AND
		"ANSWER_STREET"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET"."CHAPTER_ID" = 101
		AND
		"ANSWER_STREET"."ITEM" = 1
	)
JOIN 
	"INSTANCE_STATE" ON (
	"INSTANCE_STATE"."NAME" = ''ext''
)
LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	)
JOIN
	"FORM_GROUP_FORM" ON (
	"FORM_GROUP_FORM"."FORM_ID" = "INSTANCE"."FORM_ID"
)
WHERE
	"INSTANCE"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	AND
	"FORM_GROUP_FORM"."FORM_GROUP_ID" = 141

'
WHERE RESOURCE_ID = 162;

-- PENDENZENLISTE AMT

UPDATE R_LIST
SET QUERY = '


SELECT
	"INSTANCE"."INSTANCE_ID",
	"ANSWER_DOK_NR"."ANSWER"   AS "DOSSIER_NR",
	"FORM"."NAME"              AS "FORM",
	TO_CHAR("ACTIVATION"."DEADLINE_DATE", ''DD.MM.YYYY'') AS "DEADLINE",
	"LOCATION"."NAME"          AS "COMMUNITY",
	"ANSWER_APPLICANT"."ANSWER" AS "APPLICANT",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",
	CASE
		WHEN "ANSWER_STREET_BG"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_BG"."ANSWER"
		WHEN "ANSWER_STREET_NP"."ANSWER" IS NOT NULL THEN "ANSWER_STREET_NP"."ANSWER"
	END AS "STREET",
	"ACTIVATION"."REASON"      AS "REASON",
	"INSTANCE_STATE"."NAME"    AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"
FROM
	"INSTANCE"
JOIN
	"INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
	)

JOIN
	"LOCATION" ON (
	 "INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
	)

JOIN
	FORM ON (
		"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)

JOIN
	"ANSWER" "ANSWER_DOK_NR" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_DOK_NR"."INSTANCE_ID"
		AND
		"ANSWER_DOK_NR"."QUESTION_ID" = 6
		AND
		"ANSWER_DOK_NR"."CHAPTER_ID" = 2
		AND
		"ANSWER_DOK_NR"."ITEM" = 1
	)

LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)

LEFT JOIN
	"ANSWER" "ANSWER_STREET_BG" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_BG"."INSTANCE_ID"
		AND
		"ANSWER_STREET_BG"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_BG"."CHAPTER_ID" = 21
		AND
		"ANSWER_STREET_BG"."ITEM" = 1
	)

LEFT JOIN
	"ANSWER" "ANSWER_STREET_NP" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET_NP"."INSTANCE_ID"
		AND
		"ANSWER_STREET_NP"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET_NP"."CHAPTER_ID" = 101
		AND
		"ANSWER_STREET_NP"."ITEM" = 1
	)

JOIN
	"INSTANCE_STATE" ON (
	"INSTANCE_STATE"."NAME" = ''circ''
)

LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	)

JOIN
	"CIRCULATION" ON (
		"CIRCULATION"."INSTANCE_ID" = "INSTANCE"."INSTANCE_ID"
	)

JOIN
	"ACTIVATION" ON (
		"ACTIVATION"."CIRCULATION_ID" = "CIRCULATION"."CIRCULATION_ID"
		AND
		"ACTIVATION"."SERVICE_ID" = [SERVICE_ID]
	)

WHERE
	"INSTANCE"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	AND
	"ACTIVATION"."CIRCULATION_STATE_ID" = 1

'
WHERE RESOURCE_ID = 41;


-- PENDENZENLISTE ENDE KOORD NP


UPDATE R_LIST
SET QUERY = '


SELECT
	"INSTANCE"."INSTANCE_ID"   AS "INSTANCE_ID",
	"ANSWER_DOK_NR"."ANSWER"   AS "DOSSIER_NR",
	"FORM"."NAME"              AS "FORM",
	"LOCATION"."NAME"          AS "COMMUNITY",
	"USER"."USERNAME"          AS "USER",
	CASE WHEN
			"ANSWER_COMPANY"."ANSWER" IS NOT NULL 
		THEN "ANSWER_COMPANY"."ANSWER"
		ELSE "ANSWER_APPLICANT"."ANSWER"
	END AS "PETITION",
	(SELECT LISTAGG("NAME", '', '') WITHIN GROUP (ORDER BY "NAME") 
		FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",
	"ANSWER_STREET"."ANSWER"     AS "STREET",
	"INSTANCE_STATE"."NAME"    AS "STATE",
	"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"    AS "STATE_DESCRIPTION"
FROM
	"INSTANCE"
JOIN
	"INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
	)
JOIN 
	"LOCATION" ON (
	 "INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
	)
JOIN
	FORM ON (
		"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)
JOIN
	"USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)
JOIN
	"ANSWER" "ANSWER_DOK_NR" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_DOK_NR"."INSTANCE_ID"
		AND
		"ANSWER_DOK_NR"."QUESTION_ID" = 6
		AND
		"ANSWER_DOK_NR"."CHAPTER_ID" = 2
		AND
		"ANSWER_DOK_NR"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_APPLICANT" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_APPLICANT"."INSTANCE_ID"
		AND
		"ANSWER_APPLICANT"."QUESTION_ID" = 23
		AND
		"ANSWER_APPLICANT"."CHAPTER_ID" = 1
		AND
		"ANSWER_APPLICANT"."ITEM" = 1
	)
LEFT JOIN 
	"ANSWER" "ANSWER_COMPANY" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_COMPANY"."INSTANCE_ID"
		AND
		"ANSWER_COMPANY"."QUESTION_ID" = 221
		AND
		"ANSWER_COMPANY"."CHAPTER_ID" = 1
		AND
		"ANSWER_COMPANY"."ITEM" = 1
	)
LEFT JOIN
	"ANSWER" "ANSWER_STREET" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER_STREET"."INSTANCE_ID"
		AND
		"ANSWER_STREET"."QUESTION_ID" = 93
		AND
		"ANSWER_STREET"."CHAPTER_ID" = 101
		AND
		"ANSWER_STREET"."ITEM" = 1
	)
JOIN 
	"INSTANCE_STATE" ON (
	"INSTANCE_STATE"."NAME" = ''redac''
)
LEFT JOIN
	"INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE"."INSTANCE_STATE_ID"
	)
JOIN
	"FORM_GROUP_FORM" ON (
	"FORM_GROUP_FORM"."FORM_ID" = "INSTANCE"."FORM_ID"
)
WHERE
	"INSTANCE"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	AND
	"FORM_GROUP_FORM"."FORM_GROUP_ID" = 141

'
WHERE RESOURCE_ID = 182;
