ALTER TABLE DOCGEN_ACTIVATION_DOCKET
DROP CONSTRAINT ACTIVATION_DOCKET_FK2;

ALTER TABLE DOCGEN_ACTIVATION_DOCKET
ADD CONSTRAINT ACTIVATOIN_DOCKET_FK2
FOREIGN KEY (ACTIVATION_ID)
REFERENCES ACTIVATION(ACTIVATION_ID)
ON DELETE CASCADE;


