
CREATE OR REPLACE VIEW "VIEW_QRY_APPLICANT_ANSWER" AS

	SELECT
		"INSTANCE_ID",
		"ANSWER"
	FROM
		"ANSWER"

	WHERE
		"ANSWER"."QUESTION_ID" = 23
		AND
		"ANSWER"."CHAPTER_ID" = 1
		AND
		"ANSWER"."ITEM" = 1
	;

CREATE OR REPLACE VIEW "VIEW_QRY_COMPANY_ANSWER" AS

	SELECT
		"INSTANCE_ID",
		"ANSWER"
	FROM
		"ANSWER"
	WHERE
		"ANSWER"."QUESTION_ID" = 221
		AND
		"ANSWER"."CHAPTER_ID" = 1
		AND
		"ANSWER"."ITEM" = 1
;

CREATE OR REPLACE VIEW "VIEW_QRY_APPLICANT_ASSEMBLED" AS

	SELECT
		DECODE(
			"CMPNY_ANSWER"."ANSWER", NULL, "APPL_ANSWER"."ANSWER",
			                               "CMPNY_ANSWER"."ANSWER"
		) "APPLICANT",
		DECODE(
			"CMPNY_ANSWER"."INSTANCE_ID", NULL, "APPL_ANSWER"."INSTANCE_ID",
			                                    "CMPNY_ANSWER"."INSTANCE_ID"
		) "INSTANCE_ID"

	FROM
		"VIEW_QRY_APPLICANT_ANSWER" "APPL_ANSWER"

	FULL OUTER JOIN "VIEW_QRY_COMPANY_ANSWER" "CMPNY_ANSWER"  ON (
		"APPL_ANSWER"."INSTANCE_ID" = "CMPNY_ANSWER"."INSTANCE_ID"
	)
;

-- MATERIALIZED WOULD BE NICE
CREATE OR REPLACE VIEW "VIEW_QRY_INSTANCE_LOCATION" AS
	SELECT
		"LOCATION"."NAME",
		"LOCATION"."LOCATION_ID",
		"INSTANCE_ID"
	FROM
		"LOCATION"
	JOIN
		"INSTANCE_LOCATION" ON (
		"LOCATION"."LOCATION_ID" = "INSTANCE_LOCATION"."LOCATION_ID"
	)

;

CREATE OR REPLACE VIEW "VIEW_QRY_DOC_NR" AS
	SELECT
		"ANSWER",
		"INSTANCE_ID"
	FROM
		"ANSWER"
	WHERE 
		"ANSWER"."QUESTION_ID" = 6
		AND
		"ANSWER"."CHAPTER_ID" = 2
		AND
		"ANSWER"."ITEM" = 1
;

CREATE OR REPLACE VIEW "VIEW_QRY_STATE" AS
	SELECT
		"INSTANCE_STATE"."INSTANCE_STATE_ID",
		"INSTANCE_STATE"."NAME",
		"INSTANCE_STATE_DESCRIPTION"."DESCRIPTION"
	FROM
		"INSTANCE_STATE"
	JOIN "INSTANCE_STATE_DESCRIPTION" ON (
		"INSTANCE_STATE_DESCRIPTION"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
	)
;

CREATE OR REPLACE VIEW "VIEW_QRY_STREET_ANSWER" AS
	SELECT
		"INSTANCE_ID",
		"ANSWER"
	FROM
		"ANSWER"
	WHERE
		"ANSWER"."QUESTION_ID" = 93
		AND
		"ANSWER"."CHAPTER_ID" = 21
		AND
		"ANSWER"."ITEM" = 1
;

CREATE OR REPLACE VIEW "VIEW_LIST_QUERY" AS 
	SELECT
		"INSTANCE"."INSTANCE_ID"                                            AS "INSTANCE_ID",
		"VIEW_QRY_DOC_NR"."ANSWER"                                          AS "DOSSIER_NR",
		"FORM"."NAME"                                                       AS "FORM",
		"VIEW_QRY_INSTANCE_LOCATION"."NAME"                                 AS "COMMUNITY",
		"USER"."USERNAME"                                                   AS "USER",
		"VIEW_QRY_APPLICANT_ASSEMBLED"."APPLICANT"                          AS "APPLICANT",
		(SELECT LISTAGG("NAME", ', ') WITHIN GROUP (ORDER BY "NAME")
			FROM INTENTIONS WHERE "INSTANCE_ID" = "INSTANCE"."INSTANCE_ID") AS "INTENT",

		"VIEW_QRY_STREET_ANSWER"."ANSWER"                                   AS "STREET",
		"VIEW_QRY_STATE"."NAME"                                             AS "STATE",
		"VIEW_QRY_STATE"."INSTANCE_STATE_ID"                                AS "INSTANCE_STATE_ID",
		"VIEW_QRY_STATE"."DESCRIPTION"                                      AS "STATE_DESCRIPTION",
		"VIEW_QRY_INSTANCE_LOCATION"."LOCATION_ID"                          AS "LOCATION_ID",
		"FORM"."FORM_ID"                                                    AS "FORM_ID"
	FROM
		"INSTANCE"

	JOIN "VIEW_QRY_INSTANCE_LOCATION" ON (
		"VIEW_QRY_INSTANCE_LOCATION"."INSTANCE_ID" = "INSTANCE"."INSTANCE_ID"
	)

	JOIN
		FORM ON (
			"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
	)

	JOIN
		"USER" ON (
			"INSTANCE"."USER_ID" = "USER"."USER_ID"
	)

	JOIN "VIEW_QRY_DOC_NR" ON (
		"INSTANCE"."INSTANCE_ID" = "VIEW_QRY_DOC_NR"."INSTANCE_ID"
	)

	LEFT JOIN "VIEW_QRY_APPLICANT_ASSEMBLED" ON (
		"VIEW_QRY_APPLICANT_ASSEMBLED"."INSTANCE_ID" = "INSTANCE"."INSTANCE_ID"
	)

	LEFT JOIN "VIEW_QRY_STREET_ANSWER" ON (
		"VIEW_QRY_STREET_ANSWER"."INSTANCE_ID" = "INSTANCE"."INSTANCE_ID"
	)

	JOIN "VIEW_QRY_STATE" ON (
		"INSTANCE"."INSTANCE_STATE_ID" = "VIEW_QRY_STATE"."INSTANCE_STATE_ID"
	)

;
