SELECT
	"INSTANCE"."INSTANCE_ID" AS "INSTANCE_ID",
	"ANSWER"."ANSWER"        AS "DOSSIER_NR",
	"FORM"."NAME"            AS "FORM",
	"LOCATION"."NAME"        AS "COMMUNITY",
	"USER"."USERNAME"        AS "USER"

FROM
	"INSTANCE"
JOIN
	"INSTANCE_LOCATION" ON (
		"INSTANCE"."INSTANCE_ID" = "INSTANCE_LOCATION"."INSTANCE_ID"
	)

JOIN 
	"LOCATION" ON (
	 "INSTANCE_LOCATION"."LOCATION_ID" = "LOCATION"."LOCATION_ID"
	)

JOIN
	FORM ON (
		"INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
)

JOIN
	"USER" ON (
		"INSTANCE"."USER_ID" = "USER"."USER_ID"
)

JOIN
	"ANSWER" ON (
		"INSTANCE"."INSTANCE_ID" = "ANSWER"."INSTANCE_ID"
		AND
		"ANSWER"."QUESTION_ID" = 6
		AND
		"ANSWER"."CHAPTER_ID" = 2
		AND
		"ANSWER"."ITEM" = 1
	)
JOIN 
	"INSTANCE_STATE" ON (
	"INSTANCE_STATE"."NAME" = 'ext'
)
WHERE
	"INSTANCE"."INSTANCE_STATE_ID" = "INSTANCE_STATE"."INSTANCE_STATE_ID"
