<?php

require_once(APPLICATION_PATH . '/../library/PHPExcel/Classes/PHPExcel.php');
$objPHPExcel = new PHPExcel();
$objPHPExcel->getProperties()->setCreator('CAMAC');
$workSheet = $objPHPExcel->setActiveSheetIndex(0);
$headerColumnIndex = 0;
foreach ($this->headerColumns as $column => $order) {
	$workSheet->setCellValueByColumnAndRow($headerColumnIndex, 1, $column);
	$workSheet->getColumnDimensionByColumn($headerColumnIndex)->setAutoSize(true);
	$workSheet->setAutoFilterByColumnAndRow($headerColumnIndex, 1);
	$workSheet->getCellByColumnAndRow($headerColumnIndex, 1)->getStyle()->getFont()->setBold(true);
	$headerColumnIndex++;
}
foreach ($this->paginator as $rowIndex => $row) {
	foreach ($this->columns as $columnIndex => $column) {
		$workSheet->setCellValueByColumnAndRow($columnIndex, $rowIndex + 2, $row[$column]);
		$workSheet->getColumnDimensionByColumn($columnIndex)->setAutoSize(true);
	}
}
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
$objWriter->save('php://output');
