
<table id="issue-list" <?php if ($this->isGuest) { echo 'class="--double-stripe"'; } ?>>
	<thead>
		<tr>
			<?php $i = 0; ?>
			<?php foreach ($this->headerColumns as $column) : ?>
				<?php if (
					$column != Custom_UriConstants::COLUMN_STATE_DESCRIPTION_HEADER &&
					$column != Custom_UriConstants::COLUMN_KOOR_SHORT_HEADER &&
					($column != Custom_UriConstants::COLUMN_INTENT_HEADER || !$this->isGuest)
				) : ?>
					<?php
					$nextOrder = ($column == $this->orderColumn ? ($this->order == 'ASC' ? 'DESC' : 'ASC') : 'ASC')
					?>
					<th class="sort sort-<?php echo $nextOrder; ?>"
						<?php if ($column == Custom_UriConstants::COLUMN_STATE_HEADER) { ?>colspan="2"<?php } ?>>
						<a href="<?php echo $this->url(array('column' => $i++, 'order' => $nextOrder)) ?>">
							<?php echo $column ?>
						</a>
					</th>
				<?php endif; ?>
			<?php endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->paginator as $row) : ?>
			<?php
			// column color coding for circulation lists and services
			$rowClass = '';

			if ($this->isCirculation) {
				// This makes many DB queries, might be worth exploring if this can also be JOINed.
				$rowClass = $this->getCircListRowClass($row['INSTANCE_ID']);
			}
			else if ($this->isService) {
				// Calculate whether the deadline is past due
				// and check if the dossier is in NFD
				$deadlineDate = $row[Custom_UriConstants::COLUMN_DEADLINE];
				$deadline     = new Zend_Date($deadlineDate, 'dd.MM.YYYY');

				if ($row['CIRC_STATE'] == 'NFD') {
					$rowClass = "nfd_row";
				}
				else if ($deadline->isEarlier(new Zend_Date())) {
					$rowClass = "deadline_expired";
				}
			}
			?>
			<tr class="<?php echo $rowClass ?> clickable-row" data-href="<?php echo $this->url(array('controller' => 'index', 'action' => 'redirect-to-instance-resource', 'instance-id' => $row['INSTANCE_ID']), null, true) ?>">
				<?php $i = 0; ?>
				<?php foreach ($this->columns as $column) : ?>
					<?php if (
						$column != Custom_UriConstants::COLUMN_STATE_DESCRIPTION &&
						$column != Custom_UriConstants::COLUMN_KOOR_SHORT &&
						($column != Custom_UriConstants::COLUMN_INTENT || !$this->isGuest)
					) : ?>
					<td class="column-<?php echo $column; ?>">
						<?php if ($column == Custom_UriConstants::COLUMN_KOOR): ?>
							<?php
								$koorName  = $row[Custom_UriConstants::COLUMN_KOOR];
								$hasShortKoorName = isset($row[Custom_UriConstants::COLUMN_KOOR_SHORT]);
							?>
							<?php if ($hasShortKoorName) :?>
								<?php $koorShortName = $hasShortKoorName ? $row[Custom_UriConstants::COLUMN_KOOR_SHORT] : $koorName; ?>
								<span area-hidden="true" class="tooltip" title="<?php echo $koorName ?>"><?php echo $koorShortName; ?></span>
							<?php else: ?>
								<?php echo $koorName ?>
							<?php endif; ?>
						<?php else : ?>
							<?php echo $row[$column] ?>
						<?php endif; ?>
					</td>
					<?php if ($column == Custom_UriConstants::COLUMN_STATE) : ?>
					<td class="column-<?php echo $column ?>">
						<?php
							$cond = isset($row[Custom_UriConstants::COLUMN_STATE_DESCRIPTION]);
							$title =  $cond ? $row[Custom_UriConstants::COLUMN_STATE_DESCRIPTION] : "";
						?>
						<span area-hidden="true" class="icon icon-page-edit tooltip" title="<?php echo $title ?>"></span>
					</td>
					<?php endif; ?>
					<?php $i++ ?>
					<?php endif; ?>
				<?php endforeach; ?>
			</tr>
			<?php if ($this->isGuest) : ?>
			<tr><td colspan="5">Vorhaben: <?= $row['INTENT'] ?></td></tr>
			<?php endif; ?>
		<?php endforeach; ?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', '/partial/index-pagination.phtml'); ?>
<?php if (!$this->isGuest) : ?>
	<p>
		<a href="<?php echo $this->url(array('format' => 'xls')) ?>">Excel</a>
	</p>
<?php endif; ?>
