# Generated by Django 2.2.17 on 2021-01-20 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("file", "0001_initial")]

    operations = [
        migrations.AlterUniqueTogether(name="afilesavepdft", unique_together=None),
        migrations.AlterUniqueTogether(
            name="filecomplementstatet", unique_together=None
        ),
        migrations.AlterUniqueTogether(
            name="filecontentcategoryt", unique_together=None
        ),
        migrations.AlterUniqueTogether(name="filecontentfile", unique_together=None),
        migrations.AlterUniqueTogether(name="filecontentform", unique_together=None),
        migrations.AlterUniqueTogether(
            name="filecontentmimetype", unique_together=None
        ),
        migrations.AlterUniqueTogether(name="filecontentrequest", unique_together=None),
        migrations.AlterUniqueTogether(name="filecontentt", unique_together=None),
        migrations.AlterUniqueTogether(name="fileformatt", unique_together=None),
        migrations.AlterUniqueTogether(
            name="filevalidationtypet", unique_together=None
        ),
        migrations.AlterUniqueTogether(name="filevalidtypefile", unique_together=None),
        migrations.RemoveField(model_name="afilecheckcontent", name="action"),
        migrations.RemoveField(model_name="afilecheckcontent", name="page_form_group"),
        migrations.RemoveField(model_name="afilesavepdf", name="action"),
        migrations.RemoveField(model_name="afilesavepdf", name="file_content"),
        migrations.RemoveField(model_name="afilesavepdf", name="file_content_category"),
        migrations.RemoveField(model_name="afilesavepdf", name="page_form_group"),
        migrations.RemoveField(model_name="afilesavepdfcontentpage", name="action"),
        migrations.RemoveField(
            model_name="afilesavepdfcontentpage", name="file_content"
        ),
        migrations.RemoveField(model_name="afilesavepdfcontentpage", name="page"),
        migrations.RemoveField(model_name="afilesavepdft", name="action"),
        migrations.RemoveField(model_name="afilesdownload", name="action"),
        migrations.RemoveField(model_name="afilesdownloadcontent", name="action"),
        migrations.RemoveField(model_name="afilesdownloadcontent", name="file_content"),
        migrations.RemoveField(
            model_name="afiletransition", name="a_filetransition_date"
        ),
        migrations.RemoveField(model_name="afiletransition", name="current_state"),
        migrations.RemoveField(model_name="afiletransition", name="next_state"),
        migrations.RemoveField(model_name="file", name="file_complement_req"),
        migrations.RemoveField(model_name="file", name="file_format"),
        migrations.RemoveField(model_name="file", name="group"),
        migrations.RemoveField(model_name="file", name="instance"),
        migrations.RemoveField(model_name="file", name="instance_state"),
        migrations.RemoveField(model_name="file", name="last_version_file"),
        migrations.RemoveField(model_name="file", name="user"),
        migrations.RemoveField(
            model_name="filecomplementreq", name="file_complement_state"
        ),
        migrations.RemoveField(model_name="filecomplementreq", name="group"),
        migrations.RemoveField(model_name="filecomplementreq", name="instance"),
        migrations.RemoveField(model_name="filecomplementreq", name="user"),
        migrations.RemoveField(
            model_name="filecomplementstatet", name="file_complement_state"
        ),
        migrations.RemoveField(model_name="filecontent", name="file_content_category"),
        migrations.RemoveField(
            model_name="filecontentcategoryt", name="file_content_category"
        ),
        migrations.RemoveField(model_name="filecontentfile", name="file"),
        migrations.RemoveField(model_name="filecontentfile", name="file_content"),
        migrations.RemoveField(model_name="filecontentform", name="file_content"),
        migrations.RemoveField(model_name="filecontentform", name="form"),
        migrations.RemoveField(model_name="filecontentmimetype", name="file_content"),
        migrations.RemoveField(model_name="filecontentmimetype", name="file_mime_type"),
        migrations.RemoveField(
            model_name="filecontentrequest", name="file_complement_req"
        ),
        migrations.RemoveField(model_name="filecontentrequest", name="file_content"),
        migrations.RemoveField(model_name="filecontentrequired", name="chapter"),
        migrations.RemoveField(model_name="filecontentrequired", name="file_content"),
        migrations.RemoveField(model_name="filecontentrequired", name="form"),
        migrations.RemoveField(model_name="filecontentrequired", name="question"),
        migrations.RemoveField(model_name="filecontentt", name="file_content"),
        migrations.RemoveField(model_name="fileformatt", name="file_format"),
        migrations.RemoveField(
            model_name="filevalidationtypet", name="file_validation_type"
        ),
        migrations.RemoveField(model_name="filevalidtypefile", name="file"),
        migrations.RemoveField(
            model_name="filevalidtypefile", name="file_validation_type"
        ),
        migrations.RemoveField(
            model_name="irfilecomplementanswer", name="instance_resource"
        ),
        migrations.RemoveField(
            model_name="irfilecomplementanswer", name="ir_file_access_type"
        ),
        migrations.RemoveField(
            model_name="irfilecomplementreqcc", name="file_content_category"
        ),
        migrations.RemoveField(
            model_name="irfilecomplementreqcc", name="instance_resource"
        ),
        migrations.RemoveField(
            model_name="irfilecomplementrequest", name="instance_resource"
        ),
        migrations.RemoveField(
            model_name="irfilecomplementrequest", name="ir_file_access_type"
        ),
        migrations.RemoveField(model_name="irfilelist", name="file_validation_type"),
        migrations.RemoveField(model_name="irfilelist", name="ir_file_access_type"),
        migrations.RemoveField(model_name="irfileupload", name="instance_resource"),
        migrations.RemoveField(model_name="irfileupload", name="ir_file_access_type"),
        migrations.RemoveField(model_name="irfileupload", name="page_form_group"),
        migrations.RemoveField(
            model_name="irfileuploadcc", name="file_content_category"
        ),
        migrations.RemoveField(model_name="irfileuploadcc", name="instance_resource"),
        migrations.RemoveField(model_name="irfilevalidation", name="instance_resource"),
        migrations.RemoveField(
            model_name="irfilevalidation", name="ir_file_access_type"
        ),
        migrations.RemoveField(
            model_name="irfilevalidation", name="read_file_validation_type"
        ),
        migrations.RemoveField(
            model_name="irfilevalidation", name="write_file_validation_type"
        ),
        migrations.DeleteModel(name="AFiletransitionDate"),
        migrations.DeleteModel(name="FileComplementReqLog"),
        migrations.DeleteModel(name="FileComplementState"),
        migrations.DeleteModel(name="FileContentCategory"),
        migrations.DeleteModel(name="FileContentFileLog"),
        migrations.DeleteModel(name="FileContentRequestLog"),
        migrations.DeleteModel(name="FileFormat"),
        migrations.DeleteModel(name="FileLog"),
        migrations.DeleteModel(name="FileMimeType"),
        migrations.DeleteModel(name="FileValidationType"),
        migrations.DeleteModel(name="FileValidTypeFileLog"),
        migrations.DeleteModel(name="IrFileAccessType"),
        migrations.DeleteModel(name="AFilecheckcontent"),
        migrations.DeleteModel(name="AFilesavepdf"),
        migrations.DeleteModel(name="AFilesavepdfContentpage"),
        migrations.DeleteModel(name="AFilesavepdfT"),
        migrations.DeleteModel(name="AFilesdownload"),
        migrations.DeleteModel(name="AFilesdownloadContent"),
        migrations.DeleteModel(name="AFiletransition"),
        migrations.DeleteModel(name="File"),
        migrations.DeleteModel(name="FileComplementReq"),
        migrations.DeleteModel(name="FileComplementStateT"),
        migrations.DeleteModel(name="FileContent"),
        migrations.DeleteModel(name="FileContentCategoryT"),
        migrations.DeleteModel(name="FileContentFile"),
        migrations.DeleteModel(name="FileContentForm"),
        migrations.DeleteModel(name="FileContentMimeType"),
        migrations.DeleteModel(name="FileContentRequest"),
        migrations.DeleteModel(name="FileContentRequired"),
        migrations.DeleteModel(name="FileContentT"),
        migrations.DeleteModel(name="FileFormatT"),
        migrations.DeleteModel(name="FileValidationTypeT"),
        migrations.DeleteModel(name="FileValidTypeFile"),
        migrations.DeleteModel(name="IrFilecomplementanswer"),
        migrations.DeleteModel(name="IrFilecomplementreqCc"),
        migrations.DeleteModel(name="IrFilecomplementrequest"),
        migrations.DeleteModel(name="IrFilelist"),
        migrations.DeleteModel(name="IrFileupload"),
        migrations.DeleteModel(name="IrFileuploadCc"),
        migrations.DeleteModel(name="IrFilevalidation"),
    ]
