services:
  cache:
    image: memcached:1.6-alpine
    networks:
      - ebau.local

  proxy:
    image: nginx:1.27-alpine
    depends_on:
      - ember
      - django
      - keycloak
      - mailpit
      - document-merge-service
    volumes:
      - djangomedia:/var/lib/camac/media:ro
      - djangotmpmedia:/tmp/camac/tmpfiles:ro
    networks:
      - ebau.local

  db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: camac
      POSTGRES_PASSWORD: camac
      POSTGRES_DATABASE: ${APPLICATION}
    volumes:
      - ../db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
      - pg15data:/var/lib/postgresql/data
    networks:
      - ebau.local
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c wal_level=minimal -c max_wal_senders=0 -c archive_mode=off -c max_locks_per_transaction=128

  django: &django
    image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
      args:
        REQUIREMENTS: ${REQUIREMENTS:-requirements.txt}
    depends_on:
      - db
      - cache
      - keycloak
      - mailpit
      - unoconv
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/auth/
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DJANGO_CACHE_LOCATION=cache:11211
      - DJANGO_MEDIA_ROOT=/var/lib/camac/media
      - DJANGO_UNOCONV_URL=http://unoconv:3000
      - APPLICATION=${APPLICATION}
      - CACHE_BACKEND=django.core.cache.backends.memcached.PyMemcacheCache
      - CACHE_LOCATION=cache:11211
      - EVENT_RECEIVER_MODULES=camac.caluma.extensions.events
      - VISIBILITY_CLASSES=camac.caluma.extensions.visibilities.CustomVisibility
      - PERMISSION_CLASSES=camac.caluma.extensions.permissions.CustomPermission
      - VALIDATION_CLASSES=camac.caluma.extensions.validations.CustomValidation
      - DATA_SOURCE_CLASSES=camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services
      - DYNAMIC_GROUPS_CLASSES=camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      - DYNAMIC_TASKS_CLASSES=camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - LANGUAGE_CODE=de
      - LANGUAGES=de,fr
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=300
      - META_FIELDS=camac-instance-id,ebau-number,submit-date
      - ENABLE_HISTORICAL_API=true
      - GWR_FERNET_KEY=GUdwT6yKxqfszrnHC7wyKDmtVZdhjSVQEPnpeJYNLf8=
      - MANABI_SHARED_KEY=bNEZsIjvxDAiLhDA1chvF9zL9OJYPNlCqNPlm7KbhmU
    volumes:
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp/camac/tmpfiles
    networks:
      - ebau.local

  django-q:
    <<: *django
    command: /bin/sh -c "./wait-for-it.sh db:5431 -- ./manage.py qcluster"
    ports: []
    depends_on:
      - db
    networks:
      - ebau.local

  ember:
    image: acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../
      dockerfile: ./Dockerfile.ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember:master
      args:
        WORKSPACE: ember
      target: prod
    depends_on:
      - django
    networks:
      - ebau.local
    environment:
      - ENV=docker

  ember-caluma-portal:
    image: acr.run/camac-ng/camac-ng/ember-caluma-portal:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../
      dockerfile: ./Dockerfile.ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-caluma-portal:master
      args:
        WORKSPACE: ember-caluma-portal
      target: prod
    depends_on:
      - keycloak
      - django
    networks:
      - ebau.local
    environment:
      - ENV=docker

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../
      dockerfile: ./Dockerfile.ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:master
      args:
        WORKSPACE: ember-camac-ng
      target: prod
    networks:
      - ebau.local

  ember-ebau:
    image: acr.run/camac-ng/camac-ng/ember-ebau:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../
      dockerfile: ./Dockerfile.ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-ebau:master
      args:
        WORKSPACE: ember-ebau
      target: prod
    networks:
      - ebau.local
    environment:
      - ENV=docker


  mailpit:
    image: axllent/mailpit
    networks:
      - ebau.local

  unoconv:
    image: zrrrzzt/docker-unoconv-webservice:8.9.4
    networks:
      - ebau.local

  keycloak:
    image: acr.run/camac-ng/camac-ng/keycloak:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../keycloak
      cache_from:
        - acr.run/camac-ng/camac-ng/keycloak:${CI_COMMIT_REF_SLUG:-master}
    volumes:
      - ../keycloak/config/${APPLICATION}-test-config.json:/opt/keycloak/data/import/test-config.json:ro
    environment:
      - KC_DB_PASSWORD=camac
      - KC_DB_URL=jdbc:postgresql://db:5432/${APPLICATION}?currentSchema=keycloak
      - KC_DB_USERNAME=camac
      - KC_HOSTNAME=ebau-keycloak.local
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=camac
    networks:
      - ebau.local

  document-merge-service:
    image: acr.run/camac-ng/camac-ng/document-merge-service:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../document-merge-service
      cache_from:
        - acr.run/camac-ng/camac-ng/document-merge-service:master
      args:
        APPLICATION: ${APPLICATION}
    depends_on:
      - db
      - cache
    networks:
      - ebau.local
    environment:
      - ENV=dev
      - CACHE_LOCATION=cache:11211
      - DATABASE_HOST=db
      - DATABASE_NAME=kt_bern
      - DATABASE_USER=camac
      - DATABASE_PASSWORD=camac
      - OIDC_USERINFO_ENDPOINT=http://ebau-keycloak.local/auth/realms/ebau/protocol/openid-connect/userinfo
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=300
      - EXTENSIONS_ARGUMENTS=DJANGO_API=http://django

volumes:
  pg15data:
  djangomedia:
  djangotmpmedia:
  phpsessions:
  templatefiles:

networks:
  ebau.local:
