version: "3.4"
services:
  cache:
    image: memcached:1.6-alpine

  proxy:
    image: nginx:1.21-alpine
    depends_on:
      - ember
      - django
      - keycloak
      - mailhog
      - document-merge-service
    volumes:
      - djangomedia:/var/lib/camac/media:ro
      - djangotmpmedia:/tmp/camac/tmpfiles:ro
    networks:
      - ebau.local

  db:
    image: acr.run/camac-ng/camac-ng/db:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../db
      cache_from:
        - acr.run/camac-ng/camac-ng/db:master
    environment:
      - POSTGRES_USER=camac
      - POSTGRES_PASSWORD=camac
      - POSTGRES_DATABASE=${APPLICATION}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ebau.local

  django: &django
    image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - db
      - cache
      - clamav
      - keycloak
      - mailhog
      - unoconv
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/auth/
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DJANGO_CACHE_LOCATION=cache:11211
      - DJANGO_MEDIA_ROOT=/var/lib/camac/media
      - DJANGO_UNOCONV_URL=http://unoconv:3000
      - DJANGO_CLAMD_TCP_ADDR=clamav
      - APPLICATION=${APPLICATION}
      - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - CACHE_LOCATION=cache:11211
      - EVENT_RECEIVER_MODULES=camac.caluma.extensions.events
      - VISIBILITY_CLASSES=camac.caluma.extensions.visibilities.CustomVisibility
      - PERMISSION_CLASSES=camac.caluma.extensions.permissions.CustomPermission
      - VALIDATION_CLASSES=camac.caluma.extensions.validations.CustomValidation
      - DATA_SOURCE_CLASSES=camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services
      - DYNAMIC_GROUPS_CLASSES=camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      - DYNAMIC_TASKS_CLASSES=camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - LANGUAGE_CODE=de
      - LANGUAGES=de,fr
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=300
      - META_FIELDS=camac-instance-id,ebau-number,submit-date
      - ENABLE_HISTORICAL_API=true
      - GWR_FERNET_KEY=GUdwT6yKxqfszrnHC7wyKDmtVZdhjSVQEPnpeJYNLf8=
    volumes:
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp/camac/tmpfiles
    networks:
      - ebau.local

  django-q:
    <<: *django
    command: /bin/sh -c "./wait-for-it.sh db:5431 -- ./manage.py qcluster"
    ports: []
    depends_on:
      - db
    networks:
      - ebau.local

  ember:
    image: acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG:-master}
    build:
      target: build
      context: ../ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember:master
      args:
        DEPLOY_TARGET: staging
    depends_on:
      - django
    networks:
      - ebau.local
    environment:
      - ENV=docker

  ember-caluma-portal:
    image: acr.run/camac-ng/camac-ng/ember-caluma-portal:${CI_COMMIT_REF_SLUG:-master}
    build:
      target: build
      context: ../
      dockerfile: ./ember-caluma-portal/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-caluma-portal:master
    depends_on:
      - keycloak
      - django
    networks:
      - ebau.local
    environment:
      - ENV=docker

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../
      dockerfile: ./ember-camac-ng/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:master
      target: build
    networks:
      - ebau.local

  ember-ebau-core:
    image: acr.run/camac-ng/camac-ng/ember-ebau-core:${CI_COMMIT_REF_SLUG:-master}
    build:
      context: ../
      dockerfile: ./ember-ebau-core/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-ebau-core:master

  mailhog:
    image: mailhog/mailhog
    networks:
      - ebau.local

  unoconv:
    image: zrrrzzt/docker-unoconv-webservice:8.9.4
    networks:
      - ebau.local

  clamav:
    image: tiredofit/clamav:2.3.0
    networks:
      - ebau.local

  keycloak:
    depends_on:
      - db
    image: acr.run/camac-ng/keycloak:3.4.3.Final_theme-v0.2.0-SNAPSHOT
    environment:
      - POSTGRES_PORT_5432_TCP_ADDR=db
      - POSTGRES_USER=camac
      - POSTGRES_PASSWORD=camac
      - KEYCLOAK_PASSWORD=camac
      - POSTGRES_DATABASE=${APPLICATION}
      - KEYCLOAK_USER=admin
    volumes:
      - ../keycloak:/etc/keycloak:ro
    networks:
      - ebau.local
    command:
      [
        "-Dkeycloak.migration.action=import",
        "-Dkeycloak.migration.provider=singleFile",
        "-Dkeycloak.migration.file=/etc/keycloak/test-config.json",
        "-b",
        "0.0.0.0",
      ]

  document-merge-service:
    privileged: true
    image: ghcr.io/adfinis/document-merge-service:5.0.3
    depends_on:
      - db
      - unoconv
    volumes:
      - ../document-merge-service/uwsgi.ini:/app/uwsgi.ini:ro
      - ../document-merge-service/templatefiles:/var/lib/document-merge-service/media
      - ../document-merge-service/dump.json:/tmp/document-merge-service/dump.json
    networks:
      - ebau.local
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_HOST=db
      - DATABASE_NAME=kt_bern
      - DATABASE_USER=camac
      - DATABASE_PASSWORD=camac
      - UNOCONV_URL=http://unoconv:3000
      - REQUIRE_AUTHENTICATION=True
      - GROUP_ACCESS_ONLY=True
      - OIDC_USERINFO_ENDPOINT=http://ebau-keycloak.local/auth/realms/ebau/protocol/openid-connect/userinfo
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=300
      - OIDC_GROUPS_API=http://ebau.local/api/v1/me?include=service
      - OIDC_GROUPS_API_JSONPATH=$$.included[?(@.type=='services')].id
      - OIDC_GROUPS_API_HEADERS=AUTHORIZATION,X-CAMAC-GROUP

  metabase:
    image: metabase/metabase:v0.34.2
    depends_on:
      - db
    ports:
      - "666:3000"
    networks:
      - ebau.local
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=camac
      - MB_DB_HOST=db

volumes:
  pgdata:
  djangomedia:
  djangotmpmedia:
  phpsessions:
  templatefiles:

networks:
  ebau.local:
