version: "3.4"
services:
  cache:
    ports:
      - "11211:11211"
    networks:
      - ebau.local

  proxy:
    volumes:
      - ../proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      ebau.local:
        aliases:
          - ebau.local
          - ember-ebau.local
          - ebau-portal.local
          - ebau-rest-portal.local
          - ebau-keycloak.local

  db:
    # Workaround, same name of image as cache_from
    # better be named differently once following is fixed:
    # https://github.com/docker/compose/issues/5458
    # see also other services below
    image: acr.run/camac-ng/camac-ng/db:master
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=camac
    volumes:
      - ../db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    networks:
      - ebau.local

  django: &django
    image: acr.run/camac-ng/camac-ng/django:master
    build:
      args:
        REQUIREMENTS: requirements-dev.txt
    ports:
      - "5555:5555"
      - "5678:5678"
    volumes:
      - ../django:/app
    environment:
      - ENV=development
      - APPLICATION_ENV=development
      - KEYCLOAK_URL=http://ebau-keycloak.local/auth/
      - DATABASE_PASSWORD=camac
      - DATABASE_USER=camac
      - DJANGO_EMAIL_HOST=mailhog
      - DJANGO_EMAIL_PORT=1025
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - OIDC_USERINFO_ENDPOINT=http://ebau-keycloak.local/auth/realms/ebau/protocol/openid-connect/userinfo
      - PYTHONDONTWRITEBYTECODE=1
      - GWR_FERNET_KEY=GUdwT6yKxqfszrnHC7wyKDmtVZdhjSVQEPnpeJYNLf8=
    networks:
      - ebau.local
    command: /bin/sh -c "./wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py collectstatic --noinput && ./manage.py runserver 0:80 --pythonpath /app/$APPLICATION"

  ember-caluma-portal:
    image: acr.run/camac-ng/camac-ng/ember-caluma-portal:master
    environment:
      - BE_GIS_URL=https://map2-test.apps.be.ch
    networks:
      - ebau.local

  ember-ebau:
    image: acr.run/camac-ng/camac-ng/ember-ebau:master
    build:
      context: ../
      dockerfile: ./ember-ebau/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-ebau:master
      args:
        - APPLICATION=${APPLICATION}
    networks:
      - ebau.local

  keycloak:
    image: acr.run/camac-ng/camac-ng/keycloak-${APPLICATION}:master
    volumes:
      - ../keycloak/config/${APPLICATION}-test-config.json:/opt/keycloak/data/import/test-config.json:ro
    environment:
      - KC_DB_PASSWORD=camac
      - KC_DB_URL=jdbc:postgresql://db:5432/${APPLICATION}?currentSchema=keycloak
      - KC_DB_USERNAME=camac
      - KC_HOSTNAME=ebau-keycloak.local
      - KEYCLOAK_ADMIN_PASSWORD=camac
    networks:
      - ebau.local

  mailhog:
    networks:
      - ebau.local
    environment:
      - MH_UI_WEB_PATH=mailhog

networks:
  ebau.local:
