services:
  cache:
    image: memcached:1.6-alpine
    networks:
      - ebau.localhost

  proxy:
    image: nginx:1.29-alpine
    depends_on:
      - ember-caluma-portal
      - ember-camac-ng
      - django
      - keycloak
      - mailpit
      - document-merge-service
    volumes:
      - ../proxy/kt_bern.conf:/etc/nginx/conf.d/default.conf.in:ro
      - ../proxy/csp_headers.inc:/etc/nginx/conf.d/csp_headers.inc:ro
      - ../proxy/csp_headers_default.inc:/etc/nginx/conf.d/csp_headers_default.inc:ro
      - ../proxy/docker-entrypoint.d/90-nameserver.sh:/docker-entrypoint.d/90-nameserver.sh:ro
      - djangomedia:/var/lib/camac/media:ro
      - djangotmpmedia:/tmp/camac/tmpfiles:ro
    ports:
      - "80:80"
    networks:
      ebau.localhost:
        aliases:
          - ebau.localhost
          - ebau-portal.localhost
          - ebau-rest-portal.localhost
          - ebau-keycloak.localhost
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15-bullseye
    # uncomment and build image to install PostgreSQL Anonymizer
    # build:
    #   context: ../db
    #   dockerfile: ../db/Dockerfile.anon
    shm_size: 1g
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: camac
      POSTGRES_PASSWORD: camac
      POSTGRES_DATABASE: ${APPLICATION}
    volumes:
      - pg15data:/var/lib/postgresql/data
      - ../db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    networks:
      - ebau.localhost

  django: &django
    image: acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - cache
      - db
      - document-merge-service
      - mailpit
      - clamav
    build:
      args:
        REQUIREMENTS: requirements-dev.txt
    ports:
      - "5678:5678"
    volumes:
      - ../django:/app
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp/camac/tmpfiles
      - /app/staticfiles # prevent staticfiles from leaking to the host system
    environment: &django-environment
      APPLICATION_ENV: development
      APPLICATION: ${APPLICATION}
      DATABASE_HOST: db
      DATABASE_NAME: ${APPLICATION}
      DATABASE_PASSWORD: camac
      DATABASE_USER: camac
      DJANGO_CACHE_LOCATION: cache:11211
      DJANGO_CLAMD_ENABLED: "true"
      DJANGO_CLAMD_TCP_ADDR: clamav
      DJANGO_EMAIL_HOST: mailpit
      DJANGO_EMAIL_PORT: 1025
      DJANGO_MEDIA_ROOT: /var/lib/camac/media
      DJANGO_TEMPFILE_DOWNLOAD_URL: /tmp
      DOCUMENT_MERGE_SERVICE_URL: http://document-merge-service:8000/document-merge-service/api/v1/
      ENABLE_HISTORICAL_API: "true"
      ENV: development
      KEYCLOAK_URL: http://ebau-keycloak.localhost/auth/
      LANGUAGE_CODE: de
      LANGUAGES: de,fr
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OIDC_USERINFO_ENDPOINT: http://ebau-keycloak.localhost/auth/realms/ebau/protocol/openid-connect/userinfo
      PYTHONDONTWRITEBYTECODE: 1
      # GWR
      GWR_FERNET_KEY: GUdwT6yKxqfszrnHC7wyKDmtVZdhjSVQEPnpeJYNLf8=
      GWR_HOUSING_STAT_BASE_URI: https://www-r.housing-stat.ch/regbl/api/ech0216/2
      # Caluma
      DATA_SOURCE_CLASSES: camac.caluma.extensions.data_sources.Landowners,camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services,camac.caluma.extensions.data_sources.Attachments
      DYNAMIC_GROUPS_CLASSES: camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      DYNAMIC_TASKS_CLASSES: camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      EVENT_RECEIVER_MODULES: camac.caluma.extensions.events
      PERMISSION_CLASSES: camac.caluma.extensions.permissions.CustomPermission
      VALIDATION_CLASSES: camac.caluma.extensions.validations.CustomValidation
      VISIBILITY_CLASSES: camac.caluma.extensions.visibilities.CustomVisibilityBE
      # Alexandria
      ALEXANDRIA_MANABI_DAV_URL_PATH: /webdav
      TIKA_SERVER_ENDPOINT: "http://tika:9998"
      CELERY_RDB_HOST: redis
      CELERY_WORKER_CONCURRENCY: 1
    env_file:
      - ../garage/compose-env/dev-ebau.conf
      - ../garage/compose-env/dev-alexandria.conf
    networks:
      - ebau.localhost
    tty: true
    stdin_open: true
    command: devserver

  django-webdav:
    <<: *django
    image: acr.run/camac-ng/camac-ng/django:master
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
      args:
        REQUIREMENTS: requirements-dev.txt
    command: webdav
    ports: []

  django-webdav-alexandria:
    <<: *django
    image: acr.run/camac-ng/camac-ng/django:master
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
      args:
        REQUIREMENTS: requirements-dev.txt
    environment:
      <<: *django-environment
      DJANGO_DOCUMENT_BACKEND: alexandria
    profiles:
      - alexandria
    command: webdav
    ports: []

  celery:
    <<: *django
    image: acr.run/camac-ng/camac-ng/django:master
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
      args:
        REQUIREMENTS: requirements-dev.txt
    depends_on:
      - redis
    command: celerydev
    ports: []

  flower:
    image: mher/flower:2.0
    environment:
      FLOWER_URL_PREFIX: "/celery-flower/"
    ports:
      - "7777:7777"
    networks:
      - ebau.localhost
    command:
      [
        "celery",
        "--broker=redis://default:redis@redis:6379/0",
        "flower",
        "--port=7777",
      ]

  ember-camac-ng:
    user: nginx:nginx
    environment:
      KEYCLOAK_HOST: http://ebau-keycloak.localhost
      PORTAL_URL: http://ebau-portal.localhost
    networks:
      - ebau.localhost

  ember-caluma-portal:
    user: nginx:nginx
    environment:
      KEYCLOAK_HOST: http://ebau-keycloak.localhost
      INTERNAL_URL: http://ebau.localhost
      BE_GIS_URL: https://www.map2-test.apps.be.ch
    networks:
      - ebau.localhost


  keycloak:
    image: acr.run/camac-ng/camac-ng/keycloak:master
    depends_on:
      - db
    build:
      context: ../keycloak
      args:
        VERSION: 26.2
      cache_from:
        - acr.run/camac-ng/camac-ng/keycloak:master
    volumes:
      - ../keycloak/config/${APPLICATION}-test-config.json:/opt/keycloak/data/import/test-config.json
      - ../keycloak/themes/src/main/resources/theme/ebau-be-2.1.1:/opt/keycloak/themes/ebau-be-dev
    environment:
      KC_DB_PASSWORD: camac
      KC_DB_URL: jdbc:postgresql://db:5432/${APPLICATION}?currentSchema=keycloak
      KC_DB_USERNAME: camac
      KC_HOSTNAME: ebau-keycloak.localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: camac
    networks:
      - ebau.localhost
    command:
      [
        "start",
        "--spi-theme-static-max-age=-1",
        "--spi-theme-cache-themes=false",
        "--spi-theme-cache-templates=false",
      ]

  mailpit:
    image: axllent/mailpit
    networks:
      - ebau.localhost
    environment:
      MP_WEBROOT: mailpit

  clamav:
    image: tiredofit/clamav:2.6.17
    environment:
      - CONCURRENT_DATABASE_RELOAD=false
      - DEFINITIONS_UPDATE_FREQUENCY=1440
      - DEFINITIONS_UPDATE_BEGIN=0300
      - ENABLE_DEFINITIONS_UPDATE=false
    profiles:
      - full
    ports:
      - "3310:3310"
    networks:
      - ebau.localhost

  document-merge-service:
    image: acr.run/camac-ng/camac-ng/document-merge-service:master
    depends_on:
      - db
      - cache
    networks:
      - ebau.localhost
    cap_add:
      - CAP_SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      ENV: dev
      ISOLATE_UNOCONV: "true"
      OIDC_USERINFO_ENDPOINT: http://ebau-keycloak.localhost/auth/realms/ebau/protocol/openid-connect/userinfo
      CACHE_LOCATION: cache:11211
      DATABASE_HOST: db
      DATABASE_NAME: ${APPLICATION}
      DATABASE_USER: camac
      DATABASE_PASSWORD: camac
      DATABASE_OPTIONS: "options=-c search_path=dms"
      URL_PREFIX: document-merge-service/
      # Env variables used in document-merge-service/extensions:
      EXTENSIONS_ARGUMENTS: DJANGO_API=http://django,APPLICATION=${APPLICATION}
    env_file:
      - ../garage/compose-env/dev-dms.conf
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ../document-merge-service/extensions:/app/document_merge_service/extensions
      - ../document-merge-service/${APPLICATION}/templatefiles:/var/lib/document-merge-service/media
      - ../document-merge-service/${APPLICATION}/dump.json:/tmp/document-merge-service/dump.json
    command: devserver

  garage:
    build:
      context: ../garage
    volumes:
      - garage_meta:/var/lib/garage/meta/
      - garage_data:/var/lib/garage/data/
    env_file:
      - ../garage/compose-env/dev-garage.conf
    networks:
      - ebau.localhost

  garage-webui:
    image: khairul169/garage-webui:latest
    restart: unless-stopped
    volumes:
      - ../garage/garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
    networks:
      - ebau.localhost
    depends_on:
      - garage

  tika:
    image: apache/tika:3.2.3.0-full
    profiles:
      - alexandria
    networks:
      - ebau.localhost

  redis:
    image: redis:8.4
    volumes:
      - redis_data:/redis/data
    networks:
      - ebau.localhost

networks:
  ebau.localhost:

volumes:
  pg15data:
  djangomedia:
  djangotmpmedia:
  phpsessions:
  templatefiles:
  redis_data:
  garage_meta:
    driver: local
  garage_data:
    driver: local
