# Devtest Server at https://vm-adfch-devtest-test-westeurope-infra-01.tux42.ch/
services:
  cache:
    image: memcached:1.6-alpine
    networks:
      - ebau.local

  proxy:
    image: nginx:1.27-alpine
    depends_on:
      - ember-caluma-portal
      - ember-camac-ng
      - php
      - django
      - keycloak
      - mailpit
      - document-merge-service
    volumes:
      - djangomedia:/var/lib/camac/media:ro
      - djangotmpmedia:/tmp/camac/tmpfiles:ro
      - /home/adfinis/deploy/config/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    user: root:root
    environment:
      LETSENCRYPT_HOST: vm-adfch-devtest-test-westeurope-infra-01.tux42.ch,internal.vm-adfch-devtest-test-westeurope-infra-01.tux42.ch,portal.vm-adfch-devtest-test-westeurope-infra-01.tux42.ch
      VIRTUAL_HOST: vm-adfch-devtest-test-westeurope-infra-01.tux42.ch,internal.vm-adfch-devtest-test-westeurope-infra-01.tux42.ch,portal.vm-adfch-devtest-test-westeurope-infra-01.tux42.ch
      VIRTUAL_PORT: 80
    networks:
      - ebau.local

  nginx-proxy:
    image: ${DOCKER_REGISTRY:-docker.io/nginxproxy}/nginx-proxy:1.6.0
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/adfinis/deploy/config/nginx-proxy-options.conf:/etc/nginx/conf.d/proxy-http-options.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      ebau.local:
        aliases:
          - ebau.local
          - ebau-portal.local
          - ebau-rest-portal.local
          - ebau-keycloak.local

  nginx-proxy-acme:
    image: ${DOCKER_REGISTRY:-docker.io/nginxproxy}/acme-companion:2.4.0
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEFAULT_EMAIL: david.vogt@adfinis.com
    networks:
      - ebau.local
  db:
    image: postgres:15-bullseye
    shm_size: 1g
    ports: []
    environment:
      POSTGRES_USER: camac
      POSTGRES_PASSWORD: camac
      POSTGRES_DATABASE: ${APPLICATION}
    volumes:
      - pg15data:/var/lib/postgresql/data
      - ../db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    networks:
      - ebau.local

  django: &django
    image: acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - cache
      - db
      - document-merge-service
      - mailpit
    build:
      args:
        REQUIREMENTS: requirements-dev.txt
    ports: []
    volumes:
      - ../django:/app
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp/camac/tmpfiles
      - /app/staticfiles # prevent staticfiles from leaking to the host system
    environment:
      APPLICATION_ENV: development
      APPLICATION: ${APPLICATION}
      DATABASE_HOST: db
      DATABASE_NAME: ${APPLICATION}
      DATABASE_PASSWORD: camac
      DATABASE_USER: camac
      DJANGO_CACHE_LOCATION: cache:11211
      DJANGO_CLAMD_ENABLED: "false"
      DJANGO_EMAIL_HOST: mailpit
      DJANGO_EMAIL_PORT: 1025
      DJANGO_MEDIA_ROOT: /var/lib/camac/media
      DJANGO_TEMPFILE_DOWNLOAD_URL: /tmp
      DJANGO_Q_ENABLE_SYNC: ${DJANGO_Q_ENABLE_SYNC:-false}
      DOCUMENT_MERGE_SERVICE_URL: http://document-merge-service:8000/document-merge-service/api/v1/
      ENABLE_HISTORICAL_API: "true"
      ENV: development
      KEYCLOAK_URL: https://vm-adfch-devtest-test-westeurope-infra-01.tux42.ch/auth/
      LANGUAGE_CODE: de
      LANGUAGES: de,fr
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OIDC_USERINFO_ENDPOINT: http://vm-adfch-devtest-test-westeurope-infra-01.tux42.ch/auth/realms/ebau/protocol/openid-connect/userinfo
      PYTHONDONTWRITEBYTECODE: 1
      # GWR
      GWR_FERNET_KEY: GUdwT6yKxqfszrnHC7wyKDmtVZdhjSVQEPnpeJYNLf8=
      GWR_HOUSING_STAT_BASE_URI: https://www-r.housing-stat.ch/regbl/api/ech0216/2
      # Caluma
      DATA_SOURCE_CLASSES: camac.caluma.extensions.data_sources.Landowners,camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services,camac.caluma.extensions.data_sources.Attachments
      DYNAMIC_GROUPS_CLASSES: camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      DYNAMIC_TASKS_CLASSES: camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      EVENT_RECEIVER_MODULES: camac.caluma.extensions.events
      PERMISSION_CLASSES: camac.caluma.extensions.permissions.CustomPermission
      VALIDATION_CLASSES: camac.caluma.extensions.validations.CustomValidation
      VISIBILITY_CLASSES: camac.caluma.extensions.visibilities.CustomVisibilityBE
    networks:
      - ebau.local
    tty: true
    stdin_open: true

  django-q:
    <<: *django
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
    command: /bin/sh -c "./wait-for-it.sh db:5432 -- python manage.py qcluster --pythonpath /app/$APPLICATION"
    # to enable live reloading on file changes: comment above line, uncomment command below and run next line's command in the container
    # find -wholename "**/*.py" | entr python manage.py qcluster --pythonpath /app/$APPLICATION
    #command: /bin/sh -c "sleep inf"
    ports: []

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:master
    build:
      args:
        # reset those args that should fall back to defaults
        # to avoid reduncancy and clerical footshots
        - APP_ENV=development
        - KEYCLOAK_HOST=https://vm-adfch-devtest-test-westeurope-infra-01.tux42.ch/
        - KEYLCOAK_REALM
        - PORTAL_URL
    networks:
      - ebau.local

  ember-caluma-portal:
    image: acr.run/camac-ng/camac-ng/ember-caluma-portal:master
    build:
      args:
        # reset those args that should fall back to defaults
        # to avoid reduncancy and clerical footshots
        - KEYCLOAK_HOST=https://vm-adfch-devtest-test-westeurope-infra-01.tux42.ch/
        - KEYCLOAK_REALM
        - INTERNAL_URL=https://internal.vm-adfch-devtest-test-westeurope-infra-01.tux42.ch/
        # BE_GIS_URL defaults to the prod instance
        - BE_GIS_URL=https://map2-test.apps.be.ch
    networks:
      - ebau.local


  keycloak:
    image: acr.run/camac-ng/camac-ng/keycloak:master
    depends_on:
      - db
    build:
      context: ../keycloak
      cache_from:
        - acr.run/camac-ng/camac-ng/keycloak:master
    volumes:
      - ../keycloak/config/${APPLICATION}-test-config.json:/opt/keycloak/data/import/test-config.json
      - ../keycloak/themes/src/main/resources/theme/ebau-be:/opt/keycloak/themes/ebau-be-dev
    ports: []
    environment:
      KC_DB_PASSWORD: camac
      KC_DB_URL: jdbc:postgresql://db:5432/${APPLICATION}?currentSchema=keycloak
      KC_DB_USERNAME: camac
      KC_HOSTNAME: vm-adfch-devtest-test-westeurope-infra-01.tux42.ch
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: camac
    networks:
      - ebau.local
    command:
      [
        "start",
        "--spi-theme-static-max-age=-1",
        "--spi-theme-cache-themes=false",
        "--spi-theme-cache-templates=false",
      ]

  mailpit:
    image: axllent/mailpit
    networks:
      - ebau.local
    environment:
      MP_WEBROOT: mailpit

  document-merge-service:
    image: acr.run/camac-ng/camac-ng/document-merge-service:master
    depends_on:
      - db
      - cache
    networks:
      - ebau.local
    cap_add:
      - CAP_SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      ENV: dev
      ISOLATE_UNOCONV: "true"
      OIDC_USERINFO_ENDPOINT: http://vm-adfch-devtest-test-westeurope-infra-01.tux42.ch/auth/realms/ebau/protocol/openid-connect/userinfo
      CACHE_LOCATION: cache:11211
      DATABASE_HOST: db
      DATABASE_NAME: ${APPLICATION}
      DATABASE_USER: camac
      DATABASE_PASSWORD: camac
      URL_PREFIX: document-merge-service/
      EXTENSIONS_ARGUMENTS: DJANGO_API=http://django
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ../document-merge-service/extensions:/app/document_merge_service/extensions
      - ../document-merge-service/${APPLICATION}/templatefiles:/var/lib/document-merge-service/media
      - ../document-merge-service/${APPLICATION}/dump.json:/tmp/document-merge-service/dump.json
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it db:5432 -- poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000",
      ]

networks:
  ebau.local:
    external: true

volumes:
  pg15data:
  djangomedia:
  djangotmpmedia:
  phpsessions:
  templatefiles:
  acme:
  certs:
  html:
