services:
  django:
    image: acr.run/camac-ng/camac-ng/django:master
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:master
    build:
      context: ../
      dockerfile: ./ember-camac-ng/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:master
      args:
        APPLICATION: ${APPLICATION}
        APP_ENV: ${APP_ENV:-production}
        PORTAL_URL: $$PORTAL_URL

  ember-caluma-portal:
    image: acr.run/camac-ng/camac-ng/ember-caluma-portal:master
    build:
      context: ../
      dockerfile: ./ember-caluma-portal/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-caluma-portal:master
      args:
        APPLICATION: ${APPLICATION}


  document-merge-service:
    image: acr.run/camac-ng/camac-ng/document-merge-service:master
    build:
      context: ../document-merge-service
      cache_from:
        - acr.run/camac-ng/camac-ng/document-merge-service:master
      args:
        APPLICATION: ${APPLICATION}
