version: "3.4"
services:
  cache:
    image: memcached:1.6-alpine

  proxy:
    image: nginx:1.25-alpine

  django:
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - cache
      - keycloak
      - mailhog
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DJANGO_CACHE_LOCATION=cache:11211
      - DJANGO_MEDIA_ROOT=/var/lib/camac/media
      - DJANGO_CLAMD_ENABLED=false
      - DJANGO_CLAMD_TCP_ADDR=clamav
      - DJANGO_DEFAULT_FILE_STORAGE=alexandria.storages.backends.s3.S3Storage
      - APPLICATION=${APPLICATION}
      - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - CACHE_LOCATION=cache:11211
      - EVENT_RECEIVER_MODULES=camac.caluma.extensions.events
      - VISIBILITY_CLASSES=camac.caluma.extensions.visibilities.CustomVisibility
      - PERMISSION_CLASSES=camac.caluma.extensions.permissions.CustomPermission
      - VALIDATION_CLASSES=camac.caluma.extensions.validations.CustomValidation
      - DATA_SOURCE_CLASSES=camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services
      - DYNAMIC_GROUPS_CLASSES=camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      - DYNAMIC_TASKS_CLASSES=camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - LANGUAGE_CODE=de
      - LANGUAGES=de,it
      - META_FIELDS=camac-instance-id,submit-date
      - ENABLE_HISTORICAL_API=true
      - ALEXANDRIA_ENABLE_PDF_CONVERSION=true
      - ALEXANDRIA_USE_MANABI=true

  ember-caluma-portal:
    build:
      context: ../
      dockerfile: ./Dockerfile.ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-caluma-portal:master
      args:
        - APPLICATION=${APPLICATION}
        - ENABLE_WATERMARK=${ENABLE_WATERMARK:-false}
        - WATERMARK=${WATERMARK:-local}
        - WORKSPACE=ember-caluma-portal
      target: prod

  ember-ebau:
    build:
      context: ../
      dockerfile: ./Dockerfile.ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-ebau:master
      args:
        - APPLICATION=${APPLICATION}
        - ENABLE_WATERMARK=${ENABLE_WATERMARK:-false}
        - WATERMARK=${WATERMARK:-local}
        - WORKSPACE=ember-ebau
      target: prod

  mailhog:
    image: mailhog/mailhog
    environment:
      - MH_UI_WEB_PATH=mailhog

  keycloak:
    build:
      context: ../keycloak
      cache_from:
        - acr.run/camac-ng/camac-ng/keycloak:master

  document-merge-service:
    build:
      context: ../document-merge-service
      cache_from:
        - acr.run/camac-ng/camac-ng/document-merge-service:master
      args:
        APPLICATION: ${APPLICATION}
    environment:
      - CACHE_LOCATION=cache:11211
      - FILE_STORAGE=storages.backends.s3boto3.S3Boto3Storage
      - AWS_STORAGE_BUCKET_NAME=dms-media
      - AWS_S3_SIGNATURE_VERSION=s3v4

  clamav:
    image: tiredofit/clamav:2.6.11
    environment:
      - CONCURRENT_DATABASE_RELOAD=false
      - DEFINITIONS_UPDATE_FREQUENCY=1440
      - DEFINITIONS_UPDATE_BEGIN=0300

volumes:
  pgdata:
  djangomedia:
  djangotmpmedia:
