version: "3.4"
services:
  cache:
    image: memcached:1.6-alpine

  proxy:
    image: nginx:1.23-alpine

  django:
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - cache
      - keycloak
      - mailhog
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DJANGO_CACHE_LOCATION=cache:11211
      - DJANGO_MEDIA_ROOT=/var/lib/camac/media
      - DJANGO_CLAMD_ENABLED=false
      - APPLICATION=${APPLICATION}
      - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - CACHE_LOCATION=cache:11211
      - EVENT_RECEIVER_MODULES=camac.caluma.extensions.events
      - VISIBILITY_CLASSES=camac.caluma.extensions.visibilities.CustomVisibility
      - PERMISSION_CLASSES=camac.caluma.extensions.permissions.CustomPermission
      - VALIDATION_CLASSES=camac.caluma.extensions.validations.CustomValidation
      - DATA_SOURCE_CLASSES=camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services
      - DYNAMIC_GROUPS_CLASSES=camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      - DYNAMIC_TASKS_CLASSES=camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - LANGUAGE_CODE=de
      - LANGUAGES=de,it
      - META_FIELDS=camac-instance-id,submit-date
      - ENABLE_HISTORICAL_API=true
      # alexandria
      - ALEXANDRIA_VISIBILITY_CLASSES=camac.alexandria.extensions.visibilities.CustomVisibility
      - ALEXANDRIA_PERMISSION_CLASSES=camac.alexandria.extensions.permissions.CustomPermission
      - ALEXANDRIA_VALIDATION_CLASSES=camac.alexandria.extensions.validations.Validator

  ember-caluma-portal:
    build:
      context: ../
      dockerfile: ./ember-caluma-portal/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-caluma-portal:master
      args:
        - APPLICATION=${APPLICATION}

  ember-ebau:
    build:
      context: ../
      dockerfile: ./ember-ebau/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-ebau:master
      args:
        - APPLICATION=${APPLICATION}

  mailhog:
    image: mailhog/mailhog
    environment:
      - MH_UI_WEB_PATH=mailhog

  keycloak:
    build:
      context: ../keycloak
      cache_from:
        - acr.run/camac-ng/camac-ng/keycloak:master

  document-merge-service:
    image: ghcr.io/adfinis/document-merge-service:5.0.5
    depends_on:
      - db
    volumes:
      - ../document-merge-service/uwsgi.ini:/app/uwsgi.ini:ro
      - ../document-merge-service/kt_gr/templatefiles:/var/lib/document-merge-service/media
      - ../document-merge-service/kt_gr/dump.json:/tmp/document-merge-service/dump.json
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DATABASE_USER=camac
      - DATABASE_PASSWORD=camac
      - REQUIRE_AUTHENTICATION=True
      - GROUP_ACCESS_ONLY=True
      - OIDC_GROUPS_API_JSONPATH=$$.included[?(@.type=='services')].id
      - OIDC_GROUPS_API_HEADERS=AUTHORIZATION,X-CAMAC-GROUP
      - PAGINATION_ENABLED=False

volumes:
  pgdata:
  djangomedia:
  djangotmpmedia:
