services:
  cache:
    ports:
      - "11211:11211"
    networks:
      - ebau.local

  proxy:
    depends_on:
      - mailhog
    volumes:
      - ../proxy/kt_schwyz.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      ebau.local:
        aliases:
          - ebau.local
          - ebau-portal.local
          - ebau-rest-portal.local
          - ebau-keycloak.local

  clamav:
    profiles:
      - full
    ports:
      - "3310:3310"
    environment:
      - ENABLE_DEFINITIONS_UPDATE=false
    networks:
      - ebau.local

  db:
    image: acr.run/camac-ng/camac-ng/db:master
    build:
      context: ../db
      cache_from:
        - acr.run/camac-ng/camac-ng/db:master
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=camac
      - POSTGRES_USER=camac
      - POSTGRES_DATABASE=${APPLICATION}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    networks:
      - ebau.local

  django: &django
    image: acr.run/camac-ng/camac-ng/django:master
    build:
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
      args:
        REQUIREMENTS: requirements-dev.txt
    ports:
      - "5555:5555"
      - "5678:5678"
    volumes:
      - ../django:/app
    depends_on:
      - db
      - mailhog
    environment:
      - ENV=development
      - APPLICATION_ENV=development
      - KEYCLOAK_URL=http://ebau-keycloak.local/auth/
      - ECH0211_API_ACTIVE=True
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DATABASE_PASSWORD=camac
      - DATABASE_USER=camac
      - DJANGO_EMAIL_HOST=mailhog
      - DJANGO_EMAIL_PORT=1025
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - OIDC_USERINFO_ENDPOINT=http://ebau-keycloak.local/auth/realms/ebau/protocol/openid-connect/userinfo
      - GWR_FERNET_KEY=GUdwT6yKxqfszrnHC7wyKDmtVZdhjSVQEPnpeJYNLf8=
      - GWR_HOUSING_STAT_BASE_URI=https://www-r.housing-stat.ch/regbl/api/ech0216/2
    networks:
      - ebau.local
    command: /bin/sh -c "./wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py collectstatic --noinput && ./manage.py runserver 0.0.0.0:80 --pythonpath /app/$APPLICATION"

  # repeat definition here because otherwise prod settings are applied
  django-q:
    <<: *django
    # entr will watch for changes in the list of files piped to it and execute the command passed as argument
    # to make sure your tasks execute the latest code
    command: /bin/sh -c "./wait-for-it.sh db:5432 -- python manage.py qcluster --pythonpath /app/$APPLICATION"
    # for reloading: comment above line, uncomment command below and run next line's command in the container
    # find -wholename "**/*.py" | entr python manage.py qcluster --pythonpath /app/$APPLICATION
    #command: /bin/sh -c "while true; do sleep 10; done"
    ports: []

  ember:
    image: acr.run/camac-ng/camac-ng/ember:master
    build:
      args:
        KEYCLOAK_URL_ARG: http://ebau-keycloak.local/auth/realms/ebau/protocol/openid-connect
        INTERNAL_HOST_ARG: http://ebau.local
        DEPLOY_TARGET: staging
    networks:
      - ebau.local

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:master
    networks:
      - ebau.local

  ember-ebau:
    image: acr.run/camac-ng/camac-ng/ember-ebau:master
    build:
      context: ../
      dockerfile: ./ember-ebau/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-ebau:master
      args:
        - APPLICATION=${APPLICATION}
    networks:
      - ebau.local

  unoconv:
    ports:
      - "3000:3000"
    networks:
      - ebau.local

  keycloak:
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ../keycloak/config/${APPLICATION}-test-config.json:/opt/keycloak/data/import/test-config.json
    environment:
      - KC_DB_PASSWORD=camac
      - KC_DB_USERNAME=camac
      - KC_HOSTNAME=ebau-keycloak.local
      - KEYCLOAK_ADMIN_PASSWORD=camac
      - KC_HOSTNAME_STRICT_HTTPS=false
    networks:
      - ebau.local

  mailhog:
    image: mailhog/mailhog
    networks:
      - ebau.local
    environment:
      - MH_UI_WEB_PATH=mailhog

  metabase:
    depends_on:
      - db
    environment:
      - MB_DB_USER=camac
      - MB_DB_PASS=camac
      - MB_DB_HOST=db
    networks:
      - ebau.local

networks:
  ebau.local:

volumes:
  pgdata:
