services:
  proxy:
    image: nginx:1.29-alpine
    depends_on:
      - django
      - ember
      - ember-camac-ng
      - keycloak
      - mailpit
    volumes:
      - djangomedia:/var/lib/camac/media:ro
      # Mounting a subdirectory of a named volume currently isn't possible:
      # https://github.com/moby/moby/issues/32582
      - djangotmpmedia:/tmp/external-tmp:ro
      - ../proxy/kt_schwyz.conf:/etc/nginx/conf.d/default.conf.in:ro
      - ../proxy/csp_headers.inc:/etc/nginx/conf.d/csp_headers.inc:ro
      - ../proxy/csp_headers_default.inc:/etc/nginx/conf.d/csp_headers_default.inc:ro
      - ../proxy/docker-entrypoint.d/90-nameserver.sh:/docker-entrypoint.d/90-nameserver.sh:ro
    ports:
      - "80:80"
    networks:
      ebau.localhost:
        aliases:
          - ebau.localhost
          - ebau-portal.localhost
          - ebau-rest-portal.localhost
          - ebau-keycloak.localhost
    extra_hosts:
      - "host.docker.internal:host-gateway"

  django: &django
    build:
      context: ../django
      args:
        REQUIREMENTS: requirements-dev.txt
    ports:
      - "5555:5555"
      - "5678:5678"
    volumes:
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp
      - ../django:/app
      - /app/staticfiles # prevent staticfiles from leaking to the host system
    depends_on:
      - cache
      - clamav
      - db
      - document-merge-service
      - keycloak
      - mailpit
      - unoconv
    environment:
      APPLICATION: ${APPLICATION}
      APPLICATION_ENV: development
      CACHE_BACKEND: django.core.cache.backends.memcached.PyMemcacheCache
      CACHE_LOCATION: cache:11211
      DATABASE_HOST: db
      DATABASE_NAME: ${APPLICATION}
      DATABASE_PASSWORD: camac
      DATABASE_USER: camac
      DATA_SOURCE_CLASSES: camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services,camac.caluma.extensions.data_sources.Sanctions
      DJANGO_CACHE_LOCATION: cache:11211
      DJANGO_CLAMD_TCP_ADDR: clamav
      DJANGO_EMAIL_HOST: mailpit
      DJANGO_EMAIL_PORT: 1025
      DJANGO_MEDIA_ROOT: /var/lib/camac/media
      DJANGO_UNOCONV_URL: http://unoconv:3000
      DOCUMENT_MERGE_SERVICE_URL: http://document-merge-service:8000/api/v1/
      DYNAMIC_GROUPS_CLASSES: camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      DYNAMIC_TASKS_CLASSES: camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      ECH0211_API_ACTIVE: True
      ENABLE_HISTORICAL_API: true
      ENV: development
      EVENT_RECEIVER_MODULES: camac.caluma.extensions.events
      FORMAT_VALIDATOR_CLASSES: camac.caluma.extensions.format_validators.IntegerListFormatValidator
      GWR_FERNET_KEY: GUdwT6yKxqfszrnHC7wyKDmtVZdhjSVQEPnpeJYNLf8=
      GWR_HOUSING_STAT_BASE_URI: https://www-r.housing-stat.ch/regbl/api/ech0216/2
      KEYCLOAK_URL: http://ebau-keycloak.localhost/auth/
      MANABI_ENABLE: False
      META_FIELDS: camac-instance-id,ebau-number,submit-date
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OIDC_USERINFO_ENDPOINT: http://ebau-keycloak.localhost/auth/realms/ebau/protocol/openid-connect/userinfo
      PERMISSION_CLASSES: camac.caluma.extensions.permissions.CustomPermission
      REDIS_HOST: valkey
      VALIDATION_CLASSES: camac.caluma.extensions.validations.CustomValidation
      VISIBILITY_CLASSES: camac.caluma.extensions.visibilities.CustomVisibilitySZ
      DJANGO_DEFAULT_FILE_STORAGE: django.core.files.storage.FileSystemStorage
    env_file:
      - ../garage/compose-env/dev-ebau.conf
      - ../garage/compose-env/dev-alexandria.conf
    networks:
      - ebau.localhost
    command: devserver

  celery:
    <<: *django
    image: acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - valkey
    command: celerydev
    ports: []

  flower:
    image: mher/flower:2.0
    environment:
      FLOWER_URL_PREFIX: "/celery-flower/"
    ports:
      - "7777:7777"
    networks:
      - ebau.localhost
    command:
      [
        "celery",
        "--broker=redis://default:redis@valkey:6379/0",
        "flower",
        "--port=7777",
      ]

  ember:
    environment:
      KEYCLOAK_HOST: http://ebau-keycloak.localhost
      GIS_HOST: map-t.geo.sz.ch
    networks:
      - ebau.localhost

  ember-camac-ng:
    environment:
      APP_ENV: development
    networks:
      - ebau.localhost


  cache:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    networks:
      - ebau.localhost

  clamav:
    image: tiredofit/clamav:2.6.99
    profiles:
      - full
    ports:
      - "3310:3310"
    environment:
      CONCURRENT_DATABASE_RELOAD: false
      DEFINITIONS_UPDATE_FREQUENCY: 1440
      DEFINITIONS_UPDATE_BEGIN: 0300
      ENABLE_DEFINITIONS_UPDATE: false
      MAX_FILE_SIZE: 60M
      MAX_SCAN_SIZE: 200M
      STREAM_MAX_LENGTH: 60M
    networks:
      - ebau.localhost

  db:
    image: postgres:16-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: camac
      POSTGRES_USER: camac
      POSTGRES_DATABASE: ${APPLICATION}
    volumes:
      - pg16data:/var/lib/postgresql/data
      - ../db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    networks:
      - ebau.localhost
    command: -c max_locks_per_transaction=128

  document-merge-service:
    tty: true
    stdin_open: true
    user: ${UID}
    cap_add:
      - CAP_SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    depends_on:
      - cache
      - db
      - garage
    environment:
      CACHE_LOCATION: cache:11211
      DATABASE_HOST: db
      DATABASE_NAME: ${APPLICATION}
      DATABASE_PASSWORD: camac
      DATABASE_USER: camac
      DATABASE_OPTIONS: "options=-c search_path=dms"
      DOCXTEMPLATE_JINJA_EXTENSIONS: ""
      ENV: dev
      EXTENSIONS_ARGUMENTS: DJANGO_API=http://django
      FILE_STORAGE: storages.backends.s3.S3Storage
      ISOLATE_UNOCONV: true
      OIDC_USERINFO_ENDPOINT: http://ebau-keycloak.localhost/auth/realms/ebau/protocol/openid-connect/userinfo
      OIDC_VERIFY_SSL: true
      REQUIRE_AUTHENTICATION: true
      URL_PREFIX: document-merge-service/
    env_file:
      - ../garage/compose-env/dev-dms.conf
    volumes:
      - ../document-merge-service/extensions:/app/document_merge_service/extensions
      - ../document-merge-service/${APPLICATION}/dump.json:/tmp/document-merge-service/dump.json
    networks:
      - ebau.localhost
    command: devserver

  keycloak:
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ../keycloak/config/${APPLICATION}-test-config.json:/opt/keycloak/data/import/test-config.json
      - ../keycloak/themes/src/main/resources/theme/kanton-schwyz:/opt/keycloak/themes/kanton-schwyz-dev
    environment:
      KC_DB_URL: jdbc:postgresql://db:5432/${APPLICATION}
      KC_DB_PASSWORD: camac
      KC_DB_USERNAME: camac
      KC_HOSTNAME: ebau-keycloak.localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: camac
    networks:
      - ebau.localhost
    command:
      [
        "start",
        "--spi-theme-static-max-age=-1",
        "--spi-theme-cache-themes=false",
        "--spi-theme-cache-templates=false",
      ]

  mailpit:
    image: axllent/mailpit
    networks:
      - ebau.localhost
    environment:
      MP_WEBROOT: mailpit

  metabase:
    image: metabase/metabase:v0.58.1
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: db
      MB_DB_PORT: 5432
      MB_DB_USER: camac
      MB_DB_PASS: camac
      MB_DB_DBNAME: metabase
    networks:
      - ebau.localhost

  garage:
    volumes:
      - garage_meta:/var/lib/garage/meta/
      - garage_data:/var/lib/garage/data/
      - ../garage/garage.toml:/etc/garage.toml:ro
    env_file:
      - ../garage/compose-env/dev-garage.conf
    networks:
      - ebau.localhost

  garage-webui:
    image: khairul169/garage-webui:latest
    restart: unless-stopped
    volumes:
      - ../garage/garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
    networks:
      - ebau.localhost
    depends_on:
      - garage

  unoconv:
    image: zrrrzzt/docker-unoconv-webservice:8.9.4
    ports:
      - "3000:3000"
    networks:
      - ebau.localhost

  valkey:
    image: valkey/valkey:9.0
    volumes:
      - valkey_data:/data
    networks:
      - ebau.localhost

networks:
  ebau.localhost:

volumes:
  djangomedia:
  djangotmpmedia:
  garage_data:
    driver: local
  garage_meta:
    driver: local
  pg16data:
  phpsessions:
  templatefiles:
  valkey_data:
