version: "3.4"
services:
  cache:
    ports:
      - "11211:11211"
    networks:
      - ebau.local

  proxy:
    depends_on:
      - mailhog
    volumes:
      - ../proxy/kt_schwyz.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      ebau.local:
        aliases:
          - ebau.local
          - ebau-portal.local
          - ebau-rest-portal.local
          - ebau-keycloak.local

  clamav:
    profiles:
      - full
    ports:
      - "3310:3310"
    environment:
      - ENABLE_DEFINITIONS_UPDATE=false
    networks:
      - ebau.local

  db:
    # Workaround, same name of image as cache_from
    # better be named differently once following is fixed:
    # https://github.com/docker/compose/issues/5458
    # see also other services below
    image: acr.run/camac-ng/camac-ng/db:master
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=camac
    volumes:
      - ../db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    networks:
      - ebau.local

  django: &django
    image: acr.run/camac-ng/camac-ng/django:master
    build:
      args:
        REQUIREMENTS: requirements-dev.txt
    ports:
      - "5555:5555"
      - "5678:5678"
    volumes:
      - ../django:/app
    depends_on:
      - mailhog
    environment:
      - ENV=development
      - APPLICATION_ENV=development
      - KEYCLOAK_URL=http://ebau-keycloak.local/auth/
      - DATABASE_PASSWORD=camac
      - DATABASE_USER=camac
      - DJANGO_EMAIL_HOST=mailhog
      - DJANGO_EMAIL_PORT=1025
      - DJANGO_MERGE_DATE_FORMAT=%d.%m.%Y
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - OIDC_USERINFO_ENDPOINT=http://ebau-keycloak.local/auth/realms/ebau/protocol/openid-connect/userinfo
      - GWR_FERNET_KEY=GUdwT6yKxqfszrnHC7wyKDmtVZdhjSVQEPnpeJYNLf8=
      - GWR_HOUSING_STAT_BASE_URI=https://www-r.housing-stat.ch/regbl/api/ech0216/2
    networks:
      - ebau.local
    command: /bin/sh -c "./wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py collectstatic --noinput && ./manage.py runserver 0.0.0.0:80 --pythonpath /app/$APPLICATION"

  # repeat definition here because otherwise prod settings are applied
  django-q:
    <<: *django
    command: /bin/sh -c "./wait-for-it.sh db:5431 -- ./manage.py qcluster --pythonpath /app/$APPLICATION"
    ports: []

  ember:
    image: acr.run/camac-ng/camac-ng/ember:master
    build:
      args:
        KEYCLOAK_URL_ARG: http://ebau-keycloak.local/auth/realms/ebau/protocol/openid-connect
        INTERNAL_HOST_ARG: http://ebau.local
        DEPLOY_TARGET: staging
    networks:
      - ebau.local

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:master
    networks:
      - ebau.local

  ember-ebau:
    image: acr.run/camac-ng/camac-ng/ember-ebau:master
    build:
      context: ../
      dockerfile: ./ember-ebau/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-ebau:master
      args:
        - APPLICATION=${APPLICATION}
    networks:
      - ebau.local

  unoconv:
    ports:
      - "3000:3000"
    networks:
      - ebau.local

  keycloak:
    ports:
      - "8080:8080"
    volumes:
      - ../keycloak/${APPLICATION}-test-config.json:/etc/keycloak/test-config.json:ro
    environment:
      - DB_PASSWORD=camac
      - KEYCLOAK_PASSWORD=camac
    networks:
      - ebau.local
    # export is a bit tricky: We need to _start_ keycloak with specific arguments to perform an export
    # command: ["-Dkeycloak.migration.action=export", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/etc/keycloak/test-config.json", "-b", "0.0.0.0"]
    #
    # http://www.keycloak.org/docs/3.3/server_admin/topics/export-import.html
    command:
      [
        "-Dkeycloak.migration.action=import",
        "-Dkeycloak.migration.provider=singleFile",
        "-Dkeycloak.migration.file=/etc/keycloak/test-config.json",
        "-b",
        "0.0.0.0",
      ]

  mailhog:
    image: mailhog/mailhog
    networks:
      - ebau.local
    environment:
      - MH_UI_WEB_PATH=mailhog

  metabase:
    environment:
      - MB_DB_PASS=camac
    networks:
      - ebau.local

networks:
  ebau.local:
