version: "3.4"
services:
  cache:
    image: memcached:1.5-alpine

  proxy:
    image: nginx:1.13-alpine
    depends_on:
      - ember
      - ember-camac-ng
      - php
      - django
      - keycloak
    volumes:
      - djangomedia:/var/lib/camac/media:ro
      - djangotmpmedia:/tmp/camac/tmpfiles:ro

  db:
    build:
      context: ../db
      cache_from:
        - acr.run/camac-ng/camac-ng/db:master
    environment:
      - POSTGRES_USER=camac
      - POSTGRES_DATABASE=${APPLICATION}
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - db
      - cache
      - clamav
      - keycloak
      - unoconv
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DJANGO_CACHE_LOCATION=cache:11211
      - DJANGO_MEDIA_ROOT=/var/lib/camac/media
      - DJANGO_UNOCONV_URL=http://unoconv:3000
      - DJANGO_CLAMD_TCP_ADDR=clamav
      - DJANGO_MERGE_DATE_FORMAT=%-d. %B %Y
      - APPLICATION=${APPLICATION}
      - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - CACHE_LOCATION=cache:11211
      - EVENT_RECEIVER_MODULES=camac.caluma.extensions.events
      - VISIBILITY_CLASSES=camac.caluma.extensions.visibilities.CustomVisibility
      - PERMISSION_CLASSES=camac.caluma.extensions.permissions.CustomPermission
      - VALIDATION_CLASSES=camac.caluma.extensions.validations.CustomValidation
      - DATA_SOURCE_CLASSES=camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services
      - DYNAMIC_GROUPS_CLASSES=camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      - DYNAMIC_TASKS_CLASSES=camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - LANGUAGE_CODE=de
      - LANGUAGES=de,fr
      - META_FIELDS=camac-instance-id,ebau-number,submit-date
      - ENABLE_HISTORICAL_API=true
    volumes:
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp/camac/tmpfiles

  ember-camac-ng:
    build:
      context: ../
      dockerfile: ./ember-camac-ng/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:master
      args:
        - APPLICATION=${APPLICATION}

  ember:
    build:
      context: ../ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember:master

  php:
    build:
      context: ../php
      cache_from:
        - acr.run/camac-ng/camac-ng/php:master
    depends_on:
      - db
      - django
      - cache
      - keycloak
    environment:
      - APPLICATION=${APPLICATION}
    volumes:
      - djangomedia:/var/www/camac/media
      - phpsessions:/var/www/camac/sessions
      - /var/www/camac/vendor
      - /var/www/camac/public/public-kt_bern/css
      - /var/www/camac/public/public-kt_bern/js
      - /var/www/camac/public/node_modules

  unoconv:
    image: zrrrzzt/docker-unoconv-webservice:8.9.4

  clamav:
    image: tiredofit/clamav:2.3.0

  keycloak:
    depends_on:
      - db
    image: acr.run/camac-ng/keycloak:3.4.3.Final_theme-v0.2.0-SNAPSHOT
    environment:
      - POSTGRES_PORT_5432_TCP_ADDR=db
      - POSTGRES_USER=camac
      - POSTGRES_DATABASE=${APPLICATION}
      - KEYCLOAK_USER=admin

  metabase:
    image: metabase/metabase:v0.35.4
    depends_on:
      - db
    ports:
      - "666:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=camac
      - MB_DB_HOST=db

volumes:
  pgdata:
  djangomedia:
  djangotmpmedia:
  phpsessions:
  templatefiles:
