version: "3.4"
services:
  cache:
    ports:
      - "11211:11211"
    networks:
      - camac-ng.local

  proxy:
    depends_on:
      - mailhog
    volumes:
      - ../proxy/kt_schwyz.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      camac-ng.local:
        aliases:
          - camac-ng.local
          - camac-ng-portal.local
          - caluma-portal.local
          - camac-ng-keycloak.local

  clamav:
    ports:
      - "3310:3310"
    networks:
      - camac-ng.local

  db:
    # Workaround, same name of image as cache_from
    # better be named differently once following is fixed:
    # https://github.com/docker/compose/issues/5458
    # see also other services below
    image: acr.run/camac-ng/camac-ng/db:master
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=camac
    volumes:
      - ../db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    networks:
      - camac-ng.local

  django:
    image: acr.run/camac-ng/camac-ng/django:master
    build:
      args:
        REQUIREMENTS: requirements-dev.txt
    ports:
      - "5555:5555"
      - "5678:5678"
    volumes:
      - ../django:/app
    depends_on:
      - mailhog
    environment:
      - ENV=development
      - APPLICATION_ENV=development
      - KEYCLOAK_URL=http://camac-ng-keycloak.local/auth/
      - DATABASE_PASSWORD=camac
      - DATABASE_USER=camac
      - DJANGO_EMAIL_HOST=mailhog
      - DJANGO_EMAIL_PORT=1025
      - DJANGO_MERGE_DATE_FORMAT=%d.%m.%Y
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - OIDC_USERINFO_ENDPOINT=http://camac-ng-keycloak.local/auth/realms/ebau/protocol/openid-connect/userinfo
      - GWR_FERNET_KEY=GUdwT6yKxqfszrnHC7wyKDmtVZdhjSVQEPnpeJYNLf8=
    networks:
      - camac-ng.local
    command: /bin/sh -c "./wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py collectstatic --noinput && ./manage.py runserver 0.0.0.0:80 --pythonpath /app/$APPLICATION"

  ember:
    image: acr.run/camac-ng/camac-ng/ember:master
    build:
      args:
        KEYCLOAK_URL_ARG: http://camac-ng-keycloak.local/auth/realms/ebau/protocol/openid-connect
        DEPLOY_TARGET: staging
    networks:
      - camac-ng.local

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:master
    networks:
      - camac-ng.local

  php:
    image: acr.run/camac-ng/camac-ng/php:master
    volumes:
      - ../php/php.ini-development:/usr/local/etc/php/php.ini:ro
      - ../php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ../php:/var/www/camac
      - /var/www/camac/vendor
      - /var/www/camac/configuration
      - /var/www/camac/public/node_modules
      - /var/www/camac/public/public-kt_uri/js/dist
      - /var/www/camac/public/public-kt_schwyz/js/dist
    environment:
      - APPLICATION_ENV=development
    networks:
      - camac-ng.local
    command: [
        "/bin/sh",
        "-c",
        "cd /var/www/camac \
        && chown -R www-data:www-data media sessions kt_uri/resources \
        && rm -f configuration/* \
        && cd configuration \
        && ln -sf ../${APPLICATION}/* . \
        && php -d xdebug.remote_enable=off /var/www/camac/cronjob/clear-cache.php \
        && apache2-foreground",
      ]

  unoconv:
    ports:
      - "3000:3000"
    networks:
      - camac-ng.local

  keycloak:
    ports:
      - "8080:8080"
    volumes:
      - ../keycloak/${APPLICATION}-test-config.json:/etc/keycloak/test-config.json:ro
    environment:
      - POSTGRES_PASSWORD=camac
      - KEYCLOAK_PASSWORD=camac
    networks:
      - camac-ng.local
    # export is a bit tricky: We need to _start_ keycloak with specific arguments to perform an export
    # command: ["-Dkeycloak.migration.action=export", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/etc/keycloak/test-config.json", "-b", "0.0.0.0"]
    #
    # http://www.keycloak.org/docs/3.3/server_admin/topics/export-import.html
    command:
      [
        "-Dkeycloak.migration.action=import",
        "-Dkeycloak.migration.provider=singleFile",
        "-Dkeycloak.migration.file=/etc/keycloak/test-config.json",
        "-b",
        "0.0.0.0",
      ]

  mailhog:
    image: mailhog/mailhog
    networks:
      - camac-ng.local
    environment:
      - MH_UI_WEB_PATH=mailhog

  metabase:
    environment:
      - MB_DB_PASS=camac
    networks:
      - camac-ng.local

networks:
  camac-ng.local:
