version: "3.4"
services:
  cache:
    image: memcached:1.6-alpine

  proxy:
    image: nginx:1.23-alpine

  django:
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - cache
      - keycloak
      - mailhog
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DJANGO_CACHE_LOCATION=cache:11211
      - DJANGO_MEDIA_ROOT=/var/lib/camac/media
      - DJANGO_CLAMD_ENABLED=false
      - DJANGO_TEMPFILE_DOWNLOAD_URL=/tmp
      - APPLICATION=${APPLICATION}
      - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - CACHE_LOCATION=cache:11211
      - EVENT_RECEIVER_MODULES=camac.caluma.extensions.events
      - VISIBILITY_CLASSES=camac.caluma.extensions.visibilities.CustomVisibility
      - PERMISSION_CLASSES=camac.caluma.extensions.permissions.CustomPermission
      - VALIDATION_CLASSES=camac.caluma.extensions.validations.CustomValidation
      - DATA_SOURCE_CLASSES=camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services,camac.caluma.extensions.data_sources.Countries
      - DYNAMIC_GROUPS_CLASSES=camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      - DYNAMIC_TASKS_CLASSES=camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - LANGUAGE_CODE=de
      - LANGUAGES=de
      - ENABLE_HISTORICAL_API=true
  ember-caluma-portal:
    build:
      context: ../
      dockerfile: ./ember-caluma-portal/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-caluma-portal:master
      args:
        - APPLICATION=${APPLICATION}

  ember-ebau:
    build:
      context: ../
      dockerfile: ./ember-ebau/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-ebau:master
      args:
        - APPLICATION=${APPLICATION}

  mailhog:
    image: mailhog/mailhog
    environment:
      - MH_UI_WEB_PATH=mailhog

  keycloak:
    build:
      context: ../keycloak
      cache_from:
        - acr.run/camac-ng/camac-ng/keycloak:master

  document-merge-service:
    depends_on:
      - db
    build:
      context: ../document-merge-service
      cache_from:
        - acr.run/camac-ng/camac-ng/document-merge-service:master
    environment:
      - FILE_STORAGE=storages.backends.s3boto3.S3Boto3Storage
      - AWS_STORAGE_BUCKET_NAME=dms-media
      - AWS_S3_SIGNATURE_VERSION=s3v4

volumes:
  pgdata:
  djangomedia:
  djangotmpmedia:
  minio_data:
