version: "3.4"
services:
  cache:
    image: memcached:1.6-alpine

  proxy:
    image: nginx:1.21-alpine
    depends_on:
      - ember
      - ember-camac-ng
      - django
      - keycloak
    volumes:
      - djangomedia:/var/lib/camac/media:ro
      - djangotmpmedia:/tmp/camac/tmpfiles:ro

  db:
    build:
      context: ../db
      cache_from:
        - acr.run/camac-ng/camac-ng/db:master
    environment:
      - POSTGRES_USER=camac
      - POSTGRES_DATABASE=${APPLICATION}
    volumes:
      - pgdata:/var/lib/postgresql/data

  django: &django
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - db
      - cache
      - clamav
      - keycloak
      - unoconv
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DJANGO_CACHE_LOCATION=cache:11211
      - DJANGO_MEDIA_ROOT=/var/lib/camac/media
      - DJANGO_UNOCONV_URL=http://unoconv:3000
      - DJANGO_CLAMD_TCP_ADDR=clamav
      - DJANGO_MERGE_DATE_FORMAT=%-d. %B %Y
      - APPLICATION=${APPLICATION}
      - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - CACHE_LOCATION=cache:11211
      - EVENT_RECEIVER_MODULES=camac.caluma.extensions.events
      - VISIBILITY_CLASSES=camac.caluma.extensions.visibilities.CustomVisibilitySZ
      - PERMISSION_CLASSES=camac.caluma.extensions.permissions.CustomPermission
      - VALIDATION_CLASSES=camac.caluma.extensions.validations.CustomValidation
      - DATA_SOURCE_CLASSES=camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services
      - DYNAMIC_GROUPS_CLASSES=camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      - DYNAMIC_TASKS_CLASSES=camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - LANGUAGE_CODE=de
      - LANGUAGES=de,fr
      - META_FIELDS=camac-instance-id,ebau-number,submit-date
      - ENABLE_HISTORICAL_API=true
    volumes:
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp/camac/tmpfiles

  django-q:
    <<: *django
    command: /bin/sh -c "./wait-for-it.sh db:5431 -- ./manage.py qcluster --pythonpath /app/$APPLICATION"

  ember-camac-ng:
    build:
      context: ../
      dockerfile: ./ember-camac-ng/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:master
      args:
        - APPLICATION=${APPLICATION}

  ember:
    build:
      context: ../ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember:master


  unoconv:
    image: zrrrzzt/docker-unoconv-webservice:8.9.4

  clamav:
    image: tiredofit/clamav:2.3.0
    environment:
      - CONCURRENT_DATABASE_RELOAD=false
      - DEFINITIONS_UPDATE_FREQUENCY=1440
      - DEFINITIONS_UPDATE_BEGIN=0300

  keycloak:
    depends_on:
      - db
    image: acr.run/camac-ng/keycloak:16.1.0_theme-v1.0.1
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_USER=camac
      - DB_DATABASE=${APPLICATION}
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true

  metabase:
    image: metabase/metabase:v0.43.2
    depends_on:
      - db
    ports:
      - "666:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=camac
      - MB_DB_HOST=db

volumes:
  pgdata:
  djangomedia:
  djangotmpmedia:
  phpsessions:
  templatefiles:
