services:
  cache:
    image: memcached:1.6-alpine

  proxy:
    image: nginx:1.25-alpine
    depends_on:
      - ember
      - ember-camac-ng
      - django
      - keycloak
    volumes:
      - djangomedia:/var/lib/camac/media:ro
      # Mounting a subdirectory of a named volume currently isn't possible:
      # https://github.com/moby/moby/issues/32582
      - djangotmpmedia:/tmp/external-tmp:ro

  django: &django
    build:
      context: ../django
    depends_on:
      - cache
      - clamav
      - keycloak
      - unoconv
    environment:
      - APPLICATION=${APPLICATION}
      - DJANGO_CACHE_LOCATION=cache:11211
      - DJANGO_MEDIA_ROOT=/var/lib/camac/media
      - DJANGO_UNOCONV_URL=http://unoconv:3000
      - DJANGO_CLAMD_TCP_ADDR=clamav
      - DJANGO_MERGE_DATE_FORMAT=%-d. %B %Y
      - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - CACHE_LOCATION=cache:11211
      - EVENT_RECEIVER_MODULES=camac.caluma.extensions.events
      - VISIBILITY_CLASSES=camac.caluma.extensions.visibilities.CustomVisibilitySZ
      - PERMISSION_CLASSES=camac.caluma.extensions.permissions.CustomPermission
      - VALIDATION_CLASSES=camac.caluma.extensions.validations.CustomValidation
      - DATA_SOURCE_CLASSES=camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services
      - DYNAMIC_GROUPS_CLASSES=camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      - DYNAMIC_TASKS_CLASSES=camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - META_FIELDS=camac-instance-id,ebau-number,submit-date
      - ENABLE_HISTORICAL_API=true
    volumes:
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp

  django-q:
    <<: *django

  ember-camac-ng:
    build:
      context: ../
      dockerfile: ./ember-camac-ng/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:master
      args:
        - APPLICATION=${APPLICATION}

  ember:
    build:
      context: ../ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember:master


  unoconv:
    image: zrrrzzt/docker-unoconv-webservice:8.9.4

  clamav:
    image: tiredofit/clamav:2.3.0
    environment:
      - CONCURRENT_DATABASE_RELOAD=false
      - DEFINITIONS_UPDATE_FREQUENCY=1440
      - DEFINITIONS_UPDATE_BEGIN=0300
      - MAX_FILE_SIZE=60M
      - MAX_SCAN_SIZE=200M
      - STREAM_MAX_LENGTH=60M

  keycloak:
    build:
      context: ../keycloak
      cache_from:
        - acr.run/camac-ng/camac-ng/keycloak:master

  metabase:
    image: metabase/metabase:v0.45.3
    ports:
      - "666:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432

volumes:
  djangomedia:
  djangotmpmedia:
  phpsessions:
  templatefiles:
