version: "3.4"
services:
  cache:
    image: memcached:1.6-alpine

  proxy:
    image: nginx:1.25-alpine
    depends_on:
      - ember-caluma-portal
      - django
      - keycloak
      - ember-camac-ng
    volumes:
      - djangomedia:/var/lib/camac/media:ro
      - djangotmpmedia:/tmp/camac/tmpfiles:ro

  db:
    build:
      context: ../db
      cache_from:
        - acr.run/camac-ng/camac-ng/db:master
    environment:
      - POSTGRES_USER=camac
      - POSTGRES_DATABASE=${APPLICATION}
    volumes:
      - pgdata:/var/lib/postgresql/data

  ember-camac-ng:
    build:
      context: ../
      dockerfile: ./Dockerfile.ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:master
      args:
        - APPLICATION=${APPLICATION}
        - WORKSPACE=ember-camac-ng
      target: prod

  django:
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - db
      - keycloak
      - cache
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DJANGO_CACHE_LOCATION=cache:11211
      - DJANGO_MEDIA_ROOT=/var/lib/camac/media
      - DJANGO_CLAMD_TCP_ADDR=clamav
      - APPLICATION=${APPLICATION}
      - CACHE_BACKEND=django.core.cache.backends.memcached.PyMemcacheCache
      - CACHE_LOCATION=cache:11211
      - EVENT_RECEIVER_MODULES=camac.caluma.extensions.events
      - VISIBILITY_CLASSES=camac.caluma.extensions.visibilities.CustomVisibility
      - PERMISSION_CLASSES=camac.caluma.extensions.permissions.CustomPermission
      - VALIDATION_CLASSES=camac.caluma.extensions.validations.CustomValidation
      - DATA_SOURCE_CLASSES=camac.caluma.extensions.data_sources.Locations,camac.caluma.extensions.data_sources.Countries,camac.caluma.extensions.data_sources.Mitberichtsverfahren,camac.caluma.extensions.data_sources.Authorities,camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.ServicesForFinalReport
      - DYNAMIC_GROUPS_CLASSES=camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      - DYNAMIC_TASKS_CLASSES=camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - LANGUAGE_CODE=de
      - LANGUAGES=de,fr
      - OIDC_USERNAME_CLAIM=preferred_username
      - OIDC_BOOTSTRAP_BY_EMAIL_FALLBACK=true
      - URI_MIGRATE_PORTAL_USER=true
      - META_FIELDS=camac-instance-id,ebau-number,submit-date
      - ENABLE_HISTORICAL_API=true
      - KEYCLOAK_REALM=urec
      - DJANGO_USE_X_FORWARDED_HOST=True
      - VISIBILITY_PERFORMANCE_OPTIMISATIONS_ACTIVE=True
    volumes:
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp/camac/tmpfiles
    command: /bin/sh -c "./wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py collectstatic --noinput && uwsgi"

  ember-caluma-portal:
    build:
      context: ../
      dockerfile: ./Dockerfile.ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-caluma-portal:master
      args:
        - APPLICATION=${APPLICATION}
        - WORKSPACE=ember-caluma-portal
      target: prod


  clamav:
    image: tiredofit/clamav:2.6.8
    environment:
      - CONCURRENT_DATABASE_RELOAD=false
      - DEFINITIONS_UPDATE_FREQUENCY=1440
      - DEFINITIONS_UPDATE_BEGIN=0300

  keycloak:
    depends_on:
      - db
    build:
      context: ../keycloak
      cache_from:
        - acr.run/camac-ng/camac-ng/keycloak:master
    environment:
      - KC_DB_URL=jdbc:postgresql://db:5432/${APPLICATION}?currentSchema=keycloak

  document-merge-service:
    depends_on:
      - cache
    build:
      context: ../document-merge-service
      cache_from:
        - acr.run/camac-ng/camac-ng/document-merge-service:master
      args:
        APPLICATION: ${APPLICATION}
        CACHE_LOCATION: cache:11211
        EXTENSIONS_ARGUMENTS: DJANGO_API=http://django
    volumes:
      - ../document-merge-service/kt_uri/templatefiles:/var/lib/document-merge-service/media
      - ../document-merge-service/kt_uri/dump.json:/tmp/document-merge-service/dump.json

volumes:
  pgdata:
  djangomedia:
  djangotmpmedia:
  phpsessions:
  templatefiles:
