version: "3.4"
services:
  proxy:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/camac/nginx:/etc/nginx/conf.d:ro

  db:
    image: acr.run/camac-ng/camac-ng/db:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../db
      cache_from:
        - acr.run/camac-ng/camac-ng/db:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    volumes:
      - /etc/camac/postgres_password.conf:/run/secrets/postgres-passwd:ro

  django:
    image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    restart: always
    environment:
      - DJANGO_ENV_FILE=/run/secrets/django.env
      - GWR_WSK_ID=351388
      - GWR_HOUSING_STAT_BASE_URI=https://www-r.housing-stat.ch/regbl/api/ech0216/2
    volumes:
      - /etc/camac/django.env:/run/secrets/django.env:ro
      - /etc/camac/django/uwsgi-prod.ini:/app/uwsgi.ini

  document-merge-service:
    environment:
      - ENV_FILE=/run/secrets/document-merge-service.env
    volumes:
      - /etc/camac/document-merge-service.env:/run/secrets/document-merge-service.env:ro
      - /etc/camac/document-merge-service/uwsgi-prod.ini:/app/uwsgi.ini:ro

  php:
    image: acr.run/camac-ng/camac-ng/php:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../php
      cache_from:
        - acr.run/camac-ng/camac-ng/php:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    restart: always
    environment:
      - APPLICATION_ENV=production
    volumes:
      - /etc/camac/php.ini:/usr/local/etc/php/php.ini:ro
      - /etc/camac/application.ini:/var/www/camac/${APPLICATION}/configs/application.local.ini:ro

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../
      dockerfile: ./ember-camac-ng/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:${CI_COMMIT_REF_SLUG}-${APPLICATION}
      args:
        - APPLICATION=${APPLICATION}
    restart: always

  ember-caluma-portal:
    image: acr.run/camac-ng/camac-ng/ember-caluma-portal:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../
      dockerfile: ./ember-caluma-portal/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-caluma-portal:${CI_COMMIT_REF_SLUG}-${APPLICATION}
      args:
        - APPLICATION=${APPLICATION}
        - KEYCLOAK_HOST=${KEYCLOAK_HOST}
    restart: always

  cache:
    restart: always

  clamav:
    restart: always

  mailhog:
    restart: always

  keycloak:
    volumes:
      - /etc/camac/keycloak.env:/run/secrets/keycloak.env:ro
    environment:
      - ENV_FILE=/run/secrets/keycloak.env
    restart: always

volumes:
  pgdata:
    external:
      name: camacpgdata

  djangomedia:
    external:
      name: camacdjangomedia

  phpsessions:
    external:
      name: camacphpsessions

  phpresources:
    external:
      name: camacphpresources
