version: "3.4"
services:
  cache:
    ports:
      - "11211:11211"
    networks:
      - camac-ng.local

  proxy:
    volumes:
      - ../proxy/kt_uri.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      camac-ng.local:
        aliases:
          - camac-ng.local
          - camac-ng-portal.local
          - caluma-portal.local
          - camac-ng-keycloak.local

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:master
    networks:
      - camac-ng.local

  clamav:
    ports:
      - "3310:3310"
    networks:
      - camac-ng.local

  db:
    # Workaround, same name of image as cache_from
    # better be named differently once following is fixed:
    # https://github.com/docker/compose/issues/5458
    # see also other services below
    image: acr.run/camac-ng/camac-ng/db:master
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=camac
    volumes:
      - ../db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    networks:
      - camac-ng.local

  django:
    image: acr.run/camac-ng/camac-ng/django:master
    build:
      args:
        REQUIREMENTS: requirements-dev.txt
    ports:
      - "5555:5555"
      - "5678:5678"
    volumes:
      - ../django:/app
    environment:
      - ENV=development
      - APPLICATION_ENV=development
      - KEYCLOAK_URL=http://camac-ng-keycloak.local/auth/
      - DATABASE_PASSWORD=camac
      - DATABASE_USER=camac
      - DJANGO_EMAIL_HOST=mailhog
      - DJANGO_EMAIL_PORT=1025
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - OIDC_USERINFO_ENDPOINT=http://camac-ng-keycloak.local/auth/realms/urec/protocol/openid-connect/userinfo
      - GWR_FERNET_KEY=GUdwT6yKxqfszrnHC7wyKDmtVZdhjSVQEPnpeJYNLf8=
    networks:
      - camac-ng.local
    command: /bin/sh -c "./wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py collectstatic --noinput && ./manage.py runserver 0.0.0.0:80 --pythonpath /app/$APPLICATION"
    # Pro tip from 1337 backend devs: use this command and run `manage.py runserver 0:80 inside django container to enable pdb goodness
    # command: /bin/sh -c "while true; do sleep 10; done"

  ember-caluma-portal:
    image: acr.run/camac-ng/camac-ng/ember-caluma-portal:master
    networks:
      - camac-ng.local

  php:
    image: acr.run/camac-ng/camac-ng/php:master
    volumes:
      - ../php/php.ini-development:/usr/local/etc/php/php.ini:ro
      - ../php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ../php:/var/www/camac
      - /var/www/camac/vendor
      - /var/www/camac/configuration
      - /var/www/camac/public/node_modules
      - /var/www/camac/public/public-kt_uri/js/dist
      - /var/www/camac/public/public-kt_schwyz/js/dist
    environment:
      - APPLICATION_ENV=development
    networks:
      - camac-ng.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [
        "/bin/sh",
        "-c",
        "cd /var/www/camac \
        && chown -R www-data:www-data media sessions kt_uri/resources \
        && rm -f configuration/* \
        && cd configuration \
        && ln -sf ../${APPLICATION}/* . \
        && php -d xdebug.remote_enable=off /var/www/camac/cronjob/clear-cache.php \
        && apache2-foreground",
      ]

  mailhog:
    networks:
      - camac-ng.local
    environment:
      - MH_UI_WEB_PATH=mailhog

  keycloak:
    ports:
      - "8080:8080"
    volumes:
      - ../keycloak/${APPLICATION}-test-config.json:/etc/keycloak/test-config.json:ro
    environment:
      - DB_PASSWORD=camac
      - KEYCLOAK_PASSWORD=camac
    networks:
      - camac-ng.local
    # export is a bit tricky: We need to _start_ keycloak with specific arguments to perform an export
    # command: ["-Dkeycloak.migration.action=export", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/etc/keycloak/test-config.json", "-b", "0.0.0.0"]
    #
    # https://www.keycloak.org/docs/11.0/server_admin/#_export_import
    command:
      [
        "-Dkeycloak.migration.action=import",
        "-Dkeycloak.migration.provider=singleFile",
        "-Dkeycloak.migration.file=/etc/keycloak/test-config.json",
        "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING",
        "-b",
        "0.0.0.0",
      ]

  document-merge-service:
    networks:
      - camac-ng.local
    environment:
      - ENV=dev
      - DATABASE_PASSWORD=camac
      - OIDC_USERINFO_ENDPOINT=http://camac-ng-keycloak.local/auth/realms/urec/protocol/openid-connect/userinfo
      - OIDC_GROUPS_API=http://camac-ng.local/api/v1/me?include=service,service.service_parent
    # There appears to be bug where libreoffice can only be started as the root
    # user. The workaround of fixing owner and permissions of ~/.config did not
    # work in our case.
    #
    # https://github.com/unoconv/unoconv/issues/241#issuecomment-549434601
    # https://superuser.com/questions/564534/only-root-user-is-able-to-open-libreoffice
    # user: "${UID:?Set UID env variable to your user id}"
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it.sh db:5432 -- ./manage.py migrate && uwsgi",
      ]

networks:
  camac-ng.local:
