DELETE FROM ANSWER;
-- ANSWER has no sequence

DELETE FROM ANSWER_LOG;
DROP SEQUENCE "ANSWER_LOG_SEQ";
CREATE SEQUENCE "ANSWER_LOG_SEQ";

DELETE FROM ACTIVATION_ANSWER;
-- ACTIVATION_ANSWER has no sequence

DELETE FROM ACTIVATION_ANSWER_LOG;
DROP SEQUENCE "ACTIVATION_ANSWER_LOG_SEQ";
CREATE SEQUENCE "ACTIVATION_ANSWER_LOG_SEQ";


DELETE FROM NOTICE;
-- NOTICE has no sequence
DELETE FROM NOTICE_LOG;
DROP SEQUENCE "NOTICE_LOG_SEQ";
CREATE SEQUENCE "NOTICE_LOG_SEQ";

DELETE FROM DOCGEN_ACTIVATION_DOCKET;
DROP SEQUENCE "DOCGEN_ACTIVATION_DOCKET_SEQ";
CREATE SEQUENCE "DOCGEN_ACTIVATION_DOCKET_SEQ";

DELETE FROM ACTIVATION;
DROP SEQUENCE "ACTIVATION_SEQ";
CREATE SEQUENCE "ACTIVATION_SEQ";

DELETE FROM ACTIVATION_LOG;
DROP SEQUENCE "ACTIVATION_LOG_SEQ";
CREATE SEQUENCE "ACTIVATION_LOG_SEQ";

DELETE FROM CIRCULATION;
DROP SEQUENCE "CIRCULATION_SEQ";
CREATE SEQUENCE "CIRCULATION_SEQ";

DELETE FROM CIRCULATION_LOG;
DROP SEQUENCE "CIRCULATION_LOG_SEQ";
CREATE SEQUENCE "CIRCULATION_LOG_SEQ";

DELETE FROM INSTANCE_LOCATION;
-- no sequence

DELETE FROM INSTANCE_LOCATION_LOG;
DROP SEQUENCE "INSTANCE_LOCATION_LOG_SEQ";
CREATE SEQUENCE "INSTANCE_LOCATION_LOG_SEQ";

DELETE FROM ATTACHMENT;
DROP SEQUENCE "ATTACHMENT_SEQ";
CREATE SEQUENCE "ATTACHMENT_SEQ";

DELETE FROM WORKFLOW_ENTRY;
DROP SEQUENCE "WORKFLOW_ENTRY_SEQ";
CREATE SEQUENCE "WORKFLOW_ENTRY_SEQ";

DELETE FROM BILLING_ENTRY;
DROP SEQUENCE "BILLING_ENTRY_SEQ";
CREATE SEQUENCE "BILLING_ENTRY_SEQ";

DELETE FROM PUBLICATION_ENTRY;
DROP SEQUENCE "PUBLICATION_ENTRY_SEQ";
CREATE SEQUENCE "PUBLICATION_ENTRY_SEQ";

DELETE FROM INSTANCE;
DROP SEQUENCE "INSTANCE_SEQ";
CREATE SEQUENCE "INSTANCE_SEQ";

DELETE FROM INSTANCE_LOG;
DROP SEQUENCE "INSTANCE_LOG_SEQ";
CREATE SEQUENCE "INSTANCE_LOG_SEQ";
