# Generated by Django 5.2.11 on 2026-02-23 09:23

import django.db.models.deletion
import uuid_extensions.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caluma_workflow', '0035_uuid_v7'),
        ('instance', '0043_alter_historyentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False)),
                ('timeline_type', models.CharField(choices=[('project-change', 'Project Change'), ('submit-after-rejection', 'Submit After Rejection'), ('additional-demand', 'Additional Demand'), ('correction', 'Correction')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cases', models.ManyToManyField(blank=True, related_name='form_timelines', to='caluma_workflow.case')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_timelines', to='instance.instance')),
            ],
        ),
    ]
