# Generated by Django 4.2.20 on 2025-07-02 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.char_field
import uuid_extensions.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0032_user_division'),
        ('instance', '0041_instance_copy_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caluma_workflow', '0035_uuid_v7'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineType',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', localized_fields.fields.char_field.LocalizedCharField(required=['de'], verbose_name='Name')),
                ('lead_time', models.PositiveIntegerField(verbose_name='Lead time in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Is default')),
                ('service_groups', models.ManyToManyField(blank=True, to='user.servicegroup', verbose_name='Service groups')),
                ('services', models.ManyToManyField(blank=True, to='user.service', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Deadline type',
                'verbose_name_plural': 'Deadline types',
            },
        ),
        migrations.CreateModel(
            name='InstanceDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('total_days_of_suspension', models.PositiveIntegerField(blank=True, null=True)),
                ('process_deadline_date', models.DateField(blank=True, null=True)),
                ('process_deadline_days', models.PositiveIntegerField(blank=True, help_text='The number of days processed since the start date.', null=True, verbose_name='Process deadline days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='deadlines.deadlinetype')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deadlines', to='instance.instance')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.service')),
            ],
            options={
                'verbose_name': 'Instance deadline',
                'verbose_name_plural': 'Instance deadlines',
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('additional_demand_suspension', 'Additional demand suspension'), ('manual_suspension', 'Manual suspension')], default='manual_suspension')),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suspensions', to='deadlines.instancedeadline')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='caluma_workflow.workitem')),
            ],
        ),
    ]
