# Generated by Django 4.2.20 on 2025-07-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancedeadline',
            name='process_deadline_date_override',
            field=models.BooleanField(default=False, help_text='If set, the process deadline date is manually set and not calculated.', verbose_name='Process deadline date override'),
        ),
    ]
