# Generated by Django 4.2.20 on 2025-08-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0002_instancedeadline_process_deadline_date_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspension',
            name='reason',
            field=models.CharField(choices=[('additional_demand_suspension', 'Additional demand suspension'), ('inquiry_claim_suspension', 'Inquiry claim suspension'), ('manual_suspension', 'Manual suspension')], default='manual_suspension'),
        ),
    ]
