# Generated by Django 5.2.6 on 2025-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0003_alter_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancedeadline',
            name='target_deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
