# Generated by Django 5.2.7 on 2025-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0004_instancedeadline_target_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlinetype',
            name='exclude_public_holidays',
            field=models.BooleanField(default=False, help_text='If enabled, public holidays are not counted towards deadlines.', verbose_name='Exclude public holidays'),
        ),
        migrations.AddField(
            model_name='deadlinetype',
            name='exclude_weekends',
            field=models.BooleanField(default=False, help_text='If enabled, weekends are not counted towards deadlines.', verbose_name='Exclude weekends'),
        ),
    ]
