# Generated by Django 5.2.7 on 2025-10-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0005_deadlinetype_exclude_public_holidays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlinetype',
            name='form_types',
            field=models.JSONField(blank=True, help_text='List of form IDs this deadline type applies to. If empty, applies to all forms.', null=True, verbose_name='Form types'),
        ),
    ]
