# Generated by Django 5.2.8 on 2026-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0006_deadlinetype_form_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancedeadline',
            name='completed',
            field=models.BooleanField(default=False, help_text='Indicates whether the deadline is completed.', verbose_name='Completed'),
        ),
    ]
