# Generated by Django 5.2.8 on 2026-02-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0006_deadlinetype_form_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspension',
            old_name='reason_text',
            new_name='remark',
        ),
    ]
