# Generated by Django 5.2.11 on 2026-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0007_rename_reason_text_suspension_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspension',
            name='reason',
            field=models.CharField(choices=[('additional_demand_suspension', 'Additional demand suspension'), ('inquiry_claim_suspension', 'Inquiry claim suspension'), ('incomplete_suspension', 'Incomplete suspension'), ('request_project_change_suspension', 'Request project change suspension'), ('manual_suspension', 'Manual suspension')], default='manual_suspension'),
        ),
    ]
