# Generated by Django 5.2.11 on 2026-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0008_alter_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlinetype',
            name='procedure_type',
            field=models.CharField(blank=True, choices=[('simplified', 'Simplified procedure'), ('regular', 'Regular procedure')], max_length=20, null=True, verbose_name='Procedure type'),
        ),
    ]
