parent=keycloak

styles=css/style.css
stylesCommon=node_modules/patternfly/dist/css/patternfly.min.css node_modules/patternfly/dist/css/patternfly-additions.min.css lib/pficon/pficon.css
scripts=js/script.js

locales=de,fr

kcFormClass=sign-in-form
kcLocaleListClass=language-selector
kcLocaleListItemClass=language
kcLocaleItemClass=service-menue language-tag

