#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE kt_schwyz;
    GRANT ALL PRIVILEGES ON DATABASE kt_schwyz TO $POSTGRES_USER;
    CREATE DATABASE kt_uri;
    GRANT ALL PRIVILEGES ON DATABASE kt_uri TO $POSTGRES_USER;
    CREATE DATABASE kt_bern;
    GRANT ALL PRIVILEGES ON DATABASE kt_bern TO $POSTGRES_USER;
    CREATE DATABASE demo;
    GRANT ALL PRIVILEGES ON DATABASE demo TO $POSTGRES_USER;
    CREATE DATABASE kt_gr;
    GRANT ALL PRIVILEGES ON DATABASE kt_gr TO $POSTGRES_USER;
    CREATE DATABASE kt_so;
    GRANT ALL PRIVILEGES ON DATABASE kt_so TO $POSTGRES_USER;
    CREATE DATABASE metabase;
    GRANT ALL PRIVILEGES ON DATABASE metabase TO $POSTGRES_USER;
    \c kt_uri;
    CREATE SCHEMA keycloak AUTHORIZATION $POSTGRES_USER;
    \c kt_bern;
    CREATE SCHEMA keycloak AUTHORIZATION $POSTGRES_USER;
    \c kt_gr;
    CREATE SCHEMA keycloak AUTHORIZATION $POSTGRES_USER;
    \c kt_so;
    CREATE SCHEMA keycloak AUTHORIZATION $POSTGRES_USER;
    \c demo;
    CREATE SCHEMA keycloak AUTHORIZATION $POSTGRES_USER;
EOSQL
