#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE kt_schwyz;
    GRANT ALL PRIVILEGES ON DATABASE kt_schwyz TO $POSTGRES_USER;
    CREATE DATABASE kt_uri;
    GRANT ALL PRIVILEGES ON DATABASE kt_uri TO $POSTGRES_USER;
    CREATE DATABASE demo;
    GRANT ALL PRIVILEGES ON DATABASE demo TO $POSTGRES_USER;
EOSQL
