# Default CSP variables
# =====================
# Include this file before setting any overrides and before csp_headers.inc.

set $csp_keycloak_url "";
set $csp_use_google_fonts "false";
set $csp_use_font_data_url "false";
set $csp_portal_allow_inline_style "false";
set $csp_internal_allow_inline_style "false";
set $csp_php_allow_unsafe_eval "false";
set $csp_php_allow_localhost_scripts "false";
set $csp_external_connect_sources "";
set $csp_external_img_sources "";
set $csp_external_style_sources "";
set $csp_external_frame_sources "";
set $csp_enable_swagger "false";
