# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(db_column='NAME', max_length=500),
        ),
    ]
