# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group'),
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='instance',
            name='previous_instance_state',
            field=models.ForeignKey(db_column='PREVIOUS_INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.InstanceState'),
        ),
        migrations.AddField(
            model_name='instance',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='form_state',
            field=models.ForeignKey(db_column='FORM_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.FormState'),
        ),
    ]
