# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 15:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0002_auto_20171220_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='instance.Instance')),
            ],
        ),
        migrations.AlterField(
            model_name='instancestatedescription',
            name='instance_state',
            field=models.OneToOneField(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='description', serialize=False, to='instance.InstanceState'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together=set([('instance', 'name')]),
        ),
    ]
