# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0002_auto_20180312_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancestate',
            name='description',
            field=models.CharField(blank=True, db_column='DESCRIPTION', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instancestatedescription',
            name='instance_state',
            field=models.OneToOneField(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='instance.InstanceState'),
        ),
    ]
