# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20180531_1314'),
        ('instance', '0003_auto_20180530_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='instance.Instance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
