# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0006_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_column='LANGUAGE', max_length=2)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=500, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=1000, null=True)),
                ('form', models.ForeignKey(db_column='FORM_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instance.Form')),
            ],
            options={
                'db_table': 'FORM_T',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstanceStateT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_column='LANGUAGE', max_length=2)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=1000, null=True)),
                ('instance_state', models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instance.InstanceState')),
            ],
            options={
                'db_table': 'INSTANCE_STATE_T',
                'managed': True,
            },
        ),
    ]
