# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0007_formt_instancestatet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(blank=True, db_column='NAME', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instancestate',
            name='name',
            field=models.CharField(blank=True, db_column='NAME', max_length=100, null=True),
        ),
    ]
