# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 12:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0007_formt_instancestatet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
