# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20181119_1558'),
        ('instance', '0008_auto_20190125_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DecimalField(decimal_places=2, max_digits=10)),
                ('text', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_templates', to='instance.Instance')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueTemplateSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Group')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_template_sets', to='instance.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='IssueTemplateSetIssueTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instance.IssueTemplate')),
                ('issue_template_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_template_set_issue_templates', to='instance.IssueTemplateSet')),
            ],
        ),
        migrations.AddField(
            model_name='issuetemplateset',
            name='issue_templates',
            field=models.ManyToManyField(through='instance.IssueTemplateSetIssueTemplate', to='instance.IssueTemplate'),
        ),
        migrations.AddField(
            model_name='issuetemplateset',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Service'),
        ),
    ]
