# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0009_issuetemplate_issuetemplateset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetemplateset',
            name='issue_templates',
            field=models.ManyToManyField(blank=True, related_name='issue_template_sets', to='instance.IssueTemplate'),
        ),
    ]
