# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0010_auto_20190212_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancestatet',
            name='instance_state',
            field=models.ForeignKey(db_column='INSTANCE_STATE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='instance.InstanceState'),
        ),
    ]
