# Generated by Django 2.2.9 on 2020-02-05 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("instance", "0015_instance_service")]

    operations = [
        migrations.RunSQL(
            """CREATE INDEX "document_instance_id" ON caluma_form_document((meta->'camac-instance-id'));"""
        )
    ]

