# Generated by Django 2.2.17 on 2021-08-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instance", "0029_instance_case_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, db_column="CREATION_DATE"),
        ),
        migrations.AlterField(
            model_name="instance",
            name="modification_date",
            field=models.DateTimeField(
                auto_now_add=True, db_column="MODIFICATION_DATE"
            ),
        ),
    ]
