# Generated by Django 2.2.17 on 2021-10-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instance", "0031_reconnect_instance_case"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstanceGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="instance",
            name="instance_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="instances",
                to="instance.InstanceGroup",
            ),
        ),
    ]
