# Generated by Django 2.2.17 on 2022-01-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instance", "0032_auto_20211021_1901"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
