# Generated by Django 2.2.17 on 2022-02-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0034_auto_20220301_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='family',
            field=models.ForeignKey(db_column='FAMILY', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instance.Form'),
        ),
    ]
