# Generated by Django 4.2.20 on 2025-04-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0039_instance_rejection_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancestate',
            options={'managed': True, 'ordering': ('sort',)},
        ),
    ]
