# Generated by Django 4.2.20 on 2025-06-10 08:29

import django.db.models.deletion
from django.db import migrations, models


def migrate_copied_instances(apps, schema_editor):
    Instance = apps.get_model("instance", "Instance")

    for copy in Instance.objects.exclude(case__document__source__isnull=True).iterator(
        chunk_size=1000
    ):
        copy.copy_source = copy.case.document.source.case.instance
        copy.save(update_fields=["copy_source"])


class Migration(migrations.Migration):
    dependencies = [("instance", "0040_alter_instancestate_options")]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="copy_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="instance.instance",
            ),
        ),
        migrations.RunPython(migrate_copied_instances, migrations.RunPython.noop),
    ]
