# Generated by Django 5.2.6 on 2025-10-06 11:22

from django.conf import settings
from django.db import migrations


def fix_field_values(form_field_class):
    points_fields = form_field_class.objects.filter(
        name="punkte", value__0__has_any_keys=["lng", "lat"]
    )
    for field in points_fields.iterator():
        new_value = []
        for point in field.value:
            new_value.append([point])
        field.value = new_value
        field.save()


def forwards(apps, schema_editor):
    """Wrap 'punkte' values in a list each.

    The dossier import has wrongly added coordinate points in a single
    list instead of treating each point as a path of length 1.

    This migration finds all form fields of name `punkte` whose value is
    a list of {'lng': xyz, 'lat', xyz} and wraps these in a list to
    comply with the required structure.
    """
    if settings.APPLICATION_NAME != "kt_schwyz":
        return

    FormField = apps.get_model("instance", "FormField")
    fix_field_values(FormField)


class Migration(migrations.Migration):
    dependencies = [
        ("instance", "0041_instance_copy_source"),
    ]
    operations = [migrations.RunPython(forwards)]
