# Generated by Django 5.2.11 on 2026-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0043_alter_historyentry_user'),
        ('tags', '0006_instancemark'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instance_marks',
            field=models.ManyToManyField(related_name='instances', to='tags.instancemark'),
        ),
    ]
