CREATE OR REPLACE FUNCTION GET_STATE_ID_BY_NAME(STATE_NAME IN VARCHAR2)
	RETURN number
IS
	stateID number;
BEGIN
	SELECT
		INSTANCE_STATE_ID into stateID
	FROM
		INSTANCE_STATE
	WHERE
		LOWER(NAME) = LOWER(STATE_NAME);

	RETURN stateID;
END;
/

CREATE OR REPLACE FUNCTION GET_STATE_NAME_BY_ID(STATE_ID IN NUMBER)
	RETURN VARCHAR2
IS
	STATE_NAME VARCHAR2(255);
BEGIN
	SELECT
		NAME into STATE_NAME
	FROM
		INSTANCE_STATE
	WHERE
		INSTANCE_STATE_ID = STATE_ID;
	
	RETURN STATE_NAME;
END;
/
