Insert into AVAILABLE_INSTANCE_RESOURCE (AVAILABLE_INSTANCE_RESOURCE_ID,MODULE_NAME,CONTROLLER_NAME,DESCRIPTION) values ('documents','documents','list','List the Documents');
Insert into AIR_ACTION (AVAILABLE_INSTANCE_RESOURCE_ID,ACTION_NAME,HIDDEN) values ('documents','list',0);
Insert into AIR_ACTION (AVAILABLE_INSTANCE_RESOURCE_ID,ACTION_NAME,HIDDEN) values ('documents','upload',1);
Insert into AIR_ACTION (AVAILABLE_INSTANCE_RESOURCE_ID,ACTION_NAME,HIDDEN) values ('documents','download',1);
Insert into AIR_ACTION (AVAILABLE_INSTANCE_RESOURCE_ID,ACTION_NAME,HIDDEN) values ('documents','preview',1);
--------------------------------------------------------
--  File created - Friday-June-06-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ATTACHMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATTACHMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Table ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "ATTACHMENT" (
	"ATTACHMENT_ID" NUMBER,
	"NAME" VARCHAR2(255),
	"INSTANCE_ID" NUMBER,
	"PATH" VARCHAR2(255),
	"SIZE" NUMBER,
	"DATE" DATE,
	"USER_ID" NUMBER(10,0),
	"IDENTIFIER" VARCHAR2(255),
	"MIME_TYPE"  VARCHAR2(255)
);
--------------------------------------------------------
--  Constraints for Table ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "ATTACHMENT_PK" PRIMARY KEY ("ATTACHMENT_ID") ENABLE;
  ALTER TABLE "ATTACHMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENT" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENT" MODIFY ("SIZE" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENT" MODIFY ("PATH" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENT" MODIFY ("INSTANCE_ID" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENT" MODIFY ("ATTACHMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENT" MODIFY ("IDENTIFIER" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENT" MODIFY ("MIME_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "ATTACHMENT_FK1" FOREIGN KEY ("INSTANCE_ID") REFERENCES "INSTANCE" ("INSTANCE_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "ATTACHMENT_USER_FK" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("USER_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ATTACHMENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATTACHMENT_TRG" 
BEFORE INSERT ON ATTACHMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ATTACHMENT_ID IS NULL THEN
      SELECT ATTACHMENT_SEQ.NEXTVAL INTO :NEW.ATTACHMENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ATTACHMENT_TRG" ENABLE;
/

