Insert into AVAILABLE_INSTANCE_RESOURCE (AVAILABLE_INSTANCE_RESOURCE_ID,MODULE_NAME,CONTROLLER_NAME,DESCRIPTION) values ('workflow','workflow','list','Show the workflow entries');
Insert into AIR_ACTION (AVAILABLE_INSTANCE_RESOURCE_ID,ACTION_NAME,HIDDEN) values ('workflow','list',0);
Insert into AIR_ACTION (AVAILABLE_INSTANCE_RESOURCE_ID,ACTION_NAME,HIDDEN) values ('workflow','save',1);


INSERT INTO "AVAILABLE_ACTION" (AVAILABLE_ACTION_ID, MODULE_NAME, DESCRIPTION)
VALUES
('workflow', 'workflow', 'Set workflow date');

INSERT INTO "INSTANCE_RESOURCE_ACTION" (AVAILABLE_ACTION_ID, AVAILABLE_INSTANCE_RESOURCE_ID)
VALUES
('workflow', 'circulation');

INSERT INTO "INSTANCE_RESOURCE_ACTION" (AVAILABLE_ACTION_ID, AVAILABLE_INSTANCE_RESOURCE_ID) VALUES ('workflow', 'circulation');
INSERT INTO "INSTANCE_RESOURCE_ACTION" (AVAILABLE_ACTION_ID, AVAILABLE_INSTANCE_RESOURCE_ID) VALUES ('workflow', 'editnotice');
INSERT INTO "INSTANCE_RESOURCE_ACTION" (AVAILABLE_ACTION_ID, AVAILABLE_INSTANCE_RESOURCE_ID) VALUES ('workflow', 'formpages');
INSERT INTO "INSTANCE_RESOURCE_ACTION" (AVAILABLE_ACTION_ID, AVAILABLE_INSTANCE_RESOURCE_ID) VALUES ('workflow', 'allformpages');
INSERT INTO "INSTANCE_RESOURCE_ACTION" (AVAILABLE_ACTION_ID, AVAILABLE_INSTANCE_RESOURCE_ID) VALUES ('workflow', 'editcirculation');
INSERT INTO "INSTANCE_RESOURCE_ACTION" (AVAILABLE_ACTION_ID, AVAILABLE_INSTANCE_RESOURCE_ID) VALUES ('workflow', 'editformpages');
INSERT INTO "INSTANCE_RESOURCE_ACTION" (AVAILABLE_ACTION_ID, AVAILABLE_INSTANCE_RESOURCE_ID) VALUES ('workflow', 'page');
INSERT INTO "INSTANCE_RESOURCE_ACTION" (AVAILABLE_ACTION_ID, AVAILABLE_INSTANCE_RESOURCE_ID) VALUES ('workflow', 'editformpage');


--------------------------------------------------------
--  File created - Thursday-August-21-2014   
--------------------------------------------------------
-- Unable to render SEQUENCE DDL for object CAMAC_DEV.WORKFLOW_ENTRY_SEQ with DBMS_METADATA attempting internal generator.
CREATE SEQUENCE WORKFLOW_ENTRY_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
/
-- Unable to render SEQUENCE DDL for object CAMAC_DEV.WORKFLOW_ITEM_SEQ with DBMS_METADATA attempting internal generator.
CREATE SEQUENCE WORKFLOW_ITEM_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
/
-- Unable to render TABLE DDL for object CAMAC_DEV.WORKFLOW_ACTION with DBMS_METADATA attempting internal generator.
ALTER TABLE WORKFLOW_ACTION
ADD CONSTRAINT WORKFLOW_ACTION_FK1 FOREIGN KEY
(
  ACTION_ID 
)
REFERENCES ACTION
(
  ACTION_ID 
)
ENABLE
ALTER TABLE WORKFLOW_ACTION
ADD CONSTRAINT WORKFLOW_ACTION_FK2 FOREIGN KEY
(
  WORKFLOW_ITEM_ID 
)
REFERENCES WORKFLOW_ITEM
(
  WORKFLOW_ITEM_ID 
)
ENABLECREATE TABLE WORKFLOW_ACTION 
(
  ACTION_ID NUMBER NOT NULL 
, WORKFLOW_ITEM_ID NUMBER NOT NULL 
, CONSTRAINT WORKFLOW_ACTION_PK PRIMARY KEY 
  (
    ACTION_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)
/
-- Unable to render TABLE DDL for object CAMAC_DEV.WORKFLOW_ENTRY with DBMS_METADATA attempting internal generator.
ALTER TABLE WORKFLOW_ENTRY
ADD CONSTRAINT WORKFLOW_ENTRY_INSTANCE FOREIGN KEY
(
  INSTANCE_ID 
)
REFERENCES INSTANCE
(
  INSTANCE_ID 
)
ON DELETE CASCADE ENABLE
ALTER TABLE WORKFLOW_ENTRY
ADD CONSTRAINT WORKFLOW_ENTRY_WORKFLOW FOREIGN KEY
(
  WORKFLOW_ITEM_ID 
)
REFERENCES WORKFLOW_ITEM
(
  WORKFLOW_ITEM_ID 
)
ON DELETE CASCADE ENABLECREATE TABLE WORKFLOW_ENTRY 
(
  WORKFLOW_ENTRY_ID NUMBER NOT NULL 
, WORKFLOW_DATE DATE NOT NULL 
, INSTANCE_ID NUMBER NOT NULL 
, WORKFLOW_ITEM_ID NUMBER NOT NULL 
, CONSTRAINT WORKFLOW_ENTRY_PK PRIMARY KEY 
  (
    WORKFLOW_ENTRY_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)
/
-- Unable to render TABLE DDL for object CAMAC_DEV.WORKFLOW_ITEM with DBMS_METADATA attempting internal generator.
CREATE TABLE WORKFLOW_ITEM 
(
  WORKFLOW_ITEM_ID NUMBER NOT NULL 
, POSITION NUMBER NOT NULL 
, NAME VARCHAR2(255 BYTE) NOT NULL 
, AUTOMATICAL NUMBER(1, 0) DEFAULT 0 NOT NULL 
, DIFFERENT_COLOR NUMBER(1, 0) DEFAULT 0 NOT NULL 
, CONSTRAINT WORKFLOW_ITEM_PK PRIMARY KEY 
  (
    WORKFLOW_ITEM_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)
/
-- Unable to render TABLE DDL for object CAMAC_DEV.WORKFLOW_ROLE with DBMS_METADATA attempting internal generator.
ALTER TABLE WORKFLOW_ROLE
ADD CONSTRAINT WORKFLOW_ROLE_ROLE FOREIGN KEY
(
  ROLE_ID 
)
REFERENCES ROLE
(
  ROLE_ID 
)
ON DELETE CASCADE ENABLE
ALTER TABLE WORKFLOW_ROLE
ADD CONSTRAINT WORKFLOW_ROLE_WORKFLOW FOREIGN KEY
(
  WORKFLOW_ITEM_ID 
)
REFERENCES WORKFLOW_ITEM
(
  WORKFLOW_ITEM_ID 
)
ON DELETE CASCADE ENABLECREATE TABLE WORKFLOW_ROLE 
(
  WORKFLOW_ITEM_ID NUMBER NOT NULL 
, ROLE_ID NUMBER NOT NULL 
, CONSTRAINT WORKFLOW_ROLE_PK PRIMARY KEY 
  (
    ROLE_ID 
  , WORKFLOW_ITEM_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)
/
-- Unable to render INDEX DDL for object CAMAC_DEV.WORKFLOW_ACTION_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WORKFLOW_ACTION_PK ON WORKFLOW_ACTION (ACTION_ID) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)
/
-- Unable to render INDEX DDL for object CAMAC_DEV.WORKFLOW_ENTRY_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WORKFLOW_ENTRY_PK ON WORKFLOW_ENTRY (WORKFLOW_ENTRY_ID) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)
/
-- Unable to render INDEX DDL for object CAMAC_DEV.WORKFLOW_ITEM_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WORKFLOW_ITEM_PK ON WORKFLOW_ITEM (WORKFLOW_ITEM_ID) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)
/
-- Unable to render INDEX DDL for object CAMAC_DEV.WORKFLOW_ROLE_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX WORKFLOW_ROLE_PK ON WORKFLOW_ROLE (ROLE_ID, WORKFLOW_ITEM_ID) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)
/
-- Unable to render TRIGGER DDL for object CAMAC_DEV.WORKFLOW_ENTRY_TRG with DBMS_METADATA attempting internal generator.
CREATE TRIGGER "WORKFLOW_ENTRY_TRG" BEFORE INSERT ON WORKFLOW_ENTRY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.WORKFLOW_ENTRY_ID IS NULL THEN
      SELECT WORKFLOW_ENTRY_SEQ.NEXTVAL INTO :NEW.WORKFLOW_ENTRY_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
-- Unable to render TRIGGER DDL for object CAMAC_DEV.WORKFLOW_ITEM_TRG with DBMS_METADATA attempting internal generator.
CREATE TRIGGER "WORKFLOW_ITEM_TRG" BEFORE INSERT ON WORKFLOW_ITEM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.WORKFLOW_ITEM_ID IS NULL THEN
      SELECT WORKFLOW_ITEM_SEQ.NEXTVAL INTO :NEW.WORKFLOW_ITEM_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
