# Generated by Django 2.2.17 on 2021-10-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_servicegroup_sort'),
        ('dossier_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierimport',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.Service'),
        ),
        migrations.AddField(
            model_name='historicaldossierimport',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Service'),
        ),
    ]
