# Generated by Django 2.2.17 on 2022-01-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_import', '0003_add_field_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierimport',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('new', 'new'), ('in-progress', 'in-progress'), ('verified', 'verified'), ('failed', 'failed')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicaldossierimport',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('new', 'new'), ('in-progress', 'in-progress'), ('verified', 'verified'), ('failed', 'failed')], default='new', max_length=32),
        ),
    ]
