# Generated by Django 2.2.17 on 2022-01-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossier_import", "0004_auto_20220107_1708"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossierimport",
            name="service",
        ),
        migrations.RemoveField(
            model_name="historicaldossierimport",
            name="service",
        ),
        migrations.AlterField(
            model_name="dossierimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("in-progress", "in-progress"),
                    ("verified", "verified"),
                    ("failed", "failed"),
                    ("imported", "imported"),
                    ("confirmed", "confirmed"),
                    ("transmitting", "transmitting"),
                    ("transmitted", "transmitted"),
                ],
                default="new",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldossierimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("in-progress", "in-progress"),
                    ("verified", "verified"),
                    ("failed", "failed"),
                    ("imported", "imported"),
                    ("confirmed", "confirmed"),
                    ("transmitting", "transmitting"),
                    ("transmitted", "transmitted"),
                ],
                default="new",
                max_length=32,
            ),
        ),
    ]
