# Generated by Django 3.2.12 on 2022-03-01 13:32

import camac.dossier_import.messages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_import', '0005_auto_20220119_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierimport',
            name='messages',
            field=models.JSONField(default=camac.dossier_import.messages.default_messages_object),
        ),
        migrations.AlterField(
            model_name='historicaldossierimport',
            name='messages',
            field=models.JSONField(default=camac.dossier_import.messages.default_messages_object),
        ),
    ]
