# Generated by Django 3.2.13 on 2022-06-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_import', '0006_auto_20220301_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldossierimport',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical dossier import', 'verbose_name_plural': 'historical dossier imports'},
        ),
        migrations.AlterField(
            model_name='historicaldossierimport',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
