# Generated by Django 3.2.15 on 2023-01-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_import', '0007_simple_history_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierimport',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('verified', 'verified'), ('failed', 'failed'), ('in-progress', 'in-progress'), ('imported', 'imported'), ('import-failed', 'import-failed'), ('confirmed', 'confirmed'), ('cleaned', 'cleaned'), ('clean-failed', 'clean-failed'), ('undo-in-progress', 'undo-in-progress'), ('undo-failed', 'undo-failed'), ('undone', 'undone'), ('transmitting', 'transmitting'), ('transmitted', 'transmitted')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicaldossierimport',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('verified', 'verified'), ('failed', 'failed'), ('in-progress', 'in-progress'), ('imported', 'imported'), ('import-failed', 'import-failed'), ('confirmed', 'confirmed'), ('cleaned', 'cleaned'), ('clean-failed', 'clean-failed'), ('undo-in-progress', 'undo-in-progress'), ('undo-failed', 'undo-failed'), ('undone', 'undone'), ('transmitting', 'transmitting'), ('transmitted', 'transmitted')], default='new', max_length=32),
        ),
    ]
