# Generated by Django 4.2.20 on 2025-03-31 03:50

from django.db import migrations, models
import uuid_extensions.uuid7


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_import', '0008_add_status_choices_for_async_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierimport',
            name='id',
            field=models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaldossierimport',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid_extensions.uuid7, editable=False),
        ),
    ]
