# Generated by Django 5.2.7 on 2025-11-26 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dossier_import", "0009_alter_dossierimport_id"),
        ("instance", "0042_data_fix_sz_punkte_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationDocumentStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dms_id", models.CharField(max_length=255)),
                ("dms_version", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("ungültig", "ungültig"), ("bewilligt", "bewilligt")],
                        max_length=50,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migration_document_statuses",
                        to="instance.instance",
                    ),
                ),
            ],
            options={
                "db_table": "dossier_import_migration_document_status",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instance", "dms_id", "dms_version"),
                        name="migration_document_status_pk",
                    )
                ],
            },
        ),
    ]
