# Generated by Django 5.2.8 on 2025-12-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_import', '0009_alter_dossierimport_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierimport',
            name='created_by_group',
        ),
        migrations.RemoveField(
            model_name='dossierimport',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='dossierimport',
            name='modified_by_group',
        ),
        migrations.RemoveField(
            model_name='dossierimport',
            name='modified_by_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDossierImport',
        ),
    ]
