# Generated by Django 5.2.8 on 2026-01-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_import', '0010_migrationdocumentstatus'),
        ('dossier_import', '0010_remove_obsolete_fields'),
    ]

    operations = [
    ]
