# Generated by Django 5.2.11 on 2026-03-11 14:39

from django.db import migrations

from datetime import datetime, timezone

from django.utils.timezone import is_aware, make_aware
from django.utils.dateparse import parse_datetime

from camac.instance.domain_logic import SUBMIT_DATE_FORMAT


def migrate_dossier_import_submit_dates(apps, schema_editor):
    Instance = apps.get_model("instance", "Instance")
    instances = Instance.objects.filter(
        **{
            "case__meta__import-id__isnull": False,
        }
    )

    for instance in instances.iterator():
        meta = instance.case.meta
        if not meta.get("submit-date"):
            continue

        submit_date = parse_datetime(meta.get("submit-date"))

        if is_aware(submit_date):
            continue

        submit_date = make_aware(submit_date, timezone=timezone.utc)
        meta["submit-date"] = datetime.strftime(submit_date, SUBMIT_DATE_FORMAT)

        instance.case.meta = meta
        instance.case.save(update_fields=["meta"])


class Migration(migrations.Migration):
    dependencies = [
        ('dossier_import', '0011_merge_20260105_0803'),
    ]

    operations = [
        migrations.RunPython(migrate_dossier_import_submit_dates),
    ]
