# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_auto_20190403_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='instance.Instance'),
        ),
    ]
