# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_auto_20190508_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='created',
            field=models.DateTimeField(auto_now=True, db_column='CREATED'),
        ),
    ]
