# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-27 14:46
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Instance = apps.get_model("instance", "Instance")

    for instance in Instance.objects.all():
        if instance.involved_applicants.count() == 0:
            instance.involved_applicants.create(
                user=instance.user,
                invitee=instance.user,
                created=instance.creation_date,
            )


class Migration(migrations.Migration):

    dependencies = [("applicants", "0003_auto_20190729_1511")]

    operations = [migrations.RunPython(forwards)]
