# Generated by Django 2.2.14 on 2020-08-04 08:27

import camac.applicants.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_auto_20190923_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=camac.applicants.models.CaseInsensitiveEmailField(max_length=254),
        ),
    ]
