# Generated by Django 2.2.14 on 2020-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_auto_20190923_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            # Note: This was a custom `CaseInsenstiveEmailField` before, but it was dropped
            # in favour of `CIEmailField` (see next migration)
            field=models.CharField(max_length=254),
        ),
    ]
