# Generated by Django 2.2.14 on 2020-08-11 07:21

import django.contrib.postgres.fields.citext

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("applicants", "0006_auto_20200804_1027")]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name="applicant",
            name="email",
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254),
        ),
    ]
