# Generated by Django 4.2.13 on 2024-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_auto_20200811_0921'),
        ('core', '0109_case_insensitive_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(db_collation='case_insensitive', max_length=254),
        ),
    ]
