# Generated by Django 4.2.13 on 2024-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_alter_applicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('READ_ONLY', 'Read only')], default='ADMIN', max_length=50),
        ),
    ]
