# Generated by Django 4.2.20 on 2025-07-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_applicant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='username',
            field=models.CharField(blank=True, db_collation='case_insensitive'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, db_collation='case_insensitive', max_length=254),
        ),
    ]
