# Generated by Django 5.2.11 on 2026-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0010_applicant_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='role',
            field=models.CharField(choices=[('PROJECT_OWNER', 'Project owner'), ('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('READ_ONLY', 'Read only')], default='ADMIN', max_length=50),
        ),
    ]
