# Generated by Django 5.2.11 on 2026-03-26 15:35

import django.db.models.deletion
import uuid_extensions.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_alter_applicant_role'),
        ('caluma_form', '0049_uuid_v7'),
        ('instance', '0043_alter_historyentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantConfirmationRound',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('submit', 'Submit'), ('additional_demand', 'Additional demand')], max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('invalidated', 'Invalidated')], db_index=True, default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='caluma_form.document')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_rounds', to='instance.instance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('invalidated', 'Invalidated')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='applicants.applicant')),
                ('source_questions', models.ManyToManyField(related_name='+', to='caluma_form.question')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='applicants.applicantconfirmationround')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='applicantconfirmationround',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['running', 'completed'])), fields=('document',), name='unique_running_confirmation_round_per_document'),
        ),
        migrations.AddConstraint(
            model_name='applicantconfirmation',
            constraint=models.UniqueConstraint(fields=('applicant', 'round'), name='unique_applicant_confirmation_per_round'),
        ),
    ]
