# Generated by Django 3.2.19 on 2023-12-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingv2entry',
            name='billing_type',
            field=models.CharField(choices=[('by_authority', 'By authority'), ('forwarded', 'Forwarded'), ('direct', 'Direct')], max_length=20, null=True),
        ),
    ]
