# Generated by Django 4.2.16 on 2025-01-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_service_slug'),
        ('billing', '0003_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingv2entry',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('by_authority', 'By authority'), ('forwarded', 'Forwarded'), ('direct', 'Direct')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billingv2entry',
            name='calculation',
            field=models.CharField(blank=True, choices=[('flat', 'Flat rate'), ('percentage', 'Percentage'), ('hourly', 'Hourly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billingv2entry',
            name='organization',
            field=models.CharField(blank=True, choices=[('municipal', 'Municipal'), ('cantonal', 'Cantonal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billingv2entry',
            name='tax_mode',
            field=models.CharField(blank=True, choices=[('inclusive', 'Incl 7.7%'), ('exclusive', 'Excl 7.7%'), ('exempt', 'Tax exempt')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='BillingV2EntryTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('cost_center', models.TextField(blank=True, null=True)),
                ('legal_basis', models.TextField(blank=True, null=True)),
                ('tax_mode', models.CharField(blank=True, choices=[('inclusive', 'Incl 7.7%'), ('exclusive', 'Excl 7.7%'), ('exempt', 'Tax exempt')], max_length=20, null=True)),
                ('calculation', models.CharField(blank=True, choices=[('flat', 'Flat rate'), ('percentage', 'Percentage'), ('hourly', 'Hourly')], max_length=20, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('organization', models.CharField(blank=True, choices=[('municipal', 'Municipal'), ('cantonal', 'Cantonal')], max_length=20, null=True)),
                ('billing_type', models.CharField(blank=True, choices=[('by_authority', 'By authority'), ('forwarded', 'Forwarded'), ('direct', 'Direct')], max_length=20, null=True)),
                ('name', models.TextField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
