# Generated by Django 4.2.16 on 2025-02-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_billingv2entry_billing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingv2entrytemplate',
            name='final_rate',
        ),
        migrations.AlterField(
            model_name='billingv2entry',
            name='calculation',
            field=models.CharField(blank=True, choices=[('flat', 'Flat rate'), ('percentage', 'Percentage'), ('hourly', 'Hourly'), ('ag_processing_fee', 'AG processing fee')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billingv2entrytemplate',
            name='calculation',
            field=models.CharField(blank=True, choices=[('flat', 'Flat rate'), ('percentage', 'Percentage'), ('hourly', 'Hourly'), ('ag_processing_fee', 'AG processing fee')], max_length=20, null=True),
        ),
    ]
