# Generated by Django 4.2.18 on 2025-02-18 17:07
import uuid

import django.db.models.deletion
from django.db import migrations, models


def fk_to_m2m(apps, schema_editor):
    BillingV2EntryTemplate = apps.get_model("billing", "BillingV2EntryTemplate")

    for tpl in BillingV2EntryTemplate.objects.all():
        tpl.services.set([tpl.service])


def m2m_to_fk(apps, schema_editor):
    BillingV2EntryTemplate = apps.get_model("billing", "BillingV2EntryTemplate")
    Service = apps.get_model("user", "Service")

    fallback_service = Service.objects.first()

    for tpl in BillingV2EntryTemplate.objects.all():
        tpl.service = tpl.services.first() or fallback_service
        tpl.save()


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0028_service_slug"),
        ("billing", "0005_remove_billingv2entrytemplate_final_rate_and_more"),
    ]

    operations = [
        # Migrate ID to UUID
        migrations.AddField(
            model_name="billingv2entrytemplate",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RemoveField(
            model_name="billingv2entrytemplate",
            name="id",
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="billingv2entrytemplate",
            old_name="uuid",
            new_name="id",
        ),
        # Make service field optional
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="user.service",
            ),
        ),
        # Add new services and service groups fields
        migrations.AddField(
            model_name="billingv2entrytemplate",
            name="service_groups",
            field=models.ManyToManyField(blank=True, to="user.servicegroup"),
        ),
        migrations.AddField(
            model_name="billingv2entrytemplate",
            name="services",
            field=models.ManyToManyField(blank=True, to="user.service"),
        ),
        # Migrate service (fk) to services (m2m)
        migrations.RunPython(fk_to_m2m, m2m_to_fk),
        # Remove obsolete service field
        migrations.RemoveField(
            model_name="billingv2entrytemplate",
            name="service",
        ),
        # After this point only field and model translations were changed
        migrations.AlterModelOptions(
            name="billingv2entrytemplate",
            options={
                "verbose_name": "Billing entry template",
                "verbose_name_plural": "Billing entry templates",
            },
        ),
        migrations.AlterField(
            model_name="billingv2entry",
            name="calculation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "flat rate"),
                    ("percentage", "percentage"),
                    ("hourly", "at cost"),
                    ("ag_processing_fee", "Processing fee BG BVUAFB"),
                ],
                max_length=20,
                null=True,
                verbose_name="Calculation",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entry",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Hourly rate",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entry",
            name="hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Hours",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entry",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Quota (%)",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entry",
            name="tax_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inclusive", "inclusive"),
                    ("exclusive", "exclusive"),
                    ("exempt", "not subject to VAT"),
                ],
                max_length=20,
                null=True,
                verbose_name="VAT type",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entry",
            name="tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="VAT rate",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entry",
            name="text",
            field=models.TextField(verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="billingv2entry",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total cost",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="calculation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "flat rate"),
                    ("percentage", "percentage"),
                    ("hourly", "at cost"),
                    ("ag_processing_fee", "Processing fee BG BVUAFB"),
                ],
                max_length=20,
                null=True,
                verbose_name="Calculation",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="hint",
            field=models.TextField(blank=True, null=True, verbose_name="Hint"),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Hourly rate",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Hours",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="name",
            field=models.TextField(verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Quota (%)",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="service_groups",
            field=models.ManyToManyField(
                blank=True, to="user.servicegroup", verbose_name="Service groups"
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="services",
            field=models.ManyToManyField(
                blank=True, to="user.service", verbose_name="Services"
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="tax_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inclusive", "inclusive"),
                    ("exclusive", "exclusive"),
                    ("exempt", "not subject to VAT"),
                ],
                max_length=20,
                null=True,
                verbose_name="VAT type",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="VAT rate",
            ),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="text",
            field=models.TextField(verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="billingv2entrytemplate",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total cost",
            ),
        ),
    ]
