# Generated by Django 4.2.18 on 2025-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_template_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingv2entry',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('by_authority', 'By authority'), ('forwarded', 'Forwarded'), ('direct', 'Direct'), ('construction_outside_zone', 'Cantonal invoice for construction outside of construction zone'), ('cantonal_construction_administration', 'Cantonal invoice to cantonal construction administration')], max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='billingv2entrytemplate',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('by_authority', 'By authority'), ('forwarded', 'Forwarded'), ('direct', 'Direct'), ('construction_outside_zone', 'Cantonal invoice for construction outside of construction zone'), ('cantonal_construction_administration', 'Cantonal invoice to cantonal construction administration')], max_length=36, null=True),
        ),
    ]
