# Generated by Django 4.2.19 on 2025-03-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0039_instance_rejection_feedback'),
        ('billing', '0007_alter_billingv2entry_billing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingv2entry',
            name='product_number',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='billingv2entry',
            name='released_for_clearing',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='billingv2entrytemplate',
            name='product_number',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='billingv2entry',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_v2_entries', to='instance.instance'),
        ),
    ]
