# Generated by Django 4.2.20 on 2025-03-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_lineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingv2entry',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='billingv2entrytemplate',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
