# Generated by Django 5.2.6 on 2025-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_billingv2entry_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingv2entry',
            name='organization',
            field=models.CharField(blank=True, choices=[('municipal', 'Municipal'), ('cantonal', 'Cantonal')], max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='billingv2entrytemplate',
            name='organization',
            field=models.CharField(blank=True, choices=[('municipal', 'Municipal'), ('cantonal', 'Cantonal')], max_length=20, null=True, verbose_name='Type'),
        ),
    ]
