# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-21 06:42
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("user", "0007_rename_duplicated_users")]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(help_text="XML body")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.Service"
                    ),
                ),
            ],
            options={"ordering": ["created_at"], "managed": True},
        )
    ]
