# Generated by Django 5.2.8 on 2025-11-19 14:54
import django.utils.timezone
from django.db import migrations, models

import camac.document.models

CREATE_SQL = """
    CREATE VIEW ech0211_document AS (
        SELECT
            concat(
                "ATTACHMENT_attachment_sections"."attachmentsection_id",
                '-',
                "ATTACHMENT_attachment_sections"."attachment_id"
            ) as "id",

            "ATTACHMENT".*,
            "ATTACHMENT_attachment_sections"."attachmentsection_id"

        FROM
            "ATTACHMENT_attachment_sections"
            JOIN
            "ATTACHMENT" on (
                "ATTACHMENT"."ATTACHMENT_ID" =
                "ATTACHMENT_attachment_sections"."attachment_id"
            )
    );
"""

DROP_SQL = """
    DROP VIEW IF EXISTS ech0211_document;
"""


class Migration(migrations.Migration):
    """Create the required view for representing eCH0211 documents."""

    # Note: This migration must be stand-alone, as it needs special
    # treatment in the tests to work. See camac.conftest.setup_sql_views()
    dependencies = [
        ("ech0211", "0002_fix_unknown_message_type"),
    ]

    operations = [
        migrations.RunSQL(
            CREATE_SQL,
            DROP_SQL,
            state_operations=[
                migrations.CreateModel(
                    name="ECH0211Document",
                    options={
                        "managed": False,
                        "db_table": "ech0211_document",
                    },
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True, primary_key=True, serialize=False
                            ),
                        ),
                        ("name", models.CharField(db_column="NAME", max_length=255)),
                        (
                            "path",
                            models.FileField(
                                db_column="PATH",
                                max_length=1024,
                                upload_to=camac.document.models.attachment_path_directory_path,
                            ),
                        ),
                        ("size", models.IntegerField(db_column="SIZE")),
                        (
                            "date",
                            models.DateTimeField(
                                db_column="DATE", default=django.utils.timezone.now
                            ),
                        ),
                        (
                            "mime_type",
                            models.CharField(db_column="MIME_TYPE", max_length=255),
                        ),
                        (
                            "category",
                            models.ForeignKey(
                                "document.AttachmentSection", models.DO_NOTHING
                            ),
                        ),
                        (
                            "instance",
                            models.ForeignKey(
                                "instance.Instance",
                                models.DO_NOTHING,
                                db_column="INSTANCE_ID",
                                related_name="+",
                            ),
                        ),
                        (
                            "service",
                            models.ForeignKey(
                                "user.Service",
                                models.DO_NOTHING,
                                db_column="SERVICE_ID",
                                related_name="+",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                "user.User",
                                models.DO_NOTHING,
                                db_column="USER_ID",
                                related_name="+",
                            ),
                        ),
                    ],
                )
            ],
        )
    ]
