# Generated by Django 5.2.8 on 2025-11-26 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0022_alter_mark_name"),
        ("document", "0030_add_attachment_version"),
        ("ech0211", "0003_document_model_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="ECH0211AlexandriaCategory",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("alexandria_core.category",),
        ),
        migrations.CreateModel(
            name="ECH0211AlexandriaDocument",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("alexandria_core.document",),
        ),
        migrations.CreateModel(
            name="ECH0211CamacCategory",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("document.attachmentsection",),
        ),
    ]
