CREATE TABLE BILLING_ACCOUNT_STATE
(
  BILLING_ACCOUNT_STATE_ID NUMBER NOT NULL PRIMARY KEY
, BILLING_ACCOUNT_ID NUMBER NOT NULL
, INSTANCE_STATE_ID NUMBER NOT NULL
, CONSTRAINT BILLING_ACCOUNT_FK FOREIGN KEY (BILLING_ACCOUNT_ID) 
	REFERENCES BILLING_ACCOUNT (BILLING_ACCOUNT_ID)
, CONSTRAINT INSTANCE_STATE_FK FOREIGN KEY (INSTANCE_STATE_ID) 
	REFERENCES INSTANCE_STATE (INSTANCE_STATE_ID)
);


CREATE SEQUENCE BILLING_ACCOUNT_STATE_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9000000 MINVALUE 1 ORDER;

create or replace TRIGGER "CAMAC"."BILLING_ACCOUNT_STATE_TRG" 
BEFORE INSERT ON BILLING_ACCOUNT_STATE
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.BILLING_ACCOUNT_STATE_ID IS NULL THEN
      SELECT BILLING_ACCOUNT_STATE_SEQ.NEXTVAL INTO :NEW.BILLING_ACCOUNT_STATE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
