CREATE OR REPLACE VIEW APPLICANT_DATA_VIEW AS
SELECT
    "NAME_TBL"."ANSWER" "NAME",
    "EMAIL_TBL"."ANSWER" "EMAIL",
    "NAME_TBL"."INSTANCE_ID" "INSTANCE_ID"
FROM
    "ANSWER" "NAME_TBL"

JOIN
    "ANSWER" "EMAIL_TBL"
ON (
        "EMAIL_TBL"."CHAPTER_ID" = 1
    AND
        "EMAIL_TBL"."QUESTION_ID" = 66
    AND
        "EMAIL_TBL"."ITEM" = 1
)

WHERE
        "NAME_TBL"."CHAPTER_ID" = 1
    AND
        "NAME_TBL"."QUESTION_ID" = 23
    AND
        "NAME_TBL"."ITEM" = 1

    AND
        "NAME_TBL"."INSTANCE_ID" = "EMAIL_TBL"."INSTANCE_ID"
;


CREATE OR REPLACE VIEW PROJECT_AUTHOR_DATA_VIEW AS
SELECT
    "NAME_TBL"."ANSWER" "NAME",
    "EMAIL_TBL"."ANSWER" "EMAIL",
    "NAME_TBL"."INSTANCE_ID" "INSTANCE_ID"
FROM
    "ANSWER" "NAME_TBL"

JOIN
    "ANSWER" "EMAIL_TBL"
ON (
        "EMAIL_TBL"."CHAPTER_ID" = 1
    AND
        "EMAIL_TBL"."QUESTION_ID" = 77
    AND
        "EMAIL_TBL"."ITEM" = 1
)

WHERE
        "NAME_TBL"."CHAPTER_ID" = 1
    AND
        "NAME_TBL"."QUESTION_ID" = 71
    AND
        "NAME_TBL"."ITEM" = 1

    AND
        "NAME_TBL"."INSTANCE_ID" = "EMAIL_TBL"."INSTANCE_ID"
;



CREATE OR REPLACE VIEW PROJECT_SUBMITTER_VIEW AS
SELECT
    "ANSWER",
    "INSTANCE_ID"
FROM
    "ANSWER" "NAME_TBL"
WHERE
        "NAME_TBL"."CHAPTER_ID" = 103
    AND
        "NAME_TBL"."QUESTION_ID" = 257
    AND
        "NAME_TBL"."ITEM" = 1
;

CREATE OR REPLACE VIEW PROJECT_SUBMITTER_DATA AS
SELECT
    CASE
        PROJECT_SUBMITTER_VIEW.ANSWER
        WHEN '0' THEN APPLICANT_DATA_VIEW.NAME
        WHEN '1' THEN PROJECT_AUTHOR_DATA_VIEW.NAME
    END "NAME",
    CASE
        PROJECT_SUBMITTER_VIEW.ANSWER
        WHEN '0' THEN APPLICANT_DATA_VIEW.EMAIL
        WHEN '1' THEN PROJECT_AUTHOR_DATA_VIEW.EMAIL
    END "EMAIL",
    PROJECT_SUBMITTER_VIEW.INSTANCE_ID,
    PROJECT_SUBMITTER_VIEW.ANSWER
FROM
    PROJECT_SUBMITTER_VIEW
LEFT JOIN
    APPLICANT_DATA_VIEW ON
    PROJECT_SUBMITTER_VIEW.INSTANCE_ID = APPLICANT_DATA_VIEW.INSTANCE_ID
LEFT JOIN
    PROJECT_AUTHOR_DATA_VIEW ON
    PROJECT_SUBMITTER_VIEW.INSTANCE_ID= PROJECT_AUTHOR_DATA_VIEW.INSTANCE_ID
;
