CREATE TABLE PORTAL_SESSION 
(
  PORTAL_SESSION_ID VARCHAR2(256) NOT NULL 
, PORTAL_IDENTIFIER VARCHAR2(256) NOT NULL 
, LAST_ACTIVE DATE NOT NULL
, CONSTRAINT PORTAL_SESSION_PK PRIMARY KEY 
  (
    PORTAL_SESSION_ID 
  )
  ENABLE 
);

INSERT INTO "CAMAC"."AVAILABLE_RESOURCE" (AVAILABLE_RESOURCE_ID, MODULE_NAME, CONTROLLER_NAME, DESCRIPTION) VALUES ('portal', 'portal', 'user', 'Portal user controller')

INSERT INTO "CAMAC"."AR_ACTION" (AVAILABLE_RESOURCE_ID, ACTION_NAME, HIDDEN) VALUES ('portal', 'session', '1')

INSERT INTO "CAMAC"."AR_ACTION" (AVAILABLE_RESOURCE_ID, ACTION_NAME, HIDDEN) VALUES ('portal', 'entry', '1')

CREATE TABLE INSTANCE_PORTAL 
(
  INSTANCE_ID NUMBER(10) NOT NULL 
, PORTAL_IDENTIFIER VARCHAR2(256) NOT NULL 
, CONSTRAINT INSTANCE_PORTAL_PK PRIMARY KEY 
  (
    INSTANCE_ID 
  )
  ENABLE 
);

INSERT INTO "CAMAC"."AR_ACTION" (AVAILABLE_RESOURCE_ID, ACTION_NAME, HIDDEN) VALUES ('portal', 'overview', '1');
