--- THE ATTACHMENT TABLE

CREATE TABLE ATTACHMENT_SECTION
(
  ATTACHMENT_SECTION_ID NUMBER NOT NULL
, NAME VARCHAR2(100) NOT NULL
, SORT NUMBER(1,0) DEFAULT 0 NOT NULL
, CONSTRAINT ATTACHMENT_SECTION_PK PRIMARY KEY
  (
    ATTACHMENT_SECTION_ID
  )
  ENABLE
);


CREATE SEQUENCE ATTACHMENT_SECTION_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9000000 MINVALUE 1 ORDER;


--- THE ROLE TABLE

CREATE TABLE ATTACHMENT_SECTION_ROLE
(
  ID NUMBER NOT NULL
, ATTACHMENT_SECTION_ID NUMBER NOT NULL
, ROLE_ID NUMBER NOT NULL
, "MODE" VARCHAR2(10) CHECK ( "MODE" IN ('read', 'write', 'admin'))
, CONSTRAINT ATTACHMENT_SECTION_ROLE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

ALTER TABLE ATTACHMENT_SECTION_ROLE
ADD CONSTRAINT ATTACHMENT_SECTION_ROLE_UK1 UNIQUE
(
  ATTACHMENT_SECTION_ID
, ROLE_ID
)
ENABLE;

ALTER TABLE ATTACHMENT_SECTION_ROLE
ADD CONSTRAINT ATTACHMENT_SECTION_ROLE_FK1 FOREIGN KEY
(
  ATTACHMENT_SECTION_ID
)
REFERENCES ATTACHMENT_SECTION
(
  ATTACHMENT_SECTION_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ATTACHMENT_SECTION_ROLE
ADD CONSTRAINT ATTACHMENT_SECTION_ROLE_FK2 FOREIGN KEY
(
  ROLE_ID
)
REFERENCES ROLE
(
  ROLE_ID
)
ON DELETE CASCADE ENABLE;

CREATE SEQUENCE ATTACHMENT_SECTION_ROLE_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 90000000 MINVALUE 1;


-- THE SERVICE TABLE

CREATE TABLE ATTACHMENT_SECTION_SERVICE
(
  ID NUMBER NOT NULL
, ATTACHMENT_SECTION_ID NUMBER NOT NULL
, SERVICE_ID NUMBER NOT NULL
, "MODE" VARCHAR2(20) NOT NULL
, CONSTRAINT ATTACHMENT_SECTION_SERVICE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

ALTER TABLE ATTACHMENT_SECTION_SERVICE
ADD CONSTRAINT ATTACHMENT_SECTION_SERVICE_UK1 UNIQUE
(
  ATTACHMENT_SECTION_ID
, SERVICE_ID
)
ENABLE;

ALTER TABLE ATTACHMENT_SECTION_SERVICE
ADD CONSTRAINT ATTACHMENT_SECTION_SERVIC_FK1 FOREIGN KEY
(
  ATTACHMENT_SECTION_ID
)
REFERENCES ATTACHMENT_SECTION
(
  ATTACHMENT_SECTION_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ATTACHMENT_SECTION_SERVICE
ADD CONSTRAINT ATTACHMENT_SECTION_SERVIC_FK2 FOREIGN KEY
(
  SERVICE_ID
)
REFERENCES SERVICE
(
  SERVICE_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ATTACHMENT_SECTION_SERVICE
ADD CONSTRAINT ATTACHMENT_SECTION_SERVI_CHK1 CHECK
("MODE" in ('read', 'write', 'admin'))
ENABLE;

CREATE SEQUENCE ATTACHMENT_SECTION_SERVICE_SEQ;



-- NEW RELATION TO ATTACHMENT SECTION

ALTER TABLE ATTACHMENT
ADD ATTACHMENT_SECTION_ID NUMBER;

ALTER TABLE ATTACHMENT
ADD IS_PARCEL_PICTURE NUMBER DEFAULT 0;

ALTER TABLE ATTACHMENT
ADD CONSTRAINT ATTACHMENT_SECTION_FK1 FOREIGN KEY
(
	ATTACHMENT_SECTION_ID
)
REFERENCES ATTACHMENT_SECTION
(
	ATTACHMENT_SECTION_ID
);

UPDATE ATTACHMENT
SET ATTACHMENT_SECTION_ID = 21
WHERE TYPE = 1;

UPDATE ATTACHMENT
SET ATTACHMENT_SECTION_ID = 23
WHERE TYPE = 2;

UPDATE ATTACHMENT
SET ATTACHMENT_SECTION_ID = 21,
	IS_PARCEL_PICTURE = 1
WHERE TYPE = 4;

UPDATE ATTACHMENT
SET ATTACHMENT_SECTION_ID = 24
WHERE TYPE = 3;

UPDATE ATTACHMENT
SET ATTACHMENT_SECTION_ID = 25
WHERE TYPE = 5;

ALTER TABLE ATTACHMENT
MODIFY ATTACHMENT_SECTION_ID NUMBER;

ALTER TABLE ATTACHMENT
DROP COLUMN TYPE;



-- ATTACHMENT_EXTENSION TABLE


CREATE TABLE ATTACHMENT_EXTENSION 
(
  ATTACHMENT_EXTENSION_ID NUMBER NOT NULL 
, NAME VARCHAR2(10) NOT NULL 
, CONSTRAINT ATTACHMENT_EXTENSION_PK PRIMARY KEY 
  (
    ATTACHMENT_EXTENSION_ID 
  )
  ENABLE 
);

CREATE SEQUENCE ATTACHMENT_EXTENSION_SEQ;



-- ATTACHMENT EXTENSION ROLE

CREATE TABLE ATTACHMENT_EXTENSION_ROLE
(
  ID NUMBER NOT NULL
, ATTACHMENT_EXTENSION_ID NUMBER NOT NULL
, ROLE_ID NUMBER NOT NULL
, "MODE" VARCHAR2(10) CHECK ( "MODE" IN ('read', 'write', 'admin'))
, CONSTRAINT ATTACHMENT_EXTENSION_ROLE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

ALTER TABLE ATTACHMENT_EXTENSION_ROLE
ADD CONSTRAINT ATTACHMENT_EXTENSION_ROLE_UK1 UNIQUE
(
  ATTACHMENT_EXTENSION_ID
, ROLE_ID
)
ENABLE;

ALTER TABLE ATTACHMENT_EXTENSION_ROLE
ADD CONSTRAINT ATTACHMENT_EXTENSION_ROLE_FK1 FOREIGN KEY
(
  ATTACHMENT_EXTENSION_ID
)
REFERENCES ATTACHMENT_EXTENSION
(
  ATTACHMENT_EXTENSION_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ATTACHMENT_EXTENSION_ROLE
ADD CONSTRAINT ATTACHMENT_EXTENSION_ROLE_FK2 FOREIGN KEY
(
  ROLE_ID
)
REFERENCES ROLE
(
  ROLE_ID
)
ON DELETE CASCADE ENABLE;

CREATE SEQUENCE ATTACHMENT_EXTENSION_ROLE_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 90000000 MINVALUE 1;



-- ATTACHMENT EXTENSION SERVICE

CREATE TABLE ATTACHMENT_EXTENSION_SERVICE
(
  ID NUMBER NOT NULL
, ATTACHMENT_EXTENSION_ID NUMBER NOT NULL
, SERVICE_ID NUMBER NOT NULL
, "MODE" VARCHAR2(10) CHECK ( "MODE" IN ('read', 'write', 'admin'))
, CONSTRAINT ATTACHMENT_EXT_SERVICE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

ALTER TABLE ATTACHMENT_EXTENSION_SERVICE
ADD CONSTRAINT ATTACHMENT_EXT_SERVICE_UK1 UNIQUE
(
  ATTACHMENT_EXTENSION_ID
, SERVICE_ID
)
ENABLE;

ALTER TABLE ATTACHMENT_EXTENSION_SERVICE
ADD CONSTRAINT ATTACHMENT_EXT_SERVICE_FK1 FOREIGN KEY
(
  ATTACHMENT_EXTENSION_ID
)
REFERENCES ATTACHMENT_EXTENSION
(
  ATTACHMENT_EXTENSION_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ATTACHMENT_EXTENSION_SERVICE
ADD CONSTRAINT ATTACHMENT_EXT_SERVICE_FK2 FOREIGN KEY
(
  SERVICE_ID
)
REFERENCES SERVICE
(
  SERVICE_ID
)
ON DELETE CASCADE ENABLE;

CREATE SEQUENCE ATTACHMENT_EXT_SERVICE_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 90000000 MINVALUE 1;


-- THE SERVICE RELATION

ALTER TABLE ATTACHMENT
ADD SERVICE_ID NUMBER;

ALTER TABLE ATTACHMENT
ADD CONSTRAINT ATTACHMENT_SERVICE_FK1 FOREIGN KEY 
(
	SERVICE_ID
)
REFERENCES SERVICE 
(
	SERVICE_ID
);


UPDATE ATTACHMENT
SET SERVICE_ID = (
	SELECT
		SERVICE.SERVICE_ID
	FROM
		USER_GROUP
	LEFT JOIN "GROUP" ON (
		USER_GROUP.GROUP_ID = "GROUP"."GROUP_ID"
	)
	LEFT JOIN SERVICE ON (
		"GROUP"."SERVICE_ID" = "SERVICE"."SERVICE_ID"
	)
	WHERE
		USER_GROUP.USER_ID = ATTACHMENT.USER_ID
		AND
		USER_GROUP.DEFAULT_GROUP = 1
);
