-- This update is for issue # 12462


CREATE TABLE COMMISSION_ASSIGNMENT
(
  "COMMISSION_ASSIGNMENT_ID" NUMBER NOT NULL,
  "GROUP_ID" NUMBER NOT NULL,
  "INSTANCE_ID" NUMBER NOT NULL,
  "ADDER_ID" NUMBER NOT NULL,
  "DATE" DATE NOT NULL,
  CONSTRAINT COMMISSION_ASSIGNMENT PRIMARY KEY
  (
    "COMMISSION_ASSIGNMENT_ID"
  )
  ENABLE
);

ALTER TABLE COMMISSION_ASSIGNMENT
ADD CONSTRAINT COMMISSION_ASSIGNMENT_UK1 UNIQUE
(
  GROUP_ID, INSTANCE_ID
)
ENABLE;

ALTER TABLE COMMISSION_ASSIGNMENT
ADD CONSTRAINT COMMISSION_ASSIGNMENT_FK1 FOREIGN KEY
(
	GROUP_ID
)
REFERENCES "GROUP"
(
	GROUP_ID
)
ON DELETE CASCADE ENABLE;


ALTER TABLE COMMISSION_ASSIGNMENT
ADD CONSTRAINT COMMISSION_ASSIGNMENT_FK2 FOREIGN KEY
(
	INSTANCE_ID
)
REFERENCES "INSTANCE"
(
	INSTANCE_ID
)
ON DELETE CASCADE ENABLE;

CREATE SEQUENCE COMMISSION_ASSIGNMENT_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 90000000 MINVALUE 1;
