CREATE OR REPLACE VIEW APPLICANT_VIEW AS 
SELECT 
"INSTANCE"."INSTANCE_ID",
(SELECT LISTAGG("ANSWER", ', ') WITHIN GROUP (ORDER BY "QUESTION_ID" DESC)
  FROM
  "ANSWER"
  WHERE
  "INSTANCE"."INSTANCE_ID" = "ANSWER"."INSTANCE_ID"
  AND
  (
    "ANSWER"."QUESTION_ID" = 23
    OR
    "ANSWER"."QUESTION_ID" = 221
  )
  AND
  "ANSWER"."CHAPTER_ID" = 1
  AND
  "ANSWER"."ITEM" = 1
) AS APPLICANT
FROM "INSTANCE";
