ALTER TABLE BILLING_ACCOUNT
ADD SERVICE_GROUP_ID NUMBER;

alter table "CAMAC"."BILLING_ACCOUNT" 
add constraint BILLING_SERVICE_GROUP_FK foreign key("SERVICE_GROUP_ID") references "SERVICE_GROUP"("SERVICE_GROUP_ID");

ALTER TABLE BILLING_ENTRY
ADD SERVICE_ID NUMBER;

alter table "CAMAC"."BILLING_ENTRY" add constraint BILLING_SERVICE_FK foreign key("SERVICE_ID") references "SERVICE"("SERVICE_ID");
