
CREATE TABLE CONFIGURATION_VERSION 
(
  ID NUMBER NOT NULL 
, HASH VARCHAR2(255) NOT NULL 
, EXPORT_DATE DATE NOT NULL 
, AUTHOR VARCHAR2(255) NOT NULL 
, CONSTRAINT CONFIGURATION_VERSION_PK PRIMARY KEY 
  (
    ID
  )
  ENABLE 
);

CREATE UNIQUE INDEX CONFIGURATION_VERSION_INDEX1 ON CONFIGURATION_VERSION (HASH);

CREATE SEQUENCE CONFIGURATION_VERSION_SEQ;

CREATE TRIGGER CONFIGURATION_VERSION_TRG 
BEFORE INSERT ON CONFIGURATION_VERSION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CONFIGURATION_VERSION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
