CREATE TABLE "CAMAC"."ATTACHMENT_TYPE"
  ("ATTACHMENT_TYPE_ID" NUMBER NOT NULL ENABLE,
  "NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
  CONSTRAINT "ATTACHMENT_TYPE_PK" PRIMARY KEY ("ATTACHMENT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE OR REPLACE TRIGGER "CAMAC"."ATTACHMENT_TYPE_TRG"
  BEFORE INSERT ON ATTACHMENT_TYPE
  FOR EACH ROW
  BEGIN
    <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ATTACHMENT_TYPE_ID IS NULL THEN
      SELECT ATTACHMENT_TYPE_SEQ.NEXTVAL INTO :NEW.ATTACHMENT_TYPE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CAMAC"."ATTACHMENT_TYPE_TRG" ENABLE;
