CREATE TABLE R_SIMPLE_LIST
(
  RESOURCE_ID NUMBER NOT NULL
, INSTANCE_STATES VARCHAR2(100) NOT NULL
, CONSTRAINT R_SIMPLE_LIST_PK PRIMARY KEY (RESOURCE_ID) ENABLE
);

CREATE SEQUENCE R_SIMPLE_LIST_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9000000 MINVALUE 1 ORDER;
