create or replace TRIGGER "CAMAC"."INSTANCE_TRG"
BEFORE INSERT ON INSTANCE
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.INSTANCE_ID IS NULL THEN
      SELECT INSTANCE_SEQ.NEXTVAL INTO :NEW.INSTANCE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
