CREATE OR REPLACE FORCE VIEW "CAMAC"."PRESET_INTENTIONS" ("NAME", "VALUE", "INSTANCE_ID") AS
SELECT
		"ANSWER_LIST"."NAME",
		"ANSWER_LIST"."VALUE",
		"ANSWER"."INSTANCE_ID"
	FROM
		"ANSWER_LIST",
		 "ANSWER"

	WHERE (
			"ANSWER"."QUESTION_ID" = 97
			AND
			"CHAPTER_ID" = 21
			AND
			"ITEM" = 1
		)

		AND
			"ANSWER_LIST"."VALUE" IN (
				select "VAL" from table(json_unserialize("ANSWER"))
			)

		AND
			"ANSWER_LIST"."QUESTION_ID" = 97
