CREATE TABLE BAB_USAGE
(
  INSTANCE_ID NUMBER NOT NULL
, USAGE_TYPE NUMBER(3,0) NOT NULL
, USAGE NUMBER NOT NULL
, CONSTRAINT BAB_INSTANCE_FK FOREIGN KEY (INSTANCE_ID) REFERENCES INSTANCE (INSTANCE_ID)
, CONSTRAINT BAB_ENTRY_PK PRIMARY KEY (INSTANCE_ID, USAGE_TYPE) ENABLE
);
