ALTER TABLE A_DELETE_CIRCULATION ADD CONSTRAINT A_DELETE_CIRC_PK PRIMARY KEY (ACTION_ID);
ALTER TABLE A_DELETE_CIRCULATION ADD CONSTRAINT A_DELETE_CIRCULATION_FK FOREIGN KEY (ACTION_ID) REFERENCES ACTION (ACTION_ID);

ALTER TABLE AUTHORITY_AUTHORITY_TYPE
ADD CONSTRAINT AUTHORITY_AUTHORITY_TYPE_PK PRIMARY KEY (AUTHORITY_ID, AUTHORITY_TYPE_ID);
ALTER TABLE AUTHORITY_LOCATION
ADD CONSTRAINT AUTHORITY_LOCATION_PK PRIMARY KEY (AUTHORITY_ID, LOCATION_ID);

ALTER TABLE DOCGEN_ACTIVATIONACTION_ACTION
ADD CONSTRAINT DOCGEN_ACTIVATIONACTION_ACTION_PK PRIMARY KEY (DOCGEN_ACTIVATION_ACTION_ID, ACTION_ID);

ALTER TABLE DOCGEN_PDF_ACTION
ADD CONSTRAINT DOCGEN_PDF_PK PRIMARY KEY (DOCGEN_TEMPLATE_ID, DOCGEN_TEMPLATE_CLASS_ID, ACTION_ID);

ALTER TABLE DOCGEN_DOCX_ACTION
ADD CONSTRAINT DOCGEN_DOCX_PK PRIMARY KEY (DOCGEN_TEMPLATE_ID, DOCGEN_TEMPLATE_CLASS_ID, ACTION_ID);

ALTER TABLE INST
ADD CONSTRAINT INST_PK PRIMARY KEY (INSTANCE_ID);

ALTER TABLE INSTANCE_STATE_DESCRIPTION
ADD CONSTRAINT INSTANCE_STATE_D_PK PRIMARY KEY (INSTANCE_STATE_ID);

ALTER TABLE R_PAGE
ADD CONSTRAINT R_PAGE_PK PRIMARY KEY (RESOURCE_ID);
