ALTER TABLE "IR_EDITCIRCULATION" ADD COLUMN "CIRCULATION_EMAIL_ACTION_ID" integer;

ALTER TABLE "IR_EDITCIRCULATION" ADD CONSTRAINT "FKIR_EDITCIRC_ACTION" FOREIGN KEY ("CIRCULATION_EMAIL_ACTION_ID") REFERENCES "ACTION" ("ACTION_ID");
