CREATE TABLE BAB_USAGE
(
  BAB_USAGE_ID NUMBER NOT NULL
, INSTANCE_ID NUMBER NOT NULL
, USAGE_TYPE NUMBER(3,0) NOT NULL
, USAGE NUMBER NOT NULL
, CONSTRAINT BAB_INSTANCE_FK FOREIGN KEY (INSTANCE_ID) REFERENCES INSTANCE (INSTANCE_ID)
, CONSTRAINT BAB_ENTRY_PK PRIMARY KEY (BAB_ENTRY_ID) ENABLE
);

CREATE SEQUENCE BAB_USAGE_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9000000 MINVALUE 1 ORDER;
