
CREATE TABLE WORKFLOW_SECTION
(
  WORKFLOW_SECTION_ID NUMBER NOT NULL
, NAME VARCHAR2(60) NOT NULL
, SORT NUMBER
, CONSTRAINT WORKFLOW_SECTION_PK PRIMARY KEY (WORKFLOW_SECTION_ID) ENABLE
);

CREATE SEQUENCE WORKFLOW_SECTION_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9000000 MINVALUE 1 ORDER;

/* Add FK to WORKFLOW_SECTION */
alter table
    WORKFLOW_ITEM
add
    WORKFLOW_SECTION_ID number;

alter table "CAMAC"."WORKFLOW_ITEM" add constraint WORKFLOW_SECTION_FK foreign key("WORKFLOW_SECTION_ID") references "WORKFLOW_SECTION"("WORKFLOW_SECTION_ID") ENABLE NOVALIDATE;
