CREATE OR REPLACE VIEW "APPLICANT_VIEW" AS
SELECT
"INSTANCE"."INSTANCE_ID",
(SELECT string_agg("ANSWER", ', ' ORDER BY "QUESTION_ID" DESC)
  FROM
  "ANSWER"
  WHERE
  "INSTANCE"."INSTANCE_ID" = "ANSWER"."INSTANCE_ID"
  AND
  (
    "ANSWER"."QUESTION_ID" = 23
    OR
    "ANSWER"."QUESTION_ID" = 221
  )
  AND
  "ANSWER"."CHAPTER_ID" = 1
  AND
  "ANSWER"."ITEM" = 1
) AS "APPLICANT"
FROM "INSTANCE";

CREATE OR REPLACE  VIEW "ANSWER_STREET_BG" AS
	SELECT
		"ANSWER",
		"INSTANCE_ID"
	FROM
		"ANSWER"
	WHERE
		"QUESTION_ID" = 93
		AND
		"CHAPTER_ID" = 21
		AND
		"ITEM" = 1;

CREATE OR REPLACE  VIEW "ANSWER_STREET_NP" AS
	SELECT
		"ANSWER",
		"INSTANCE_ID"
	FROM
		"ANSWER"
	WHERE
		"QUESTION_ID" = 93
		AND
		"CHAPTER_ID" = 101
		AND
		"ITEM" = 1;

CREATE OR REPLACE  VIEW "ANSWER_STREET_247" AS
	SELECT
		"ANSWER",
		"INSTANCE_ID"
	FROM
		"ANSWER"
	WHERE
		"QUESTION_ID" = 93
		AND
		"CHAPTER_ID" = 102
		AND
		"ITEM" = 1;

create or replace FUNCTION "GET_INST_STATE_DESCRIPTION" (STATE_NAME VARCHAR)
	RETURNS varchar AS $$
DECLARE
	DESCRIPTION varchar;
BEGIN
	SELECT
		"DESCRIPTION" into DESCRIPTION
	FROM
		"INSTANCE_STATE_DESCRIPTION"
	WHERE
		"INSTANCE_STATE_ID" = "GET_INST_STATE_ID_BY_NAME"(STATE_NAME);
	RETURN DESCRIPTION;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION
"GET_INST_STATE_ID_BY_NAME" (STATE_NAME VARCHAR)
	RETURNS integer AS $$
DECLARE
	ID integer;
BEGIN
	SELECT
		"INSTANCE_STATE_ID" into ID
	FROM
		"INSTANCE_STATE"
	WHERE
		LOWER("NAME") = LOWER(STATE_NAME);
	RETURN ID;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE VIEW "PRESET_INTENTIONS" ("NAME", "VALUE", "INSTANCE_ID") AS
SELECT
		"ANSWER_LIST"."NAME",
		"ANSWER_LIST"."VALUE",
		"ANSWER"."INSTANCE_ID"
	FROM
		"ANSWER_LIST"
	JOIN
		"ANSWER" ON (
			"ANSWER"."QUESTION_ID" = 97
			AND
			"CHAPTER_ID" = 21
			AND
			"ITEM" = 1
		)
	WHERE
			"ANSWER_LIST"."QUESTION_ID" = 97
		AND
			"ANSWER"."ANSWER"::jsonb ? "ANSWER_LIST"."VALUE";

CREATE OR REPLACE VIEW "OTHER_INTENTIONS" ("ANSWER", "INSTANCE_ID") AS
SELECT
	"ANSWER",
	"INSTANCE_ID"
	FROM
		"ANSWER"
	WHERE
		(
			"QUESTION_ID" = 98
			AND
			(
				"CHAPTER_ID" = 21
				OR
				"CHAPTER_ID" = 101
			)
			AND
			"ITEM" = 1
		)
		OR
		(
			"QUESTION_ID" = 93
			AND
			"CHAPTER_ID" = 102
		);

CREATE OR REPLACE VIEW "INTENTIONS" AS
SELECT
		"PRESET_INTENTIONS"."NAME"         "NAME",
		"PRESET_INTENTIONS"."INSTANCE_ID"  "INSTANCE_ID"
		FROM
		"PRESET_INTENTIONS"
	UNION
	SELECT
		"OTHER_INTENTIONS"."ANSWER"       "NAME",
		"OTHER_INTENTIONS"."INSTANCE_ID"  "INSTANCE_ID"
		FROM
		"OTHER_INTENTIONS";
