ALTER TABLE IR_EDITCIRCULATION ADD (
		CIRCULATION_EMAIL_ACTION_ID NUMBER(10)
	);

	ALTER TABLE "IR_EDITCIRCULATION" ADD CONSTRAINT "FKIR_EDITCIR466073" FOREIGN KEY ("CIRCULATION_EMAIL_ACTION_ID") REFERENCES "ACTION" ("ACTION_ID");
