<div class="table-container column column-100">

	<div class="title">
		<ul>
			<li class="type">
				<span class="icon icon-info"  aria-hidden="true"></span>
			</li>
			<li class="active">
				<a href="javascript:void(0)">
					<span class="icon icon-puzzle"  aria-hidden="true"></span>
					<?php echo $this->translate("Templateclasses") ?>
				</a>
			</li>
			<li class="help">
				<a href="javascript:void(0)">
					<span class="icon icon-question"  aria-hidden="true"></span>
				</a>
				<div class="tooltip">
					<p>
						<?php echo $this->translate('The actions are availables through a context menu. Right click to trigger the context menu.') ?><br/>
					</p>
				</div>
			</li>
		</ul>
	</div>
	<table class="datatables context-menu templateclass" data-menu="templateclass" data-disable-sorting="1" data-display-length="25">
		<thead>
			<tr>
				<th class="no-sort">
					<?php echo $this->translate('Name') ?>
				</th>
				<th class="no-sort">
					<?php echo $this->translate('Type') ?>
				</th>
			</tr>
		</thead>
		<tbody>
			<?php if (count($this->rows)) :?>
				<?php foreach ($this->rows as $row) : ?>
					<tr data-id="<?php echo $row->docgenTemplateclassId ?>">
						<td>
							<span class="icon icon-puzzle" area-hidden="true"></span>
							<?php echo $this->escape($row->name); ?>
						</td>
						<td>
							<?php echo $row->type == Docgen_Model_Mapper_Templateclass::TYPE_DOCX ? 'DocX' : 'PDF' ?>
						</td>
					</tr>
				<?php endforeach ?>
			<?php else : ?>
					<tr class="alert information">
						<td class="empty">
							<span aria-hidden="true" class="icon-info"></span>
							<?php echo $this->translate('No templateclasses found.') ?>
						</td>
						<td class="empty"> </td>
					</tr>
			<?php endif ?>
		</tbody>
	</table>
</div>

<ul class="templateclass-menu context-menu">
	<li>
		<span><?php echo $this->translate('Templateclass')?></span>
	</li>
	<li class="edit-only">
		<a href="<?php echo $this->url(array(
				'controller' => 'module_data-loader',
				'action'     => 'delete',
				'module-id'  => 'docgen',
				'data-id'    => 'templateclass',
				'id'         => '%id'
			)) ?>">
			<span class="icon-remove"></span>
			<?php echo $this->translate('Delete') ?>
		</a>
	</li>
	<li class="edit-only">
		<a href="<?php echo $this->url(array(
				'controller' => 'module_data-loader',
				'action'     => 'edit',
				'module-id'  => 'docgen',
				'data-id'    => 'templateclass',
				'id'         => '%id'
				)) ?>">
			<span class="icon-pencil"></span>
			<?php echo $this->translate('Edit') ?>
		</a>
	</li>
	<?php /*
	<li class="edit-only">
		<a href="<?php echo $this->url(array(
			'controller' => 'module_data-loader',
			'action'     => 'download',
			'module-id'  => 'docgen',
			'data-id'    => 'templateclass'
		)) ?>">
		<span class="icon-download3"></span>
		<?php echo $this->translate('Download') ?>
		</a>
	</li>
	*/ ?>
	<li>
		<a href="<?php echo $this->url(array(
				'controller' => 'module_data-loader',
				'action'     => 'add',
				'module-id'  => 'docgen',
				'data-id'    => 'templateclass')) ?>">
			<span class="icon-plus"></span>
			<?php echo $this->translate('Add') ?>
		</a>
	</li>

</ul>
