mutation CreateInternalWorkflow {
  saveWorkflow(
    input: {
      slug: "internal"
      name: "Internes Verfahren"
      startTasks: ["submit"]
      allowForms: ["baupolizeiliches-verfahren", "zutrittsermaechtigung", "zutrittsermaechtigung-v2"]
      isPublished: true
    }
  ) {
    clientMutationId
  }
}

mutation CreateFlow {
  addWorkflowFlow(
    input: {
      workflow: "internal"
      tasks: ["submit"]
      next: "['ebau-number', 'audit', 'nfd', 'decision', 'create-manual-workitems']|tasks"
    }
  ) {
    clientMutationId
  }
}
