<?php
	$instanceId    = Camac_Nest_Pigeon::getInstance()->instanceId;
	$instLocMapper = new Application_Model_Mapper_InstanceLocation();

	// we always only save one location on an instance
	$locations = $instLocMapper->getInstanceLocations($instanceId);
	$location = array_pop($locations);
?>

<?php switch ($location->getLocationId()):
	// funny thing here: "Any output (including whitespace) between a switch
	// statement and the first case will result in a syntax error."
	case 1: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/altdorf.pdf') ?>

	<?php break; case 2: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/andermatt.pdf') ?>

	<?php break; case 3: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/attinghausen.pdf') ?>

	<?php break; case 4: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/bauen.pdf') ?>

	<?php break; case 5: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/burglen.pdf') ?>

	<?php break; case 6: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/erstfeld.pdf') ?>

	<?php break; case 7: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/fluelen.pdf') ?>

	<?php break; case 10: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/hospental.pdf') ?>

	<?php break; case 11: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/isenthal.pdf') ?>

	<?php break; case 12: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/realp.pdf') ?>

	<?php break; case 13: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/schattdorf.pdf') ?>

	<?php break; case 14: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/seedorf.pdf') ?>

	<?php break; case 15: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/seelisberg.pdf') ?>

	<?php break; case 16: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/silenen.pdf') ?>

	<?php break; case 17: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/sisikon.pdf') ?>

	<?php break; case 18: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/spiringen.pdf') ?>

	<?php break; case 19: ?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/unterschachen.pdf') ?>

	<?php break; case 9: // gurtnellen ?>
	<?php case 8: // göschenen?>
	<?php case 20: // wassen?>
		<?php echo $this->baseUrl('/public/pdf/sign_pages/bkuo.pdf') ?>

	<?php break; default ?>
		http://www.ur.ch/de/verwaltung/dienstleistungen/?dienst_id=3693
	<?php break; ?>
<?php endswitch ?>
