CREATE OR REPLACE VIEW PRESET_INTENTIONS AS

    SELECT 
		"ANSWER_LIST"."NAME",
		"ANSWER_LIST"."VALUE",
		"ANSWER"."INSTANCE_ID"
	FROM 
		"ANSWER_LIST",
		 "ANSWER"

	WHERE (
			"ANSWER"."QUESTION_ID" = 97
			AND
			"CHAPTER_ID" = 21
			AND
			"ITEM" = 1
		)

		AND 
			"ANSWER_LIST"."VALUE" IN (
				select "VAL" from table(json_unserialize("ANSWER"))
			)
;

CREATE OR REPLACE VIEW OTHER_INTENTIONS AS 
	
	SELECT
		"ANSWER",
		"INSTANCE_ID"
		FROM
			"ANSWER"
		WHERE
			"QUESTION_ID" = 98
			AND
			(
				"CHAPTER_ID" = 21
				OR
				"CHAPTER_ID" = 101
			)
			AND
			"ITEM" = 1

	;

CREATE OR REPLACE VIEW INTENTIONS AS 

	SELECT
		"PRESET_INTENTIONS"."NAME"         "NAME",
		"PRESET_INTENTIONS"."INSTANCE_ID"  "INSTANCE_ID"
		FROM
		"PRESET_INTENTIONS"
	UNION
	SELECT
		"OTHER_INTENTIONS"."ANSWER"       "NAME",
		"OTHER_INTENTIONS"."INSTANCE_ID"  "INSTANCE_ID"
		FROM
		"OTHER_INTENTIONS"

;

SELECT * FROM INTENTIONS WHERE "INSTANCE_ID" = 2757;


select LISTAGG("NAME", ', ') WITHIN GROUP (ORDER BY "NAME") from INTENTIONS
where instance_id = 2718;
