ALTER TABLE CAMAC.DOCGEN_ACTIVATION_DOCKET
DROP CONSTRAINT ACTIVATION_DOCKET_FK2;

ALTER TABLE CAMAC.DOCGEN_ACTIVATION_DOCKET
ADD CONSTRAINT ACTIVATION_DOCKET_FK2
FOREIGN KEY (ACTIVATION_ID)
REFERENCES CAMAC.ACTIVATION(ACTIVATION_ID)
ON DELETE CASCADE;


