from dataclasses import asdict
from datetime import datetime

import pytest
from django.utils.timezone import make_aware

from camac.dossier_import.config.kt_ag.dossier_import.dossier_loader import (
    KtAargauDossierLoader,
    datetime_from_long_number,
)
from camac.dossier_import.dossier_classes import Dossier
from camac.dossier_import.tests.test_utils import to_sorted_json


def test_datetime_from_long_number():
    assert datetime_from_long_number(20250415082103.53) == make_aware(
        datetime(2025, 4, 15, 8, 21, 3)
    )
    assert datetime_from_long_number(20250415082103) == make_aware(
        datetime(2025, 4, 15, 8, 21, 3)
    )
    assert datetime_from_long_number(0) is None
    assert datetime_from_long_number(None) is None


def test_simple_mapping(snapshot):
    result: Dossier = KtAargauDossierLoader.map_data(
        {
            "GESUCH_ID": "EBPA-0001-6924",
            "TXT30": "Verfügung erstellt",
            "BTITEL": "EFH Muster",
            "GEMEINDE_BG": "2021-344",
            "BVUAFBNR": "BVUAFB.21.104",
            "EINDAT": "20210629",
            "CITY": "Möhlin",
            "CITY_ID": "4254",
            "PROFIL_KTR": "00000000",
            "STANDORTE": [
                {
                    "STRASSE": "Musterstrasse",
                    "STRASNR": "1",
                    "KOORDB": "1300000",
                    "KOORDL": "2480000",
                    "POSTAL_CODE": "4663",
                    "CITY": "Möhlin",
                    "CITY_ID": "4254",
                }
            ],
        }
    )

    snapshot.assert_match(to_sorted_json(asdict(result)))


def test_empty_string(snapshot):
    result: Dossier = KtAargauDossierLoader.map_data(
        {
            "ERDSND_KNZ": "",
        }
    )

    snapshot.assert_match(to_sorted_json(asdict(result)))


def test_missing_fields():
    result: Dossier = KtAargauDossierLoader.map_data({})
    assert result
    assert result.id is None
    assert len(result.applicant) == 0
    assert len(result.landowner) == 0
    assert len(result.project_author) == 0


def test_mapping_for_multiple_locations(snapshot):
    result: Dossier = KtAargauDossierLoader.map_data(
        {
            "CITY": "Möhlin",
            "CITY_ID": "4254",
            "STANDORTE": [
                {
                    "STRASSE": "Andere Strasse",
                    "STRASNR": "5",
                    "CITY": "Aarburg",
                    "CITY_ID": "4271",
                },
                {
                    "STRASSE": "Musterstrasse",
                    "STRASNR": "1",
                    "CITY": "Möhlin",
                    "CITY_ID": "4254",
                },
                {
                    "STRASSE": "Nicht gematchte Strasse",
                    "STRASNR": "11",
                    "CITY": "Möhlin",
                    "CITY_ID": "4254",
                },
            ],
        }
    )

    snapshot.assert_match(to_sorted_json(asdict(result)))


@pytest.mark.order(1)
def test_all_mappings(snapshot):
    result: Dossier = KtAargauDossierLoader.map_data(
        {
            "GESUCH_ID": "EBPA-0001-6924",
            "BTITEL": "EFH Muster",
            "BSGUID_TXT": "Dies ist eine detaillierte Beschreibung",
            "BVUAFBNR": "BVUAFB.21.104",
            "GEMEINDE_BG": "2021-344",
            "EINDAT": "20210629",
            "CITY": "Aarau",
            "CITY_ID": "4001",
            "ERFGRND": "Nacherfassung",
            "VERFTYP": "Ordentlich",
            "GEMEINDE_STATUS": "Verfügung erstellt",
            "KANTONS_STATUS": "Neues Gesuch",
            "PROFIL_KNZ": "1",
            "PROFIL_DAT": "20240213",
            "PRGUID": "",
            "PROFIL_KTR": "20250501",
            "PROFIL_OK": "",
            "BAUANL_KNZ": "X",
            "REKLAM_KNZ": "",
            "ABRUCH_KNZ": "",
            "UMNUTZ_KNZ": "",
            "ANFRAG_KNZ": "",
            "VORENT_KNZ": "",
            "RODUNG_KNZ": "",
            "UMWELT_KNZ": "X",
            "PARZELLEN": [
                {
                    "SGUID": "e1a5f3d1-7126-4a7d-b355-b3ac8ad9",
                    "PGUID": "f32b7723-87ed-4010-8c2a-38ad3e09",
                    "PARZNR": "123123",
                    "PARZM2": "",
                    "CITY": "Aarburg",
                    "CITY_ID": "4271",
                },
                {
                    "SGUID": "3ed4fbbd-e6a5-4daf-a5dc-177fc47e",
                    "PGUID": "6e0dbfb8-62f0-4f86-a597-d9e0edc5",
                    "PARZNR": "234234",
                    "PARZM2": "",
                    "CITY": "Aarau",
                    "CITY_ID": "4001",
                },
            ],
            "STANDORTE": [
                {
                    "STRASSE": "Aarburg-Mapping-Str. 5",
                    "STRASNR": "",
                    "ASSEKNR": "1234",
                    "EGID": "2345",
                    "KOORDB": "1111",
                    "KOORDL": "1111",
                    "POSTAL_CODE": "4663",
                    "CITY": "Aarburg",
                    "CITY_ID": "4271",
                },
                {
                    "STRASSE": "Aarau-Mapping-Str. 1",
                    "STRASNR": "",
                    "ASSEKNR": "3456",
                    "EGID": "4567",
                    "KOORDB": "2635136",
                    "KOORDL": "1240872",
                    "POSTAL_CODE": "5004",
                    "CITY": "Aarau",
                    "CITY_ID": "4001",
                },
            ],
            "KONTAKTE": [
                {
                    "PTROL": "BH",
                    "FIRMA": "",
                    "NAME": "Mapper",
                    "VNAM": "Manfred",
                    "STRASSE": "Mappingstr.",
                    "STRASNR": "777",
                    "PLZ": "7777",
                    "ORT": "Mappingen",
                    "TELMOBI": "076 331 9446",
                    "TELFEST": "061 511 3600",
                    "EMAIL": "manfred@mapper.ch",
                },
                {
                    "PTROL": "GE",
                    "FIRMA": "Grundbesitzer AG",
                    "VNAM": "Gero",
                    "NAME": "Grund",
                    "STRASSE": "Gundeldingerstr.",
                    "STRASNR": "1",
                    "PLZ": "4000",
                    "ORT": "Basel",
                    "TELMOBI": "",
                    "TELFEST": "+41 61 228 9400",
                    "EMAIL": "gero.grund@grundbesitz.com",
                },
                {
                    "PTROL": "PV",
                    "FIRMA": "Architekturbüro Bauschön",
                    "NAME": "Schön",
                    "VNAM": "Benno",
                    "STRASSE": "Im schönen Ort",
                    "STRASNR": "3",
                    "PLZ": "1234",
                    "ORT": "Belair",
                    "TELMOBI": "076 123 23456",
                    "TELFEST": "",
                    "EMAIL": "schoen@bauschoen.ar",
                },
                {
                    "PTROL": "BH",
                    "FIRMA": "",
                    "NAME": "Mapper",
                    "VNAM": "Manuela",
                    "STRASSE": "Mappingstr.",
                    "STRASNR": "777",
                    "PLZ": "7777",
                    "ORT": "Mappingen",
                    "TELMOBI": "",
                    "TELFEST": "",
                    "EMAIL": "manu@mapper.ch",
                },
                {
                    "PTROL": "GV",
                    "FIRMA": "",
                    "NAME": "Vertreter",
                    "VNAM": "Gesetzlicher",
                    "STRASSE": "Mappingstr.",
                    "STRASNR": "777",
                    "PLZ": "7777",
                    "ORT": "Mappingen",
                    "TELMOBI": "",
                    "TELFEST": "",
                    "EMAIL": "legal@repr.ch",
                },
                {
                    "PTROL": "RE",
                    "FIRMA": "",
                    "NAME": "Recipient",
                    "VNAM": "Invoice",
                    "STRASSE": "Mappingstr.",
                    "STRASNR": "777",
                    "PLZ": "7777",
                    "ORT": "Mappingen",
                    "TELMOBI": "",
                    "TELFEST": "",
                    "EMAIL": "invoices@mapper.ch",
                },
            ],
            "WOHNUTZ": [
                {
                    "ANZ_WHG": "2",
                    "ANZ_ZIM": "2",
                    "ANZ_ZWHG": "1",
                },
                {
                    "ANZ_WHG": "3",
                    "ANZ_ZIM": "3",
                    "ANZ_ZWHG": "1",
                },
                {
                    "ANZ_WHG": "2",
                    "ANZ_ZIM": "",
                    "ANZ_ZWHG": "",
                },
            ],
            # Zweckbestimmung
            "WHNTZ_KNZ": "X",
            "GINTZ_KNZ": "X",
            "GINTZ_ART": "Gewerbe",
            "GIBRANCHE": "Telekommunikation",
            "LWNTZ_KNZ": "X",
            "LWNTZ_EL": "10000",
            "LWNTZ_PL": "20000",
            "LWNTZ_TBB": "50",
            "LWNTZ_TBN": "75",
            "ABNTZ_KNZ": "X",
            "ABNTZ_BEZ": "Garage",
            "ABNTZ_ART": "Privat",
            # Gebäudehülle
            "AWND_BART": "Schiefer",
            "AWND_COL": "dunkelgrau",
            "DBEL_MAT": "Beton",
            "DBEL_COL": "gr\u00fcn",
            # Parkplätze
            "PARK_KNZ": "X",
            "ANZ_OPARK": "1",
            "ANZ_OPARK_P": "2",
            "ANZ_OPARK_NP": "3",
            "ANZ_NPARK": "4",
            "ANZ_NPARK_P": "5",
            "ANZ_NPARK_NP": "6",
            # Gebäudeheizung und Energie
            "GHNO_KNZ": "X",
            "GHIS_KNZ": "X",
            "GHNW_KNZ": "X",
            "GHNW_KW": "2000",
            "GHES_KNZ": "X",
            "GHES_KW": "1000",
            "GHUK_KNZ": "X",
            "GHGUID_TXT": "Some text here",
            "BA_OEL_KNZ": "X",
            "BA_OEN_KNZ": "1",
            "BA_GAS": "X",
            "BA_HLZ": "X",
            "BA_ELK": "X",
            "BA_FRN": "X",
            "BA_WAP": "X",
            "BA_WAB": "X",
            "BA_LUF": "X",
            "BA_OTH": "X",
            "BA_OTB": "was ganz anderes",
            # Kanalisationsanschluss, Dach- und Sickerwasser
            "KA_LGS_KNZ": "X",
            "KA_LGN_KNZ": "bestehend",
            "KA_BAU_KNZ": "X",
            "KA_BAN_KNZ": "nicht angeschlossen",
            "DS_VSK_KNZ": "X",
            "DS_VSN_KNZ": "0",
            "DS_OGW_KNZ": "X",
            "DS_OGN_KNZ": "0",
            "DS_KNL_KNZ": "X",
            "DS_KNN_KNZ": "0",
            "DS_EIG_KNZ": "X",
            # Bauzonen
            "BAU_ZON": "innerhalb rechtskr\u00e4ftiger Bauzone",
            "NTZ_ZON": "Nuzungszone",
            "UBL_ZON": "\u00dcberlagerte Zone",
            "SND_PLN": "Sondernutzungsplanung",
            # Dichteziffern
            "ASN_ZIF_ZOD": "10.0",
            "ASN_ZIF_BPJ": "9.1",
            "BMS_ZIF_ZOD": "8.2",
            "BMS_ZIF_BPJ": "7.3",
            "GFL_ZIF_ZOD": "4.6",
            "GFL_ZIF_BPJ": "5.5",
            "GSF_ZIF_ZOD": "6.4",
            "GSF_ZIF_BPJ": "3.7",
            "UEB_ZIF_ZOD": "2.8",
            "UEB_ZIF_BPJ": "1.9",
            # Bauzonen - weitere Angaben
            "GWS_AU_KNZ": "X",
            "GWS_UB_KNZ": "X",
            "GWS_QB_KNZ": "X",
            "HWG_KNZ": "1",
            "EKE_ERF": "nicht erforderlich",
            "EMP_STF": "4",
            # Umweltrechtliche Angaben
            "ERDSND_KNZ": "X",
            "SDBOHR_KNZ": "X",
            "SOLAR_KNZ": "X",
            "ALTLAST_KNZ": "X",
            "GWABSNK_KNZ": "X",
            "BODEIN_KNZ": "X",
            "LSMERF_KNZ": "X",
            "MATABB_KNZ": "X",
            "KANAL_KNZ": "X",
            "ENERGIE_KNZ": "X",
            # Angaben zur Sicherheit
            "BS_KANT_KNZ": "X",
            "BSFKANT_KNZ": "X",
            "BS_KOMM_KNZ": "X",
            "BETRIEB_KNZ": "X",
            "STOER_KNZ": "X",
            "HWGEFHR_KNZ": "X",
            "SRBAUPF_KNZ": "X",
            # Kantonsstrasse, Wald
            "KANTSTR_KNZ": "X",
            "BAULINE_KNZ": "X",
            "ERSCHLS_KNZ": "X",
            "REKLAME_KNZ": "X",
            "BLGUID_TXT": "Grund der Unterschreitung",
            "MAWALD_KNZ": "X",
            "BVWALD_KNZ": "X",
            "MAGUID_TXT": "Grund der Unterschreitung",
            # Bauen ausserhalb der Bauzone
            "LWBETR_KNZ": "X",
            "BSTAND_KNZ": "X",
            "BVBZON_KNZ": "X",
            "TVBZON_KNZ": "X",
            # Weitere Angaben, Gewässer, ...
            "OEFFGW_KNZ": "X",
            "OEFFGW_NAM": "Bodensee",
            "OEFFGW_ABS": "X",
            "GWGUID_TXT": "Ich habe nah am Wasser gebaut",
            "OEFFGW_EIN": "X",
            "DENKMAL_KNZ": "X",
            "LFHIND_KNZ": "X",
            # Baukosten
            "BKOLND": 1700000,
            "BKUMGB": 40000,
            "BKTOTAL": 1740000,
            # Weitere Angaben - Bemerkungen
            "BKGUID_TXT": "Famous last words",
            "VERFSTAND": [
                {
                    "MANDT": "600",
                    "PROCESS_ID": "ZEBP",
                    "EXTERN_ID": "EBPA-0219-7779",
                    "VGUID": "005056ABB4351EDD92DB92C8A93BF8A2",
                    "VORIGIN": "S",
                    "ACTION": "Gesuch an Kanton senden",
                    "STEP": "Gesuch an Kanton gesendet",
                    "TSTAMPL": 20221013095122.074,
                    "WHOTXT": "Testautomatisierung EBP",
                    "KOMMENTAR": "Gesuch EBPA-0219-7779 wurde an den Kanton gesendet.",
                    "VFSTD_ID": "1500",
                    "DOC_ID": "0000000000000000000000000",
                },
                {
                    "MANDT": "600",
                    "PROCESS_ID": "ZEBP",
                    "EXTERN_ID": "EBPA-0219-7779",
                    "VGUID": "005056ABB4351EDD949070992C1CD8A2",
                    "VORIGIN": "S",
                    "ACTION": "Dokumente an Kanton senden",
                    "STEP": "Dokumente an Kanton gesendet",
                    "TSTAMPL": 20221020142900.65,
                    "WHOTXT": "EB2_AFB_02",
                    "KOMMENTAR": "Dokumente vom Gesuch EBPA-0219-7779 wurden an den Kanton gesendet.",
                    "VFSTD_ID": "1510",
                    "DOC_ID": "0000000000000000000000000",
                },
            ],
            "KOMMENTARE": [
                {
                    "MANDT": "600",
                    "GESUCH_ID": "EBPA-4406-5058",
                    "GUID": "005056ABB4351FD092F1938B54F778C1",
                    "SACHB": "EB2_AFB_01",
                    "KOMMENTAR": "Kommentar aus eBau AG",
                    "CREATED_AT": 20250617150613,
                    "SACHB_FIRSTNAME": "Markus Test",
                    "SACHB_LASTNAME": "Krause Test",
                }
            ],
            "DWFLOW": [
                {
                    "MANDT": "600",
                    "PROCESS_ID": "ZEBP",
                    "DWGUID": "005056ABB4351EDF88E2D652AD0EF8B3",
                    "DWTYP": "Stellungnahme Gesuch",
                    "DWBEG": "20240605",
                    "DWEND": "00000000",
                    "DWSTAT": "offen",
                    "STDATE": "00000000",
                    "ANTRAG": "",
                    "ACTIVE": "X",
                    "GUID1": "",
                    "GUID2": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "ERGGUID": "",
                    "BVIGUID": "",
                    "ERGGUID2": "",
                },
                {
                    "MANDT": "600",
                    "PROCESS_ID": "ZEBP",
                    "DWGUID": "005056ABB4351EDF88E2DA476D3F18B3",
                    "DWTYP": "Einsicht",
                    "DWBEG": "20240605",
                    "DWEND": "00000000",
                    "DWSTAT": "",
                    "STDATE": "00000000",
                    "ANTRAG": "",
                    "ACTIVE": "X",
                    "GUID1": "",
                    "GUID2": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "ERGGUID": "",
                    "BVIGUID": "",
                    "ERGGUID2": "",
                },
                {
                    "MANDT": "600",
                    "PROCESS_ID": "ZEBP",
                    "DWGUID": "005056ABB4351EDF8CC4AEB16F86B8B4",
                    "DWTYP": "Stellungnahme Gesuch",
                    "DWBEG": "20240624",
                    "DWEND": "00000000",
                    "DWSTAT": "offen",
                    "STDATE": "00000000",
                    "ANTRAG": "",
                    "ACTIVE": "X",
                    "GUID1": "",
                    "GUID2": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "ERGGUID": "",
                    "BVIGUID": "",
                    "ERGGUID2": "",
                },
            ],
            "DWFLOW_DOC": [
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2D652AD0EF8B3",
                    "DMS_ID": "0000000000000010001925809",
                    "EMPFGUID": "",
                    "DOCTYPE": "Stellungnahme einfordern",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240605",
                    "DTIME": "103627",
                    "BEMERKUNG": "",
                    "DMS_VERS": "01",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2D652AD0EF8B3",
                    "DMS_ID": "0000000000000010001922835",
                    "EMPFGUID": "",
                    "DOCTYPE": "Stellungnahme einfordern",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240605",
                    "DTIME": "103627",
                    "BEMERKUNG": "",
                    "DMS_VERS": "00",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2DA476D3F18B3",
                    "DMS_ID": "0000000000000010001925809",
                    "EMPFGUID": "",
                    "DOCTYPE": "R\u00fcckbau akzeptieren",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240605",
                    "DTIME": "103726",
                    "BEMERKUNG": "",
                    "DMS_VERS": "00",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2DA476D3F18B3",
                    "DMS_ID": "0000000000000010001925809",
                    "EMPFGUID": "",
                    "DOCTYPE": "R\u00fcckbau akzeptieren",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240605",
                    "DTIME": "103726",
                    "BEMERKUNG": "",
                    "DMS_VERS": "01",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2DA476D3F18B3",
                    "DMS_ID": "0000000000000010001925810",
                    "EMPFGUID": "",
                    "DOCTYPE": "R\u00fcckbau akzeptieren",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240605",
                    "DTIME": "103726",
                    "BEMERKUNG": "",
                    "DMS_VERS": "00",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2DA476D3F18B3",
                    "DMS_ID": "0000000000000010001925811",
                    "EMPFGUID": "",
                    "DOCTYPE": "R\u00fcckbau akzeptieren",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240605",
                    "DTIME": "103726",
                    "BEMERKUNG": "",
                    "DMS_VERS": "00",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2DA476D3F18B3",
                    "DMS_ID": "0000000000000010001925814",
                    "EMPFGUID": "",
                    "DOCTYPE": "R\u00fcckbau akzeptieren",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240605",
                    "DTIME": "103726",
                    "BEMERKUNG": "",
                    "DMS_VERS": "00",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2DA476D3F18B3",
                    "DMS_ID": "0000000000000010001925808",
                    "EMPFGUID": "",
                    "DOCTYPE": "R\u00fcckbau akzeptieren",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240605",
                    "DTIME": "103726",
                    "BEMERKUNG": "",
                    "DMS_VERS": "00",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2DA476D3F18B3",
                    "DMS_ID": "0000000000000010001922835",
                    "EMPFGUID": "",
                    "DOCTYPE": "R\u00fcckbau akzeptieren",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240605",
                    "DTIME": "103726",
                    "BEMERKUNG": "",
                    "DMS_VERS": "00",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2DA476D3F18B3",
                    "DMS_ID": "0000000000000010001922836",
                    "EMPFGUID": "",
                    "DOCTYPE": "R\u00fcckbau akzeptieren",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240605",
                    "DTIME": "103726",
                    "BEMERKUNG": "",
                    "DMS_VERS": "00",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF8CC4AEB16F86B8B4",
                    "DMS_ID": "0000000000000010001925809",
                    "EMPFGUID": "",
                    "DOCTYPE": "Stellungnahme einfordern",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240624",
                    "DTIME": "142954",
                    "BEMERKUNG": "",
                    "DMS_VERS": "01",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF8CC4AEB16F86B8B4",
                    "DMS_ID": "0000000000000010001925811",
                    "EMPFGUID": "",
                    "DOCTYPE": "Stellungnahme einfordern",
                    "ULDL": "",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DDATE": "20240624",
                    "DTIME": "142954",
                    "BEMERKUNG": "",
                    "DMS_VERS": "00",
                },
            ],
            "DWFLOW_REC": [
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2DA476D3F18B3",
                    "EMPFGUID": "005056ABB4351EDF88E2DA476D3F38B3",
                    "EMPFID": "",
                    "EMPFNAM": "eBau Training FS",
                    "EMPFADR": "ebau.training+fs@gmail.com",
                    "REASON": "",
                    "MAN_KNZ": "",
                    "ACTIVE": "X",
                    "DDATE": "20240605",
                    "DTIME": "103726",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "RCSTAT": "",
                    "BEMERKUNG": "",
                    "ANTRAG": "",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF8CC4AEB16F86B8B4",
                    "EMPFGUID": "005056ABB4351EDF8CC4AEB16F86D8B4",
                    "EMPFID": "N858614511",
                    "EMPFNAM": "eBau extFachstelle Viktor Sch.",
                    "EMPFADR": "ebau.extended+extFS@gmail.com",
                    "REASON": "",
                    "MAN_KNZ": "",
                    "ACTIVE": "X",
                    "DDATE": "20240624",
                    "DTIME": "142954",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "RCSTAT": "Offen",
                    "BEMERKUNG": "",
                    "ANTRAG": "",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2D652AD0EF8B3",
                    "EMPFGUID": "005056ABB4351EDF88E2D652AD0F18B3",
                    "EMPFID": "N433697952",
                    "EMPFNAM": "eBau Training FS",
                    "EMPFADR": "ebau.training+fs@gmail.com",
                    "REASON": "",
                    "MAN_KNZ": "",
                    "ACTIVE": "",
                    "DDATE": "20240605",
                    "DTIME": "000000",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "RCSTAT": "Offen",
                    "BEMERKUNG": "",
                    "ANTRAG": "",
                },
                {
                    "MANDT": "600",
                    "DWGUID": "005056ABB4351EDF88E2D652AD0EF8B3",
                    "EMPFGUID": "005056ABB4351EDF8CC4AEB16F86D8B4",
                    "EMPFID": "N858614511",
                    "EMPFNAM": "eBau extFachstelle Viktor Sch.",
                    "EMPFADR": "ebau.extended+extFS@gmail.com",
                    "REASON": "",
                    "MAN_KNZ": "",
                    "ACTIVE": "",
                    "DDATE": "20240624",
                    "DTIME": "000000",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "RCSTAT": "Offen",
                    "BEMERKUNG": "",
                    "ANTRAG": "",
                },
            ],
            "ENTSCHEID": [
                {
                    "MANDT": "600",
                    "GUID": "005056ABB4351EDFA8997FEF899E78BA",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "ART_ID": "Bewilligung",
                    "ART_TEXT": "Bewilligung",
                    "VERFUGUNGSDAT": "20241112",
                    "RECHTSKRAFTDAT": "20241128",
                    "RECHTMITTELDAT": "00000000",
                    "BEMERKUNG": "",
                },
                {
                    "MANDT": "600",
                    "GUID": "005056ABB4351FD099DD6AE766D518C2",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "ART_ID": "Bewilligung",
                    "ART_TEXT": "Bewilligung",
                    "VERFUGUNGSDAT": "20250722",
                    "RECHTSKRAFTDAT": "20250728",
                    "RECHTMITTELDAT": "00000000",
                    "BEMERKUNG": "Nur der Schuppen",
                },
            ],
            "DATES": [
                {
                    "MANDT": "600",
                    "PROCESS_ID": "ZEBP",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "TRMTYP": "Frist",
                    "GUID": "005056ABB4351EDF8CC4AEB16F8AF8B4",
                    "DATVON": "20240613",
                    "DATBIS": "20240613",
                    "NOTICE": "Stellungnahme eBau Training FS ebau.training+fs@gmail.com",
                    "GRUND_KEY": "",
                    "GRUND_TXT": "",
                    "GUID2": "",
                    "CRUSR": "EBETDOB",
                    "CRDAT": "20240605",
                    "CRTIM": "103631",
                    "ABGS": "X",
                },
                {
                    "MANDT": "600",
                    "PROCESS_ID": "ZEBP",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "TRMTYP": "Auflagefrist",
                    "GUID": "005056ABB4351EDF8CC4AEB16F8B18B4",
                    "DATVON": "20240712",
                    "DATBIS": "20240712",
                    "NOTICE": "Stellungnahme eBau extFachstelle Viktor Sch. ebau.extended+extFS@gmail.com",
                    "GRUND_KEY": "",
                    "GRUND_TXT": "",
                    "GUID2": "",
                    "CRUSR": "EBP_TEST1",
                    "CRDAT": "20240624",
                    "CRTIM": "142959",
                    "ABGS": "X",
                },
            ],
            "KANTON_EINGANG": "20250612",
            "KANTON_BEARBEITUNGSFRIST": "20250811",
            "KANTON_GRUPPE": "DIBA Test Team",
            "KANTON_GRUPPE2": "DIBA Test Team",
            "KANTON_SACHBEARBEITER": "EMARHUB001",
            "KANTON_VORL_ABSCHLUSS": "20250930",
            "KANTON_ABSCHLUSSCODE": "teilweise Zustimmung",
            "KANTON_DAUER": 108,
            "KANTON_LWAG_NR": "1111111",
            "KANTON_STATUSVERLAUF": [
                {
                    "SOURCE": "S",
                    "TSTAMPL": 20230315101228,
                    "WHOTXT": "Kantons Admin eBau extended",
                    "KOMMENTAR": "Dokument hinzugef\u00fcgt mit der ID 0000000000000010001687849",
                    "DOC_ID": "0000000000000000000000000",
                    "DOC_VERSION": "",
                    "ACTION_TXT": "Dokument hinzugef\u00fcgt",
                    "STEP_TXT": "Gesuch in Bearbeitung",
                },
                {
                    "SOURCE": "S",
                    "TSTAMPL": 20230315102239,
                    "WHOTXT": "Kantons Admin eBau extended",
                    "KOMMENTAR": 'Gesuchsstatus wurde in "Freigabeverfahren" ge\u00e4ndert.',
                    "DOC_ID": "0000000000000000000000000",
                    "DOC_VERSION": "",
                    "ACTION_TXT": "Status \u00c4nderung",
                    "STEP_TXT": "Status \u00c4nderung",
                },
            ],
            "KANTON_KOMMENTARE": [
                {"TIMESTAMP": 20221020163137, "USER_ID": "EB2_AFB_02", "TEXT": ""},
                {
                    "TIMESTAMP": 20221020163153,
                    "USER_ID": "EB2_AFB_02",
                    "TEXT": "UE einfordern",
                },
            ],
            "KANTON_GESUCHSCODES": [
                {
                    "BAUG_ID": "A02",
                    "DESCRIPTION": "Art. 16a Landw. Wohnbauten, neue freistehende Geb\u00e4ude",
                }
            ],
            "KANTON_NUTZUNGSZONEN": [
                {"DESCRIPTION": "Innerhalb der Bauzone"},
                {"DESCRIPTION": "Materialabbauzone"},
            ],
            "KANTON_SCHUTZZONEN": [
                {"DESCRIPTION": "Grundwasserschutzzone"},
                {"DESCRIPTION": "Landschaftsschutzzone"},
            ],
            "KANTON_KANTSTR_KNZ": "X",
            "KANTON_STRASSEN": [
                {
                    "DESCRIPTION": "Nationalstrasse (Hochleistungsstrasse, HLS)",
                    "ROAD_NUMBER": "123",
                },
                {"DESCRIPTION": "Hauptverkehrsstrasse (HVS)", "ROAD_NUMBER": "111"},
            ],
            "KANTON_BAHNEN": [{"DESCRIPTION": "SBB"}, {"DESCRIPTION": "AVA"}],
            "KANTON_OEFFGW_KNZ": "X",
            "KANTON_GEWAESSER": [
                {"RIVER_ID": "1234", "RIVER_NAME": "DIBA-See"},
                {"RIVER_ID": "2345", "RIVER_NAME": "eBau - Weiher"},
            ],
            "KANTON_KANALISATION": "Nicht angeschlossen",
            "KANTON_MAWALD_KNZ": "X",
            "KANTON_SNDF_ENTW_KNZ": "X",
            "KANTON_GWABSNK_KNZ": "X",
            "KANTON_AWA_KNZ": "X",
            "KANTON_BVWALD_KNZ": "X",
            "KANTON_HWG_KNZ": "X",
            "KANTON_DENKMAL_KNZ": "X",
            "KANTON_WANDERWEGE_KNZ": "X",
            "KANTON_ORTSBILD": "X",
            "KANTON_STOER_KNZ": "X",
            "KANTON_ARCH_KNZ": "X",
            "KANTON_VERKEHR_KNZ": "X",
            "KANTON_LSMERF_KNZ": "X",
            "KANTON_MATABB_KNZ": "X",
            "KANTON_AGV_KNZ": "X",
            "KANTON_RADWEGE_KNZ": "X",
            "KANTON_FLACHENVERBRAUCH": 2000,
            "KANTON_KOKO_DATUM": "20250621",
            "KANTON_KOKO_STATUS": "",
            "KANTON_BESCHLUSS_GEMEINDE": "20250627",
            "KANTON_BESCHLUSS_ART": "Bewilligung (BEWIL)",
            "KANTON_VERZOGERUNG": "Interne kant. Fachstellen konnten ihre Termine nicht einhalten (INT)",
            "KANTON_BEGRUNDUNG": "Sommerferien",
            "KANTON_NACHTR_GESUCH_KNZ": "X",
            "KANTON_GEBUEHREN": [
                {
                    "COST_TYPE": "ZROD",
                    "DESCRIPTION": "Rodungsbewilligung AW",
                    "CALCULATION_SCHEME": "AW KFA 1",
                    "CALC_SCHEME_POSITION": "0010",
                    "REQUEST_TASK_ID": "000000028332",
                    "UNIT_PRICE": 0,
                    "AMOUNT": 1,
                    "MSEHI": "LE",
                    "TAKE": "",
                    "SHOW_IN_GV": "",
                    "COMMENT_FS": "",
                    "COMMENT_AFB": "",
                },
                {
                    "COST_TYPE": "ZATB",
                    "DESCRIPTION": "Behandlungsgeb\u00fchr ATB",
                    "CALCULATION_SCHEME": "ATB",
                    "CALC_SCHEME_POSITION": "0010",
                    "REQUEST_TASK_ID": "000000028333",
                    "UNIT_PRICE": 0,
                    "AMOUNT": 1,
                    "MSEHI": "LE",
                    "TAKE": "",
                    "SHOW_IN_GV": "",
                    "COMMENT_FS": "",
                    "COMMENT_AFB": "",
                },
                {
                    "COST_TYPE": "ZIAK",
                    "DESCRIPTION": "Aufbruchbewilligung ATB",
                    "CALCULATION_SCHEME": "ATB",
                    "CALC_SCHEME_POSITION": "0020",
                    "REQUEST_TASK_ID": "000000028333",
                    "UNIT_PRICE": 0,
                    "AMOUNT": 1,
                    "MSEHI": "LE",
                    "TAKE": "",
                    "SHOW_IN_GV": "",
                    "COMMENT_FS": "",
                    "COMMENT_AFB": "",
                },
            ],
            "KANTON_SISTIERUNGEN": [
                {
                    "DATVON": "20250904",
                    "DATBIS": "00000000",
                    "NOTE": "",
                    "REASON": "Unterlagenerg\u00e4nzung",
                    "PREV_STATUS": "Freigabeverfahren",
                    "CREATED_ON": "20250908",
                    "CREATED_BY": "FAMT",
                    "RESUME_DATE": "20250929",
                    "RESUME_BY": "MMOA",
                },
                {
                    "DATVON": "20251113",
                    "DATBIS": "00000000",
                    "NOTE": "",
                    "REASON": "Unterlagenerg\u00e4nzung",
                    "PREV_STATUS": "Freigabeverfahren",
                    "CREATED_ON": "20251113",
                    "CREATED_BY": "MMOA",
                    "RESUME_DATE": "00000000",
                    "RESUME_BY": "",
                },
                {
                    "DATVON": "20251030",
                    "DATBIS": "00000000",
                    "NOTE": "",
                    "REASON": "Unterlagenerg\u00e4nzung",
                    "PREV_STATUS": "Freigabeverfahren",
                    "CREATED_ON": "20251030",
                    "CREATED_BY": "MMOA",
                    "RESUME_DATE": "20251030",
                    "RESUME_BY": "MMOA",
                },
            ],
            "DOK_STATUS": [
                {
                    "MANDT": "600",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DMS_ID": "0000000000000010001922835",
                    "STATUS_ID": "B",
                    "STATUS_TEXT": "bewilligt",
                    "DMS_VERS": "00",
                },
                {
                    "MANDT": "600",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DMS_ID": "0000000000000010001922836",
                    "STATUS_ID": "B",
                    "STATUS_TEXT": "bewilligt",
                    "DMS_VERS": "00",
                },
                {
                    "MANDT": "600",
                    "EXTERN_ID": "EBPA-1720-6526",
                    "DMS_ID": "0000000000000010001925808",
                    "STATUS_ID": "U",
                    "STATUS_TEXT": "ung\u00fcltig",
                    "DMS_VERS": "00",
                },
            ],
        }
    )

    snapshot.assert_match(to_sorted_json(asdict(result)))
