# Generated by Django 3.2.19 on 2023-12-14 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0010_mark"),
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationsattachment",
            name="alexandria_file",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="alexandria_core.file",
            ),
        ),
    ]
