# Generated by Django 4.2.20 on 2025-03-19 15:58

import camac.communications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_communicationsreadmarker_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationsattachment',
            name='file_attachment',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to=camac.communications.models.attachment_path_directory_path),
        ),
    ]
