# Generated by Django 4.2.20 on 2025-06-03 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alexandria_core', '0022_alter_mark_name'),
        ('document', '0030_add_attachment_version'),
        ('communications', '0004_alter_communicationsattachment_file_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationsattachment',
            name='alexandria_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alexandria_core.file'),
        ),
        migrations.AlterField(
            model_name='communicationsattachment',
            name='document_attachment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='document.attachment'),
        ),
    ]
