export default {
  name: "sg",
  languages: ["de"],
  fallbackLanguage: "de",
  prodUrl: "ebau.sg.ch",
  allowApplicantManualWorkItem: false,
  documentBackend: "alexandria",
  showIdInInternalArea: false,
  instanceStates: {
    new: 1,
  },
  gwr: {
    cantonAbbreviation: "SG",
    importModels: ["project", "building", "dwelling"],
    modalContainer: "body",
  },
  submittedStates: [],
  answerSlugs: {
    objectStreet: "strasse-und-nr",
    objectZIP: "plz",
    objectLocation: "ort",
    description: "beschreibung-bauvorhaben",
    municipality: "gemeinde",
    specialId: "dossier-number",
    parcel: "parzelle",
    parcelNumber: "parzellennummer",
    firstNameApplicant: "vorname",
    lastNameApplicant: "name",
    juristicNameApplicant: "juristische-person-name",
    isJuristicApplicant: "juristische-person",
    isJuristicApplicantYes: "juristische-person-ja",
    personalDataApplicant: "gesuchstellerin",
  },
  personalSuggestions: {
    tableQuestions: ["gesuchstellerin"],
    firstNameRegexp: "^vorname$",
    lastNameRegexp: "^name$",
    juristicNameRegexp: "^juristische-person-name$",
    emailRegexp: "^e-mail$",
  },
  intentSlugs: ["beschreibung-bauvorhaben"],
  submitComponent: {
    requiredPermissions: {
      submit: ["instance-submit"],
    },
    export: { enabled: () => false },
  },
  communication: {
    rolesWithApplicantContact: ["activeOrInolvedLeadAuthority", "service"],
  },
};
