<script src="/public/js/overlay.js" type="text/javascript"></script>
<script>
	$(function() {
		$('.delete').click(function() {
			return confirm("Möchten Sie die Datei wirklich löschen?");
		});
	})
</script>

<div class="ui-helper-clearfix">

<?php foreach ($this->sections as $section): ?>
	<?php if (array_key_exists($section->attachmentSectionID, $this->privileges)) : ?>
	<?php $empty = !count($this->attachments[$section->attachmentSectionID]); ?>
	<?php if($this->isPublic()) : ?>
		<h3>Dokumente</h3>
	<?php else: ?>
		<h3><?php echo $section->name ?></h3>
	<?php endif; ?>
		<form action="<?php echo $this->baseUrl($this->downloadSectionAction);?>" method="POST">
			<input type="hidden" name="section" value="<?php echo $section->attachmentSectionID; ?>">
			<table class="document_list">
				<thead>
					<tr>
						<?php if (!$empty) : ?>
							<th style="width: 1em;"><input type="checkbox" class="toggle" /></th>
						<?php endif; ?>
						<th>Dateiname</th>
						<th></th>
						<th>Grösse</th>
						<th>Datum</th>
						<?php if (!$this->isPublic()) : ?>
							<th>User</th>
							<th>Fachstelle</th>
							<th>Aktion</th> <?php // nach user einschränken ?>
						<?php endif; ?>
					</tr>
				</thead>
				<tbody>
				<?php if (!$empty) : ?>
					<?php foreach ($this->attachments[$section->attachmentSectionID] as $attachmentWrapper) :
						$attachment = $attachmentWrapper['attachment'];
						$version = $attachmentWrapper['version'] ? ' (Version ' . $attachmentWrapper['version'] . ')' : '';
						?>
						<tr>
							<td style="width: 1em;"><input type="checkbox" name="selected[]" value="<?php echo $attachment->identifier; ?>" /></td>
							<td>
								<?php echo $this->makeLink($attachment, true) . $version ?>
								<?php if ($attachment->isConfidential) : ?>
									<span class="confidential-marker">Vertraulich!</span>
								<?php endif ?>
							</td>
							<td class="center"><?php if ($attachment->digitalSignature) { ?><i class="fa fa-lock"></i><?php } ?></td>
							<td><?php echo $this->humanReadable($attachment->size);?></td>
							<td><?=$this->date($attachment->date) ?></td>
							<?php if (!$this->isPublic()) : ?>
								<td><?php echo $attachment->getUserName() ?></td>
								<td><?php echo $attachment->getService() ?></td>
								<td>
									<?php if ($this->controller->isDeleteAllowed($attachment)) :?>
										<a class="delete" href="<?php echo $this->url(array('action'=>'delete', 'attachmentid' => $attachment->identifier))?>">löschen</a>
									<?php endif; ?>
									<?php if ($this->controller->showPublish($section->attachmentSectionID)) :?>
										- <a href="<?php echo $this->url(array('action'=>'toggle-publish', 'attachmentid' => $attachment->identifier))?>">publizieren</a>
									<?php elseif ($this->controller->showUnpublish($section->attachmentSectionID)) :?>
										<a href="<?php echo $this->url(array('action'=>'toggle-publish', 'attachmentid' => $attachment->identifier))?>">nicht publizieren</a>
									<?php endif; ?>
								</td>
							<?php endif; ?>
						</tr>
					<?php endforeach ?>
				<?php else: ?>
					<tr>
						<td colspan="7">Keine Dateien vorhanden</td>
					</tr>
				<?php endif ?>
				</tbody>
			</table>
			<?php if (!$empty) : ?>
				<p><button class="button download">Dokumente herunterladen</button>
			<?php endif ?>
		</form>
	<?php endif ?>
<?php endforeach ?>

<?php if (!$this->isPublic() && in_array('write', $this->privileges) || in_array('admin', $this->privileges)) :?>

<h2>Dateien hochladen</h2>

<form action="<?php echo $this->baseUrl($this->uploadAction);?>" id="upload" method="POST" enctype="multipart/form-data">
<?php echo $this->form->getCsrf(); ?>

<div class="clearfix">
	<div style="width: 50%; float: left;">
		<p>
		Hochladen nach: <br />
		<select id="upload_target" name="upload_target">
			<option value="0">-</option>
			<?php foreach($this->sections as $section): ?>
				<?php
				$key = $section->attachmentSectionID;
				if (array_key_exists($key, $this->privileges) &&
					in_array($this->privileges[$key], array('write', 'admin'))
				) : ?>
					<option value="<?php echo $section->attachmentSectionID ?>">
						<?php echo $section->name ?>
					</option>
				<?php endif ?>
			<?php endforeach ?>
		</select>
		</p>

		<?php if (Custom_UriUtils::isKoord()) : ?>
			<p>
			Hochladen als: <br />
			<select id="upload_as" name="upload_as" style="width: 200px">
				<option value="0">-</option>
				<?php foreach ($this->getUserList() as $roleName => $users) : ?>

					<?php if (in_array(strtolower($roleName), array('admin', 'guest'))) { continue; } ?>
					<option disabled="disabled"><?php echo $roleName; ?></option>

					<?php foreach ($users as $user) : ?>
						<?php if ($user->USERNAME != 'admin' && $user->USERNAME != 'guest') : ?>
							<option value="<?php echo $user->USER_ID?>">
								<?php echo $user->USERNAME ?>
							</option>
						<?php endif ?>
					<?php endforeach ?>
				<?php endforeach ?>
			</select>
			</p>
		<?php endif ?>
	</div>
	<div style="width: 50%; float: left;">
		<p><strong class="red">Bitte vertrauliche Dokumente entsprechend kennzeichnen!</strong></p>
		<?php for ($idx = 0; $idx <=5; $idx++): ?>
			<input type="checkbox" id="isConfidential<?php echo $idx; ?>" name="isConfidential[<?php echo $idx; ?>]" value="1">
			<label for="isConfidential<?php echo $idx; ?>">Vertraulich</label>
			<input type="file" name="file[<?php echo $idx; ?>]" /> <br />
		<?php endfor ?>
	</div>

	<div style="margin-top: 15px; clear:both;">
	<input type="submit" value="Hochladen" />
	</div>

	<div style="margin-top: 15px;">
	Maximal erlaubte Grösse: <?php echo $this->maxFileSize ?>.
	Erlaubte Dateiendungen: <?php echo strtoupper(join(', ', $this->allowedExtensions)) ?>
	</div>

	<?php if (isset($this->form->buttons)) : ?>
		<div class="actions">
			<?php foreach ($this->form->buttons as $button) : ?>
				<input class="button <?php echo $button->class; ?>" type="submit" name="<?php echo $button->getName() ?>" value="<?php echo $button->getLabel() ?>" />
			<?php endforeach; ?>
		</div>
	<?php endif ?>


</div>
</form>

<div>
<form action="<?php echo $this->baseUrl($this->navigateAction);?>" method="GET" enctype="multipart/form-data">
	<?php if ($this->isPortal) : ?>


	<?php endif ?>
</div>

</form>
<?php endif ?>

<?php if ($this->isPublic()) : ?>
	<p>Die hier angezeigten Dokumente entsprechen der öffentlichen Auflage.<br>
	Wir machen Sie darauf aufmerksam, dass alle hier hinterlegten Dokumente urheberrechtlich
	geschützt sein können. Das Ausdrucken, Speichern, Fotografieren und Weiterverwenden der
	Dokumente ist nur mit ausdrücklicher Zustimmung des Planerstellers bzw. des geistigen
	Eigentümers gestattet.</p>
	<p>Aus Gründen des Datenschutzes werden hier nur die für das Baubewilligungsverfahren
	relevanten Dokumente publiziert, die vom Gesuchsteller nicht explizit als vertrauenswürdig
	und nicht öffentlich zugänglich eingestuft wurden. Weitere Dokumente können im Rahmen der
	Auflagefrist bei der zuständigen Gemeindekanzlei eingesehen werden.</p>
<?php endif; ?>


<script src="/public/js/dist/documents.js" type="text/javascript"></script>
