COUNTRIES = [
    "Schweiz",
    "Deutschland",
    "Österreich",
    "Frankreich",
    "Italien",
    "Liechtenstein",
    "Ägypten",
    "Äquatorialguinea",
    "Äthiopien",
    "Afghanistan",
    "Albanien",
    "Algerien",
    "Amerikanisch-Samoa",
    "Amerikanische Jungferninseln",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarktis",
    "Antigua und Barbuda",
    "Argentinien",
    "Armenien",
    "Aruba",
    "Aserbaidschan",
    "Australien",
    "Bahamas",
    "Bahrain",
    "Bangladesch",
    "Barbados",
    "Belgien",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivien",
    "Bosnien und Herzegowina",
    "Botsuana (Botswana)",
    "Brasilien",
    "Britische Jungferninseln",
    "Brunei",
    "Bulgarien",
    "Burkina Faso",
    "Burundi",
    "Caymaninseln, auch Kaimaninseln",
    "Chile",
    "China, Volksrepublik China",
    "Cookinseln",
    "Costa Rica",
    "Demokratische Republik Kongo",
    "Dominica",
    "Dominikanische Republik (Dom Rep)",
    "Dschibuti",
    "Dänemark",
    "Ecuador",
    "El Salvador",
    "Elfenbeinküste",
    "Eritrea",
    "Estland",
    "Falklandinseln",
    "Fidschi",
    "Finnland",
    "Französisch-Guayana",
    "Französisch-Polynesien",
    "Französische Süd- und Antarktisgebiete",
    "Färöer (Färöer-Inseln)",
    "Föderierte Staaten von Mikronesien",
    "Gabun",
    "Gambia",
    "Georgien",
    "Ghana",
    "Gibraltar",
    "Grenada",
    "Griechenland",
    "Grönland",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Indien",
    "Indonesien",
    "Irak",
    "Iran (Persien)",
    "Irland",
    "Island",
    "Israel",
    "Jamaica",
    "Japan",
    "Jemen",
    "Jordanien",
    "Kambodscha",
    "Kamerun",
    "Kanada",
    "Kap Verde",
    "Kasachstan",
    "Katar",
    "Kenia",
    "Kirgisistan (Kirgistan)",
    "Kiribati",
    "Kokosinseln, Keelinginseln",
    "Kolumbien",
    "Komoren",
    "Kosovo",
    "Kroatien",
    "Kuba",
    "Kuwait",
    "Laos",
    "Lesotho",
    "Lettland",
    "Libanon",
    "Liberia",
    "Libyen",
    "Litauen",
    "Luxemburg",
    "Macau",
    "Madagaskar",
    "Malawi",
    "Malaysia",
    "Malediven",
    "Mali",
    "Malta",
    "Marokko",
    "Marshallinseln",
    "Martinique",
    "Mauritanien",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Monaco, Fürstentum Monaco",
    "Mongolei",
    "Montenegro",
    "Montserrat",
    "Mosambik",
    "Myanmar, Birma, Burma",
    "Namibia",
    "Nauru",
    "Nepal",
    "Neukaledonien",
    "Neuseeland",
    "Nicaragua",
    "Niederlande, Holland",
    "Niger",
    "Nigeria",
    "Nordkorea",
    "Nordmazedonien",
    "Norwegen",
    "Nördliche Marianen",
    "Oman",
    "Osttimor",
    "Osttimor",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua-Neuguinea",
    "Paraguay",
    "Peru",
    "Philippinen",
    "Pitcairn",
    "Polen",
    "Portugal",
    "Puerto Rico",
    "Republik China (Taiwan)",
    "Republik Kongo",
    "Republik Moldau, (Moldavien)",
    "Ruanda, Rwanda",
    "Rumänien",
    "Russland, Russische Föderation ",
    "Réunion",
    "Salomonen",
    "Sambia",
    "Samoa",
    "San Marino",
    "Saudi-Arabien",
    "Schweden",
    "Senegal",
    "Serbien",
    "Seychellen",
    "Sierra Leone",
    "Simbabwe",
    "Singapur",
    "Slovenien",
    "Slowakei",
    "Somalia",
    "Spanien",
    "Sri Lanka (vorm. Ceylon)",
    "St. Kitts und Nevis",
    "St. Lucia",
    "St. Vincent und die Grenadinen",
    "Staat Palästina",
    "Sudan",
    "Suriname (Surinam)",
    "Swasiland (Eswatini)",
    "Syrien",
    "São Tomé und Príncipe",
    "Südafrika",
    "Südkorea (Republik Korea)",
    "Südsudan",
    "Tadschikistan",
    "Tansania",
    "Thailand",
    "Tibet",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad und Tobago",
    "Tschad",
    "Tschechien",
    "Tunesien",
    "Turkmenistan",
    "Turks- und Caicosinseln",
    "Tuvalu",
    "Türkei",
    "Uganda",
    "Ukraine",
    "Ungarn",
    "Uruguay",
    "Usbekistan",
    "Vanuatu",
    "Vatikanstadt (Heiliger Stuhl)",
    "Venezuela",
    "Vereinigte Arabische Emirate",
    "Vereinigte Staaten (Amerika, USA)",
    "Vereinigtes Königreich (Großbritannien, England)",
    "Vietnam",
    "Wallis und Futuna",
    "Weihnachtsinsel",
    "Weißrussland",
    "Westsahara",
    "Zentralafrikanische Republik",
    "Zypern",
]
