COUNTRIES = {
    "Schweiz": "CH",
    "Deutschland": "DE",
    "Österreich": "AT",
    "Frankreich": "FR",
    "Italien": "IT",
    "Liechtenstein": "LI",
    "Ägypten": "EG",
    "Äquatorialguinea": "GQ",
    "Äthiopien": "ET",
    "Afghanistan": "AF",
    "Albanien": "AL",
    "Algerien": "DZ",
    "Amerikanisch-Samoa": "AS",
    "Amerikanische Jungferninseln": "VI",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarktis": "AQ",
    "Antigua und Barbuda": "AG",
    "Argentinien": "AR",
    "Armenien": "AM",
    "Aruba": "AW",
    "Aserbaidschan": "AZ",
    "Australien": "AU",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesch": "BD",
    "Barbados": "BB",
    "Belgien": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivien": "BO",
    "Bosnien und Herzegowina": "BA",
    "Botsuana (Botswana)": "BW",
    "Brasilien": "BR",
    "Britische Jungferninseln": "VG",
    "Brunei": "BN",
    "Bulgarien": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Caymaninseln, auch Kaimaninseln": "KY",
    "Chile": "CL",
    "China, Volksrepublik China": "CN",
    "Cookinseln": "CK",
    "Costa Rica": "CR",
    "Demokratische Republik Kongo": "CD",
    "Dominica": "DM",
    "Dominikanische Republik (Dom Rep)": "DO",
    "Dschibuti": "DJ",
    "Dänemark": "DK",
    "Ecuador": "EC",
    "El Salvador": "SV",
    "Elfenbeinküste": "CI",
    "Eritrea": "ER",
    "Estland": "EE",
    "Falklandinseln": "FK",
    "Fidschi": "FJ",
    "Finnland": "FI",
    "Französisch-Guayana": "GF",
    "Französisch-Polynesien": "PF",
    "Französische Süd- und Antarktisgebiete": "TF",
    "Färöer (Färöer-Inseln)": "FO",
    "Föderierte Staaten von Mikronesien": "FM",
    "Gabun": "GA",
    "Gambia": "GM",
    "Georgien": "GE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Grenada": "GD",
    "Griechenland": "GR",
    "Grönland": "GL",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Indien": "IN",
    "Indonesien": "ID",
    "Irak": "IQ",
    "Iran (Persien)": "IR",
    "Irland": "IE",
    "Island": "IS",
    "Israel": "IL",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jemen": "YE",
    "Jordanien": "JO",
    "Kambodscha": "KH",
    "Kamerun": "CM",
    "Kanada": "CA",
    "Kap Verde": "CV",
    "Kasachstan": "KZ",
    "Katar": "QA",
    "Kenia": "KE",
    "Kirgisistan (Kirgistan)": "KG",
    "Kiribati": "KI",
    "Kokosinseln, Keelinginseln": "CC",
    "Kolumbien": "CO",
    "Komoren": "KM",
    "Kosovo": "XK",
    "Kroatien": "HR",
    "Kuba": "CU",
    "Kuwait": "KW",
    "Laos": "LA",
    "Lesotho": "LS",
    "Lettland": "LV",
    "Libanon": "LB",
    "Liberia": "LR",
    "Libyen": "LY",
    "Litauen": "LT",
    "Luxemburg": "LU",
    "Macau": "MO",
    "Madagaskar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Malediven": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marokko": "MA",
    "Marshallinseln": "MH",
    "Martinique": "MQ",
    "Mauritanien": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexico": "MX",
    "Monaco, Fürstentum Monaco": "MC",
    "Mongolei": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Mosambik": "MZ",
    "Myanmar, Birma, Burma": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Neukaledonien": "NC",
    "Neuseeland": "NZ",
    "Nicaragua": "NI",
    "Niederlande, Holland": "NL",
    "Niger": "NE",
    "Nigeria": "NG",
    "Nordkorea": "KP",
    "Nordmazedonien": "MK",
    "Norwegen": "NO",
    "Nördliche Marianen": "MP",
    "Oman": "OM",
    "Osttimor": "TL",
    "Pakistan": "PK",
    "Palau": "PW",
    "Panama": "PA",
    "Papua-Neuguinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippinen": "PH",
    "Pitcairn": "PN",
    "Polen": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Republik China (Taiwan)": "TW",
    "Republik Kongo": "CG",
    "Republik Moldau, (Moldavien)": "MD",
    "Ruanda, Rwanda": "RW",
    "Rumänien": "RO",
    "Russland, Russische Föderation": "RU",
    "Réunion": "RE",
    "Salomonen": "SB",
    "Sambia": "ZM",
    "Samoa": "WS",
    "San Marino": "SM",
    "Saudi-Arabien": "SA",
    "Schweden": "SE",
    "Senegal": "SN",
    "Serbien": "RS",
    "Seychellen": "SC",
    "Sierra Leone": "SL",
    "Simbabwe": "ZW",
    "Singapur": "SG",
    "Slovenien": "SI",
    "Slowakei": "SK",
    "Somalia": "SO",
    "Spanien": "ES",
    "Sri Lanka (vorm. Ceylon)": "LK",
    "St. Kitts und Nevis": "KN",
    "St. Lucia": "LC",
    "St. Vincent und die Grenadinen": "VC",
    "Staat Palästina": "PS",
    "Sudan": "SD",
    "Suriname (Surinam)": "SR",
    "Swasiland (Eswatini)": "SZ",
    "Syrien": "SY",
    "São Tomé und Príncipe": "ST",
    "Südafrika": "ZA",
    "Südkorea (Republik Korea)": "KR",
    "Südsudan": "SS",
    "Tadschikistan": "TJ",
    "Tansania": "TZ",
    "Thailand": "TH",
    "Tibet": "CN",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad und Tobago": "TT",
    "Tschad": "TD",
    "Tschechien": "CZ",
    "Tunesien": "TN",
    "Turkmenistan": "TM",
    "Turks- und Caicosinseln": "TC",
    "Tuvalu": "TV",
    "Türkei": "TR",
    "Uganda": "UG",
    "Ukraine": "UA",
    "Ungarn": "HU",
    "Uruguay": "UY",
    "Usbekistan": "UZ",
    "Vanuatu": "VU",
    "Vatikanstadt (Heiliger Stuhl)": "VA",
    "Venezuela": "VE",
    "Vereinigte Arabische Emirate": "AE",
    "Vereinigte Staaten (Amerika, USA)": "US",
    "Vereinigtes Königreich (Großbritannien, England)": "GB",
    "Vietnam": "VN",
    "Wallis und Futuna": "WF",
    "Weihnachtsinsel": "CX",
    "Weißrussland": "BY",
    "Westsahara": "EH",
    "Zentralafrikanische Republik": "CF",
    "Zypern": "CY",
}
