COUNTRIES = [
    "Afghanistan",
    "Albanien",
    "Algerien",
    "Amerikanisch-Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarktis",
    "Antigua und Barbuda",
    "Argentinien",
    "Armenien",
    "Aruba",
    "Australien",
    "Aserbaidschan",
    "Bahamas",
    "Bahrain",
    "Bangladesch",
    "Barbados",
    "Weißrussland",
    "Belgien",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivien",
    "Bosnien und Herzegowina",
    "Botsuana (Botswana)",
    "Brasilien",
    "Brunei",
    "Bulgarien",
    "Burkina Faso",
    "Burundi",
    "Kambodscha",
    "Kamerun",
    "Kanada",
    "Kap Verde",
    "Caymaninseln, auch Kaimaninseln",
    "Zentralafrikanische Republik",
    "Tschad",
    "Chile",
    "China, Volksrepublik China",
    "Weihnachtsinsel",
    "Kokosinseln, Keelinginseln",
    "Kolumbien",
    "Komoren",
    "Demokratische Republik Kongo",
    "Republik Kongo",
    "Cookinseln",
    "Costa Rica",
    "Elfenbeinküste",
    "Kroatien",
    "Kuba",
    "Zypern",
    "Tschechien",
    "Dänemark",
    "Dschibuti",
    "Dominica",
    "Dominikanische Republik (Dom Rep)",
    "Osttimor",
    "Ecuador",
    "Ägypten",
    "El Salvador",
    "Äquatorialguinea",
    "Eritrea",
    "Estland",
    "Äthiopien",
    "Falklandinseln",
    "Färöer (Färöer-Inseln)",
    "Fidschi",
    "Finnland",
    "Französisch-Guayana",
    "Französisch-Polynesien",
    "Französische Süd- und Antarktisgebiete",
    "Gabun",
    "Gambia",
    "Georgien",
    "Ghana",
    "Gibraltar",
    "Griechenland",
    "Grönland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Ungarn",
    "Island",
    "Indien",
    "Indonesien",
    "Iran (Persien)",
    "Irak",
    "Irland",
    "Israel",
    "Jamaica",
    "Japan",
    "Jordanien",
    "Kasachstan",
    "Kenia",
    "Kiribati",
    "Nordkorea",
    "Südkorea (Republik Korea)",
    "Kosovo",
    "Kuwait",
    "Kirgisistan (Kirgistan)",
    "Laos",
    "Lettland",
    "Libanon",
    "Lesotho",
    "Liberia",
    "Libyen",
    "Litauen",
    "Luxemburg",
    "Macau",
    "Nordmazedonien",
    "Madagaskar",
    "Malawi",
    "Malaysia",
    "Malediven",
    "Mali",
    "Malta",
    "Marshallinseln",
    "Martinique",
    "Mauritanien",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Föderierte Staaten von Mikronesien",
    "Republik Moldau, (Moldavien)",
    "Monaco, Fürstentum Monaco",
    "Mongolei",
    "Montenegro",
    "Montserrat",
    "Marokko",
    "Mosambik",
    "Myanmar, Birma, Burma",
    "Namibia",
    "Nauru",
    "Nepal",
    "Niederlande, Holland",
    "Neukaledonien",
    "Neuseeland",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Nördliche Marianen",
    "Norwegen",
    "Oman",
    "Pakistan",
    "Palau",
    "Staat Palästina",
    "Panama",
    "Papua-Neuguinea",
    "Paraguay",
    "Peru",
    "Philippinen",
    "Pitcairn",
    "Polen",
    "Portugal",
    "Puerto Rico",
    "Katar",
    "Réunion",
    "Rumänien",
    "Russland, Russische Föderation ",
    "Ruanda, Rwanda",
    "St. Kitts und Nevis",
    "St. Lucia",
    "St. Vincent und die Grenadinen",
    "Samoa",
    "San Marino",
    "São Tomé und Príncipe",
    "Saudi-Arabien",
    "Senegal",
    "Serbien",
    "Seychellen",
    "Sierra Leone",
    "Singapur",
    "Slowakei",
    "Slovenien",
    "Salomonen",
    "Somalia",
    "Südafrika",
    "Südsudan",
    "Spanien",
    "Sri Lanka (vorm. Ceylon)",
    "Sudan",
    "Suriname (Surinam)",
    "Swasiland (Eswatini)",
    "Schweden",
    "Syrien",
    "Republik China (Taiwan)",
    "Tadschikistan",
    "Tansania",
    "Thailand",
    "Tibet",
    "Osttimor",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad und Tobago",
    "Tunesien",
    "Türkei",
    "Turkmenistan",
    "Turks- und Caicosinseln",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "Vereinigte Arabische Emirate",
    "Vereinigtes Königreich (Großbritannien, England)",
    "Vereinigte Staaten (Amerika, USA)",
    "Uruguay",
    "Usbekistan",
    "Vanuatu",
    "Vatikanstadt (Heiliger Stuhl)",
    "Venezuela",
    "Vietnam",
    "Britische Jungferninseln",
    "Amerikanische Jungferninseln",
    "Wallis und Futuna",
    "Westsahara",
    "Jemen",
    "Sambia",
    "Simbabwe",
]
