EBAU_S3_ACCESS_KEY_ID=GKbef634011e4e34a013f8fa19
EBAU_S3_SECRET_ACCESS_KEY=7475cc947a168c97fd8e1cf4f1b1c763568fefa03d88e7d5d4696afdee0092c0
EBAU_S3_ENDPOINT_URL=http://garage:3900
EBAU_STORAGE_BUCKET_NAME=ebau-media
EBAU_S3_REGION_NAME=garage
EBAU_S3_SIGNATURE_VERSION=s3v4
DJANGO_DEFAULT_FILE_STORAGE=storages.backends.s3.S3Storage
#EBAU_S3_STORAGE_SSEC_SECRET=3780f7299d8574fdaff7f55849aa6eed
#EBAU_ENCRYPTION_METHOD=ssec-global
#EBAU_ENABLE_AT_REST_ENCRYPTION=true
