<div id="app">
  <ca-message :result="result"></ca-message>
  <form @submit.prevent="validateBeforeSubmit">
    <h3>Art / Grundlage / Verfahren</h3>
    <ca-form-element v-for="question in questions" :name="question.NAME">
      <span v-if="readonly">{{ translateAnswer(question.ANSWER) }}</span>
      <select v-else v-model="question.ANSWER">
        <option disabled value="">Bitte wählen</option>
        <option v-for="answer in getAnswerList(question.QUESTION_ID)" :value="answer.VALUE">{{answer.NAME}}</option>
      </select>
    </ca-form-element>

    <h3>Lage / Flächenbedarf</h3>
    <div v-for="(entry, index) in usageEntries">
      <ca-form-element name="Grundnutzung">
        <span v-if="readonly">{{ translateUsageType(entry.USAGE_TYPE) }}</span>
        <select v-else v-model="entry.USAGE_TYPE" :name="'type ' + index" data-vv-as="Grundnutzung" v-validate="'required'">
          <option disabled value="">Bitte wählen</option>
          <option v-for="type in getAvailableTypes(entry.USAGE_TYPE)" :value="type.key">{{type.name}}</option>
        </select>
        <span v-show="errors.has('type ' + index)" class="error">{{ errors.first('type ' + index) }}</span>
      </ca-form-element>
      <ca-form-element name="Flächenbedarf nach Grundnutzung (m²)">
        <span v-if="readonly">{{ entry.USAGE }}</span>
        <input v-else type="text" v-model="entry.USAGE" :name="'usage ' + index" data-vv-as="Flächenverbrauch" v-validate="'required|numeric'">
        <span v-show="errors.has('usage ' + index)" class="error">{{ errors.first('usage ' + index) }}</span>
      </ca-form-element>
      <p v-if="!readonly" style="margin-top:0"><a v-on:click="remove(index)" href="javascript:void(0)">Eintrag löschen</a></p>
    </div>
    <button v-if="!readonly" v-on:click="add">Lage / Flächenbedarf hinzufügen</button>

    <ca-form-element v-for="input in inputs" :name="input.NAME">
      <ca-input v-model="input.ANSWER" :readonly="readonly"></ca-input>
    </ca-form-element>

    <div class="actions">
      <button v-if="!readonly" type="submit" :disabled="errors.any()">Speichern</button>
    </div>
  </form>
</div>

<script>
  var instanceResourceId = <?= $this->instanceResourceId ?>;
  var instanceId = <?= $this->instanceId ?>;
  var readonly = <?= $this->readonly ? 'true' : 'false' ?>;
</script>

<script src="/node_modules/babel-polyfill/dist/polyfill.min.js" type="text/javascript"></script>
<script src="/node_modules/vue/dist/vue.min.js" type="text/javascript"></script>
<script src="/node_modules/vee-validate/dist/vee-validate.min.js" type="text/javascript"></script>
<script src="/node_modules/vee-validate/dist/locale/de.js" type="text/javascript"></script>
<script src="/public/js/dist/bab.js" type="text/javascript"></script>
