metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "e9d97004f699695b024fed976221a2411fd65e7c074343360bd9e05f2a22964d"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".garage-s3.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".garage.localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "S0LX8I1y8gyTaNB4BvsonAxm4UJhRhnF6eJwidR0I7o="
metrics_token = "/PV24DK0Xpb8pHERfYHlZwd5Mq10FGmRSPVR5HZOARY="
