mutation CreateSubmitTask {
  saveCompleteWorkflowFormTask(
    input: {
      slug: "submit"
      name: "Gesuch einreichen"
      addressGroups: "[\"applicant\"]"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFormalExamTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "formal-exam"
      form: "formelle-vorpruefung"
      name: "Formelle Prüfung"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
      leadTime: 432000 # 5 days
      meta: "{\"directLink\":{\"route\":\"cases.detail.task-form\",\"models\":[\"INSTANCE_ID\",\"TASK_SLUG\"]},\"redirectToWorkItemsAfterCompletion\":true, \"writePermissionKey\": \"formal-exam-write\"}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateMaterialExamTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "material-exam"
      form: "materielle-pruefung"
      name: "Materielle Prüfung"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
      leadTime: 432000 # 5 days
      meta: "{\"directLink\":{\"route\":\"cases.detail.task-form\",\"models\":[\"INSTANCE_ID\",\"TASK_SLUG\"]},\"redirectToWorkItemsAfterCompletion\":true, \"writePermissionKey\": \"material-exam-write\"}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateManualWorkItemTask {
  saveSimpleTask(
    input: {
      slug: "create-manual-workitems"
      name: "Manuelle Aufgaben erfassen"
      addressGroups: "[]"
      isMultipleInstance: true
      meta: "{\"is-manually-completable\":true}"
    }
  ) {
    clientMutationId
  }
}

mutation CreatePublicationTask {
  saveSimpleTask(
    input: {
      slug: "publication"
      name: "Dossier publizieren"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
      leadTime: 604800 # 7 days
      meta: "{\"is-manually-completable\":true,\"directLink\":{\"route\":\"cases.detail.publication\",\"models\":[\"INSTANCE_ID\",\"public\"]}}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFillPublicationTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "fill-publication"
      name: "Publikation ausfüllen"
      form: "publikation"
      addressGroups: "[\"municipality\"]|groups"
    }
  ) {
    clientMutationId
  }
}

mutation CreateNewPublicationTask {
  saveSimpleTask(
    input: {
      slug: "create-publication"
      name: "Neue Publikation erfassen"
      addressGroups: "[\"municipality\"]|groups"
    }
  ) {
    clientMutationId
  }
}

mutation CreateInformationOfNeighborsTask {
  saveSimpleTask(
    input: {
      slug: "information-of-neighbors"
      name: "Bauanzeigen versenden"
      addressGroups: "['municipality']|groups"
      controlGroups: "['municipality']|groups"
      leadTime: 604800 # 7 days
      meta: "{\"is-manually-completable\":true,\"directLink\":{\"route\":\"cases.detail.publication\",\"models\":[\"INSTANCE_ID\",\"neighbors\"]}}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFillInformationOfNeighborsTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "fill-information-of-neighbors"
      name: "Bauanzeigen ausfüllen"
      form: "bauanzeige"
      addressGroups: "['municipality']|groups"
    }
  ) {
    clientMutationId
  }
}

mutation CreateNewInformationOfNeighborsTask {
  saveSimpleTask(
    input: {
      slug: "create-information-of-neighbors"
      name: "Bauanzeigen erstellen"
      addressGroups: "['municipality']|groups"
    }
  ) {
    clientMutationId
  }
}

mutation CreateDecisionTask {
  saveCompleteTaskFormTask(
    input: {
      slug: "decision"
      form: "entscheid"
      name: "Entscheid verfügen"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
      leadTime: 864000 # 10 days
      meta: "{\"directLink\":{\"route\":\"cases.detail.task-form\",\"models\":[\"INSTANCE_ID\",\"TASK_SLUG\"]},\"redirectToWorkItemsAfterCompletion\":true}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateWithdrawalRequestTask {
  saveSimpleTask(
    input: {
      slug: "withdrawal-request"
      name: "Rückzug beantragen"
      addressGroups: "[\"applicant\"]"
    }
  ) {
    clientMutationId
  }
}

mutation CreateWithdrawalCheckTask {
  saveSimpleTask(
    input: {
      slug: "withdrawal-check"
      name: "Rückzug prüfen"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
      leadTime: 432000 # 5 days
      meta: "{\"is-manually-completable\":true}"
    }
  ) {
    clientMutationId
  }
}
