mutation CreateSubmitTask {
  saveCompleteWorkflowFormTask(
    input: {
      slug: "submit"
      name: "Gesuch einreichen"
      addressGroups: "[\"applicant\"]"
    }
  ) {
    clientMutationId
  }
}

mutation CreateFormalExamTask {
  saveSimpleTask(
    input: {
      slug: "formal-exam"
      name: "Formelle Vorpüfung"
      addressGroups: "[\"municipality\"]|groups"
      controlGroups: "[\"municipality\"]|groups"
      leadTime: 432000 # 5 days
      meta: "{\"directLink\":{\"route\":\"cases.detail.task-form\",\"models\":[\"INSTANCE_ID\",\"TASK_SLUG\"]}}"
    }
  ) {
    clientMutationId
  }
}

mutation CreateManualWorkItemTask {
  saveSimpleTask(
    input: {
      slug: "create-manual-workitems"
      name: "Manuelle Aufgaben erfassen"
      addressGroups: "[]"
      isMultipleInstance: true
      meta: "{\"is-manually-completable\":true}"
    }
  ) {
    clientMutationId
  }
}
