# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
