# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
    ]
