# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181119_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='disabled',
            field=models.PositiveSmallIntegerField(db_column='DISABLED', default=0),
        ),
    ]
