# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181119_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='notification',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
