# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_service_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupt',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='user.Group'),
        ),
        migrations.AlterField(
            model_name='locationt',
            name='location',
            field=models.ForeignKey(db_column='LOCATION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='user.Location'),
        ),
        migrations.AlterField(
            model_name='servicet',
            name='service',
            field=models.ForeignKey(db_column='SERVICE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='user.Service'),
        ),
    ]
