# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-29 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190515_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroupt',
            name='service_group',
            field=models.ForeignKey(db_column='SERVICE_GROUP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='user.ServiceGroup'),
        ),
    ]
