# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_duplicated_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='role',
            field=models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='user.Role'),
        ),
    ]
