# Generated by Django 2.2.8 on 2020-01-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20191129_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='users', through='user.UserGroup', to='user.Group'),
        ),
    ]
