# Generated by Django 2.2.11 on 2020-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200110_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group_prefix',
            field=models.CharField(blank=True, db_column='GROUP_PREFIX', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rolet',
            name='group_prefix',
            field=models.CharField(blank=True, db_column='GROUP_PREFIX', max_length=100, null=True),
        ),
    ]
