# Generated by Django 2.2.17 on 2021-05-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210119_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
