# Generated by Django 3.2.12 on 2022-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0014_servicegroup_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': True, 'ordering': ['service_group__name']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_column='IS_STAFF', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
