# Generated by Django 3.2.15 on 2022-10-13 11:49

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_role_service_group_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'managed': True, 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': True, 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': True, 'ordering': ['service_group__name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicegroup',
            options={'managed': True, 'verbose_name': 'Service group', 'verbose_name_plural': 'Service groups'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(blank=True, db_column='ADDRESS', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='group',
            name='city',
            field=models.CharField(blank=True, db_column='CITY', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='group',
            name='disabled',
            field=models.PositiveSmallIntegerField(db_column='DISABLED', default=0, verbose_name='Disabled?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.CharField(blank=True, db_column='EMAIL', max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='group',
            name='locations',
            field=models.ManyToManyField(through='user.GroupLocation', to='user.Location', verbose_name='Locations'),
        ),
        migrations.AlterField(
            model_name='group',
            name='phone',
            field=models.CharField(blank=True, db_column='PHONE', max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='group',
            name='role',
            field=models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='user.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='group',
            name='service',
            field=models.ForeignKey(blank=True, db_column='SERVICE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='user.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='group',
            name='zip',
            field=models.CharField(blank=True, db_column='ZIP', max_length=10, null=True, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='grouplocation',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='grouplocation',
            name='location',
            field=models.ForeignKey(db_column='LOCATION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='groupt',
            name='city',
            field=models.CharField(blank=True, db_column='CITY', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='groupt',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='user.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='groupt',
            name='language',
            field=models.CharField(db_column='LANGUAGE', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='role',
            name='group_prefix',
            field=models.CharField(blank=True, db_column='GROUP_PREFIX', max_length=100, null=True, verbose_name='Group prefix'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_parent',
            field=models.ForeignKey(blank=True, db_column='ROLE_PARENT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.role', verbose_name='Role parent'),
        ),
        migrations.AlterField(
            model_name='rolet',
            name='group_prefix',
            field=models.CharField(blank=True, db_column='GROUP_PREFIX', max_length=100, null=True, verbose_name='Group prefix'),
        ),
        migrations.AlterField(
            model_name='rolet',
            name='language',
            field=models.CharField(db_column='LANGUAGE', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, db_column='ADDRESS', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, db_column='CITY', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, db_column='DESCRIPTION', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='disabled',
            field=models.PositiveSmallIntegerField(db_column='DISABLED', default=0, verbose_name='Disabled?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.CharField(blank=True, db_column='EMAIL', max_length=1000, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='service',
            name='notification',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Receive notifications?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=models.CharField(blank=True, db_column='PHONE', max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_group',
            field=models.ForeignKey(db_column='SERVICE_GROUP_ID', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.servicegroup', verbose_name='Service group'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_parent',
            field=models.ForeignKey(blank=True, db_column='SERVICE_PARENT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.service', verbose_name='Service parent'),
        ),
        migrations.AlterField(
            model_name='service',
            name='zip',
            field=models.CharField(blank=True, db_column='ZIP', max_length=10, null=True, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='servicegroupt',
            name='language',
            field=models.CharField(db_column='LANGUAGE', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='servicet',
            name='city',
            field=models.CharField(blank=True, db_column='CITY', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='servicet',
            name='description',
            field=models.CharField(blank=True, db_column='DESCRIPTION', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicet',
            name='language',
            field=models.CharField(db_column='LANGUAGE', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, db_column='ADDRESS', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_column='CITY', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disabled',
            field=models.PositiveSmallIntegerField(db_column='DISABLED', default=0, verbose_name='Disabled?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, db_column='EMAIL', max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(db_column='LANGUAGE', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='LAST_REQUEST_DATE', null=True, verbose_name='Last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_column='NAME', max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_column='PHONE', max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(db_column='SURNAME', max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='USERNAME', max_length=250, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.CharField(blank=True, db_column='ZIP', max_length=10, null=True, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='default_group',
            field=models.PositiveSmallIntegerField(db_column='DEFAULT_GROUP', verbose_name='Default group?'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(db_column='GROUP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
