# Generated by Django 3.2.15 on 2023-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_service_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='responsibility_construction_control',
            field=models.BooleanField(default=False, verbose_name='Apply responsibility in construction control?'),
        ),
    ]
