# Generated by Django 3.2.23 on 2024-01-29 13:47

import camac.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_service_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=camac.user.models.logo_path, verbose_name='Logo'),
        ),
    ]
