# Generated by Django 3.2.25 on 2024-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_service_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='external_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='External identifier'),
        ),
    ]
