# Generated by Django 4.2.13 on 2024-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_service_external_identifier'),
        ('core', '0109_case_insensitive_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_collation='case_insensitive', db_column='EMAIL', max_length=100, null=True, verbose_name='Email'),
        ),
    ]
