# Generated by Django 4.2.20 on 2025-05-26 09:15

from django.db import migrations, models
from django.db.models import F


def set_name_as_slug(apps, schema_editor):
    apps.get_model("user", "ServiceGroup").objects.all().update( slug=F("name") )

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_and_service_new_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.RunPython(set_name_as_slug, migrations.RunPython.noop)
    ]
