# Generated by Django 4.2.20 on 2025-06-12 12:47
# This migration is only for those systems that already executed migration 0030.
# For all systems that have not yet migrated to 0030, this changes nothing.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_servicegroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroup',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
