# Generated by Django 4.2.20 on 2025-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0031_alter_servicegroup_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="division",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Division"
            ),
        ),
    ]
