# Generated by Django 5.2.5 on 2025-09-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_user_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='functional_services',
            field=models.ManyToManyField(related_name='has_function_in', through='user.ServiceRelation', through_fields=('receiver', 'provider'), to='user.service', verbose_name='Services that perform a specific function'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='users', through='user.UserGroup', through_fields=('user', 'group'), to='user.group'),
        ),
    ]
