# Generated by Django 5.2.6 on 2025-10-10 13:48

from datetime import timedelta

from django.db import migrations, models


def populate_missing_expiration_dates(apps, schema_editor):
    """Set default expiration date of 14 days from created_at for existing invitations without expires_at."""
    UserGroupInvitation = apps.get_model('user', 'UserGroupInvitation')
    
    invitations_without_expiry = UserGroupInvitation.objects.filter(expires_at__isnull=True)
    
    for invitation in invitations_without_expiry:
        invitation.expires_at = invitation.created_at + timedelta(days=14)
        invitation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_usergroupinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_missing_expiration_dates,
        ),
    ]
