# Generated by Django 5.2.7 on 2025-10-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0035_usergroupinvitation_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="meta",
            field=models.JSONField(default=dict),
        ),
    ]
