# Generated by Django 5.2.7 on 2025-11-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0036_service_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
