# Generated by Django 5.2.8 on 2025-11-13 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_service_meta_allow_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometerChangeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(default=None, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('completed', 'completed'), ('scheduled', 'scheduled'), ('failed', 'failed')])),
                ('geometer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.service')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.service')),
            ],
        ),
    ]
