# Generated by Django 5.2.11 on 2026-03-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_role_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='uses_ech_api',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Using the ECH API?'),
        ),
    ]
