mutation CreateInternalDossierWorkflow {
  saveWorkflow(
    input: {
      slug: "internal-dossier"
      name: "Internes Dossier"
      startTasks: ["submit"]
      allowForms: ["internes-dossier"]
      isPublished: true
    }
  ) {
    clientMutationId
  }
}

mutation CreateInternalDossierFlowAfter {
  addWorkflowFlow(
    input: {
      workflow: "internal-dossier"
      tasks: ["submit"]
      next: "[\"complete-instance\", \"create-manual-workitems\"]|tasks"
    }
  ) {
    clientMutationId
  }
}
