# Generated by Django 5.2.5 on 2025-09-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Alert Message',
                'verbose_name_plural': 'Alert Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
