# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responsible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibleservice',
            name='instance',
            field=models.ForeignKey(db_column='INSTANCE_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsible_services', to='instance.Instance'),
        ),
    ]
