# Generated by Django 2.2.14 on 2020-08-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("responsible", "0002_auto_20190806_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsibleservice",
            name="responsible_user",
            field=models.ForeignKey(
                db_column="RESPONSIBLE_USER_ID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="responsible_services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
