# Generated by Django 2.2.17 on 2021-03-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210119_1201'),
        ('instance', '0028_journalentry_visibility'),
        ('responsible', '0003_auto_20200805_1455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responsibleservice',
            unique_together={('instance', 'service')},
        ),
    ]
