# Generated by Django 2.2.17 on 2021-08-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("responsible", "0004_auto_20210301_1253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsibleservice",
            name="instance",
            field=models.ForeignKey(
                db_column="INSTANCE_ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsible_services",
                to="instance.Instance",
            ),
        ),
    ]
