# Generated by Django 2.2.17 on 2021-08-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsible', '0005_instance_responsibility'),
        ('responsible', '0005_on_delete_cascade'),
    ]

    operations = [
    ]
