# Generated by Django 3.2.12 on 2022-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsible', '0006_merge_20210827_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asetresponsiblegroup',
            name='is_required',
            field=models.BooleanField(db_column='IS_REQUIRED', null=True),
        ),
        migrations.AlterField(
            model_name='asetresponsiblegroup',
            name='is_service_responsible',
            field=models.BooleanField(db_column='IS_SERVICE_RESPONSIBLE', null=True),
        ),
        migrations.AlterField(
            model_name='ireditresponsibleuser',
            name='is_required',
            field=models.BooleanField(db_column='IS_REQUIRED', null=True),
        ),
        migrations.AlterField(
            model_name='ireditresponsibleuser',
            name='is_service_responsible',
            field=models.BooleanField(db_column='IS_SERVICE_RESPONSIBLE', null=True),
        ),
    ]
